#!/usr/bin/env python3
"""
Enhanced Code Generator - Real Implementation for Your IDE
Builds on your existing AI integration and GUI framework
"""

import os
import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Any
import tempfile
import subprocess

class RealCodeGenerator:
    """
    Real code generator that leverages your existing AI system
    Integrates with your 3,653-line EON Compiler GUI
    """
    
    def __init__(self, ide_instance):
        self.ide = ide_instance
        self.templates_dir = Path(__file__).parent / "code_templates"
        self.templates = self.load_code_templates()
        self.ai_available = hasattr(ide_instance, 'ai_system')
        
    def load_code_templates(self) -> Dict[str, Dict]:
        """Load code templates from your existing system"""
        templates = {
            "console_app": {
                "eon": '''module {name}

function main() -> int {{
    println("Hello from {name}!")
    return 0
}}''',
                "python": '''#!/usr/bin/env python3
"""
{name} - Console Application
Generated by Enhanced Code Generator
"""

def main():
    print("Hello from {name}!")
    return 0

if __name__ == "__main__":
    exit(main())''',
                "cpp": '''#include <iostream>
using namespace std;

/**
 * {name} - Console Application
 * Generated by Enhanced Code Generator
 */
int main() {{
    cout << "Hello from {name}!" << endl;
    return 0;
}}''',
                "javascript": '''/**
 * {name} - Console Application
 * Generated by Enhanced Code Generator
 */

console.log("Hello from {name}!");

// Export for Node.js
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = {{ main: () => console.log("Hello from {name}!") }};
}}'''
            },
            
            "gui_app": {
                "python": '''#!/usr/bin/env python3
"""
{name} - GUI Application
Generated by Enhanced Code Generator
"""

import tkinter as tk
from tkinter import ttk, messagebox

class {class_name}App:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("{name}")
        self.root.geometry("800x600")
        self.setup_ui()
    
    def setup_ui(self):
        # Main frame
        main_frame = ttk.Frame(self.root, padding="10")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        # Title
        title_label = ttk.Label(main_frame, text="{name}", font=("Arial", 16, "bold"))
        title_label.grid(row=0, column=0, columnspan=2, pady=(0, 20))
        
        # Button
        action_button = ttk.Button(main_frame, text="Click Me!", command=self.on_button_click)
        action_button.grid(row=1, column=0, columnspan=2, pady=10)
        
        # Configure grid weights
        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)
        main_frame.columnconfigure(0, weight=1)
    
    def on_button_click(self):
        messagebox.showinfo("{name}", "Hello from {name} GUI!")
    
    def run(self):
        self.root.mainloop()

def main():
    app = {class_name}App()
    app.run()

if __name__ == "__main__":
    main()''',
                
                "eon": '''module {name}

import std.gui.window
import std.gui.button
import std.gui.label

class {class_name}App {{
    var main_window: Window
    var title_label: Label
    var action_button: Button
    
    function init() {{
        main_window = Window("{name}", 800, 600)
        setup_ui()
    }}
    
    function setup_ui() {{
        title_label = Label("{name}")
        title_label.setFont("Arial", 16, BOLD)
        main_window.add(title_label, 10, 10)
        
        action_button = Button("Click Me!")
        action_button.onClick = on_button_click
        main_window.add(action_button, 10, 50)
    }}
    
    function on_button_click() {{
        main_window.showMessage("Hello from {name} GUI!")
    }}
    
    function run() {{
        main_window.show()
        main_window.eventLoop()
    }}
}}

function main() -> int {{
    var app = {class_name}App()
    app.init()
    app.run()
    return 0
}}'''
            },
            
            "web_service": {
                "python": '''#!/usr/bin/env python3
"""
{name} - Web Service
Generated by Enhanced Code Generator
"""

import http.server
import socketserver
import json
import urllib.parse
from datetime import datetime

class {class_name}Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/":
            self.send_response(200)
            self.send_header("Content-type", "text/html")
            self.end_headers()
            self.wfile.write(self.get_index_html().encode())
        elif self.path == "/api/status":
            self.send_json_response({{"status": "running", "service": "{name}", "timestamp": datetime.now().isoformat()}})
        else:
            self.send_response(404)
            self.end_headers()
    
    def do_POST(self):
        content_length = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(content_length).decode('utf-8')
        
        if self.path == "/api/echo":
            try:
                data = json.loads(post_data)
                response = {{"echo": data, "service": "{name}"}}
                self.send_json_response(response)
            except json.JSONDecodeError:
                self.send_json_response({{"error": "Invalid JSON"}}, 400)
    
    def send_json_response(self, data, status=200):
        self.send_response(status)
        self.send_header("Content-type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode())
    
    def get_index_html(self):
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>{name}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        .container {{ max-width: 800px; margin: 0 auto; }}
        .status {{ background: #f0f8f0; padding: 15px; border-radius: 5px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{name} Web Service</h1>
        <div class="status">
            <h3>Service Status: Running</h3>
            <p>Generated by Enhanced Code Generator</p>
        </div>
        <h3>Available Endpoints:</h3>
        <ul>
            <li><strong>GET /</strong> - This page</li>
            <li><strong>GET /api/status</strong> - Service status</li>
            <li><strong>POST /api/echo</strong> - Echo JSON data</li>
        </ul>
    </div>
</body>
</html>"""

def main():
    PORT = 8080
    with socketserver.TCPServer(("", PORT), {class_name}Handler) as httpd:
        print(f"{name} web service running on port {{PORT}}")
        print(f"Visit: http://localhost:{{PORT}}")
        httpd.serve_forever()

if __name__ == "__main__":
    main()'''
            }
        }
        
        return templates
    
    def generate_from_description(self, description: str, language: str = "python") -> str:
        """
        Generate code from natural language description
        Uses your existing AI system if available
        """
        
        if self.ai_available and hasattr(self.ide.ai_system, 'generate_code'):
            # Use your existing AI integration
            try:
                prompt = f"Generate {language} code for: {description}"
                ai_result = self.ide.ai_system.generate_code(prompt)
                if ai_result and ai_result.strip():
                    return ai_result
            except Exception as e:
                print(f"AI generation failed, using templates: {e}")
        
        # Fallback to template-based generation
        return self.generate_from_template(description, language)
    
    def generate_from_template(self, description: str, language: str = "python") -> str:
        """Template-based code generation as fallback"""
        
        # Analyze description to determine template type
        template_type = self.detect_template_type(description)
        
        if template_type in self.templates and language in self.templates[template_type]:
            # Extract project name from description
            name = self.extract_name_from_description(description)
            class_name = self.to_class_name(name)
            
            template = self.templates[template_type][language]
            return template.format(name=name, class_name=class_name)
        
        # Basic code generation
        return self.generate_basic_code(description, language)
    
    def detect_template_type(self, description: str) -> str:
        """Detect what type of application to generate"""
        description_lower = description.lower()
        
        if any(word in description_lower for word in ["web", "server", "api", "http", "rest"]):
            return "web_service"
        elif any(word in description_lower for word in ["gui", "window", "interface", "ui", "tkinter"]):
            return "gui_app"
        else:
            return "console_app"
    
    def extract_name_from_description(self, description: str) -> str:
        """Extract project name from description"""
        
        # Look for "called X" or "named X"
        name_patterns = [
            r"called\s+([a-zA-Z_][a-zA-Z0-9_]*)",
            r"named\s+([a-zA-Z_][a-zA-Z0-9_]*)",
            r"create\s+([a-zA-Z_][a-zA-Z0-9_]*)",
            r"make\s+([a-zA-Z_][a-zA-Z0-9_]*)"
        ]
        
        for pattern in name_patterns:
            match = re.search(pattern, description, re.IGNORECASE)
            if match:
                return match.group(1)
        
        # Default name
        return "MyApplication"
    
    def to_class_name(self, name: str) -> str:
        """Convert name to proper class name"""
        # Remove non-alphanumeric characters and convert to PascalCase
        clean_name = re.sub(r'[^a-zA-Z0-9]', '', name)
        return clean_name.capitalize()
    
    def generate_basic_code(self, description: str, language: str) -> str:
        """Generate basic code structure"""
        
        if language.lower() == "python":
            return f'''#!/usr/bin/env python3
"""
Generated code for: {description}
Created by Enhanced Code Generator
"""

def main():
    print("Generated code for: {description}")
    # TODO: Implement functionality based on description
    pass

if __name__ == "__main__":
    main()'''
        
        elif language.lower() == "eon":
            return f'''module generated_code

// Generated code for: {description}
// Created by Enhanced Code Generator

function main() -> int {{
    println("Generated code for: {description}")
    // TODO: Implement functionality based on description
    return 0
}}'''
        
        elif language.lower() in ["cpp", "c++"]:
            return f'''#include <iostream>
using namespace std;

/**
 * Generated code for: {description}
 * Created by Enhanced Code Generator
 */
int main() {{
    cout << "Generated code for: {description}" << endl;
    // TODO: Implement functionality based on description
    return 0;
}}'''
        
        else:
            return f'// Generated code for: {description}\\n// Language: {language}\\n// TODO: Implement functionality'

class ProjectTemplateGenerator:
    """
    Generates complete project structures
    Integrates with your existing file management system
    """
    
    def __init__(self, ide_instance, code_generator: RealCodeGenerator):
        self.ide = ide_instance
        self.code_gen = code_generator
    
    def create_project(self, name: str, project_type: str, language: str, output_dir: str) -> bool:
        """Create a complete project structure"""
        
        try:
            project_path = Path(output_dir) / name
            project_path.mkdir(parents=True, exist_ok=True)
            
            if project_type == "console_app":
                return self.create_console_project(name, language, project_path)
            elif project_type == "gui_app":
                return self.create_gui_project(name, language, project_path)
            elif project_type == "web_service":
                return self.create_web_project(name, language, project_path)
            else:
                return self.create_basic_project(name, language, project_path)
                
        except Exception as e:
            if hasattr(self.ide, 'log_message'):
                self.ide.log_message(f"Project creation failed: {e}")
            return False
    
    def create_console_project(self, name: str, language: str, project_path: Path) -> bool:
        """Create console application project"""
        
        # Main source file
        if language == "python":
            main_file = project_path / f"{name.lower()}.py"
            code = self.code_gen.templates["console_app"]["python"].format(name=name)
        elif language == "eon":
            main_file = project_path / f"{name.lower()}.eon"
            code = self.code_gen.templates["console_app"]["eon"].format(name=name)
        elif language in ["cpp", "c++"]:
            main_file = project_path / "main.cpp"
            code = self.code_gen.templates["console_app"]["cpp"].format(name=name)
        else:
            main_file = project_path / f"main.{language}"
            code = f"// {name} - Console Application\\n// Generated by Enhanced Code Generator\\n"
        
        main_file.write_text(code, encoding='utf-8')
        
        # README
        readme_content = f"""# {name}

Console application generated by Enhanced Code Generator.

## Build and Run

### {language.capitalize()}
"""
        
        if language == "python":
            readme_content += f"""
```bash
python {name.lower()}.py
```"""
        elif language == "eon":
            readme_content += f"""
```bash
# Compile with EON compiler
eon compile {name.lower()}.eon
./{name.lower()}
```"""
        elif language in ["cpp", "c++"]:
            readme_content += f"""
```bash
g++ -o {name.lower()} main.cpp
./{name.lower()}
```"""
        
        (project_path / "README.md").write_text(readme_content, encoding='utf-8')
        
        return True
    
    def create_gui_project(self, name: str, language: str, project_path: Path) -> bool:
        """Create GUI application project"""
        
        if language == "python":
            main_file = project_path / f"{name.lower()}_gui.py"
            class_name = self.code_gen.to_class_name(name)
            code = self.code_gen.templates["gui_app"]["python"].format(name=name, class_name=class_name)
            main_file.write_text(code, encoding='utf-8')
            
            # Requirements file
            requirements = """# GUI Application Requirements
tkinter  # Usually included with Python
# Add other dependencies as needed
"""
            (project_path / "requirements.txt").write_text(requirements, encoding='utf-8')
            
        elif language == "eon":
            main_file = project_path / f"{name.lower()}_gui.eon"
            class_name = self.code_gen.to_class_name(name)
            code = self.code_gen.templates["gui_app"]["eon"].format(name=name, class_name=class_name)
            main_file.write_text(code, encoding='utf-8')
        
        # Create README
        readme_content = f"""# {name} GUI Application

GUI application generated by Enhanced Code Generator.

## Features
- Modern user interface
- Event-driven architecture
- Cross-platform compatibility

## Run
```bash
python {name.lower()}_gui.py
```
"""
        (project_path / "README.md").write_text(readme_content, encoding='utf-8')
        
        return True
    
    def create_web_project(self, name: str, language: str, project_path: Path) -> bool:
        """Create web service project"""
        
        if language == "python":
            main_file = project_path / f"{name.lower()}_server.py"
            class_name = self.code_gen.to_class_name(name)
            code = self.code_gen.templates["web_service"]["python"].format(name=name, class_name=class_name)
            main_file.write_text(code, encoding='utf-8')
        
        # Create static files directory
        static_dir = project_path / "static"
        static_dir.mkdir(exist_ok=True)
        
        # Basic CSS
        css_content = """/* Generated styles */
body {
    font-family: Arial, sans-serif;
    margin: 40px;
    background-color: #f5f5f5;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}
"""
        (static_dir / "styles.css").write_text(css_content, encoding='utf-8')
        
        # Create README
        readme_content = f"""# {name} Web Service

RESTful web service generated by Enhanced Code Generator.

## API Endpoints

- `GET /` - Main page
- `GET /api/status` - Service status  
- `POST /api/echo` - Echo JSON data

## Run
```bash
python {name.lower()}_server.py
```

Then visit: http://localhost:8080
"""
        (project_path / "README.md").write_text(readme_content, encoding='utf-8')
        
        return True
    
    def create_basic_project(self, name: str, language: str, project_path: Path) -> bool:
        """Create basic project structure"""
        
        main_file = project_path / f"main.{language}"
        code = f"""// {name} - Basic Project
// Generated by Enhanced Code Generator
// Language: {language}

// TODO: Implement your application logic here
"""
        main_file.write_text(code, encoding='utf-8')
        
        readme_content = f"""# {name}

Basic {language} project generated by Enhanced Code Generator.

## Getting Started

Edit `main.{language}` to implement your application.
"""
        (project_path / "README.md").write_text(readme_content, encoding='utf-8')
        
        return True

# Integration function for your existing IDE
def integrate_with_ide(ide_instance):
    """
    Integration point for your existing 3,653-line EON Compiler GUI
    Call this from your main IDE to add enhanced code generation
    """
    
    # Create code generator
    code_gen = RealCodeGenerator(ide_instance)
    project_gen = ProjectTemplateGenerator(ide_instance, code_gen)
    
    # Add to IDE instance
    ide_instance.code_generator = code_gen
    ide_instance.project_generator = project_gen
    
    # Add menu items (if your IDE supports it)
    if hasattr(ide_instance, 'add_menu_item'):
        ide_instance.add_menu_item("Tools", "Generate Code from Description", lambda: show_code_generator_dialog(ide_instance))
        ide_instance.add_menu_item("File", "New Project from Template", lambda: show_project_generator_dialog(ide_instance))
    
    print("✅ Enhanced Code Generator integrated with IDE")
    
    return code_gen, project_gen

def show_code_generator_dialog(ide_instance):
    """Show code generator dialog (integrates with your Tkinter GUI)"""
    
    import tkinter as tk
    from tkinter import ttk, messagebox
    
    dialog = tk.Toplevel(ide_instance.root if hasattr(ide_instance, 'root') else None)
    dialog.title("Generate Code from Description")
    dialog.geometry("600x400")
    
    # Description input
    ttk.Label(dialog, text="Describe what you want to create:").pack(pady=5)
    description_text = tk.Text(dialog, height=4, width=70)
    description_text.pack(pady=5, padx=10, fill='x')
    
    # Language selection
    ttk.Label(dialog, text="Target Language:").pack(pady=5)
    language_var = tk.StringVar(value="python")
    language_combo = ttk.Combobox(dialog, textvariable=language_var, 
                                 values=["python", "eon", "cpp", "javascript", "java", "csharp"])
    language_combo.pack(pady=5)
    
    # Output area
    ttk.Label(dialog, text="Generated Code:").pack(pady=(10,5))
    output_text = tk.Text(dialog, height=15, width=70)
    output_text.pack(pady=5, padx=10, fill='both', expand=True)
    
    def generate():
        description = description_text.get(1.0, tk.END).strip()
        if not description:
            messagebox.showwarning("Warning", "Please enter a description")
            return
        
        try:
            code = ide_instance.code_generator.generate_from_description(description, language_var.get())
            output_text.delete(1.0, tk.END)
            output_text.insert(1.0, code)
        except Exception as e:
            messagebox.showerror("Error", f"Code generation failed: {e}")
    
    def insert_into_editor():
        code = output_text.get(1.0, tk.END).strip()
        if code and hasattr(ide_instance, 'insert_text'):
            ide_instance.insert_text(code)
            dialog.destroy()
    
    # Buttons
    button_frame = ttk.Frame(dialog)
    button_frame.pack(pady=10)
    
    ttk.Button(button_frame, text="Generate", command=generate).pack(side='left', padx=5)
    ttk.Button(button_frame, text="Insert into Editor", command=insert_into_editor).pack(side='left', padx=5)
    ttk.Button(button_frame, text="Close", command=dialog.destroy).pack(side='left', padx=5)

def show_project_generator_dialog(ide_instance):
    """Show project generator dialog"""
    
    import tkinter as tk
    from tkinter import ttk, messagebox, filedialog
    
    dialog = tk.Toplevel(ide_instance.root if hasattr(ide_instance, 'root') else None)
    dialog.title("Create New Project")
    dialog.geometry("500x350")
    
    # Project name
    ttk.Label(dialog, text="Project Name:").pack(pady=5)
    name_var = tk.StringVar(value="MyProject")
    name_entry = ttk.Entry(dialog, textvariable=name_var, width=50)
    name_entry.pack(pady=5)
    
    # Project type
    ttk.Label(dialog, text="Project Type:").pack(pady=5)
    type_var = tk.StringVar(value="console_app")
    type_combo = ttk.Combobox(dialog, textvariable=type_var, 
                             values=["console_app", "gui_app", "web_service"])
    type_combo.pack(pady=5)
    
    # Language
    ttk.Label(dialog, text="Language:").pack(pady=5)
    lang_var = tk.StringVar(value="python")
    lang_combo = ttk.Combobox(dialog, textvariable=lang_var, 
                             values=["python", "eon", "cpp", "javascript"])
    lang_combo.pack(pady=5)
    
    # Output directory
    ttk.Label(dialog, text="Output Directory:").pack(pady=5)
    dir_var = tk.StringVar(value=os.getcwd())
    dir_frame = ttk.Frame(dialog)
    dir_frame.pack(pady=5, fill='x', padx=10)
    dir_entry = ttk.Entry(dir_frame, textvariable=dir_var)
    dir_entry.pack(side='left', fill='x', expand=True)
    
    def browse_dir():
        directory = filedialog.askdirectory(initialdir=dir_var.get())
        if directory:
            dir_var.set(directory)
    
    ttk.Button(dir_frame, text="Browse", command=browse_dir).pack(side='right', padx=(5,0))
    
    def create_project():
        try:
            success = ide_instance.project_generator.create_project(
                name_var.get(), type_var.get(), lang_var.get(), dir_var.get()
            )
            if success:
                messagebox.showinfo("Success", f"Project '{name_var.get()}' created successfully!")
                dialog.destroy()
            else:
                messagebox.showerror("Error", "Failed to create project")
        except Exception as e:
            messagebox.showerror("Error", f"Project creation failed: {e}")
    
    # Buttons
    button_frame = ttk.Frame(dialog)
    button_frame.pack(pady=20)
    
    ttk.Button(button_frame, text="Create Project", command=create_project).pack(side='left', padx=5)
    ttk.Button(button_frame, text="Cancel", command=dialog.destroy).pack(side='left', padx=5)

if __name__ == "__main__":
    # Test the code generator
    print("🚀 Enhanced Code Generator - Test Mode")
    
    class MockIDE:
        def __init__(self):
            self.ai_system = None  # Simulate no AI initially
    
    ide = MockIDE()
    code_gen = RealCodeGenerator(ide)
    
    # Test code generation
    test_descriptions = [
        "Create a console app called Calculator",
        "Make a GUI application named FileManager", 
        "Create a web service called ApiServer"
    ]
    
    for desc in test_descriptions:
        print(f"\n--- Testing: {desc} ---")
        code = code_gen.generate_from_description(desc, "python")
        print(f"Generated {len(code)} characters of code")
        print(f"First 100 chars: {code[:100]}...")
    
    print("\n✅ Enhanced Code Generator tests completed!")
