#!/usr/bin/env python3
"""
Universal Extension Compiler
Can compile source code to ANY extension dynamically
Generated by ASM to Universal Compiler Runtime
"""

import sys
import os
import subprocess
import tempfile
import shutil
from pathlib import Path
import mimetypes
import time
import json
import zipfile
import tarfile
import gzip

class UniversalExtensionCompiler:
    """Universal compiler that can output to ANY extension"""
    
    def __init__(self):
        self.spec = {
            'name': 'Universal Extension Compiler',
            'source_language': 'any',
            'target_language': 'any',
            'target_type': 'any',
            'language_type': 'any',
            'extensions': ['*'],
            'output_format': 'any',
            'optimization_level': 2,
            'debug_info': True
        }
        
        # Universal extension mapping
        self.extension_handlers = {
            # Executable formats
            '.exe': self._compile_to_exe,
            '.bin': self._compile_to_binary,
            '.elf': self._compile_to_elf,
            '.mach': self._compile_to_mach,
            
            # Script formats
            '.py': self._compile_to_python,
            '.js': self._compile_to_javascript,
            '.rb': self._compile_to_ruby,
            '.pl': self._compile_to_perl,
            '.sh': self._compile_to_shell,
            '.bat': self._compile_to_batch,
            '.ps1': self._compile_to_powershell,
            
            # Bytecode formats
            '.pyc': self._compile_to_python_bytecode,
            '.class': self._compile_to_java_bytecode,
            '.o': self._compile_to_object,
            '.so': self._compile_to_shared_lib,
            '.dll': self._compile_to_dll,
            
            # Source formats
            '.c': self._compile_to_c,
            '.cpp': self._compile_to_cpp,
            '.java': self._compile_to_java,
            '.rs': self._compile_to_rust,
            '.go': self._compile_to_go,
            '.cs': self._compile_to_csharp,
            '.php': self._compile_to_php,
            '.swift': self._compile_to_swift,
            '.kt': self._compile_to_kotlin,
            '.scala': self._compile_to_scala,
            
            # Web formats
            '.html': self._compile_to_html,
            '.css': self._compile_to_css,
            '.xml': self._compile_to_xml,
            '.json': self._compile_to_json,
            '.yaml': self._compile_to_yaml,
            '.toml': self._compile_to_toml,
            
            # Data formats
            '.csv': self._compile_to_csv,
            '.tsv': self._compile_to_tsv,
            '.sql': self._compile_to_sql,
            '.md': self._compile_to_markdown,
            '.txt': self._compile_to_text,
            
            # Archive formats
            '.zip': self._compile_to_zip,
            '.tar': self._compile_to_tar,
            '.gz': self._compile_to_gzip,
            
            # Media formats
            '.png': self._compile_to_png,
            '.jpg': self._compile_to_jpeg,
            '.gif': self._compile_to_gif,
            '.svg': self._compile_to_svg,
            
            # Custom extensions
            '.custom': self._compile_to_custom,
            '.unknown': self._compile_to_unknown
        }
    
    def compile(self, source_file: str, output_file: str = None) -> bool:
        """Compile source file to ANY extension"""
        try:
            if not output_file:
                output_file = self._get_output_filename(source_file)
            
            # Detect target extension
            target_ext = os.path.splitext(output_file)[1].lower()
            
            print(f"🔨 Compiling {source_file} to {output_file} ({target_ext})...")
            
            # Read source file
            with open(source_file, 'r', encoding='utf-8') as f:
                source_code = f.read()
            
            # Get handler for extension
            handler = self.extension_handlers.get(target_ext, self._compile_to_unknown)
            
            # Compile to target extension
            success = handler(source_code, output_file)
            
            if success:
                print(f"✅ Successfully compiled to {target_ext}: {output_file}")
                return True
            else:
                print(f"❌ Failed to compile to {target_ext}")
                return False
                
        except Exception as e:
            print(f"❌ Compilation failed: {str(e)}")
            return False
    
    def _get_output_filename(self, source_file: str) -> str:
        """Get output filename with appropriate extension"""
        base_name = os.path.splitext(source_file)[0]
        return f"{base_name}.exe"  # Default to executable
    
    # Universal extension handlers
    def _compile_to_exe(self, source_code: str, output_file: str) -> bool:
        """Compile to Windows executable"""
        return self._compile_to_executable(source_code, output_file, 'exe')
    
    def _compile_to_binary(self, source_code: str, output_file: str) -> bool:
        """Compile to binary format"""
        return self._compile_to_executable(source_code, output_file, 'bin')
    
    def _compile_to_elf(self, source_code: str, output_file: str) -> bool:
        """Compile to ELF executable"""
        return self._compile_to_executable(source_code, output_file, 'elf')
    
    def _compile_to_mach(self, source_code: str, output_file: str) -> bool:
        """Compile to Mach-O executable"""
        return self._compile_to_executable(source_code, output_file, 'mach')
    
    def _compile_to_python(self, source_code: str, output_file: str) -> bool:
        """Compile to Python script"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# Generated Python code\n")
            f.write(f"# Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_python(source_code))
        return True
    
    def _compile_to_javascript(self, source_code: str, output_file: str) -> bool:
        """Compile to JavaScript"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated JavaScript code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_javascript(source_code))
        return True
    
    def _compile_to_ruby(self, source_code: str, output_file: str) -> bool:
        """Compile to Ruby script"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# Generated Ruby code\n")
            f.write(f"# Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_ruby(source_code))
        return True
    
    def _compile_to_perl(self, source_code: str, output_file: str) -> bool:
        """Compile to Perl script"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"#!/usr/bin/perl\n")
            f.write(f"# Generated Perl code\n")
            f.write(f"# Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_perl(source_code))
        return True
    
    def _compile_to_shell(self, source_code: str, output_file: str) -> bool:
        """Compile to shell script"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"#!/bin/bash\n")
            f.write(f"# Generated shell script\n")
            f.write(f"# Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_shell(source_code))
        os.chmod(output_file, 0o755)
        return True
    
    def _compile_to_batch(self, source_code: str, output_file: str) -> bool:
        """Compile to batch file"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"@echo off\n")
            f.write(f"REM Generated batch file\n")
            f.write(f"REM Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_batch(source_code))
        return True
    
    def _compile_to_powershell(self, source_code: str, output_file: str) -> bool:
        """Compile to PowerShell script"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# Generated PowerShell script\n")
            f.write(f"# Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_powershell(source_code))
        return True
    
    def _compile_to_python_bytecode(self, source_code: str, output_file: str) -> bool:
        """Compile to Python bytecode"""
        try:
            import py_compile
            # Create temporary Python file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
                f.write(source_code)
                temp_py = f.name
            
            # Compile to bytecode
            py_compile.compile(temp_py, output_file, doraise=True)
            os.unlink(temp_py)
            return True
        except Exception as e:
            print(f"Bytecode compilation failed: {e}")
            return False
    
    def _compile_to_java_bytecode(self, source_code: str, output_file: str) -> bool:
        """Compile to Java bytecode"""
        try:
            # Create temporary Java file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.java', delete=False) as f:
                f.write(source_code)
                temp_java = f.name
            
            # Compile with javac
            result = subprocess.run(['javac', '-d', os.path.dirname(output_file), temp_java], 
                                  capture_output=True, text=True)
            os.unlink(temp_java)
            return result.returncode == 0
        except Exception as e:
            print(f"Java bytecode compilation failed: {e}")
            return False
    
    def _compile_to_object(self, source_code: str, output_file: str) -> bool:
        """Compile to object file"""
        return self._compile_to_executable(source_code, output_file, 'o')
    
    def _compile_to_shared_lib(self, source_code: str, output_file: str) -> bool:
        """Compile to shared library"""
        return self._compile_to_executable(source_code, output_file, 'so')
    
    def _compile_to_dll(self, source_code: str, output_file: str) -> bool:
        """Compile to DLL"""
        return self._compile_to_executable(source_code, output_file, 'dll')
    
    def _compile_to_c(self, source_code: str, output_file: str) -> bool:
        """Compile to C source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"/* Generated C code */\n")
            f.write(f"/* Source: {self.spec['source_language']} */\n\n")
            f.write(self._transpile_to_c(source_code))
        return True
    
    def _compile_to_cpp(self, source_code: str, output_file: str) -> bool:
        """Compile to C++ source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated C++ code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_cpp(source_code))
        return True
    
    def _compile_to_java(self, source_code: str, output_file: str) -> bool:
        """Compile to Java source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated Java code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_java(source_code))
        return True
    
    def _compile_to_rust(self, source_code: str, output_file: str) -> bool:
        """Compile to Rust source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated Rust code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_rust(source_code))
        return True
    
    def _compile_to_go(self, source_code: str, output_file: str) -> bool:
        """Compile to Go source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated Go code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_go(source_code))
        return True
    
    def _compile_to_csharp(self, source_code: str, output_file: str) -> bool:
        """Compile to C# source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated C# code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_csharp(source_code))
        return True
    
    def _compile_to_php(self, source_code: str, output_file: str) -> bool:
        """Compile to PHP source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"<?php\n")
            f.write(f"// Generated PHP code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_php(source_code))
        return True
    
    def _compile_to_swift(self, source_code: str, output_file: str) -> bool:
        """Compile to Swift source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated Swift code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_swift(source_code))
        return True
    
    def _compile_to_kotlin(self, source_code: str, output_file: str) -> bool:
        """Compile to Kotlin source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated Kotlin code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_kotlin(source_code))
        return True
    
    def _compile_to_scala(self, source_code: str, output_file: str) -> bool:
        """Compile to Scala source"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"// Generated Scala code\n")
            f.write(f"// Source: {self.spec['source_language']}\n\n")
            f.write(self._transpile_to_scala(source_code))
        return True
    
    def _compile_to_html(self, source_code: str, output_file: str) -> bool:
        """Compile to HTML"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"<!DOCTYPE html>\n<html>\n<head>\n")
            f.write(f"<title>Generated from {self.spec['source_language']}</title>\n")
            f.write(f"</head>\n<body>\n")
            f.write(f"<pre>{self._escape_html(source_code)}</pre>\n")
            f.write(f"</body>\n</html>")
        return True
    
    def _compile_to_css(self, source_code: str, output_file: str) -> bool:
        """Compile to CSS"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"/* Generated CSS from {self.spec['source_language']} */\n")
            f.write(self._transpile_to_css(source_code))
        return True
    
    def _compile_to_xml(self, source_code: str, output_file: str) -> bool:
        """Compile to XML"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
            f.write(f"<generated source=\"{self.spec['source_language']}\">\n")
            f.write(f"<code>{self._escape_xml(source_code)}</code>\n")
            f.write(f"</generated>")
        return True
    
    def _compile_to_json(self, source_code: str, output_file: str) -> bool:
        """Compile to JSON"""
        data = {
            "source_language": self.spec['source_language'],
            "target_language": self.spec['target_language'],
            "code": source_code,
            "generated_at": time.time()
        }
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        return True
    
    def _compile_to_yaml(self, source_code: str, output_file: str) -> bool:
        """Compile to YAML"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# Generated YAML from {self.spec['source_language']}\n")
            f.write(f"source_language: {self.spec['source_language']}\n")
            f.write(f"target_language: {self.spec['target_language']}\n")
            f.write(f"code: |\n")
            for line in source_code.split('\n'):
                f.write(f"  {line}\n")
        return True
    
    def _compile_to_toml(self, source_code: str, output_file: str) -> bool:
        """Compile to TOML"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# Generated TOML from {self.spec['source_language']}\n")
            f.write(f"source_language = \"{self.spec['source_language']}\"\n")
            f.write(f"target_language = \"{self.spec['target_language']}\"\n")
            f.write(f"code = \"\"\"\n{source_code}\n\"\"\"\n")
        return True
    
    def _compile_to_csv(self, source_code: str, output_file: str) -> bool:
        """Compile to CSV"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"line,content\n")
            for i, line in enumerate(source_code.split('\n'), 1):
                f.write(f"{i},\"{line.replace('\"', '\"\"')}\"\n")
        return True
    
    def _compile_to_tsv(self, source_code: str, output_file: str) -> bool:
        """Compile to TSV"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"line\tcontent\n")
            for i, line in enumerate(source_code.split('\n'), 1):
                f.write(f"{i}\t{line}\n")
        return True
    
    def _compile_to_sql(self, source_code: str, output_file: str) -> bool:
        """Compile to SQL"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"-- Generated SQL from {self.spec['source_language']}\n")
            f.write(f"CREATE TABLE generated_code (\n")
            f.write(f"    id INTEGER PRIMARY KEY,\n")
            f.write(f"    line_number INTEGER,\n")
            f.write(f"    content TEXT\n")
            f.write(f");\n\n")
            for i, line in enumerate(source_code.split('\n'), 1):
                escaped_line = line.replace("'", "''")
                f.write(f"INSERT INTO generated_code (line_number, content) VALUES ({i}, '{escaped_line}');\n")
        return True
    
    def _compile_to_markdown(self, source_code: str, output_file: str) -> bool:
        """Compile to Markdown"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# Generated Code from {self.spec['source_language']}\n\n")
            f.write(f"## Source Code\n\n")
            f.write(f"```{self.spec['source_language']}\n{source_code}\n```\n")
        return True
    
    def _compile_to_text(self, source_code: str, output_file: str) -> bool:
        """Compile to plain text"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"Generated from {self.spec['source_language']}\n")
            f.write(f"=" * 50 + "\n\n")
            f.write(source_code)
        return True
    
    def _compile_to_zip(self, source_code: str, output_file: str) -> bool:
        """Compile to ZIP archive"""
        with zipfile.ZipFile(output_file, 'w') as zf:
            zf.writestr('source.txt', source_code)
            zf.writestr('info.txt', f"Generated from {self.spec['source_language']}")
        return True
    
    def _compile_to_tar(self, source_code: str, output_file: str) -> bool:
        """Compile to TAR archive"""
        with tarfile.open(output_file, 'w') as tf:
            import io
            source_file = io.BytesIO(source_code.encode('utf-8'))
            tarinfo = tarfile.TarInfo(name='source.txt')
            tarinfo.size = len(source_code)
            tf.addfile(tarinfo, source_file)
        return True
    
    def _compile_to_gzip(self, source_code: str, output_file: str) -> bool:
        """Compile to GZIP archive"""
        with gzip.open(output_file, 'wt') as f:
            f.write(f"Generated from {self.spec['source_language']}\n")
            f.write(source_code)
        return True
    
    def _compile_to_png(self, source_code: str, output_file: str) -> bool:
        """Compile to PNG image"""
        try:
            from PIL import Image, ImageDraw, ImageFont
            # Create image with code
            img = Image.new('RGB', (800, 600), color='white')
            draw = ImageDraw.Draw(img)
            try:
                font = ImageFont.truetype("arial.ttf", 12)
            except:
                font = ImageFont.load_default()
            
            y = 10
            for line in source_code.split('\n')[:40]:  # Limit to 40 lines
                draw.text((10, y), line, fill='black', font=font)
                y += 15
            
            img.save(output_file)
            return True
        except ImportError:
            print("PIL not available, creating text file instead")
            return self._compile_to_text(source_code, output_file)
    
    def _compile_to_jpeg(self, source_code: str, output_file: str) -> bool:
        """Compile to JPEG image"""
        return self._compile_to_png(source_code, output_file.replace('.jpg', '.png'))
    
    def _compile_to_gif(self, source_code: str, output_file: str) -> bool:
        """Compile to GIF image"""
        return self._compile_to_png(source_code, output_file.replace('.gif', '.png'))
    
    def _compile_to_svg(self, source_code: str, output_file: str) -> bool:
        """Compile to SVG"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600">\n')
            f.write(f'<rect width="800" height="600" fill="white"/>\n')
            f.write(f'<text x="10" y="20" font-family="monospace" font-size="12">\n')
            for i, line in enumerate(source_code.split('\n')[:40]):
                f.write(f'<tspan x="10" dy="15">{self._escape_svg(line)}</tspan>\n')
            f.write(f'</text>\n')
            f.write(f'</svg>')
        return True
    
    def _compile_to_custom(self, source_code: str, output_file: str) -> bool:
        """Compile to custom format"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"CUSTOM FORMAT GENERATED FROM {self.spec['source_language'].upper()}\n")
            f.write(f"=====================================\n\n")
            f.write(source_code)
        return True
    
    def _compile_to_unknown(self, source_code: str, output_file: str) -> bool:
        """Compile to unknown extension - try to detect and handle"""
        ext = os.path.splitext(output_file)[1].lower()
        
        # Default handling
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# Generated from {self.spec['source_language']} to {ext}\n")
            f.write(f"# Unknown extension: {ext}\n\n")
            f.write(source_code)
        return True
    
    def _compile_to_executable(self, source_code: str, output_file: str, format_type: str) -> bool:
        """Compile to executable format"""
        try:
            # Create temporary source file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.c', delete=False) as f:
                f.write(source_code)
                temp_source = f.name
            
            # Compile with gcc
            result = subprocess.run(['gcc', '-o', output_file, temp_source], 
                                  capture_output=True, text=True)
            
            os.unlink(temp_source)
            return result.returncode == 0
            
        except Exception as e:
            print(f"Executable compilation failed: {e}")
            return False
    
    # Transpilation methods
    def _transpile_to_python(self, source_code: str) -> str:
        """Transpile to Python"""
        return f"# Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_javascript(self, source_code: str) -> str:
        """Transpile to JavaScript"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_ruby(self, source_code: str) -> str:
        """Transpile to Ruby"""
        return f"# Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_perl(self, source_code: str) -> str:
        """Transpile to Perl"""
        return f"# Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_shell(self, source_code: str) -> str:
        """Transpile to shell script"""
        return f"# Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_batch(self, source_code: str) -> str:
        """Transpile to batch file"""
        return f"REM Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_powershell(self, source_code: str) -> str:
        """Transpile to PowerShell"""
        return f"# Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_c(self, source_code: str) -> str:
        """Transpile to C"""
        return f"/* Transpiled from {self.spec['source_language']} */\n{source_code}"
    
    def _transpile_to_cpp(self, source_code: str) -> str:
        """Transpile to C++"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_java(self, source_code: str) -> str:
        """Transpile to Java"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_rust(self, source_code: str) -> str:
        """Transpile to Rust"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_go(self, source_code: str) -> str:
        """Transpile to Go"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_csharp(self, source_code: str) -> str:
        """Transpile to C#"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_php(self, source_code: str) -> str:
        """Transpile to PHP"""
        return f"<?php\n// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_swift(self, source_code: str) -> str:
        """Transpile to Swift"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_kotlin(self, source_code: str) -> str:
        """Transpile to Kotlin"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_scala(self, source_code: str) -> str:
        """Transpile to Scala"""
        return f"// Transpiled from {self.spec['source_language']}\n{source_code}"
    
    def _transpile_to_css(self, source_code: str) -> str:
        """Transpile to CSS"""
        return f"/* Transpiled from {self.spec['source_language']} */\n{source_code}"
    
    # Utility methods
    def _escape_html(self, text: str) -> str:
        """Escape HTML characters"""
        return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    
    def _escape_xml(self, text: str) -> str:
        """Escape XML characters"""
        return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')
    
    def _escape_svg(self, text: str) -> str:
        """Escape SVG characters"""
        return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

def main():
    """Main function"""
    if len(sys.argv) < 2:
        print("Usage: python {sys.argv[0]} <source_file> [output_file]")
        print("\nSupported extensions:")
        print("  Executables: .exe, .bin, .elf, .mach")
        print("  Scripts: .py, .js, .rb, .pl, .sh, .bat, .ps1")
        print("  Bytecode: .pyc, .class, .o, .so, .dll")
        print("  Source: .c, .cpp, .java, .rs, .go, .cs, .php, .swift, .kt, .scala")
        print("  Web: .html, .css, .xml, .json, .yaml, .toml")
        print("  Data: .csv, .tsv, .sql, .md, .txt")
        print("  Archives: .zip, .tar, .gz")
        print("  Media: .png, .jpg, .gif, .svg")
        print("  Custom: .custom, .unknown")
        sys.exit(1)
    
    source_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None
    
    compiler = UniversalExtensionCompiler()
    success = compiler.compile(source_file, output_file)
    
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
