// D:\rawrxd\generator\generator.cpp
// Sovereign Code Generator Implementation

#include "generator.hpp"
#include <filesystem>
#include <algorithm>
#include <sstream>
#include <iomanip>
#include <ctime>
#include <unordered_set>

namespace RawrXD::CodeGen {

SovereignGenerator::SovereignGenerator(const GeneratorConfig& config)
    : config_(config)
    , builder_(std::make_unique<CodeBuilder>())
    , emitter_(std::make_unique<FileEmitter>())
{
    // Ensure output directory exists
    emitter_->SetOutputDirectory(config.output_directory);
}

SovereignGenerator::~SovereignGenerator() = default;

std::expected<std::vector<GeneratedFile>, GeneratorError> 
SovereignGenerator::Generate(const AST::Module& schema) {
    // Validate schema before generation
    if (auto validation = ValidateAST(schema); !validation) {
        return std::unexpected(validation.error());
    }
    
    std::vector<GeneratedFile> files;
    
    // Generate each type
    for (const auto& type : schema.types) {
        if (config_.generate_header) {
            if (auto header = GenerateHeader(type); header) {
                files.push_back(std::move(*header));
            } else {
                return std::unexpected(header.error());
            }
        }
        
        if (config_.generate_source && !type.is_struct) {
            if (auto source = GenerateSource(type); source) {
                files.push_back(std::move(*source));
            } else {
                return std::unexpected(source.error());
            }
        }
    }
    
    return files;
}

std::expected<void, GeneratorError> 
SovereignGenerator::ValidateAST(const AST::Module& schema) {
    // Check for circular dependencies
    std::unordered_set<std::string> visited;
    std::unordered_set<std::string> in_stack;
    
    std::function<bool(const std::string&)> has_cycle = [&](const std::string& type_name) -> bool {
        if (in_stack.count(type_name)) return true;
        if (visited.count(type_name)) return false;
        
        visited.insert(type_name);
        in_stack.insert(type_name);
        
        // Find dependencies
        for (const auto& type : schema.types) {
            if (type.name == type_name) {
                for (const auto& field : type.fields) {
                    if (has_cycle(field.type_name)) return true;
                }
                for (const auto& method : type.methods) {
                    for (const auto& param : method.parameters) {
                        if (has_cycle(param.type_name)) return true;
                    }
                }
            }
        }
        
        in_stack.erase(type_name);
        return false;
    };
    
    for (const auto& type : schema.types) {
        if (has_cycle(type.name)) {
            return std::unexpected(GeneratorError::CircularDependency);
        }
    }
    
    return {};
}

std::expected<GeneratedFile, GeneratorError> 
SovereignGenerator::GenerateHeader(const AST::Type& type) {
    GeneratedFile file;
    file.relative_path = type.name + ".hpp";
    file.is_header = true;
    
    std::ostringstream oss;
    
    // Header guard
    std::string guard = "RAWRXD_GENERATED_" + type.name + "_HPP";
    std::transform(guard.begin(), guard.end(), guard.begin(), ::toupper);
    
    // File header
    oss << "// D:\\rawrxd\\generated\\" << type.name << ".hpp\n";
    oss << "// AUTO-GENERATED BY RAWRXD CODE GENERATOR - DO NOT EDIT\n";
    
    // Generate timestamp
    auto now = std::time(nullptr);
    auto gmt = std::gmtime(&now);
    char time_str[32];
    std::strftime(time_str, sizeof(time_str), "%FT%TZ", gmt);
    oss << "// Generated: " << time_str << "\n\n";
    
    oss << "#pragma once\n\n";
    oss << "#ifndef " << guard << "\n";
    oss << "#define " << guard << "\n\n";
    
    // Include dependencies
    oss << "#include <expected>\n";
    oss << "#include <vector>\n";
    oss << "#include <string>\n";
    oss << "#include <memory>\n";
    oss << "#include <functional>\n";
    if (config_.atomic_transactions) {
        oss << "#include <mutex>\n";
    }
    oss << "\n";
    
    // Namespace begin
    oss << "namespace " << config_.namespace_name << " {\n\n";
    
    // Forward declarations
    for (const auto& dep : type.dependencies) {
        oss << "class " << dep << ";\n";
    }
    if (!type.dependencies.empty()) oss << "\n";
    
    // Error enum (minimal)
    oss << "enum class Error {\n";
    oss << "    Success = 0,\n";
    oss << "    InvalidParameter = 1,\n";
    oss << "    TransactionFailed = 2,\n";
    oss << "    CommitFailed = 3,\n";
    oss << "    FileAccessDenied = 4,\n";
    oss << "    BridgeCorruption = 5\n";
    oss << "};\n\n";
    
    // Class/Struct declaration
    if (type.is_struct) {
        oss << "struct " << type.name << " {\n";
        // Fields (for structs)
        for (const auto& field : type.fields) {
            oss << "    " << field.type_name << " " << field.name;
            if (!field.default_value.empty()) {
                oss << " = " << field.default_value;
            }
            oss << ";\n";
        }
        oss << "};\n\n";
    } else {
        oss << "class " << type.name << " {\n";
        oss << "public:\n";
        oss << "    " << type.name << "() = default;\n";
        oss << "    ~" << type.name << "() = default;\n";
        oss << "    " << type.name << "(const " << type.name << "&) = delete;\n";
        oss << "    " << type.name << "& operator=(const " << type.name << "&) = delete;\n";
        oss << "    " << type.name << "(" << type.name << "&&) = default;\n";
        oss << "    " << type.name << "& operator=(" << type.name << "&&) = default;\n\n";
        
        // Methods (for classes)
        for (const auto& method : type.methods) {
            oss << "    " << GenerateMethodSignature(method, true) << ";\n";
        }
        oss << "\n";
        
        // Private members
        oss << "private:\n";
        for (const auto& field : type.fields) {
            oss << "    " << field.type_name << " " << field.name << "_;\n";
        }
        
        // Atomic transaction wrapper (Sovereign pattern)
        if (config_.atomic_transactions && type.requires_atomic) {
            oss << "\n    // Sovereign Atomic Transaction Support\n";
            oss << "    mutable std::mutex transaction_mutex_;\n";
            oss << "    bool in_transaction_ = false;\n";
        }
        
        oss << "};\n";
    }
    
    oss << "\n} // namespace " << config_.namespace_name << "\n\n";
    oss << "#endif // " << guard << "\n";
    
    file.content = oss.str();
    return file;
}

std::expected<GeneratedFile, GeneratorError>
SovereignGenerator::GenerateSource(const AST::Type& type) {
    GeneratedFile file;
    file.relative_path = type.name + ".cpp";
    file.is_header = false;
    
    std::ostringstream oss;
    
    oss << "// D:\\rawrxd\\generated\\" << type.name << ".cpp\n";
    oss << "// AUTO-GENERATED BY RAWRXD CODE GENERATOR - DO NOT EDIT\n\n";
    
    oss << "#include \"" << type.name << ".hpp\"\n";
    oss << "#include <stdexcept>\n";
    oss << "#include <immintrin.h>\n\n";
    
    oss << "namespace " << config_.namespace_name << " {\n\n";
    
    // Method implementations
    for (const auto& method : type.methods) {
        oss << GenerateMethodSignature(method, false) << " {\n";
        oss << GenerateMethodBody(method, type.name);
        oss << "}\n\n";
    }
    
    oss << "} // namespace " << config_.namespace_name << "\n";
    
    file.content = oss.str();
    return file;
}

std::string SovereignGenerator::GenerateMethodSignature(const AST::Method& method, bool is_header) {
    std::ostringstream oss;
    
    // Return type with std::expected for error handling
    if (method.can_fail) {
        oss << "std::expected<" << method.return_type << ", Error> ";
    } else if (!method.return_type.empty()) {
        oss << method.return_type << " ";
    } else {
        oss << "void ";
    }
    
    oss << method.name << "(";
    
    for (size_t i = 0; i < method.parameters.size(); ++i) {
        const auto& param = method.parameters[i];
        if (param.is_const_ref) oss << "const ";
        oss << param.type_name;
        if (param.is_const_ref && param.type_name.find('*') == std::string::npos) {
            oss << "&";
        }
        if (param.is_optional) oss << "*";
        oss << " " << param.name;
        if (!param.default_value.empty()) oss << " = " << param.default_value;
        if (i < method.parameters.size() - 1) oss << ", ";
    }
    
    oss << ")";
    
    if (is_header && method.is_const) oss << " const";
    
    return oss.str();
}

std::string SovereignGenerator::GenerateMethodBody(const AST::Method& method, const std::string& class_name) {
    std::ostringstream oss;
    
    // Atomic transaction wrapper (Sovereign pattern)
    if (config_.atomic_transactions && method.requires_atomic) {
        oss << "    std::lock_guard<std::mutex> lock(transaction_mutex_);\n";
        oss << InsertMemoryBarrier("pre");
    }
    
    // Parameter validation
    for (const auto& param : method.parameters) {
        if (param.requires_validation) {
            oss << "    if (!" << param.name << ") {\n";
            oss << "        return std::unexpected(Error::InvalidParameter);\n";
            oss << "    }\n";
        }
    }
    
    // Implementation stub (would be filled by schema)
    if (!method.implementation_stub.empty()) {
        oss << "    " << method.implementation_stub << "\n";
    } else if (method.can_fail) {
        oss << "    // TODO: Implement " << method.name << "\n";
        oss << "    return " << method.return_type << "{};\n";
    } else if (method.return_type.empty()) {
        oss << "    // TODO: Implement " << method.name << "\n";
    } else {
        oss << "    // TODO: Implement " << method.name << "\n";
        oss << "    return " << method.return_type << "{};\n";
    }
    
    // Memory barrier for atomic operations
    if (config_.atomic_transactions && method.requires_atomic) {
        oss << InsertMemoryBarrier("post");
    }
    
    return oss.str();
}

std::string SovereignGenerator::WrapInAtomicScope(const std::string& code, const std::string& tx_name) {
    std::ostringstream oss;
    oss << "{\n";
    oss << "    AtomicScope " << tx_name << "_scope(\"" << tx_name << "\");\n";
    oss << "    if (!" << tx_name << "_scope.Begin()) {\n";
    oss << "        return std::unexpected(Error::TransactionFailed);\n";
    oss << "    }\n\n";
    oss << code << "\n\n";
    oss << "    if (!" << tx_name << "_scope.Commit()) {\n";
    oss << "        " << tx_name << "_scope.Rollback();\n";
    oss << "        return std::unexpected(Error::CommitFailed);\n";
    oss << "    }\n";
    oss << "}\n";
    return oss.str();
}

std::string SovereignGenerator::InsertMemoryBarrier(const std::string& location) {
    return "    _mm_mfence(); // Sovereign Memory Barrier (" + location + ")\n";
}

std::expected<std::vector<GeneratedFile>, GeneratorError>
SovereignGenerator::GenerateSelf(const GeneratorConfig& config) {
    // Generate the generator's own components
    AST::Module self_schema;
    self_schema.name = "Generator";
    self_schema.namespace_name = config.namespace_name;
    
    // Define Generator type
    AST::Type generator_type;
    generator_type.name = "SovereignGenerator";
    generator_type.is_struct = false;
    generator_type.requires_atomic = true;
    
    // Add essential methods
    AST::Method generate_method;
    generate_method.name = "Generate";
    generate_method.return_type = "std::expected<std::vector<GeneratedFile>, GeneratorError>";
    generate_method.can_fail = true;
    AST::Parameter param;
    param.type_name = "const AST::Module&";
    param.name = "schema";
    param.is_const_ref = true;
    param.requires_validation = true;
    generate_method.parameters.push_back(param);
    generate_method.requires_atomic = true;
    generator_type.methods.push_back(generate_method);
    
    self_schema.types.push_back(generator_type);
    
    SovereignGenerator self_gen(config);
    return self_gen.Generate(self_schema);
}

std::expected<std::vector<GeneratedFile>, GeneratorError>
SovereignGenerator::GenerateIncremental(const AST::Module& schema, 
                                        const std::vector<std::string>& changed_types) {
    std::vector<GeneratedFile> files;
    
    for (const auto& type_name : changed_types) {
        auto it = std::find_if(schema.types.begin(), schema.types.end(),
            [&](const AST::Type& t) { return t.name == type_name; });
        
        if (it == schema.types.end()) {
            return std::unexpected(GeneratorError::InvalidAST);
        }
        
        if (config_.generate_header) {
            if (auto header = GenerateHeader(*it); header) {
                files.push_back(std::move(*header));
            }
        }
        
        if (config_.generate_source && !it->is_struct) {
            if (auto source = GenerateSource(*it); source) {
                files.push_back(std::move(*source));
            }
        }
    }
    
    return files;
}

} // namespace RawrXD::CodeGen
