; ============================================================================
; hello.asm - Hello World Test Program for MASM Compiler
; Demonstrates basic compilation and Windows API usage
; ============================================================================


; ─── Cross-module symbol resolution ───
INCLUDE rawrxd_master.inc

.data
    message     db 'Hello from MASM Self-Compiling Compiler!', 13, 10
                db 'This executable was generated by our custom compiler.', 13, 10, 0
    messageLen  equ $ - message

.code
    extern GetStdHandle
    extern WriteFile
    extern ExitProcess

; ============================================================================
; Main Entry Point
; ============================================================================
main proc
    push rbp
    mov rbp, rsp
    sub rsp, 64                     ; Shadow space + locals
    
    ; Get stdout handle
    mov rcx, -11                    ; STD_OUTPUT_HANDLE
    call GetStdHandle
    test rax, rax
    jz .error
    mov rbx, rax                    ; Save handle
    
    ; Write message to console
    mov rcx, rbx                    ; hFile
    lea rdx, [message]              ; lpBuffer
    mov r8, messageLen              ; nNumberOfBytesToWrite
    lea r9, [rsp+48]                ; lpNumberOfBytesWritten
    mov qword ptr [rsp+32], 0       ; lpOverlapped = NULL
    call WriteFile
    
    test rax, rax
    jz .error
    
    ; Success
    xor rcx, rcx                    ; Exit code 0
    jmp .exit
    
.error:
    mov rcx, 1                      ; Exit code 1
    
.exit:
    add rsp, 64
    pop rbp
    call ExitProcess
    
    ; Should never reach here
    ret
main endp

end main
