#Requires -Version 7.0
<#
.SYNOPSIS
    Consolidates all required (real functionality) modules into a clean folder structure
.DESCRIPTION
    Copies modules identified as having real functionality (not scaffolding) into a new organized structure
.PARAMETER SourcePath
    Source directory containing all modules
.PARAMETER DestinationPath
    Destination directory for consolidated modules
.PARAMETER AnalysisPath
    Path to the scaffolding detection report
#>

param(
    [string]$SourcePath = "d:\lazy init ide",
    [string]$DestinationPath = "",
    [string]$AnalysisPath = ""
)

# Generate destination path if not specified
if (-not $DestinationPath) {
    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $DestinationPath = Join-Path $SourcePath "Consolidated_Modules_$timestamp"
}

# Create destination directory
if (-not (Test-Path $DestinationPath)) {
    New-Item -Path $DestinationPath -ItemType Directory -Force | Out-Null
    Write-Host "Created destination: $DestinationPath" -ForegroundColor Green
}

# Get all modules
$modules = Get-ChildItem -Path $SourcePath -Recurse -Filter "*.psm1" -ErrorAction SilentlyContinue

# Define critical source files to copy (CLI and GUI versions)
$criticalFiles = @(
    # CLI Version
    "RawrXD.ps1",
    
    # GUI Version and dependencies
    "RawrXD.exe",
    "RawrXD.exe.config",
    "RawrXD.ico",
    
    # Additional core files
    "RawrXD_Manifest.json",
    "config.example.json",
    "model_config.json"
)

Write-Host "=== CONSOLIDATING REQUIRED MODULES ===" -ForegroundColor Cyan
Write-Host "Source: $SourcePath" -ForegroundColor White
Write-Host "Destination: $DestinationPath" -ForegroundColor White
Write-Host "Total modules found: $($modules.Count)" -ForegroundColor Green
Write-Host ""

# Categorize modules based on our analysis
$requiredModules = @{
    "Core" = @(
        "ArchitectureEnhancementEngine.psm1",
        "ManifestTracer.psm1",
        "RawrXD.Config.psm1",
        "RawrXD.Core.psm1",
        "RawrXD.ErrorHandling.psm1",
        "RawrXD.Logging.psm1",
        "RawrXD.Metrics.psm1",
        "RawrXD.ModelLoader.psm1",
        "RawrXD.Tracing.psm1",
        "RawrXD.UI.psm1"
    )
    "Agentic" = @(
        "RawrXD.Agentic.Autonomy.psm1",
        "RawrXD.AutonomousAgent.psm1"
    )
    "Production" = @(
        "RawrXD.ProductionOrchestrator.psm1",
        "RawrXD.Win32Deployment.psm1"
    )
    "AutoGenerated_Real" = @(
        "RawrXD_AIIntervention.psm1",
        "RawrXD_UniversalIntegrator.psm1",
        "RawrXD.AgenticCommands.psm1",
        "RawrXD.AutoDependencyGraph.psm1",
        "RawrXD.AutonomousEnhancement.psm1",
        "RawrXD.AutoRefactorSuggestor.psm1",
        "RawrXD.ContinuousIntegrationTrigger.psm1",
        "RawrXD.CustomModelLoaders.psm1",
        "RawrXD.CustomModelPerformance.psm1",
        "RawrXD.DeploymentOrchestrator.psm1",
        "RawrXD.DynamicTestHarness.psm1",
        "RawrXD.FullBraceError.psm1",
        "RawrXD.LiveMetricsDashboard.psm1",
        "RawrXD.ManifestChangeNotifier.psm1",
        "RawrXD.Master.psm1",
        "RawrXD.Production.psm1",
        "RawrXD.ProductionDeployer.psm1",
        "RawrXD.ReverseEngineering.psm1",
        "RawrXD.SecurityScanner.psm1",
        "RawrXD.SelfHealingModule.psm1",
        "RawrXD.SourceCodeSummarizer.psm1",
        "RawrXD.SwarmAgent.psm1",
        "RawrXD.SwarmMaster.psm1",
        "RawrXD.SwarmOrchestrator.psm1",
        "RawrXD.TestFramework.psm1",
        "RawrXD.UltimateProduction.psm1"
    )
    "Extensions" = @(
        "PoshLLM.psm1"
    )
    "Mixed" = @(
        "RawrXD.ManifestChangeNotifier.psm1",
        "RawrXD..psm1"
    )
}

# Create folder structure
$folders = @(
    "01_Core",
    "02_Agentic",
    "03_Production",
    "04_Testing",
    "05_Security",
    "06_Extensions",
    "07_Mixed_NeedsCleanup"
)

foreach ($folder in $folders) {
    $folderPath = Join-Path $DestinationPath $folder
    if (-not (Test-Path $folderPath)) {
        New-Item -Path $folderPath -ItemType Directory -Force | Out-Null
        Write-Host "Created folder: $folder" -ForegroundColor Gray
    }
}

# Copy modules to appropriate folders
$copySummary = @()

foreach ($category in $requiredModules.Keys) {
    $targetFolder = switch ($category) {
        "Core" { "01_Core" }
        "Agentic" { "02_Agentic" }
        "Production" { "03_Production" }
        "AutoGenerated_Real" { "04_Testing" }
        "Security" { "05_Security" }
        "Extensions" { "06_Extensions" }
        "Mixed" { "07_Mixed_NeedsCleanup" }
    }
    
    $targetPath = Join-Path $DestinationPath $targetFolder
    
    foreach ($moduleName in $requiredModules[$category]) {
        # Find the module (prefer root directory version if duplicate)
        $module = $modules | Where-Object { $_.Name -eq $moduleName } | Sort-Object { 
            # Prioritize root directory, then auto_generated_methods
            if ($_.Directory.FullName -eq $SourcePath) { 0 }
            elseif ($_.Directory.Name -eq "auto_generated_methods") { 1 }
            else { 2 }
        } | Select-Object -First 1
        
        if ($module) {
            $sourceFile = $module.FullName
            $destFile = Join-Path $targetPath $moduleName
            
            try {
                Copy-Item -Path $sourceFile -Destination $destFile -Force
                
                $copySummary += [PSCustomObject]@{
                    ModuleName = $moduleName
                    Category = $category
                    SourcePath = $sourceFile -replace [regex]::Escape($SourcePath), ''
                    DestinationPath = $destFile -replace [regex]::Escape($DestinationPath), ''
                    SizeKB = [math]::Round($module.Length / 1KB, 1)
                    Status = "Copied"
                }
                
                Write-Host "✓ Copied $moduleName to $targetFolder" -ForegroundColor Green
            }
            catch {
                Write-Host "✗ Failed to copy $moduleName : $_" -ForegroundColor Red
                
                $copySummary += [PSCustomObject]@{
                    ModuleName = $moduleName
                    Category = $category
                    SourcePath = $sourceFile -replace [regex]::Escape($SourcePath), ''
                    DestinationPath = "Failed"
                    SizeKB = [math]::Round($module.Length / 1KB, 1)
                    Status = "Failed: $_"
                }
            }
        }
        else {
            Write-Host "⚠ Module not found: $moduleName" -ForegroundColor Yellow
            
            $copySummary += [PSCustomObject]@{
                ModuleName = $moduleName
                Category = $category
                SourcePath = "Not found"
                DestinationPath = "N/A"
                SizeKB = 0
                Status = "Not found"
            }
        }
    }
}

# Create manifest file
$manifestPath = Join-Path $DestinationPath "MODULE_MANIFEST.txt"
$manifestContent = @"
=== MODULE CONSOLIDATION MANIFEST ===
Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
Source: $SourcePath
Destination: $DestinationPath

=== MODULE SUMMARY ===
Total modules copied: $($copySummary.Count)
Real functionality modules: $($requiredModules.Values | ForEach-Object { $_.Count } | Measure-Object -Sum | Select-Object -ExpandProperty Sum)
Mixed modules (needs cleanup): $($requiredModules['Mixed'].Count)

=== FOLDER STRUCTURE ===
01_Core - Core framework modules
02_Agentic - Agent-based functionality
03_Production - Production/deployment modules
04_Testing - Testing and quality assurance
05_Security - Security-related modules
06_Extensions - Extension modules
07_Mixed_NeedsCleanup - Modules with scaffolding that need cleanup

=== MODULES BY CATEGORY ===

"@ + ($copySummary | Format-Table -AutoSize | Out-String)

$manifestContent | Set-Content -Path $manifestPath -Encoding UTF8

# Create cleanup recommendations
$cleanupPath = Join-Path $DestinationPath "CLEANUP_RECOMMENDATIONS.md"
$cleanupContent = @"
# Cleanup Recommendations

## Mixed Modules (Needs Cleanup)

The following modules were identified as having some scaffolding/placeholders:

$(($requiredModules['Mixed'] | ForEach-Object { "- $_" }) -join "`n")

### Recommended Actions:

1. **Remove TODO comments and placeholders**
2. **Complete incomplete functions**
3. **Remove excessive Write-Host statements**
4. **Add proper error handling**
5. **Document public functions**

## Auto-Generated Modules

The following modules were auto-generated and may need review:

$(($requiredModules['AutoGenerated_Real'] | ForEach-Object { "- $_" }) -join "`n")

### Review Criteria:

- Check for duplicate functionality with original modules
- Verify naming conventions match your standards
- Test thoroughly before production use
- Consider merging with original modules if appropriate

## Next Steps

1. Review modules in 07_Mixed_NeedsCleanup folder
2. Test all modules in the new structure
3. Update import statements to reflect new paths
4. Consider creating a master module loader
5. Document the new module organization

## Backup Information

Original location: $SourcePath
Consolidated location: $DestinationPath
Manifest file: $manifestPath

"@

$cleanupContent | Set-Content -Path $cleanupPath -Encoding UTF8

# Final summary
Write-Host ""
Write-Host "=== CONSOLIDATION COMPLETE ===" -ForegroundColor Green
Write-Host "Destination: $DestinationPath" -ForegroundColor White
Write-Host "Modules copied: $($copySummary.Count)" -ForegroundColor Green
Write-Host "Manifest: $manifestPath" -ForegroundColor White
Write-Host "Cleanup recommendations: $cleanupPath" -ForegroundColor White
Write-Host ""

# Copy critical source files (CLI and GUI versions)
Write-Host "=== COPYING CRITICAL SOURCE FILES ===" -ForegroundColor Cyan
Write-Host "Copying CLI and GUI versions..." -ForegroundColor White

$criticalFilesCopied = @()
$criticalFilesFailed = @()

foreach ($fileName in $criticalFiles) {
    $sourceFile = Join-Path $SourcePath $fileName
    $destFile = Join-Path $DestinationPath $fileName
    
    if (Test-Path $sourceFile) {
        try {
            Copy-Item -Path $sourceFile -Destination $destFile -Force
            $criticalFilesCopied += $fileName
            Write-Host "✓ Copied $fileName" -ForegroundColor Green
        }
        catch {
            $criticalFilesFailed += $fileName
            Write-Host "✗ Failed to copy $fileName : $_" -ForegroundColor Red
        }
    }
    else {
        $criticalFilesFailed += $fileName
        Write-Host "⚠ Skipped $fileName (not found)" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "Critical files copied: $($criticalFilesCopied.Count)" -ForegroundColor Green
Write-Host "Critical files failed: $($criticalFilesFailed.Count)" -ForegroundColor Red
Write-Host ""

# Create a summary of critical files
$criticalFilesSummary = @"
=== CRITICAL SOURCE FILES SUMMARY ===

Successfully copied:
$(($criticalFilesCopied | ForEach-Object { "- $_" }) -join "`n")

Failed or skipped:
$(($criticalFilesFailed | ForEach-Object { "- $_" }) -join "`n")

"@

$criticalFilesSummary | Out-File -FilePath (Join-Path $DestinationPath "CRITICAL_FILES_SUMMARY.txt") -Encoding UTF8

Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Review modules in 07_Mixed_NeedsCleanup folder" -ForegroundColor White
Write-Host "2. Test all modules in the new structure" -ForegroundColor White
Write-Host "3. Follow cleanup recommendations" -ForegroundColor White
Write-Host "4. Verify CLI and GUI versions work correctly" -ForegroundColor White
