# RawrXD-ProductionDeployment.ps1
# Comprehensive production deployment and validation script

param(
    [ValidateSet('PreDeploy', 'Deploy', 'Verify', 'Monitor', 'Rollback')]
    [string]$Mode = 'Verify',
    [string]$RawrXDRoot,
    [switch]$SkipBackup
)

# ============================================
# INITIALIZATION
# ============================================

$ErrorActionPreference = 'Stop'
$VerbosePreference = 'SilentlyContinue'
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'

if ([string]::IsNullOrWhiteSpace($RawrXDRoot)) {
    if ($env:LAZY_INIT_IDE_ROOT -and (Test-Path $env:LAZY_INIT_IDE_ROOT)) {
        $RawrXDRoot = $env:LAZY_INIT_IDE_ROOT
    } else {
        $RawrXDRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
    }
}

if (-not (Test-Path $RawrXDRoot)) {
    throw "RawrXDRoot does not exist: $RawrXDRoot"
}

$deploymentLog = Join-Path $RawrXDRoot "deployment_${timestamp}.log"

try {
    $deploymentLogDir = Split-Path -Parent $deploymentLog
    if ($deploymentLogDir -and -not (Test-Path $deploymentLogDir)) {
        New-Item -ItemType Directory -Path $deploymentLogDir -Force | Out-Null
    }
} catch {
    # Best-effort; logging will still attempt to write.
}

function Write-DeployLog {
    param(
        [string]$Message,
        [ValidateSet('INFO', 'SUCCESS', 'WARNING', 'ERROR')]
        [string]$Level = 'INFO',
        [ConsoleColor]$Color = 'Cyan'
    )
    $entryTimestamp = Get-Date -Format o
    $entry = "[$entryTimestamp] [$Level] $Message"
    Write-Host $entry -ForegroundColor $Color
    Add-Content -Path $deploymentLog -Value $entry
}

# ============================================
# PRE-DEPLOYMENT VALIDATION
# ============================================

function Invoke-PreDeployment {
    Write-DeployLog 'Starting pre-deployment validation...' INFO

    try {
        $runLogDir = Join-Path $RawrXDRoot 'logs'
        if (-not (Test-Path $runLogDir)) {
            New-Item -ItemType Directory -Path $runLogDir -Force | Out-Null
        }
        $env:RAWRXD_LOG_PATH = Join-Path $runLogDir "RawrXD_run_${timestamp}.log"
        if (-not (Test-Path $env:RAWRXD_LOG_PATH)) {
            New-Item -ItemType File -Path $env:RAWRXD_LOG_PATH -Force | Out-Null
        }
        Write-DeployLog "Using run log: $env:RAWRXD_LOG_PATH" INFO
    } catch {
        Write-DeployLog "Failed to set RAWRXD_LOG_PATH: $_" WARNING Yellow
    }
    
    $checks = @()
    
    # Check paths
    $requiredPaths = @(
        'RawrXD.Config.psm1',
        'RawrXD.Logging.psm1',
        'RawrXD.Core.psm1',
        'RawrXD.Metrics.psm1',
        'RawrXD.Tracing.psm1',
        'RawrXD.ErrorHandling.psm1',
        'RawrXD.ModelLoader.psm1',
        'RawrXD.Agentic.Autonomy.psm1',
        'RawrXD.Win32Deployment.psm1',
        'auto_generated_methods/RawrXD_UniversalIntegrator.psm1',
        'auto_generated_methods/Analyze_AutoGeneratedMethods.ps1'
    )
    
    foreach ($path in $requiredPaths) {
        $fullPath = Join-Path $RawrXDRoot $path
        $exists = Test-Path $fullPath
        $checks += @{
            Component = $path
            Status = if ($exists) { 'OK' } else { 'MISSING' }
            Details = $fullPath
        }
        Write-DeployLog "Path check: $path - $(if ($exists) { 'OK' } else { 'MISSING' })" $(if ($exists) { 'SUCCESS' } else { 'ERROR' })
    }
    
    # Run analyzer
    Write-DeployLog 'Running health analyzer...' INFO
    $analyzerPath = Join-Path $RawrXDRoot 'auto_generated_methods/Analyze_AutoGeneratedMethods.ps1'
    & $analyzerPath 2>&1 | ForEach-Object { Write-DeployLog $_ INFO }
    
    # Load and check modules
    Write-DeployLog 'Validating module imports...' INFO
    try {
        Import-Module (Join-Path $RawrXDRoot 'RawrXD.Config.psm1') -Force -ErrorAction Stop
        Write-DeployLog 'RawrXD.Config imported successfully' SUCCESS Green
    } catch {
        Write-DeployLog "RawrXD.Config import failed: $_" ERROR Red
        return $false
    }
    
    try {
        Import-Module (Join-Path $RawrXDRoot 'RawrXD.Logging.psm1') -Force -ErrorAction Stop
        Write-DeployLog 'RawrXD.Logging imported successfully' SUCCESS Green
    } catch {
        Write-DeployLog "RawrXD.Logging import failed: $_" ERROR Red
        return $false
    }
    
    try {
        Import-Module (Join-Path $RawrXDRoot 'RawrXD.Core.psm1') -Force -ErrorAction Stop
        Write-DeployLog 'RawrXD.Core imported successfully' SUCCESS Green
    } catch {
        Write-DeployLog "RawrXD.Core import failed: $_" ERROR Red
        return $false
    }
    
    # Check for issues
    $ciReportPath = Join-Path $RawrXDRoot 'auto_generated_methods/AutoGeneratedMethods_CIReport.json'
    if (Test-Path $ciReportPath) {
        $report = Get-Content $ciReportPath -Raw | ConvertFrom-Json
        Write-DeployLog "Health Status: Healthy=$($report.Healthy), Methods=$($report.TotalMethods)" $(if ($report.Healthy) { 'SUCCESS' } else { 'WARNING' }) $(if ($report.Healthy) { 'Green' } else { 'Yellow' })
        
        if (-not $report.Healthy) {
            Write-DeployLog 'Some methods are not healthy' WARNING Yellow
        }
    }
    
    Write-DeployLog 'Pre-deployment validation complete' SUCCESS Green
    return $true
}

# ============================================
# DEPLOYMENT
# ============================================

function Invoke-Deployment {
    Write-DeployLog 'Starting production deployment...' INFO

    try {
        $runLogDir = Join-Path $RawrXDRoot 'logs'
        if (-not (Test-Path $runLogDir)) {
            New-Item -ItemType Directory -Path $runLogDir -Force | Out-Null
        }
        if (-not $env:RAWRXD_LOG_PATH) {
            $env:RAWRXD_LOG_PATH = Join-Path $runLogDir "RawrXD_run_${timestamp}.log"
        }
        if (-not (Test-Path $env:RAWRXD_LOG_PATH)) {
            New-Item -ItemType File -Path $env:RAWRXD_LOG_PATH -Force | Out-Null
        }
        Write-DeployLog "Using run log: $env:RAWRXD_LOG_PATH" INFO
    } catch {
        Write-DeployLog "Failed to set RAWRXD_LOG_PATH: $_" WARNING Yellow
    }
    
    # Backup current state
    if (-not $SkipBackup) {
        Write-DeployLog 'Creating backup...' INFO
        $backupDir = Join-Path $RawrXDRoot "backup_$timestamp"
        New-Item -ItemType Directory -Path $backupDir -ErrorAction SilentlyContinue | Out-Null
        
        @('config', 'logs') | ForEach-Object {
            $source = Join-Path $RawrXDRoot $_
            $dest = Join-Path $backupDir $_
            if (Test-Path $source) {
                Copy-Item -Path $source -Destination $dest -Recurse -Force
                Write-DeployLog "Backed up $_ to $dest" SUCCESS Green
            }
        }
    }
    
    # Load universal integrator
    Write-DeployLog 'Loading universal integrator...' INFO
    $integratorPath = Join-Path $RawrXDRoot 'auto_generated_methods/RawrXD_UniversalIntegrator.psm1'
    Import-Module $integratorPath -Force
    
    # Run integration
    Write-DeployLog 'Running universal integration...' INFO
    try {
        Invoke-RawrXD_UniversalIntegration -AutoMethodsDir (Join-Path $RawrXDRoot 'auto_generated_methods') 2>&1 | ForEach-Object {
            Write-DeployLog $_ INFO
        }
        Write-DeployLog 'Universal integration completed successfully' SUCCESS Green
    } catch {
        Write-DeployLog "Integration failed: $_" ERROR Red
        return $false
    }
    
    Write-DeployLog 'Deployment complete' SUCCESS Green
    return $true
}

# ============================================
# VERIFICATION
# ============================================

function Invoke-Verification {
    Write-DeployLog 'Starting post-deployment verification...' INFO
    
    $allPassed = $true
    
    # Check integration report
    $reportPath = Join-Path $RawrXDRoot 'auto_generated_methods/integration_report.json'
    $sinceTime = (Get-Date).AddMinutes(-5)
    if (Test-Path $reportPath) {
        $report = Get-Content $reportPath -Raw | ConvertFrom-Json
        try {
            if ($report.Timestamp) {
                $sinceTime = [DateTime]::Parse($report.Timestamp)
            }
        } catch {
            # keep default window
        }
        Write-DeployLog "Integration Status: Healthy=$($report.Healthy)" $(if ($report.Healthy) { 'SUCCESS' } else { 'WARNING' }) $(if ($report.Healthy) { 'Green' } else { 'Yellow' })
        
        if ($report.Analyzer -and $report.Analyzer.Healthy) {
            Write-DeployLog "All $($report.Analyzer.TotalMethods) methods healthy" SUCCESS Green
        } elseif ($report.Analyzer) {
            Write-DeployLog "Some methods not healthy" WARNING Yellow
            $allPassed = $false
        } else {
            Write-DeployLog "Integration report missing Analyzer section" WARNING Yellow
        }
    }
    
    function Resolve-VerificationLogPath {
        param(
            [string]$RootPath,
            [DateTime]$Since
        )

        $logsDir = Join-Path $RootPath 'logs'
        if (-not (Test-Path $logsDir)) { return (Join-Path $RootPath 'logs/RawrXD.log') }

        $override = $env:RAWRXD_LOG_PATH
        if ($override -and (Test-Path $override)) { return $override }

        $candidateList = @()
        $candidateList += @(Get-ChildItem -Path $logsDir -Filter 'RawrXD_run_*.log' -File -ErrorAction SilentlyContinue)
        $candidateList += @(Get-ChildItem -Path $logsDir -Filter 'RawrXD_*.log' -File -ErrorAction SilentlyContinue)
        $candidates = $candidateList | Where-Object { $_ -and $_.LastWriteTime -ge $Since } | Sort-Object -Property LastWriteTime -Descending

        if ($candidates -and $candidates.Count -gt 0) {
            return $candidates[0].FullName
        }

        return (Join-Path $RootPath 'logs/RawrXD.log')
    }

    # Check logs (only since last integration timestamp to avoid historical noise)
    $logPath = Resolve-VerificationLogPath -RootPath $RawrXDRoot -Since $sinceTime
    Write-DeployLog "Verifying log file: $logPath" INFO
    if (Test-Path $logPath) {
        $parsedErrors = New-Object System.Collections.Generic.List[object]
        $logLines = Get-Content $logPath -ErrorAction SilentlyContinue
        foreach ($line in $logLines) {
            if ([string]::IsNullOrWhiteSpace($line)) { continue }
            $entryObj = $null
            try {
                $entryObj = $line | ConvertFrom-Json -ErrorAction Stop
            } catch {
                continue
            }

            $entryTime = $null
            try {
                if ($entryObj.Timestamp) { $entryTime = [DateTime]::Parse($entryObj.Timestamp) }
            } catch { $entryTime = $null }
            if (-not $entryTime) { continue }
            if ($entryTime -lt $sinceTime) { continue }

            $level = "$($entryObj.Level)"
            $msg = "$($entryObj.Message)"
            if ($level -match '^(ERROR|FATAL)$' -or $msg -match '(?i)\b(ERROR|FAIL)\b') {
                $parsedErrors.Add($entryObj) | Out-Null
            }
        }

        if ($parsedErrors.Count -gt 0) {
            Write-DeployLog "Found $($parsedErrors.Count) error(s) in logs since $sinceTime" WARNING Yellow
            $parsedErrors | Select-Object -Last 10 | ForEach-Object {
                Write-DeployLog "[$($_.Timestamp)] [$($_.Level)] $($_.Message)" WARNING Yellow
            }
            $allPassed = $false
        } else {
            Write-DeployLog "No errors in logs since $sinceTime" SUCCESS Green
        }
    }
    
    # Check manifests
    $manifestDir = Join-Path $RawrXDRoot 'orchestrator_smoke_output/manifest_tracer'
    if (Test-Path $manifestDir) {
        $manifests = @(Get-ChildItem -Path $manifestDir -Filter '*.json' -ErrorAction SilentlyContinue)
        Write-DeployLog "Found $($manifests.Count) manifest(s)" INFO
        foreach ($manifest in $manifests) {
            try {
                $content = Get-Content $manifest.FullName -Raw | ConvertFrom-Json
                Write-DeployLog "Manifest valid: $($manifest.Name)" SUCCESS Green
            } catch {
                Write-DeployLog "Manifest invalid: $($manifest.Name) - $_" ERROR Red
                $allPassed = $false
            }
        }
    }
    
    Write-DeployLog "Verification $(if ($allPassed) { 'PASSED' } else { 'FAILED' })" $(if ($allPassed) { 'SUCCESS' } else { 'WARNING' }) $(if ($allPassed) { 'Green' } else { 'Yellow' })
    return $allPassed
}

# ============================================
# MONITORING
# ============================================

function Invoke-Monitoring {
    Write-DeployLog 'Starting production monitoring...' INFO
    
    Write-Host "`n=== RawrXD Production Monitoring ===" -ForegroundColor Cyan
    
    # Recent logs
    Write-Host "`nRecent Logs (last 20 entries):" -ForegroundColor Yellow
    $logPath = Join-Path $RawrXDRoot 'logs/RawrXD.log'
    if (Test-Path $logPath) {
        Get-Content $logPath -Tail 20 -ErrorAction SilentlyContinue | Write-Host
    }
    
    # Integration status
    Write-Host "`nIntegration Status:" -ForegroundColor Yellow
    $reportPath = Join-Path $RawrXDRoot 'auto_generated_methods/integration_report.json'
    if (Test-Path $reportPath) {
        Get-Content $reportPath -Raw | ConvertFrom-Json | Format-Table -AutoSize
    }
    
    # Feature metrics
    Write-Host "`nFeature Metrics:" -ForegroundColor Yellow
    $metricsPath = Join-Path $RawrXDRoot 'auto_generated_methods/FeatureMetrics.json'
    if (Test-Path $metricsPath) {
        Get-Content $metricsPath -Raw | ConvertFrom-Json | Select-Object -ExpandProperty Metrics | Format-Table -AutoSize
    }
}

# ============================================
# ROLLBACK
# ============================================

function Invoke-Rollback {
    Write-DeployLog 'Starting rollback procedure...' WARNING Yellow
    
    # Stop all jobs
    Get-Job | Stop-Job -ErrorAction SilentlyContinue
    Write-DeployLog 'Stopped all background jobs' INFO
    
    # Unregister events
    Get-EventSubscriber -ErrorAction SilentlyContinue | Unregister-Event -ErrorAction SilentlyContinue
    Write-DeployLog 'Unregistered all events' INFO
    
    # Remove modules
    Get-Module RawrXD* | Remove-Module -Force -ErrorAction SilentlyContinue
    Write-DeployLog 'Removed RawrXD modules' INFO
    
    # Restore backup
    $latestBackup = Get-ChildItem -Path $RawrXDRoot -Filter 'backup_*' -Directory | Sort-Object -Descending | Select-Object -First 1
    if ($latestBackup) {
        Write-DeployLog "Restoring from backup: $($latestBackup.Name)" INFO
        Copy-Item -Path "$($latestBackup.FullName)/*" -Destination $RawrXDRoot -Recurse -Force
        Write-DeployLog 'Rollback complete' SUCCESS Green
    } else {
        Write-DeployLog 'No backup found for rollback' WARNING Yellow
    }
}

# ============================================
# MAIN EXECUTION
# ============================================

Write-Host "RawrXD Production Deployment Script" -ForegroundColor Cyan
Write-Host "Mode: $Mode" -ForegroundColor Yellow
Write-Host "Root: $RawrXDRoot" -ForegroundColor Yellow
Write-Host ""

switch ($Mode) {
    'PreDeploy' {
        $result = Invoke-PreDeployment
        exit $(if ($result) { 0 } else { 1 })
    }
    'Deploy' {
        Invoke-PreDeployment | Out-Null
        $result = Invoke-Deployment
        exit $(if ($result) { 0 } else { 1 })
    }
    'Verify' {
        $result = Invoke-Verification
        exit $(if ($result) { 0 } else { 1 })
    }
    'Monitor' {
        Invoke-Monitoring
        exit 0
    }
    'Rollback' {
        Invoke-Rollback
        exit 0
    }
}

Write-DeployLog 'Deployment script completed' SUCCESS Green
