; =============================================================================
; RawrXD_ChatService_Agentic.asm
; Pure x64 MASM - Enterprise-Grade Chat Integration
; Implements: IDE UI -> Chat Service -> LLM API -> Token Stream -> Renderer
; =============================================================================

OPTION CASEMAP:NONE

; --- Externs ---
extrn RawrXD_Inference_Init: proc
extrn RawrXD_Inference_Generate: proc
extrn RawrXD_Tokenizer_Init: proc
extrn RawrXD_Tokenizer_Encode: proc
extrn RawrXD_Tokenizer_Decode: proc
extrn OutputDebugStringA: proc
extrn GetProcessHeap: proc
extrn HeapAlloc: proc
extrn HeapFree: proc
extrn RtlZeroMemory: proc

; --- Structures ---
CHAT_CONTEXT STRUCT 16
    hInference      dq ?        ; Inference engine handle
    hTokenizer      dq ?        ; Tokenizer handle
    pHistory        dq ?        ; Chat history buffer
    nHistoryLen     dd ?        ; Current history tokens
    maxHistory      dd ?        ; Max context window
    pSystemPrompt   dq ?        ; Current persona
CHAT_CONTEXT ENDS

.data
    ALIGN 16
    szChatInit          db "[CHAT] Initializing Agentic Pipeline...", 0
    szChatInput         db "[CHAT] Encoding Input Prompt...", 0
    szChatStream        db "[CHAT] Token Stream Active: 0x%08X", 0
    szDefaultSystem     db "You are the RawrXD Agentic Assistant. Expert in x64 MASM.", 0
    
    ; Built-in Prompt Templates
    szPrompt_Header     db "<|system|>", 13, 10, "%s", 13, 10, "<|user|>", 13, 10, "%s", 13, 10, "<|assistant|>", 13, 10, 0

.code

; =============================================================================
; Chat_Init - Bootstraps the LLM pipeline
; rcx = model_path, rdx = vocab_path
; Returns: rax = hChatContext
; =============================================================================
Chat_Init PROC FRAME
    push rbp
    .pushreg rbp
    push rbx
    .pushreg rbx
    sub rsp, 56
    .allocstack 56
    .endprolog

    mov [rsp+32], rcx           ; Save model path
    mov [rsp+40], rdx           ; Save vocab path

    lea rcx, szChatInit
    call OutputDebugStringA

    ; Alloc context
    call GetProcessHeap
    mov rcx, rax
    xor edx, edx
    mov r8, SIZEOF CHAT_CONTEXT
    call HeapAlloc
    test rax, rax
    jz @Fail
    mov rbx, rax                ; RBX = pContext

    ; Init Tokenizer
    mov rcx, [rsp+40]           ; Vocab path
    call RawrXD_Tokenizer_Init
    mov [rbx].CHAT_CONTEXT.hTokenizer, rax

    ; Init Inference
    mov rcx, [rsp+32]           ; Model path
    mov rdx, [rbx].CHAT_CONTEXT.hTokenizer
    call RawrXD_Inference_Init
    mov [rbx].CHAT_CONTEXT.hInference, rax

    lea rax, szDefaultSystem
    mov qword ptr [rbx].CHAT_CONTEXT.pSystemPrompt, rax
    mov dword ptr [rbx].CHAT_CONTEXT.maxHistory, 8192

    mov rax, rbx
    jmp @Done

@Fail:
    xor eax, eax
@Done:
    add rsp, 56
    pop rbx
    pop rbp
    ret
Chat_Init ENDP

; =============================================================================
; Chat_ProcessInput - Main loop for streaming generation
; rcx = hChatContext, rdx = pUserPrompt, r8 = pOutputBuffer
; =============================================================================
Chat_ProcessInput PROC FRAME
    push rbp
    .pushreg rbp
    push rbx
    .pushreg rbx
    push rsi
    .pushreg rsi
    push rdi
    .pushreg rdi
    push r12
    .pushreg r12
    sub rsp, 64
    .allocstack 64
    .endprolog

    mov rbx, rcx                ; Context
    mov rsi, rdx                ; User Input
    mov rdi, r8                 ; Output Target

    ; 1. Prompt Builder (Format for Llama-3/Codex)
    ; (Simplified: directly encoding for now)
    lea rcx, szChatInput
    call OutputDebugStringA

    ; 2. Tokenizer Encode
    mov rcx, [rbx].CHAT_CONTEXT.hTokenizer
    mov rdx, rsi                ; Text
    xor r8, r8                  ; text_len (auto)
    lea r9, [rsp+32]            ; out_tokens (stack scratch)
    mov qword ptr [rsp+20h], 1024 ; max_tokens
    call RawrXD_Tokenizer_Encode
    mov r12, rax                ; n_tokens

    ; 3. Inference Generate (Token Stream)
    mov rcx, [rbx].CHAT_CONTEXT.hInference
    mov rdx, rsi                ; raw prompt text
    mov r8, 2048                ; max generated bytes/chars
    mov r9, rdi                 ; out_tokens (final destination)
    call RawrXD_Inference_Generate
    mov r12, rax                ; generated output length/count
    
    ; 4. Result sent to Stream Renderer (Handled by UI)
    mov rax, r12

    add rsp, 64
    pop r12
    pop rdi
    pop rsi
    pop rbx
    pop rbp
    ret
Chat_ProcessInput ENDP

PUBLIC Chat_Init
PUBLIC Chat_ProcessInput

END
