; =============================================================================
; RawrXD_Telemetry_Kernel.asm — Pure x64 MASM Implementation
; High-performance, Lock-free Metrics & Logging
; =============================================================================
;
; Architecture:
;   - Wait-Free Atomic Ring Buffer for events (lock xadd slot reservation)
;   - Lock-Free 64-bit Counters via single-instruction lock inc
;   - Direct Win32 I/O (no CRT, no Qt, no std::ofstream)
;   - Sub-microsecond timestamps via GetSystemTimePreciseAsFileTime
;
; Exports:
;   UTC_IncrementCounter     — Thread-safe atomic increment of any counter
;   UTC_DecrementCounter     — Thread-safe atomic decrement
;   UTC_ReadCounter          — Acquire-fence read of a counter
;   UTC_ResetCounter         — Atomic exchange to zero
;   UTC_LogEvent             — Wait-free write to ring buffer
;   UTC_FlushToDisk          — Drain ring buffer to log file
;   UTC_InitTelemetry        — Open log file handle
;   UTC_ShutdownTelemetry    — Flush + close handle
;   UTC_GetMetricTableBase   — Returns pointer to METRIC_TABLE_START
;   UTC_GetEventBufferStats  — Returns head/tail indices
;
; Pattern: PatchResult (RAX=0 success, RAX=error code on failure)
; Rule:    NO CRT, NO Qt, NO std::, NO exceptions
; =============================================================================

include RawrXD_Common.inc

; Win32 APIs not in Common.inc
EXTERNDEF GetSystemTimePreciseAsFileTime:PROC
EXTERNDEF FileTimeToSystemTime:PROC
EXTERNDEF WriteFile:PROC
EXTERNDEF CreateFileA:PROC
EXTERNDEF FlushFileBuffers:PROC

; =============================================================================
;                              Data Segment
; =============================================================================

; Cache-line aligned counters (separate segment for 64-byte alignment)
TELEMETRY_CL SEGMENT ALIGN(64) 'DATA'

    ; =========================================================================
    ; Atomic Metrics Table (cache-line padded to prevent false sharing)
    ; =========================================================================
    PUBLIC g_MetricTableStart
    g_MetricTableStart      dq 0DEADBEEFCAFEBABEh   ; Sentinel / magic
                            db 56 dup(0)             ; Pad to 64 bytes

    PUBLIC g_Counter_Inference
    g_Counter_Inference     dq 0    ; Total tokens generated by ASM kernels
                            db 56 dup(0)

    PUBLIC g_Counter_ScsiFails
    g_Counter_ScsiFails     dq 0    ; Hardware SCSI timeout count
                            db 56 dup(0)

    PUBLIC g_Counter_AgentLoop
    g_Counter_AgentLoop     dq 0    ; Total agentic loop steps executed
                            db 56 dup(0)

    PUBLIC g_Counter_BytePatches
    g_Counter_BytePatches   dq 0    ; Byte-level hotpatches applied
                            db 56 dup(0)

    PUBLIC g_Counter_MemPatches
    g_Counter_MemPatches    dq 0    ; Memory hotpatches applied
                            db 56 dup(0)

    PUBLIC g_Counter_ServerPatches
    g_Counter_ServerPatches dq 0    ; Server-layer hotpatches applied
                            db 56 dup(0)

    PUBLIC g_Counter_FlushOps
    g_Counter_FlushOps      dq 0    ; Number of flush-to-disk operations
                            db 56 dup(0)

    PUBLIC g_Counter_Errors
    g_Counter_Errors        dq 0    ; Total errors observed
                            db 56 dup(0)

    PUBLIC g_MetricTableEnd
    g_MetricTableEnd        dq 0BADCAFEDEADFACEh   ; Sentinel / end marker
                            db 56 dup(0)

TELEMETRY_CL ENDS

; Ring buffer and other data (standard .data alignment)
.data

    ; =========================================================================
    ; Ring Buffer Configuration
    ; EVENT_BUFFER_SIZE must be a power of 2 for bitmask indexing.
    ; Each slot is EVENT_STRUCT_SIZE bytes (null-terminated string w/ timestamp).
    ; =========================================================================

    EVENT_BUFFER_SIZE       equ 8192    ; 8K slots (power of 2)
    EVENT_STRUCT_SIZE       equ 256     ; Max bytes per event entry
    EVENT_BUFFER_MASK       equ (EVENT_BUFFER_SIZE - 1)
    EVENT_STRUCT_SHIFT      equ 8       ; log2(256) = 8, used with shl

    align 16
    g_EventBuffer       db (EVENT_BUFFER_SIZE * EVENT_STRUCT_SIZE) dup(0)

    align 8
    g_HeadIdx           dq 0    ; Producer index (atomic xadd)
    g_TailIdx           dq 0    ; Consumer index (single-writer: flush thread)

    ; =========================================================================
    ; Win32 File Handle for log output
    ; =========================================================================
    g_hLogFile          dq -1   ; INVALID_HANDLE_VALUE initially
    g_bInitialized      dq 0    ; Boolean: telemetry subsystem ready

    ; Log file path (default)
    szLogPath           db "rawrxd_kernel.log", 0

    ; Timestamp format helpers
    szBracketOpen       db "[", 0
    szBracketClose      db "] ", 0
    szColon             db ":", 0
    szNewline           db 13, 10, 0     ; CRLF for Windows

    ; Status strings
    szInitOk            db "[UTC] Telemetry kernel initialized", 13, 10, 0
    szFlushOk           db "[UTC] Buffer flushed to disk", 13, 10, 0
    szShutdownOk        db "[UTC] Telemetry kernel shutdown", 13, 10, 0

; =============================================================================
;                              Code Segment
; =============================================================================

.code

; =============================================================================
; UTC_InitTelemetry — Opens the log file and marks subsystem as ready
; RCX = Pointer to log file path (null-terminated), or NULL for default
; Returns: RAX = 0 on success, GetLastError on failure
; =============================================================================
UTC_InitTelemetry PROC FRAME
    push rbx
    .pushreg rbx
    push rdi
    .pushreg rdi
    sub  rsp, 48
    .allocstack 48
    .endprolog

    ; Use default path if caller passed NULL
    test rcx, rcx
    jnz  @use_custom_path
    lea  rcx, szLogPath
@use_custom_path:

    ; CreateFileA(path, GENERIC_WRITE, FILE_SHARE_READ, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL)
    mov  rbx, rcx               ; Save path
    sub  rsp, 32                ; Shadow space
    mov  rcx, rbx               ; lpFileName
    mov  edx, GENERIC_WRITE     ; dwDesiredAccess
    mov  r8d, FILE_SHARE_READ   ; dwShareMode
    xor  r9, r9                 ; lpSecurityAttributes = NULL
    mov  dword ptr [rsp+32], CREATE_ALWAYS ; dwCreationDisposition
    mov  dword ptr [rsp+40], 80h           ; dwFlagsAndAttributes = FILE_ATTRIBUTE_NORMAL
    mov  qword ptr [rsp+48], 0             ; hTemplateFile = NULL
    call CreateFileA
    add  rsp, 32

    ; Check result
    cmp  rax, INVALID_HANDLE_VALUE
    je   @init_failed

    ; Store handle and mark initialized
    mov  g_hLogFile, rax
    mov  qword ptr g_bInitialized, 1

    ; Reset all counters
    xor  eax, eax
    mov  g_Counter_Inference, rax
    mov  g_Counter_ScsiFails, rax
    mov  g_Counter_AgentLoop, rax
    mov  g_Counter_BytePatches, rax
    mov  g_Counter_MemPatches, rax
    mov  g_Counter_ServerPatches, rax
    mov  g_Counter_FlushOps, rax
    mov  g_Counter_Errors, rax
    mov  g_HeadIdx, rax
    mov  g_TailIdx, rax

    ; Write init banner to log
    lea  rcx, szInitOk
    call UTC_LogEvent

    xor  eax, eax               ; Return success
    jmp  @init_done

@init_failed:
    call GetLastError
    ; RAX already contains error code

@init_done:
    add  rsp, 48
    pop  rdi
    pop  rbx
    ret
UTC_InitTelemetry ENDP

; =============================================================================
; UTC_ShutdownTelemetry — Flush remaining events, close handle
; Returns: RAX = 0 on success
; =============================================================================
UTC_ShutdownTelemetry PROC FRAME
    push rbx
    .pushreg rbx
    sub  rsp, 40
    .allocstack 40
    .endprolog

    ; Flush remaining events
    call UTC_FlushToDisk

    ; Close file handle
    mov  rcx, g_hLogFile
    cmp  rcx, INVALID_HANDLE_VALUE
    je   @skip_close

    sub  rsp, 32
    call CloseHandle
    add  rsp, 32

@skip_close:
    mov  qword ptr g_hLogFile, INVALID_HANDLE_VALUE
    mov  qword ptr g_bInitialized, 0

    xor  eax, eax
    add  rsp, 40
    pop  rbx
    ret
UTC_ShutdownTelemetry ENDP

; =============================================================================
; UTC_IncrementCounter — Thread-safe atomic increment
; RCX = Pointer to the counter (e.g., offset g_Counter_Inference)
; Returns: RAX = new value after increment
; =============================================================================
UTC_IncrementCounter PROC
    mov  rax, 1
    lock xadd qword ptr [rcx], rax  ; RAX = old value
    inc  rax                         ; RAX = new value
    ret
UTC_IncrementCounter ENDP

; =============================================================================
; UTC_DecrementCounter — Thread-safe atomic decrement
; RCX = Pointer to the counter
; Returns: RAX = new value after decrement
; =============================================================================
UTC_DecrementCounter PROC
    mov  rax, -1
    lock xadd qword ptr [rcx], rax  ; RAX = old value
    dec  rax                         ; RAX = new value
    ret
UTC_DecrementCounter ENDP

; =============================================================================
; UTC_ReadCounter — Acquire-fence read of a 64-bit counter
; RCX = Pointer to the counter
; Returns: RAX = current value
; =============================================================================
UTC_ReadCounter PROC
    mov  rax, qword ptr [rcx]
    ; x64 loads are acquire-ordered on Intel; lfence for formal guarantee
    lfence
    ret
UTC_ReadCounter ENDP

; =============================================================================
; UTC_ResetCounter — Atomically zero a counter and return old value
; RCX = Pointer to the counter
; Returns: RAX = previous value
; =============================================================================
UTC_ResetCounter PROC
    xor  eax, eax
    lock xchg qword ptr [rcx], rax
    ret
UTC_ResetCounter ENDP

; =============================================================================
; UTC_LogEvent — Wait-free write to the ring buffer
; RCX = Pointer to null-terminated message string
; Returns: RAX = slot index used
; =============================================================================
; Strategy:
;   1. Atomically reserve a slot via lock xadd on g_HeadIdx
;   2. Compute buffer address: (slot & MASK) << SHIFT + base
;   3. Write [HH:MM:SS] timestamp prefix
;   4. Copy message bytes (up to EVENT_STRUCT_SIZE - timestamp overhead)
;   5. Return (no blocking, no mutex)
; =============================================================================
UTC_LogEvent PROC FRAME
    push rbx
    .pushreg rbx
    push rsi
    .pushreg rsi
    push rdi
    .pushreg rdi
    sub  rsp, 64
    .allocstack 64
    .endprolog

    mov  rbx, rcx               ; Save message pointer

    ; 1. Reserve slot in ring buffer via atomic exchange-add on Head
    mov  rax, 1
    lock xadd qword ptr [g_HeadIdx], rax
    ; RAX = old Head (our reserved slot index)

    push rax                    ; Save slot index for return

    ; 2. Calculate destination address: g_EventBuffer + ((slot & MASK) << SHIFT)
    and  rax, EVENT_BUFFER_MASK
    shl  rax, EVENT_STRUCT_SHIFT
    lea  rdi, [g_EventBuffer + rax]

    ; 3. Write timestamp prefix: [HH:MM:SS]
    mov  rcx, rdi
    call UTC_Internal_GetTimestamp
    ; RAX = updated pointer past timestamp
    mov  rdi, rax

    ; 4. Copy message string (bounded by remaining space)
    mov  rsi, rbx               ; Source = message
    lea  rdx, [g_EventBuffer]
    ; Calculate end-of-slot boundary
    pop  rax                    ; Restore slot index
    push rax                    ; Keep on stack for return
    and  rax, EVENT_BUFFER_MASK
    shl  rax, EVENT_STRUCT_SHIFT
    lea  rdx, [g_EventBuffer + rax]
    add  rdx, EVENT_STRUCT_SIZE
    sub  rdx, 2                 ; Leave room for CRLF terminator

@copy_loop:
    cmp  rdi, rdx               ; Bounds check
    jae  @copy_done
    lodsb
    test al, al
    jz   @copy_done
    stosb
    jmp  @copy_loop

@copy_done:
    ; Append newline
    mov  byte ptr [rdi], 13     ; CR
    inc  rdi
    mov  byte ptr [rdi], 10     ; LF
    inc  rdi
    mov  byte ptr [rdi], 0      ; Null terminator

    pop  rax                    ; Return slot index
    add  rsp, 64
    pop  rdi
    pop  rsi
    pop  rbx
    ret
UTC_LogEvent ENDP

; =============================================================================
; UTC_FlushToDisk — Drains the ring buffer to the log file
; Single-consumer model: only one thread should call this.
; Returns: RAX = number of events flushed
; =============================================================================
UTC_FlushToDisk PROC FRAME
    push rbx
    .pushreg rbx
    push rsi
    .pushreg rsi
    push rdi
    .pushreg rdi
    push r12
    .pushreg r12
    push r13
    .pushreg r13
    sub  rsp, 80
    .allocstack 80
    .endprolog

    xor  r12d, r12d             ; r12 = events flushed count

    ; Check if initialized
    cmp  qword ptr g_bInitialized, 0
    je   @flush_exit

    mov  rax, g_hLogFile
    cmp  rax, INVALID_HANDLE_VALUE
    je   @flush_exit

@flush_loop:
    ; Load tail and head
    mov  rsi, g_TailIdx
    mov  rdi, g_HeadIdx
    cmp  rsi, rdi
    jge  @flush_done            ; Nothing to flush

    ; Calculate buffer address for current tail
    mov  rax, rsi
    and  rax, EVENT_BUFFER_MASK
    shl  rax, EVENT_STRUCT_SHIFT
    lea  rbx, [g_EventBuffer + rax]

    ; Find string length (up to EVENT_STRUCT_SIZE)
    mov  rcx, rbx
    xor  edx, edx
@strlen_loop:
    cmp  edx, EVENT_STRUCT_SIZE
    jge  @strlen_done
    cmp  byte ptr [rcx + rdx], 0
    je   @strlen_done
    inc  edx
    jmp  @strlen_loop
@strlen_done:

    ; Skip empty slots
    test edx, edx
    jz   @advance_tail

    ; WriteFile(g_hLogFile, buffer, length, &bytesWritten, NULL)
    mov  r13d, edx              ; Save length
    sub  rsp, 32
    mov  rcx, g_hLogFile        ; hFile
    mov  rdx, rbx               ; lpBuffer
    mov  r8d, r13d              ; nNumberOfBytesToWrite
    lea  r9, [rsp+64]           ; lpNumberOfBytesWritten (on stack)
    mov  qword ptr [rsp+32], 0  ; lpOverlapped = NULL
    call WriteFile
    add  rsp, 32

@advance_tail:
    ; Advance tail
    inc  qword ptr g_TailIdx
    inc  r12                    ; Increment flush count
    jmp  @flush_loop

@flush_done:
    ; Flush OS buffers
    test r12d, r12d
    jz   @flush_exit

    sub  rsp, 32
    mov  rcx, g_hLogFile
    call FlushFileBuffers
    add  rsp, 32

    ; Increment flush ops counter
    lea  rcx, g_Counter_FlushOps
    lock inc qword ptr [rcx]

@flush_exit:
    mov  rax, r12               ; Return events flushed

    add  rsp, 80
    pop  r13
    pop  r12
    pop  rdi
    pop  rsi
    pop  rbx
    ret
UTC_FlushToDisk ENDP

; =============================================================================
; UTC_GetMetricTableBase — Returns pointer to the metric table start
; Returns: RAX = address of g_MetricTableStart
; =============================================================================
UTC_GetMetricTableBase PROC
    lea  rax, g_MetricTableStart
    ret
UTC_GetMetricTableBase ENDP

; =============================================================================
; UTC_GetEventBufferStats — Returns head and tail indices
; Returns: RAX = Head index, RDX = Tail index
; =============================================================================
UTC_GetEventBufferStats PROC
    mov  rax, g_HeadIdx
    mov  rdx, g_TailIdx
    lfence
    ret
UTC_GetEventBufferStats ENDP

; =============================================================================
; UTC_Internal_GetTimestamp — High-resolution timestamp formatter
; RCX = Destination buffer pointer
; Returns: RAX = updated pointer past the timestamp
;
; Writes "[HH:MM:SS.mmm] " format using GetSystemTimePreciseAsFileTime
; (Win8+ API, sub-microsecond precision)
; =============================================================================
UTC_Internal_GetTimestamp PROC FRAME
    push rbx
    .pushreg rbx
    push rdi
    .pushreg rdi
    sub  rsp, 80
    .allocstack 80
    .endprolog

    mov  rdi, rcx               ; Save destination buffer pointer

    ; GetSystemTimePreciseAsFileTime(&fileTime)
    lea  rcx, [rsp+48]         ; lpFileTime (8 bytes at rsp+48)
    sub  rsp, 32
    call GetSystemTimePreciseAsFileTime
    add  rsp, 32

    ; FileTimeToSystemTime(&fileTime, &systemTime)
    lea  rcx, [rsp+48]         ; lpFileTime
    lea  rdx, [rsp+56]         ; lpSystemTime (16 bytes at rsp+56)
    sub  rsp, 32
    call FileTimeToSystemTime
    add  rsp, 32

    ; SYSTEMTIME offsets from rsp+56:
    ;   +0  wYear       (WORD)
    ;   +2  wMonth      (WORD)
    ;   +4  wDayOfWeek  (WORD)
    ;   +6  wDay        (WORD)
    ;   +8  wHour       (WORD)
    ;   +10 wMinute     (WORD)
    ;   +12 wSecond     (WORD)
    ;   +14 wMilliseconds (WORD)

    ; Format: [HH:MM:SS.mmm]
    mov  byte ptr [rdi], '['
    inc  rdi

    ; Hour
    movzx eax, word ptr [rsp+56+8]
    call UTC_Internal_U16ToAscii2
    mov  byte ptr [rdi], ':'
    inc  rdi

    ; Minute
    movzx eax, word ptr [rsp+56+10]
    call UTC_Internal_U16ToAscii2
    mov  byte ptr [rdi], ':'
    inc  rdi

    ; Second
    movzx eax, word ptr [rsp+56+12]
    call UTC_Internal_U16ToAscii2
    mov  byte ptr [rdi], '.'
    inc  rdi

    ; Milliseconds (3 digits, zero-padded)
    movzx eax, word ptr [rsp+56+14]
    call UTC_Internal_U16ToAscii3

    mov  byte ptr [rdi], ']'
    inc  rdi
    mov  byte ptr [rdi], ' '
    inc  rdi

    mov  rax, rdi               ; Return updated pointer

    add  rsp, 80
    pop  rdi
    pop  rbx
    ret
UTC_Internal_GetTimestamp ENDP

; =============================================================================
; UTC_Internal_U16ToAscii2 — Convert 0-99 value to 2 zero-padded ASCII digits
; EAX = value (0-99), RDI = destination (advances RDI by 2)
; =============================================================================
UTC_Internal_U16ToAscii2 PROC
    ; Tens digit
    xor  edx, edx
    mov  ecx, 10
    div  ecx                    ; EAX = tens, EDX = ones
    add  al, '0'
    mov  byte ptr [rdi], al
    inc  rdi

    ; Ones digit
    add  dl, '0'
    mov  byte ptr [rdi], dl
    inc  rdi
    ret
UTC_Internal_U16ToAscii2 ENDP

; =============================================================================
; UTC_Internal_U16ToAscii3 — Convert 0-999 value to 3 zero-padded ASCII digits
; EAX = value (0-999), RDI = destination (advances RDI by 3)
; =============================================================================
UTC_Internal_U16ToAscii3 PROC
    ; Hundreds digit
    xor  edx, edx
    mov  ecx, 100
    div  ecx                    ; EAX = hundreds, EDX = remainder
    add  al, '0'
    mov  byte ptr [rdi], al
    inc  rdi

    ; Tens digit
    mov  eax, edx
    xor  edx, edx
    mov  ecx, 10
    div  ecx                    ; EAX = tens, EDX = ones
    add  al, '0'
    mov  byte ptr [rdi], al
    inc  rdi

    ; Ones digit
    add  dl, '0'
    mov  byte ptr [rdi], dl
    inc  rdi
    ret
UTC_Internal_U16ToAscii3 ENDP

END
