apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: true
  namespace: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts: [ "true" ]
      secretName: true-tls
  rules:
    - host: true
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: true
                port:
                  number: 80
