#!/usr/bin/env php
<?php
class T{public int $i;public string $n;public int $d;function __construct($i,$n,$d){$this->i=$i;$this->n=$n;$this->d=$d;}}
$tasks=[new T(1,"hello_world",1),new T(2,"fibonacci",2),new T(3,"reverse_string",2),new T(4,"binary_search",3),new T(5,"merge_sort",4)];
$snippets=["java"=>["hello_world"=>"public class Hello{public static void main(String[]a){System.out.println(\"Hello, world!\");}}","fibonacci"=>"public static int fib(int n){if(n<2)return n;return fib(n-1)+fib(n-2);}","reverse_string"=>"public static String reverse(String s){return new StringBuilder(s).reverse().toString();}","binary_search"=>"public static int bs(int[]a,int x){int l=0,r=a.length-1;while(l<=r){int m=l+(r-l)/2;if(a[m]==x)return m;if(a[m]<x)l=m+1;else r=m-1;}return-1;}","merge_sort"=>"public static void ms(int[]a){if(a.length<2)return;int m=a.length/2;int[]L=Arrays.copyOfRange(a,0,m);int[]R=Arrays.copyOfRange(a,m,a.length);ms(L);ms(R);merge(a,L,R);}"]];
function pick(string$lang,int$n,array$tasks):array{$h=hash('sha256',$lang,true);$s=unpack('J',substr($h,0,8))[1];if($s<0)$s=~$s+1;$seen=[];$result=[];$c=count($tasks);$idx=[$s%$c,intdiv($s,7)%$c,intdiv($s,13)%$c];foreach($idx as$i)if(!in_array($i,$seen)){$seen[]=$i;$result[]=$tasks[$i];}$k=1;while(count($result)<$n){$new=abs($s+31*$k)%$c;if(!in_array($new,$seen)){$seen[]=$new;$result[]=$tasks[$new];}$k++;}return array_slice($result,0,min($n,count($result)));}
function md(string$lang,array$tasks,array$snippets):string{$out="# ".strtoupper($lang)." examples\n\n";foreach($tasks as$t){$s=$snippets[$lang][$t->n]??'';$out.="## {$t->n} (difficulty {$t->d})\n```java\n{$s}\n```\n\n";}return$out;}
function json(string$lang,array$tasks,array$snippets):string{$data=[];foreach($tasks as$t)$data[]=["id"=>$t->i,"name"=>$t->n,"difficulty"=>$t->d,"snippet"=>$snippets[$lang][$t->n]??''];return json_encode($data,JSON_PRETTY_PRINT)."\n";}
function ask(string$p,string$url,?string$auth):string{$ch=curl_init();if($auth!==null)$url.="?key=".urlencode($auth);$post=json_encode(["contents"=>[["parts"=>[["text"=>$p]]]]]);curl_setopt_array($ch,[CURLOPT_URL=>$url,CURLOPT_POST=>1,CURLOPT_RETURNTRANSFER=>1,CURLOPT_HTTPHEADER=>["Content-Type: application/json"],CURLOPT_POSTFIELDS=>$post]);$r=curl_exec($ch);$e=curl_error($ch);$c=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($e||$c>=400)return"AI call failed (HTTP code: {$c}, Error: {$e}) – showing deterministic examples anyway.\n\n";$j=json_decode($r,true);return isset($j['candidates'][0]['content']['parts'][0]['text'])?"AI reply:\n".$j['candidates'][0]['content']['parts'][0]['text']."\n\n":"AI call failed (invalid response) – showing deterministic examples anyway.\n\n";}
$lang="java";$prompt=$url="https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent";$auth=null;$argv=array_slice($argv,1);for($i=0;$i<count($argv);$i++){if($argv[$i]==="--lang"&&isset($argv[$i+1]))$lang=$argv[++$i];elseif($argv[$i]==="--ask"&&isset($argv[$i+1]))$prompt=$argv[++$i];elseif($argv[$i]==="--api"&&isset($argv[$i+1]))$url=$argv[++$i];elseif($argv[$i]==="--auth"&&isset($argv[$i+1]))$auth=$argv[++$i];}
if($prompt!==null)echo ask($prompt,$url,$auth);
$ex=pick($lang,3,$tasks);echo"=== MARKDOWN ===\n".md($lang,$ex,$snippets)."\n=== JSON ===\n".json($lang,$ex,$snippets);
