// g_feature_manifest_stub.cpp — Minimal g_FeatureManifest definition for standalone smoke tests
// Provides the extern symbol expected by license_enforcement.cpp / feature_flags_runtime.cpp
// without pulling in the full enterprise_license_v2.cpp (which has header conflict issues).

#include "include/enterprise_license.h"

namespace RawrXD::License {

const FeatureDefV2 g_FeatureManifest[TOTAL_FEATURES] = {
    {FeatureID::BasicGGUFLoading,      "Basic GGUF Loading",      "", LicenseTierV2::Community,    true, true, false, "", ""},
    {FeatureID::Q4Quantization,        "Q4 Quantization",         "", LicenseTierV2::Community,    true, true, false, "", ""},
    {FeatureID::CPUInference,          "CPU Inference",            "", LicenseTierV2::Community,    true, true, false, "", ""},
    {FeatureID::BasicChatUI,           "Basic Chat UI",            "", LicenseTierV2::Community,    true, true, false, "", ""},
    {FeatureID::ConfigFileSupport,     "Config File Support",      "", LicenseTierV2::Community,    true, true, false, "", ""},
    {FeatureID::SingleModelSession,    "Single Model Session",     "", LicenseTierV2::Community,    true, true, false, "", ""},
    {FeatureID::MemoryHotpatching,     "Memory Hotpatching",       "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::ByteLevelHotpatching,  "Byte-Level Hotpatching",   "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::ServerHotpatching,     "Server Hotpatching",       "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::UnifiedHotpatchManager,"Unified Hotpatch Manager", "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::Q5Q8F16Quantization,   "Q5/Q8/F16 Quantization",  "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::MultiModelLoading,     "Multi-Model Loading",      "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::CUDABackend,           "CUDA Backend",             "", LicenseTierV2::Professional, false,false,false, "", ""},
    {FeatureID::AdvancedSettingsPanel, "Advanced Settings Panel",  "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::PromptTemplates,       "Prompt Templates",         "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::TokenStreaming,         "Token Streaming",          "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::InferenceStatistics,   "Inference Statistics",     "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::KVCacheManagement,     "KV Cache Management",      "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::ModelComparison,       "Model Comparison",         "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::BatchProcessing,       "Batch Processing",         "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::CustomStopSequences,   "Custom Stop Sequences",    "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::GrammarConstrainedGen, "Grammar Constrained Gen",  "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::LoRAAdapterSupport,    "LoRA Adapter Support",     "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::ResponseCaching,       "Response Caching",         "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::PromptLibrary,         "Prompt Library",           "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::ExportImportSessions,  "Export/Import Sessions",   "", LicenseTierV2::Professional, true, true, false, "", ""},
    {FeatureID::HIPBackend,            "HIP Backend",              "", LicenseTierV2::Professional, false,false,false, "", ""},
    {FeatureID::DualEngine800B,        "Dual Engine 800B",         "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::AgenticFailureDetect,  "Agentic Failure Detect",   "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::AgenticPuppeteer,      "Agentic Puppeteer",        "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::AgenticSelfCorrection, "Agentic Self-Correction",  "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::ProxyHotpatching,      "Proxy Hotpatching",        "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::ServerSidePatching,    "Server-Side Patching",     "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::SchematicStudioIDE,    "Schematic Studio IDE",     "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::WiringOracleDebug,     "Wiring Oracle Debug",      "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::FlashAttention,        "Flash Attention",           "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::SpeculativeDecoding,   "Speculative Decoding",     "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::ModelSharding,         "Model Sharding",           "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::TensorParallel,        "Tensor Parallel",          "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::PipelineParallel,      "Pipeline Parallel",        "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::ContinuousBatching,    "Continuous Batching",      "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::GPTQQuantization,      "GPTQ Quantization",        "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::AWQQuantization,       "AWQ Quantization",          "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::CustomQuantSchemes,    "Custom Quant Schemes",     "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::MultiGPULoadBalance,   "Multi-GPU Load Balance",   "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::DynamicBatchSizing,    "Dynamic Batch Sizing",     "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::PriorityQueuing,       "Priority Queuing",         "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::RateLimitingEngine,    "Rate Limiting Engine",     "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::AuditLogging,          "Audit Logging",            "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::APIKeyManagement,      "API Key Management",       "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::ModelSigningVerify,    "Model Signing Verify",     "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::RBAC,                  "RBAC",                     "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::ObservabilityDashboard,"Observability Dashboard",  "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::AVX512Acceleration,    "AVX512 Acceleration",      "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::RawrTunerIDE,          "RawrTuner IDE",            "", LicenseTierV2::Enterprise,   true, true, false, "", ""},
    {FeatureID::AirGappedDeploy,       "Air-Gapped Deploy",        "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::HSMIntegration,        "HSM Integration",          "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::FIPS140_2Compliance,   "FIPS 140-2 Compliance",   "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::CustomSecurityPolicies,"Custom Security Policies", "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::SovereignKeyMgmt,      "Sovereign Key Mgmt",      "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::ClassifiedNetwork,     "Classified Network",       "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::ImmutableAuditLogs,    "Immutable Audit Logs",     "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::KubernetesSupport,     "Kubernetes Support",       "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::TamperDetection,       "Tamper Detection",         "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
    {FeatureID::SecureBootChain,       "Secure Boot Chain",        "", LicenseTierV2::Sovereign,    true, true, false, "", ""},
};

} // namespace RawrXD::License
