# CMake generated Testfile for 
# Source directory: D:/rawrxd/tests
# Build directory: D:/rawrxd/build-ninja-ctx2/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ai_completions]=] "D:/rawrxd/build-ninja-ctx2/tests/test_ai_completions.exe")
set_tests_properties([=[test_ai_completions]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;98;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_llm_connectivity]=] "D:/rawrxd/build-ninja-ctx2/tests/test_llm_connectivity.exe")
set_tests_properties([=[test_llm_connectivity]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;110;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_tool_registry]=] "D:/rawrxd/build-ninja-ctx2/tests/test_tool_registry.exe")
set_tests_properties([=[test_tool_registry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;122;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_zero_retention_manager]=] "D:/rawrxd/build-ninja-ctx2/tests/test_zero_retention_manager.exe")
set_tests_properties([=[test_zero_retention_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;136;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_semantic_diff_analyzer]=] "D:/rawrxd/build-ninja-ctx2/tests/test_semantic_diff_analyzer.exe")
set_tests_properties([=[test_semantic_diff_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;145;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_ai_merge_resolver]=] "D:/rawrxd/build-ninja-ctx2/tests/test_ai_merge_resolver.exe")
set_tests_properties([=[test_ai_merge_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;157;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_ide_model_autonomy]=] "D:/rawrxd/build-ninja-ctx2/tests/test_ide_model_autonomy.exe")
set_tests_properties([=[test_ide_model_autonomy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;181;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_extreme_memory_optimizer]=] "D:/rawrxd/build-ninja-ctx2/tests/test_extreme_memory_optimizer.exe")
set_tests_properties([=[test_extreme_memory_optimizer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;195;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_quality_corrector]=] "D:/rawrxd/build-ninja-ctx2/tests/test_quality_corrector.exe")
set_tests_properties([=[test_quality_corrector]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;209;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_sandboxed_terminal]=] "D:/rawrxd/build-ninja-ctx2/tests/test_sandboxed_terminal.exe")
set_tests_properties([=[test_sandboxed_terminal]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;218;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_agentic_file_operations]=] "D:/rawrxd/build-ninja-ctx2/tests/test_agentic_file_operations.exe")
set_tests_properties([=[test_agentic_file_operations]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;227;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[model_registry_test]=] "D:/rawrxd/build-ninja-ctx2/tests/model_registry_test.exe")
set_tests_properties([=[model_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;236;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_gguf_integration]=] "D:/rawrxd/build-ninja-ctx2/tests/test_gguf_integration.exe")
set_tests_properties([=[test_gguf_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;246;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_engine_revolver]=] "D:/rawrxd/build-ninja-ctx2/tests/test_engine_revolver.exe")
set_tests_properties([=[test_engine_revolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;254;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_swarm_scheduler_pin]=] "D:/rawrxd/build-ninja-ctx2/tests/test_swarm_scheduler_pin.exe")
set_tests_properties([=[test_swarm_scheduler_pin]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;267;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_swarm_expert_heatmap_stress]=] "D:/rawrxd/build-ninja-ctx2/tests/test_swarm_expert_heatmap_stress.exe")
set_tests_properties([=[test_swarm_expert_heatmap_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;280;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_mixture_reference]=] "D:/rawrxd/build-ninja-ctx2/tests/test_moe_mixture_reference.exe")
set_tests_properties([=[test_moe_mixture_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;288;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_down_project_policy]=] "D:/rawrxd/build-ninja-ctx2/tests/test_moe_down_project_policy.exe")
set_tests_properties([=[test_moe_down_project_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;296;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_plan_row_mixture_pack_cache]=] "D:/rawrxd/build-ninja-ctx2/tests/test_moe_plan_row_mixture_pack_cache.exe")
set_tests_properties([=[test_moe_plan_row_mixture_pack_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;304;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_batched_down_project]=] "D:/rawrxd/build-ninja-ctx2/tests/test_moe_batched_down_project.exe")
set_tests_properties([=[test_moe_batched_down_project]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;312;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_pack_hud_metrics]=] "D:/rawrxd/build-ninja-ctx2/tests/test_moe_pack_hud_metrics.exe")
set_tests_properties([=[test_moe_pack_hud_metrics]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;320;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_basic_profiler]=] "D:/rawrxd/build-ninja-ctx2/tests/test_basic_profiler.exe")
set_tests_properties([=[test_basic_profiler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;340;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_batch3_profiler_smoke]=] "D:/rawrxd/build-ninja-ctx2/tests/test_batch3_profiler_smoke.exe")
set_tests_properties([=[test_batch3_profiler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;353;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_kv_cache_ownership]=] "D:/rawrxd/build-ninja-ctx2/tests/test_kv_cache_ownership.exe")
set_tests_properties([=[test_kv_cache_ownership]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;376;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_speculative_pipeline]=] "D:/rawrxd/build-ninja-ctx2/tests/test_speculative_pipeline.exe")
set_tests_properties([=[test_speculative_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;395;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_extension_host]=] "D:/rawrxd/build-ninja-ctx2/tests/test_extension_host.exe")
set_tests_properties([=[test_extension_host]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;421;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_sovereign_kernels]=] "D:/rawrxd/build-ninja-ctx2/tests/test_sovereign_kernels.exe")
set_tests_properties([=[test_sovereign_kernels]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;467;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[bench_sovereign_kernels]=] "D:/rawrxd/build-ninja-ctx2/tests/bench_sovereign_kernels.exe")
set_tests_properties([=[bench_sovereign_kernels]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;500;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_production_regression]=] "D:/rawrxd/build-ninja-ctx2/tests/test_production_regression.exe")
set_tests_properties([=[test_production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;535;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_instructions_provider]=] "D:/rawrxd/build-ninja-ctx2/tests/test_instructions_provider.exe")
set_tests_properties([=[test_instructions_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;556;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[sovereign_assembler_smoke]=] "D:/rawrxd/build-ninja-ctx2/bin/sovereign_assembler_smoke.exe")
set_tests_properties([=[sovereign_assembler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;561;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[rawrengine_copilot_smoke]=] "D:/rawrxd/build-ninja-ctx2/bin/RawrEngine.exe" "--copilot-smoke")
set_tests_properties([=[rawrengine_copilot_smoke]=] PROPERTIES  LABELS "smoke;copilot;inference" TIMEOUT "600" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;567;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[win32ide_agentic_smoke]=] "D:/rawrxd/build-ninja-ctx2/bin/RawrXD-Win32IDE.exe" "--agentic-smoke")
set_tests_properties([=[win32ide_agentic_smoke]=] PROPERTIES  LABELS "smoke;agentic;win32ide" TIMEOUT "600" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;577;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[win32ide_high_pressure_ui]=] "pwsh" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "D:/rawrxd/tests/smoke/win32ide_high_pressure_ui.ps1" "-ExePath" "D:/rawrxd/build-ninja-ctx2/bin/RawrXD-Win32IDE.exe")
set_tests_properties([=[win32ide_high_pressure_ui]=] PROPERTIES  LABELS "smoke;stress;win32ide;lsp;model" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;585;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[ollama_stream_routing_env_smoke]=] "pwsh" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "D:/rawrxd/scripts/Test-OllamaStreamRoutingEnv.ps1")
set_tests_properties([=[ollama_stream_routing_env_smoke]=] PROPERTIES  LABELS "smoke;agentic;ollama" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;598;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[production_readiness_expansion_quality_gate]=] "C:/Program Files/CMake/bin/cmake.exe" "-D" "BINARY_DIR=D:/rawrxd/build-ninja-ctx2" "-D" "CONFIG=Debug" "-D" "BUILD_TARGET=self_test_gate" "-P" "D:/rawrxd/tests/smoke/build_target_with_retry.cmake")
set_tests_properties([=[production_readiness_expansion_quality_gate]=] PROPERTIES  LABELS "quality-gate;production;aggregate" TIMEOUT "1800" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;611;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_model_loader_streamer_smoke]=] "D:/rawrxd/build-ninja-ctx2/tests/test_model_loader_streamer_smoke.exe")
set_tests_properties([=[test_model_loader_streamer_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;651;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
subdirs("../_deps/googletest-build")
