#include "prompt_templates.h"
std::string PromptTemplates::generateDebugPrompt(const void* &debugInfo)
{
    std::stringList promptLines;
    promptLines << "You are an expert software debugger. Analyze the following debug information and suggest a fix for the code.";
    promptLines << "";
    promptLines << "Debug Information:";
    promptLines << "==================";
    promptLines << "";
    
    if (debugInfo.contains("locals")) {
        promptLines << "Local Variables:";
        promptLines << formatLocals(debugInfo["locals"].toArray());
        promptLines << "";
    }
    
    if (debugInfo.contains("stack")) {
        promptLines << "Call Stack:";
        promptLines << formatStack(debugInfo["stack"].toArray());
        promptLines << "";
    }
    
    if (debugInfo.contains("registers")) {
        promptLines << "Registers:";
        promptLines << formatRegisters(debugInfo["registers"].toArray());
        promptLines << "";
    }
    
    promptLines << "Please provide a diff of the suggested fix, explaining the problem and your solution.";
    promptLines << "The diff should be in unified format (as generated by 'diff -u').";
    
    return promptLines.join("\n");
}

std::string PromptTemplates::formatLocals(const void* &locals)
{
    std::stringList lines;
    for (const void* &local : locals) {
        // In a real implementation, each local would be a JSON object with name, value, type, etc.
        // For this example, we'll just convert the value to a string.
        lines << "  " + local.toString();
    }
    return lines.join("\n");
}

std::string PromptTemplates::formatStack(const void* &stack)
{
    std::stringList lines;
    for (const void* &frame : stack) {
        // In a real implementation, each frame would be a JSON object with function name, file, line, etc.
        // For this example, we'll just convert the value to a string.
        lines << "  " + frame.toString();
    }
    return lines.join("\n");
}

std::string PromptTemplates::formatRegisters(const void* ®isters)
{
    std::stringList lines;
    for (const void* ® : registers) {
        // In a real implementation, each register would be a JSON object with name and value.
        // For this example, we'll just convert the value to a string.
        lines << "  " + reg.toString();
    }
    return lines.join("\n");
}

