#include "prompt_templates.h"
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonDocument>
#include <QStringList>
#include <QDebug>

QString PromptTemplates::generateDebugPrompt(const QJsonObject &debugInfo)
{
    QStringList promptLines;
    promptLines << "You are an expert software debugger. Analyze the following debug information and suggest a fix for the code.";
    promptLines << "";
    promptLines << "Debug Information:";
    promptLines << "==================";
    promptLines << "";
    
    if (debugInfo.contains("locals")) {
        promptLines << "Local Variables:";
        promptLines << formatLocals(debugInfo["locals"].toArray());
        promptLines << "";
    }
    
    if (debugInfo.contains("stack")) {
        promptLines << "Call Stack:";
        promptLines << formatStack(debugInfo["stack"].toArray());
        promptLines << "";
    }
    
    if (debugInfo.contains("registers")) {
        promptLines << "Registers:";
        promptLines << formatRegisters(debugInfo["registers"].toArray());
        promptLines << "";
    }
    
    promptLines << "Please provide a diff of the suggested fix, explaining the problem and your solution.";
    promptLines << "The diff should be in unified format (as generated by 'diff -u').";
    
    return promptLines.join("\n");
}

QString PromptTemplates::formatLocals(const QJsonArray &locals)
{
    QStringList lines;
    for (const QJsonValue &local : locals) {
        // In a real implementation, each local would be a JSON object with name, value, type, etc.
        // For this example, we'll just convert the value to a string.
        lines << "  " + local.toString();
    }
    return lines.join("\n");
}

QString PromptTemplates::formatStack(const QJsonArray &stack)
{
    QStringList lines;
    for (const QJsonValue &frame : stack) {
        // In a real implementation, each frame would be a JSON object with function name, file, line, etc.
        // For this example, we'll just convert the value to a string.
        lines << "  " + frame.toString();
    }
    return lines.join("\n");
}

QString PromptTemplates::formatRegisters(const QJsonArray ®isters)
{
    QStringList lines;
    for (const QJsonValue ® : registers) {
        // In a real implementation, each register would be a JSON object with name and value.
        // For this example, we'll just convert the value to a string.
        lines << "  " + reg.toString();
    }
    return lines.join("\n");
}