; AddTwoNumbers.asm - Generated by BigDaddyG AI

OPTION CASEMAP:NONE

.code

add_two_numbers PROC
    ; Input parameters (rcx = a, rdx = b)
    mov rax, rcx
    add rax, rdx
    ret

add_two_numbers ENDP

END