#!/usr/bin/env python3
"""polish_batch_align.py

Batch polish/alignment helper (NO MIXING: YES)

Purpose
- Uses ONLY existing sources (no recoding, no deletion, no moving).
- Generates CMake include fragments that improve *graphical appearance* in
  Visual Studio generators via `source_group(TREE ...)`.
- Produces a JSON report for review.

It does NOT modify any source files under src/.

Usage
  python scripts/polish_batch_align.py --root D:\RawrXD --batch 1

Outputs (default)
  D:\RawrXD\cmake\polish_batches\batch_1_sources.cmake
  D:\RawrXD\cmake\polish_batches\batch_1_source_groups.cmake
  D:\RawrXD\polish\batch_1\batch_1_polish_report.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import time
from pathlib import Path
from typing import Dict, List, Tuple


CMAKE_TOKEN_RE = re.compile(r"[\w/\\${}.-]+\.(?:c|cc|cpp|cxx|h|hh|hpp|asm|s|S)\b", re.IGNORECASE)


def _posix_rel(path: str) -> str:
    return path.replace("\\", "/").lstrip("./")


def load_batches(batches_path: Path) -> Dict:
    return json.loads(batches_path.read_text(encoding="utf-8", errors="replace"))


def get_batch_sources(batches: Dict, batch_id: int) -> List[str]:
    for b in batches.get("batches", []):
        if int(b.get("batch_id")) == batch_id:
            return [str(s) for s in b.get("sources", [])]
    raise SystemExit(f"batch_id {batch_id} not found in {batches.get('deliverable','<unknown>')}")


def scan_cmake_tokens(cmake_path: Path) -> Tuple[List[str], List[str]]:
    if not cmake_path.is_file():
        return [], []
    text = cmake_path.read_text(encoding="utf-8", errors="replace")
    raw = [m.group(0) for m in CMAKE_TOKEN_RE.finditer(text)]
    norm = [_posix_rel(t) for t in raw]
    return raw, norm


def ensure_dirs(*dirs: Path) -> None:
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)


def write_cmake_batch_sources(out_path: Path, root: Path, rel_sources: List[str], batch_id: int) -> None:
    var = f"RAWRXD_BATCH_{batch_id}_SOURCES"
    lines = []
    lines.append(f"# Auto-generated by scripts/polish_batch_align.py on {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
    lines.append("# Safe: this file only defines a list; it does NOT modify sources.\n")
    lines.append(f"set({var}")
    for rel in rel_sources:
        # Use CMAKE_SOURCE_DIR so include location doesn't affect path resolution.
        lines.append(f"  \"${{CMAKE_SOURCE_DIR}}/{rel}\"")
    lines.append(")\n")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_cmake_source_groups(out_path: Path, batch_id: int) -> None:
    var = f"RAWRXD_BATCH_{batch_id}_SOURCES"
    lines = []
    lines.append(f"# Auto-generated by scripts/polish_batch_align.py on {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
    lines.append("# Graphical appearance: organizes files into solution filters when using VS generators.\n")
    lines.append(f"if(DEFINED {var})")
    lines.append(f"  source_group(TREE \"${{CMAKE_SOURCE_DIR}}\" PREFIX \"\" FILES ${{{var}}})")
    lines.append("endif()\n")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=r"D:\RawrXD", help="Project root")
    ap.add_argument("--batch", type=int, default=1, help="Batch ID")
    ap.add_argument(
        "--batches-file",
        default=None,
        help="Path to masm_recode_batches.json (defaults to <root>/masm_recode_batches.json)",
    )
    args = ap.parse_args()

    root = Path(args.root).resolve()
    batches_path = Path(args.batches_file).resolve() if args.batches_file else (root / "masm_recode_batches.json")

    cmake_path = root / "CMakeLists.txt"
    cmake_raw, cmake_norm = scan_cmake_tokens(cmake_path)
    cmake_basenames = {Path(t).name for t in cmake_norm}
    cmake_norm_set = set(cmake_norm)

    batches = load_batches(batches_path)
    batch_sources = get_batch_sources(batches, args.batch)

    # Normalize batch sources to posix and ensure they are within repo.
    rel_sources = [_posix_rel(s) for s in batch_sources]

    exists: List[str] = []
    missing_on_disk: List[str] = []
    for rel in rel_sources:
        if (root / rel).is_file():
            exists.append(rel)
        else:
            missing_on_disk.append(rel)

    referenced_by_cmake: List[str] = []
    not_referenced_by_cmake: List[str] = []
    for rel in exists:
        base = Path(rel).name
        # If exact token exists or basename is referenced anywhere.
        if rel in cmake_norm_set or base in cmake_basenames:
            referenced_by_cmake.append(rel)
        else:
            not_referenced_by_cmake.append(rel)

    # Output locations
    cmake_out_dir = root / "cmake" / "polish_batches"
    polish_out_dir = root / "polish" / f"batch_{args.batch}"
    ensure_dirs(cmake_out_dir, polish_out_dir)

    cmake_sources_out = cmake_out_dir / f"batch_{args.batch}_sources.cmake"
    cmake_groups_out = cmake_out_dir / f"batch_{args.batch}_source_groups.cmake"
    report_out = polish_out_dir / f"batch_{args.batch}_polish_report.json"

    write_cmake_batch_sources(cmake_sources_out, root, exists, args.batch)
    write_cmake_source_groups(cmake_groups_out, args.batch)

    report = {
        "deliverable": "batch_polish_alignment",
        "no_mixing": "YES",
        "policy": {
            "uses_only_existing_sources": True,
            "does_not_delete_sources": True,
            "does_not_recode_sources": True,
            "does_not_move_sources": True,
            "writes_only": [
                str(cmake_sources_out),
                str(cmake_groups_out),
                str(report_out),
            ],
        },
        "generated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "project_root": str(root),
        "batch": {
            "batch_id": args.batch,
            "requested_count": len(rel_sources),
            "exists_on_disk": len(exists),
            "missing_on_disk": len(missing_on_disk),
        },
        "cmake_alignment": {
            "cmake_file": str(cmake_path),
            "cmake_tokens_found": len(cmake_raw),
            "batch_files_referenced_by_cmake": len(referenced_by_cmake),
            "batch_files_not_referenced_by_cmake": len(not_referenced_by_cmake),
        },
        "lists": {
            "missing_on_disk": missing_on_disk,
            "not_referenced_by_cmake": not_referenced_by_cmake,
            "referenced_by_cmake": referenced_by_cmake,
        },
        "cmake_outputs": {
            "batch_sources_cmake": str(cmake_sources_out),
            "batch_source_groups_cmake": str(cmake_groups_out),
            "include_hint": [
                f"include(cmake/polish_batches/batch_{args.batch}_sources.cmake)",
                f"include(cmake/polish_batches/batch_{args.batch}_source_groups.cmake)",
                "# Then add ${RAWRXD_BATCH_<id>_SOURCES} to your target_sources(...) as desired."
            ],
        },
    }

    report_out.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print("=== Batch Polish Alignment (NO MIXING) ===")
    print(f"Root: {root}")
    print(f"Batch: {args.batch} | Files: {len(rel_sources)} | Exists: {len(exists)} | Missing-on-disk: {len(missing_on_disk)}")
    print(f"Referenced-by-CMake: {len(referenced_by_cmake)} | Not-referenced-by-CMake: {len(not_referenced_by_cmake)}")
    print(f"Wrote: {cmake_sources_out}")
    print(f"Wrote: {cmake_groups_out}")
    print(f"Wrote: {report_out}")


if __name__ == "__main__":
    main()
