# EXTENSION ECOSYSTEM CONSOLIDATION HAMMER
# Fixes undefined publishers, generates enterprise manifests, wires unified agentic IDE

$extensions = @{
    "cursor-simple-ai" = @{ "pub" = "ItsMehRAWRXD"; "type" = "ai"; "deps" = @() }
    "rawrz-agentic" = @{ "pub" = "rawrz-underground"; "type" = "agent"; "deps" = @("cursor-simple-ai") }
    "rawrxd-lsp-client" = @{ "pub" = "ItsMehRAWRXD"; "type" = "lsp"; "deps" = @() }
    "cursor-ollama-proxy" = @{ "pub" = "ItsMehRAWRXD"; "type" = "proxy"; "deps" = @() }
    "cursor-multi-ai" = @{ "pub" = "ItsMehRAWRXD"; "type" = "ai"; "deps" = @("cursor-simple-ai") }
    "bigdaddyg-copilot" = @{ "pub" = "bigdaddyg"; "type" = "copilot"; "deps" = @("cursor-multi-ai", "rawrxd-lsp-client") }
    "bigdaddyg-cursor-chat" = @{ "pub" = "bigdaddyg"; "type" = "chat"; "deps" = @("bigdaddyg-copilot") }
    "bigdaddyg-asm-ide" = @{ "pub" = "bigdaddyg"; "type" = "ide"; "deps" = @("rawrxd-lsp-client", "bigdaddyg-copilot") }
    "bigdaddyg-asm-extension" = @{ "pub" = "bigdaddyg"; "type" = "lang"; "deps" = @() }
}

$basePath = "D:\rawrxd\extensions"
New-Item -ItemType Directory -Force -Path $basePath | Out-Null

# Generate enterprise package.json for each
$extensions.GetEnumerator() | ForEach-Object {
    $name = $_.Key
    $cfg = $_.Value
    $extPath = "$basePath\$($cfg.pub).$name"
    New-Item -ItemType Directory -Force -Path $extPath | Out-Null
    New-Item -ItemType Directory -Force -Path "$extPath\src" | Out-Null
    New-Item -ItemType Directory -Force -Path "$extPath\out" | Out-Null

    $extensionDeps = $cfg.deps | ForEach-Object {
        $depCfg = $extensions[$_]
        "$($depCfg.pub).$_"
    }

    $manifest = @{
        name = $name
        publisher = $cfg.pub
        version = "14.2.0"
        engines = @{ vscode = "^1.90.0" }
        categories = @("Programming Languages", "Machine Learning", "Debuggers")
        activationEvents = @("onStartupFinished")
        main = "./out/extension.js"
        contributes = @{
            commands = @(
                @{ command = "$name.activate"; title = "Activate $name"; category = "RawrXD" }
                @{ command = "$name.hammer"; title = "Execute Hammer Protocol"; category = "RawrXD" }
            )
            configuration = @{
                title = $name
                properties = @{
                    "$name.enabled" = @{ type = "boolean"; default = $true; description = "Enable $name" }
                    "$name.autoConnect" = @{ type = "boolean"; default = $true; description = "Auto-connect to RawrXD core" }
                }
            }
            views = @{
                explorer = @(@{ id = "$name.view"; name = "$name Agentic Panel"; when = "rawrxd.enabled" })
            }
        }
        scripts = @{ compile = "tsc -p ./"; watch = "tsc -watch -p ./"; package = "vsce package" }
        devDependencies = @{ "@types/vscode" = "^1.90.0"; typescript = "^5.4.0"; "@types/node" = "^20.0.0"; vsce = "^2.15.0" }
    }
    if ($extensionDeps.Count -gt 0) {
        $manifest.extensionDependencies = @($extensionDeps)
    }
    $manifest | ConvertTo-Json -Depth 10 | Set-Content "$extPath\package.json" -Encoding utf8

    # Generate TypeScript stub that wires to MASM64 backend
    $tsStub = @"
// Auto-generated by Extension Hammer v14.2.0
import * as vscode from 'vscode';
import { spawn } from 'child_process';

const EXT_ID = '$($cfg.pub).$name';
const HAMMER_PATH = 'D:\\rawrxd\\build_prod\\RawrXD_Agent.exe';

export function activate(context: vscode.ExtensionContext) {
    const output = vscode.window.createOutputChannel('$name');
    output.appendLine('[RawrXD] Extension Hammer Activated: $name');

    // Wire to MASM64 backend via named pipe (spawn only if executable exists)
    let pipe: ReturnType<typeof spawn> | null = null;
    try {
        pipe = spawn(HAMMER_PATH, ['--extension-pipe', EXT_ID], { detached: true });
    } catch {
        output.appendLine('[RawrXD] Backend not found at ' + HAMMER_PATH + '; running in standalone mode.');
    }

    context.subscriptions.push(
        vscode.commands.registerCommand('$name.activate', () => {
            vscode.window.showInformationMessage('$name: Connected to RawrXD Core');
            pipe?.stdin?.write?.('INIT:$name\n');
        }),

        vscode.commands.registerCommand('$name.hammer', () => {
            pipe?.stdin?.write?.('HAMMER:EXECUTE\n');
            output.appendLine('Hammer protocol executed');
        })
    );

    // Auto-connect to RawrXD if available
    const config = vscode.workspace.getConfiguration();
    if (config.get<boolean>('$name.autoConnect') !== false && pipe) {
        setTimeout(() => pipe?.stdin?.write?.('AUTOCONNECT\n'), 1000);
    }
}

export function deactivate() {
    // Cleanup MASM64 connections
}
"@
    $tsStub | Set-Content "$extPath\src\extension.ts" -Encoding utf8

    # Generate tsconfig
    @{
        compilerOptions = @{
            module = "commonjs"
            target = "ES2020"
            lib = @("ES2020")
            outDir = "./out"
            rootDir = "./src"
            strict = $true
        }
        exclude = @("node_modules", ".vscode-test")
    } | ConvertTo-Json | Set-Content "$extPath\tsconfig.json" -Encoding utf8

    Write-Host "Generated: $($cfg.pub).$name" -ForegroundColor Green
}

# Create Extension Pack (Unified RawrXD Distribution)
$packPath = "$basePath\ItsMehRAWRXD.rawrxd-complete-pack"
New-Item -ItemType Directory -Force -Path $packPath | Out-Null
$packExts = $extensions.GetEnumerator() | ForEach-Object { "$($_.Value.pub).$($_.Key)" }
@{
    name = "rawrxd-complete-pack"
    publisher = "ItsMehRAWRXD"
    version = "14.2.0"
    displayName = "RawrXD Complete Agentic IDE"
    description = "Complete MASM64 AI IDE with Copilot, LSP, and Ollama Proxy"
    extensionPack = @($packExts)
} | ConvertTo-Json -Depth 5 | Set-Content "$packPath\package.json" -Encoding utf8

Write-Host ""
Write-Host "EXTENSION ECOSYSTEM HAMMERED" -ForegroundColor Magenta
Write-Host "Unified Publisher: ItsMehRAWRXD + bigdaddyg" -ForegroundColor Gray
Write-Host "Extensions: 9 packages generated" -ForegroundColor Gray
Write-Host "Extension Pack: ItsMehRAWRXD.rawrxd-complete-pack" -ForegroundColor Green
Write-Host ""
Write-Host "EXECUTE: .\BUILD_ALL_EXTENSIONS.ps1 -Install" -ForegroundColor Yellow
