; =============================================================================
; RawrXD_Prometheus_Exporter.asm — Pure x64 MASM
; Formats UTC binary counters into Prometheus Text Format (v0.0.4)
; =============================================================================
;
; Architecture:
;   - Zero-allocation formatting: writes directly into a caller-provided buffer
;   - Custom high-speed U64-to-ASCII (division-based, in-place reverse)
;   - No sprintf, no CRT, no heap churn
;   - Directly consumable by Prometheus /metrics scrape endpoint
;
; Exports:
;   ExportPrometheus          — Full metrics payload into buffer
;   ExportPrometheusMetric    — Single metric line into buffer
;   Internal_U64ToAscii       — 64-bit integer to ASCII conversion
;   Internal_AppendString     — Fast memcpy-style string append
;
; Pattern: Returns RAX = total bytes written
; Rule:    NO CRT, NO Qt, NO exceptions, NO heap
; =============================================================================

include RawrXD_Common.inc

; Import counter symbols from RawrXD_Telemetry_Kernel.asm
EXTERNDEF g_Counter_Inference:QWORD
EXTERNDEF g_Counter_ScsiFails:QWORD
EXTERNDEF g_Counter_AgentLoop:QWORD
EXTERNDEF g_Counter_BytePatches:QWORD
EXTERNDEF g_Counter_MemPatches:QWORD
EXTERNDEF g_Counter_ServerPatches:QWORD
EXTERNDEF g_Counter_FlushOps:QWORD
EXTERNDEF g_Counter_Errors:QWORD

; =============================================================================
;                           Data Segment
; =============================================================================

.data

    ; =========================================================================
    ; Prometheus Metric Metadata — Inference Tokens
    ; =========================================================================
    metric_inf_help   db "# HELP rawrxd_inference_tokens_total Total tokens generated by ASM inference kernels", 10, 0
    metric_inf_type   db "# TYPE rawrxd_inference_tokens_total counter", 10, 0
    metric_inf_name   db "rawrxd_inference_tokens_total", 0

    ; =========================================================================
    ; Agent Loop Steps
    ; =========================================================================
    metric_agent_help db "# HELP rawrxd_agent_steps_total Count of completed agentic loop iterations", 10, 0
    metric_agent_type db "# TYPE rawrxd_agent_steps_total counter", 10, 0
    metric_agent_name db "rawrxd_agent_steps_total", 0

    ; =========================================================================
    ; SCSI Hardware Failures
    ; =========================================================================
    metric_scsi_help  db "# HELP rawrxd_scsi_failures_total Hardware SCSI timeout and error count", 10, 0
    metric_scsi_type  db "# TYPE rawrxd_scsi_failures_total counter", 10, 0
    metric_scsi_name  db "rawrxd_scsi_failures_total", 0

    ; =========================================================================
    ; Byte-Level Hotpatches
    ; =========================================================================
    metric_byte_help  db "# HELP rawrxd_byte_patches_total Byte-level GGUF hotpatches applied", 10, 0
    metric_byte_type  db "# TYPE rawrxd_byte_patches_total counter", 10, 0
    metric_byte_name  db "rawrxd_byte_patches_total", 0

    ; =========================================================================
    ; Memory Hotpatches
    ; =========================================================================
    metric_mem_help   db "# HELP rawrxd_memory_patches_total Memory-layer hotpatches applied via VirtualProtect", 10, 0
    metric_mem_type   db "# TYPE rawrxd_memory_patches_total counter", 10, 0
    metric_mem_name   db "rawrxd_memory_patches_total", 0

    ; =========================================================================
    ; Server Hotpatches
    ; =========================================================================
    metric_srv_help   db "# HELP rawrxd_server_patches_total Server-layer request/response patches applied", 10, 0
    metric_srv_type   db "# TYPE rawrxd_server_patches_total counter", 10, 0
    metric_srv_name   db "rawrxd_server_patches_total", 0

    ; =========================================================================
    ; Flush Operations
    ; =========================================================================
    metric_flush_help db "# HELP rawrxd_flush_ops_total Ring buffer flush-to-disk operations", 10, 0
    metric_flush_type db "# TYPE rawrxd_flush_ops_total counter", 10, 0
    metric_flush_name db "rawrxd_flush_ops_total", 0

    ; =========================================================================
    ; Error Counter
    ; =========================================================================
    metric_err_help   db "# HELP rawrxd_errors_total Total errors observed across all subsystems", 10, 0
    metric_err_type   db "# TYPE rawrxd_errors_total counter", 10, 0
    metric_err_name   db "rawrxd_errors_total", 0

    ; =========================================================================
    ; Info metric (build identification)
    ; =========================================================================
    metric_info_help  db "# HELP rawrxd_build_info Build metadata for RawrXD kernel", 10, 0
    metric_info_type  db "# TYPE rawrxd_build_info gauge", 10, 0
    metric_info_line  db 'rawrxd_build_info{version="tier3-masm",arch="x64",runtime="none"} 1', 10, 0

    ; Common characters
    szSpace           db " ", 0
    szNewlineProm     db 10, 0

; =============================================================================
;                           Code Segment
; =============================================================================

.code

; =============================================================================
; ExportPrometheus — Generates the full Prometheus metrics payload
; RCX = Destination buffer (should be >= 8KB for safety)
; Returns: RAX = Total bytes written to buffer
; =============================================================================
ExportPrometheus PROC FRAME
    push rbx
    .pushreg rbx
    push rdi
    .pushreg rdi
    push rsi
    .pushreg rsi
    push r12
    .pushreg r12
    sub  rsp, 40
    .allocstack 40
    .endprolog

    mov  rdi, rcx               ; RDI = current write position
    mov  rbx, rcx               ; RBX = start address (for length calc)

    ; --- Build Info (static gauge) ---
    lea  rsi, metric_info_help
    call Internal_AppendString
    lea  rsi, metric_info_type
    call Internal_AppendString
    lea  rsi, metric_info_line
    call Internal_AppendString

    ; --- Inference Tokens ---
    lea  rsi, metric_inf_help
    call Internal_AppendString
    lea  rsi, metric_inf_type
    call Internal_AppendString
    lea  rsi, metric_inf_name
    call Internal_AppendString
    mov  byte ptr [rdi], ' '
    inc  rdi
    mov  rax, qword ptr [g_Counter_Inference]
    call Internal_U64ToAscii
    mov  byte ptr [rdi], 10     ; LF
    inc  rdi

    ; --- Agent Steps ---
    lea  rsi, metric_agent_help
    call Internal_AppendString
    lea  rsi, metric_agent_type
    call Internal_AppendString
    lea  rsi, metric_agent_name
    call Internal_AppendString
    mov  byte ptr [rdi], ' '
    inc  rdi
    mov  rax, qword ptr [g_Counter_AgentLoop]
    call Internal_U64ToAscii
    mov  byte ptr [rdi], 10
    inc  rdi

    ; --- SCSI Failures ---
    lea  rsi, metric_scsi_help
    call Internal_AppendString
    lea  rsi, metric_scsi_type
    call Internal_AppendString
    lea  rsi, metric_scsi_name
    call Internal_AppendString
    mov  byte ptr [rdi], ' '
    inc  rdi
    mov  rax, qword ptr [g_Counter_ScsiFails]
    call Internal_U64ToAscii
    mov  byte ptr [rdi], 10
    inc  rdi

    ; --- Byte Patches ---
    lea  rsi, metric_byte_help
    call Internal_AppendString
    lea  rsi, metric_byte_type
    call Internal_AppendString
    lea  rsi, metric_byte_name
    call Internal_AppendString
    mov  byte ptr [rdi], ' '
    inc  rdi
    mov  rax, qword ptr [g_Counter_BytePatches]
    call Internal_U64ToAscii
    mov  byte ptr [rdi], 10
    inc  rdi

    ; --- Memory Patches ---
    lea  rsi, metric_mem_help
    call Internal_AppendString
    lea  rsi, metric_mem_type
    call Internal_AppendString
    lea  rsi, metric_mem_name
    call Internal_AppendString
    mov  byte ptr [rdi], ' '
    inc  rdi
    mov  rax, qword ptr [g_Counter_MemPatches]
    call Internal_U64ToAscii
    mov  byte ptr [rdi], 10
    inc  rdi

    ; --- Server Patches ---
    lea  rsi, metric_srv_help
    call Internal_AppendString
    lea  rsi, metric_srv_type
    call Internal_AppendString
    lea  rsi, metric_srv_name
    call Internal_AppendString
    mov  byte ptr [rdi], ' '
    inc  rdi
    mov  rax, qword ptr [g_Counter_ServerPatches]
    call Internal_U64ToAscii
    mov  byte ptr [rdi], 10
    inc  rdi

    ; --- Flush Ops ---
    lea  rsi, metric_flush_help
    call Internal_AppendString
    lea  rsi, metric_flush_type
    call Internal_AppendString
    lea  rsi, metric_flush_name
    call Internal_AppendString
    mov  byte ptr [rdi], ' '
    inc  rdi
    mov  rax, qword ptr [g_Counter_FlushOps]
    call Internal_U64ToAscii
    mov  byte ptr [rdi], 10
    inc  rdi

    ; --- Errors ---
    lea  rsi, metric_err_help
    call Internal_AppendString
    lea  rsi, metric_err_type
    call Internal_AppendString
    lea  rsi, metric_err_name
    call Internal_AppendString
    mov  byte ptr [rdi], ' '
    inc  rdi
    mov  rax, qword ptr [g_Counter_Errors]
    call Internal_U64ToAscii
    mov  byte ptr [rdi], 10
    inc  rdi

    ; --- Final EOF marker (empty line per Prometheus spec) ---
    mov  byte ptr [rdi], 10
    inc  rdi
    mov  byte ptr [rdi], 0      ; Null terminate

    ; Calculate total length
    mov  rax, rdi
    sub  rax, rbx

    add  rsp, 40
    pop  r12
    pop  rsi
    pop  rdi
    pop  rbx
    ret
ExportPrometheus ENDP

; =============================================================================
; ExportPrometheusMetric — Exports a single metric line
; RCX = Destination buffer
; RDX = Metric name (null-terminated string)
; R8  = Pointer to the counter QWORD
; Returns: RAX = bytes written
; =============================================================================
ExportPrometheusMetric PROC FRAME
    push rdi
    .pushreg rdi
    push rsi
    .pushreg rsi
    push rbx
    .pushreg rbx
    sub  rsp, 32
    .allocstack 32
    .endprolog

    mov  rdi, rcx               ; Destination
    mov  rbx, rcx               ; Start for length calc

    ; Copy metric name
    mov  rsi, rdx
    call Internal_AppendString

    ; Space separator
    mov  byte ptr [rdi], ' '
    inc  rdi

    ; Load and convert counter value
    mov  rax, qword ptr [r8]
    call Internal_U64ToAscii

    ; Newline
    mov  byte ptr [rdi], 10
    inc  rdi
    mov  byte ptr [rdi], 0

    ; Return length
    mov  rax, rdi
    sub  rax, rbx

    add  rsp, 32
    pop  rbx
    pop  rsi
    pop  rdi
    ret
ExportPrometheusMetric ENDP

; =============================================================================
; Internal_U64ToAscii — Fast division-based 64-bit to ASCII conversion
; RAX = Value to convert
; RDI = Destination buffer (pointer is advanced past the digits)
; =============================================================================
; Algorithm:
;   1. Repeatedly divide by 10, collecting remainders (digits in reverse)
;   2. In-place two-pointer reverse to correct order
;   3. Zero produces "0" (not empty string)
; =============================================================================
Internal_U64ToAscii PROC
    push r8
    push r9
    push r10

    mov  r10, rdi               ; Mark start position
    mov  r9,  10                 ; Divisor = 10

    ; Handle zero specially
    test rax, rax
    jnz  @convert_loop
    mov  byte ptr [rdi], '0'
    inc  rdi
    jmp  @convert_done

@convert_loop:
    xor  rdx, rdx
    div  r9                     ; RAX = quotient, RDX = remainder
    add  dl, '0'                ; Convert to ASCII digit
    mov  byte ptr [rdi], dl
    inc  rdi
    test rax, rax
    jnz  @convert_loop

    ; Digits are in reverse order — perform in-place swap
    mov  r8, r10                ; Left pointer = start
    lea  r9, [rdi - 1]          ; Right pointer = end

@reverse_loop:
    cmp  r8, r9
    jae  @convert_done
    mov  al, byte ptr [r8]
    mov  cl, byte ptr [r9]
    mov  byte ptr [r8], cl
    mov  byte ptr [r9], al
    inc  r8
    dec  r9
    jmp  @reverse_loop

@convert_done:
    pop  r10
    pop  r9
    pop  r8
    ret
Internal_U64ToAscii ENDP

; =============================================================================
; Internal_AppendString — Copy null-terminated string from RSI to RDI
; RSI = Source string (null-terminated)
; RDI = Destination (advanced past copied bytes)
; =============================================================================
Internal_AppendString PROC
@@:
    lodsb                       ; AL = [RSI++]
    test al, al                 ; Check for null terminator
    jz   @done
    stosb                       ; [RDI++] = AL
    jmp  @b
@done:
    ret
Internal_AppendString ENDP

END
