; =============================================================================
; rawr_globals.asm — Centralized Global State for RawrXD (x64 MASM64)
; =============================================================================
;
; Single translation unit that OWNS all cross-module shared state.
; Every other .asm file must reference these symbols via EXTERN / EXTERNDEF
; (provided by rawr_globals.inc).
;
; Categories:
;   1. CPU Feature Flags      — CPUID results cached at init
;   2. Dispatch Pointers      — Function pointers for runtime dispatch
;   3. Telemetry Counters     — Cache-line padded atomic counters
;   4. Shell Integration      — Cache-line padded shell metrics
;   5. Agentic Shell Bridge   — Cache-line padded AI bridge metrics
;   6. Enterprise License     — Feature gate flags
;   7. Flash Attention        — AVX-512 readiness + perf counters
;   8. Inference Stats        — GEMM/GEMV accumulated metrics
;
; Build: ml64.exe /c /Zi /Zd /I"src/asm" rawr_globals.asm
; Rule:  NO SOURCE FILE IS TO BE SIMPLIFIED
; =============================================================================

option casemap:none

; =============================================================================
;  1. CPU Feature Flags + Inference Dispatch  (64-byte aligned)
; =============================================================================
_DATA64 SEGMENT ALIGN(64) 'DATA'

; ─── CPUID Feature Flags (set by InferenceCore_Init) ─────────────────────────
PUBLIC g_HasAVX2
PUBLIC g_HasFMA3
PUBLIC g_HasAVX512F

g_HasAVX2               DD 0
g_HasFMA3               DD 0
g_HasAVX512F            DD 0
                        DD 0            ; pad to 16 bytes

; ─── Inference Performance Counters ──────────────────────────────────────────
PUBLIC g_GemmCalls
PUBLIC g_GemvCalls
PUBLIC g_GemmFlops

g_GemmCalls             DQ 0
g_GemvCalls             DQ 0
g_GemmFlops             DQ 0            ; Accumulated FLOPs

; ─── Dispatch Function Pointers (set by Init to best available path) ─────────
PUBLIC g_GemmDispatch
PUBLIC g_GemvDispatch

g_GemmDispatch          DQ 0            ; -> sgemm_avx2 or sgemm_avx512
g_GemvDispatch          DQ 0            ; -> sgemv_avx2 or sgemv_avx512

; ─── Flash Attention AVX-512 ─────────────────────────────────────────────────
; Broadcast-ready constants (64-byte aligned for ZMM loads)
PUBLIC g_NegInf
PUBLIC g_AVX512Ready
PUBLIC g_FlashAttnCalls
PUBLIC g_FlashAttnTiles

ALIGN 64
g_NegInf                DD 16 DUP(0FF800000h)  ; -inf x16 (one ZMM)

g_AVX512Ready           DD 0

ALIGN 8
g_FlashAttnCalls        DQ 0
g_FlashAttnTiles        DQ 0

_DATA64 ENDS

; =============================================================================
;  2. Enterprise License Flags
; =============================================================================
.data
ALIGN 16

PUBLIC g_800B_Unlocked
PUBLIC g_EnterpriseFeatures

g_800B_Unlocked         DD 0
g_EnterpriseFeatures    DQ 0

; =============================================================================
;  3. Telemetry Counters  (cache-line padded to prevent false sharing)
; =============================================================================
; Each entry is manually padded to 64 bytes for cache-line isolation.
; ml64 maximum segment alignment is 16; data self-pads to 64.

TELEMETRY_CL SEGMENT ALIGN(16) 'DATA'

    PUBLIC g_MetricTableStart
    g_MetricTableStart      DQ 0DEADBEEFCAFEBABEh   ; Sentinel / magic
                            DB 56 DUP(0)             ; Pad to 64 bytes

    PUBLIC g_Counter_Inference
    g_Counter_Inference     DQ 0    ; Total tokens generated by ASM kernels
                            DB 56 DUP(0)

    PUBLIC g_Counter_ScsiFails
    g_Counter_ScsiFails     DQ 0    ; Hardware SCSI timeout count
                            DB 56 DUP(0)

    PUBLIC g_Counter_AgentLoop
    g_Counter_AgentLoop     DQ 0    ; Total agentic loop steps executed
                            DB 56 DUP(0)

    PUBLIC g_Counter_BytePatches
    g_Counter_BytePatches   DQ 0    ; Byte-level hotpatches applied
                            DB 56 DUP(0)

    PUBLIC g_Counter_MemPatches
    g_Counter_MemPatches    DQ 0    ; Memory hotpatches applied
                            DB 56 DUP(0)

    PUBLIC g_Counter_ServerPatches
    g_Counter_ServerPatches DQ 0    ; Server-layer hotpatches applied
                            DB 56 DUP(0)

    PUBLIC g_Counter_FlushOps
    g_Counter_FlushOps      DQ 0    ; Number of flush-to-disk operations
                            DB 56 DUP(0)

    PUBLIC g_Counter_Errors
    g_Counter_Errors        DQ 0    ; Total errors observed
                            DB 56 DUP(0)

    PUBLIC g_MetricTableEnd
    g_MetricTableEnd        DQ 0BADCAFEDEADFACEh   ; Sentinel / end marker
                            DB 56 DUP(0)

TELEMETRY_CL ENDS

; =============================================================================
;  4. Shell Integration Counters  (cache-line padded)
; =============================================================================

SHELLINTEG_CL SEGMENT ALIGN(16) 'DATA'

    PUBLIC g_ShellInteg_MetricStart
    g_ShellInteg_MetricStart    DQ 05348454C4C494E54h  ; "SHELLINT" sentinel
                                DB 56 DUP(0)

    PUBLIC g_SI_Counter_CmdsExecuted
    g_SI_Counter_CmdsExecuted   DQ 0
                                DB 56 DUP(0)

    PUBLIC g_SI_Counter_CmdsDetected
    g_SI_Counter_CmdsDetected   DQ 0
                                DB 56 DUP(0)

    PUBLIC g_SI_Counter_BytesRead
    g_SI_Counter_BytesRead      DQ 0
                                DB 56 DUP(0)

    PUBLIC g_SI_Counter_BytesWritten
    g_SI_Counter_BytesWritten   DQ 0
                                DB 56 DUP(0)

    PUBLIC g_SI_Counter_OSC633Injected
    g_SI_Counter_OSC633Injected DQ 0
                                DB 56 DUP(0)

    PUBLIC g_SI_Counter_PipeReadErrors
    g_SI_Counter_PipeReadErrors DQ 0
                                DB 56 DUP(0)

    PUBLIC g_SI_Counter_PipeWriteErrors
    g_SI_Counter_PipeWriteErrors DQ 0
                                DB 56 DUP(0)

    PUBLIC g_SI_Counter_ProcessRestarts
    g_SI_Counter_ProcessRestarts DQ 0
                                DB 56 DUP(0)

    PUBLIC g_ShellInteg_MetricEnd
    g_ShellInteg_MetricEnd      DQ 0454E44534849454Ch  ; "ENDSHIEL" sentinel
                                DB 56 DUP(0)

SHELLINTEG_CL ENDS

; =============================================================================
;  5. Agentic Shell Bridge Counters  (cache-line padded)
; =============================================================================

AGENTSHELL_CL SEGMENT ALIGN(16) 'DATA'

    PUBLIC g_AS_MetricStart
    g_AS_MetricStart        DQ 04147454E544149h     ; "AGENTAI" sentinel
                            DB 56 DUP(0)

    PUBLIC g_AS_Counter_CtxCaptured
    g_AS_Counter_CtxCaptured    DQ 0
                                DB 56 DUP(0)

    PUBLIC g_AS_Counter_AIRequests
    g_AS_Counter_AIRequests     DQ 0
                                DB 56 DUP(0)

    PUBLIC g_AS_Counter_AISuccess
    g_AS_Counter_AISuccess      DQ 0
                                DB 56 DUP(0)

    PUBLIC g_AS_Counter_AIFailures
    g_AS_Counter_AIFailures     DQ 0
                                DB 56 DUP(0)

    PUBLIC g_AS_Counter_BytesSentToAI
    g_AS_Counter_BytesSentToAI  DQ 0
                                DB 56 DUP(0)

    PUBLIC g_AS_Counter_BytesFromAI
    g_AS_Counter_BytesFromAI    DQ 0
                                DB 56 DUP(0)

    PUBLIC g_AS_Counter_CtxDropped
    g_AS_Counter_CtxDropped     DQ 0
                                DB 56 DUP(0)

    PUBLIC g_AS_Counter_LocalStubHits
    g_AS_Counter_LocalStubHits  DQ 0
                                DB 56 DUP(0)

    PUBLIC g_AS_MetricEnd
    g_AS_MetricEnd          DQ 0454E44414745h       ; "ENDAGE" sentinel
                            DB 56 DUP(0)

AGENTSHELL_CL ENDS

; =============================================================================
; No code — this is a data-only translation unit.
; =============================================================================

END
