; masm_header_gen.asm - Pure MASM x64 header generator
; Scans a directory for .asm files and emits a .inc header with EXTERNDEF/PROTO lines
; Usage: masm_header_gen.exe <input_dir> <output_file>

option casemap:none

.data
    CRLF            db 13,10,0
    USAGE_TEXT      db "Usage: masm_header_gen <input_dir> <output_file>",13,10,0
    GEN_HEADER_1    db "; Generated by masm_header_gen (pure MASM)",13,10,0
    GEN_HEADER_2    db "; Do not edit manually.",13,10,13,10,0

    patternSuffix   db "\\*.asm",0
    backslash       db "\\",0
    PUBLIC_kw       db "PUBLIC ",0
    PROC_kw         db " PROC",0

    inDir           db 512 dup(0)
    outPath         db 512 dup(0)
    searchPattern   db 1024 dup(0)
    filePath        db 1024 dup(0)

    findData        db 320 dup(0)        ; WIN32_FIND_DATAA (enough space)

    readBuf         db 65536 dup(0)
    lineBuf         db 4096 dup(0)

    symbolsBuf      db 65536 dup(0)      ; concatenated null-terminated symbols
    symbolsLen      dq 0

    hStdOut         dq 0
    hFind           dq 0
    hIn             dq 0
    hOut            dq 0

    bytesIO         dq 0

.code

extern  GetCommandLineA:proc
extern  WriteFile:proc
extern  GetStdHandle:proc
extern  CreateFileA:proc
extern  CloseHandle:proc
extern  ReadFile:proc
extern  FindFirstFileA:proc
extern  FindNextFileA:proc
extern  FindClose:proc
extern  ExitProcess:proc

STD_OUTPUT_HANDLE equ -11
GENERIC_READ   equ 80000000h
GENERIC_WRITE  equ 40000000h
FILE_SHARE_READ equ 1
OPEN_EXISTING  equ 3
CREATE_ALWAYS  equ 2
FILE_ATTRIBUTE_NORMAL equ 80h
INVALID_HANDLE_VALUE equ -1

; ---------------------------------------------
; Simple helpers
; ---------------------------------------------
strlenA proc psz_local:QWORD
    mov rdi, psz_local
    xor rax, rax
@@:
    cmp byte ptr [rdi+rax], 0
    je @f
    inc rax
    jmp @B
@@:
    ret
strlenA endp

strcpyA proc uses rsi rdi rcx, dst:QWORD, src:QWORD
    mov rdi, dst
    mov rsi, src
@@:
    mov al, [rsi]
    mov [rdi], al
    inc rsi
    inc rdi
    test al, al
    jnz @B
    ret
strcpyA endp

strcatA proc uses rsi rdi rax, dst:QWORD, src:QWORD
    mov rdi, dst
next:
    mov al, [rdi]
    test al, al
    jz copy
    inc rdi
    jmp next
copy:
    mov rsi, src
@@:
    mov al, [rsi]
    mov [rdi], al
    inc rsi
    inc rdi
    test al, al
    jnz @B
    ret
strcatA endp

toupperA proc uses rax, cval:BYTE
    movzx rax, cval
    cmp al, 'a'
    jb @f
    cmp al, 'z'
    ja @f
    sub al, 32
@@:
    movzx rax, al
    ret
toupperA endp

; write null-terminated string to handle in rcx
writeZ proc uses rdx r8 r9 rax, h:QWORD, psz_local:QWORD
    mov rcx, psz_local
    call strlenA
    mov r8, rax
    mov rcx, h
    mov rdx, psz_local
    lea r9, bytesIO
    sub rsp, 32
    call WriteFile
    add rsp, 32
    ret
writeZ endp

; compare begins-with (case-insensitive), psz line vs psz prefix
; returns ZF=1 if begins with
begins_with_ci proc uses rsi rdi rax rbx rcx, psz_local:QWORD, pfx:QWORD
    mov rsi, psz_local
    mov rdi, pfx
loop_local:
    mov bl, [rdi]
    test bl, bl
    jz equal_local     ; end of prefix reached
    mov cl, [rsi]
    test cl, cl
    jz notequal_local
    ; toupper BL
    cmp bl, 'a'
    jb no_up1_local
    cmp bl, 'z'
    ja no_up1_local
    sub bl, 32
no_up1_local:
    ; toupper CL
    cmp cl, 'a'
    jb no_up2_local
    cmp cl, 'z'
    ja no_up2_local
    sub cl, 32
no_up2_local:
    cmp bl, cl
    jne notequal_local
    inc rdi
    inc rsi
    jmp loop_local
equal_local:
    mov rax, 1
    ret
notequal_local:
    xor rax, rax
    ret
begins_with_ci endp

; find substring (case-insensitive). returns offset in RAX or -1
find_ci proc psz_local:QWORD, sub_str:QWORD
    mov rsi, psz_local
    mov rbx, sub_str
    xor rax, rax
outer:
    mov rdi, rsi
    ; compare at rdi
    mov rcx, rdi
    mov rdx, rbx
    ; manual compare loop
@@:
    mov al, [rdx]
    test al, al
    jz found
    mov dl, [rcx]
    test dl, dl
    jz notfound
    ; toupper
    mov bl, al
    mov cl, dl
    cmp bl, 'a'
    jb @F
    cmp bl, 'z'
    ja @F
    sub bl, 32
@@:
    cmp cl, 'a'
    jb F2_local
    cmp cl, 'z'
    ja F2_local
    sub cl, 32
F2_local:
    cmp bl, cl
    jne nextpos
    inc rdx
    inc rcx
    jmp @B
found:
    ; return offset = rdi - psz_local
    mov rax, rdi
    sub rax, psz_local
    ret
nextpos:
    inc rsi
    mov al, [rsi]
    test al, al
    jnz outer
notfound:
    mov rax, -1
    ret
find_ci endp

; add symbol to symbolsBuf if not present
add_symbol proc uses rsi rdi rbx rax, psz_local:QWORD
    mov rbx, psz_local
    mov rsi, OFFSET symbolsBuf

    ; scan existing
scan_loop:
    ; if first byte zero, buffer empty at this pos
    cmp byte ptr [rsi], 0
    je add_here

    ; compare strings
    mov rdi, rsi
cmploop:
    mov al, [rdi]
    mov dl, [rbx]
    cmp al, dl
    jne @F
    test al, al
    jz already
    inc rdi
    inc rbx
    jmp cmploop
@@:
    ; advance to next stored symbol
    ; move rbx back to start param
    mov rbx, psz_local
skip_sym:
    cmp byte ptr [rsi], 0
    je add_here
    inc rsi
    jmp skip_sym

add_here:
    ; copy psz into rsi
    mov rdi, rsi
    mov rsi, psz_local
cpy_sym:
    mov al, [rsi]
    mov [rdi], al
    inc rsi
    inc rdi
    test al, al
    jnz cpy_sym
    ; update symbolsLen
    mov rax, rdi
    lea rdx, symbolsBuf
    sub rax, rdx
    mov symbolsLen, rax
    ret

already:
    ret
add_symbol endp

; process a single line in lineBuf
process_line proc uses rax rbx rcx rdx, psz_local:QWORD
    ; Check for PUBLIC
    mov rcx, psz_local
    mov rdx, OFFSET PUBLIC_kw
    call begins_with_ci
    test rax, rax
    jz check_proc
    ; after PUBLIC, parse tokens (comma/space separated)
    ; skip "PUBLIC "
    mov rsi, psz_local
    add rsi, 7
skipsp:
    cmp byte ptr [rsi], ' '
    je @F
    cmp byte ptr [rsi], 9
    je @F
    jmp parse_tokens
@@:
    inc rsi
    jmp skipsp
parse_tokens:
    ; token start in rsi
    cmp byte ptr [rsi], 0
    je done
    ; skip delimiters
    cmp byte ptr [rsi], ' '
    je @F
    cmp byte ptr [rsi], 9
    je @F
    cmp byte ptr [rsi], ','
    je @F
    jmp tok_collect
@@:
    inc rsi
    jmp parse_tokens

tok_collect:
    lea rdi, lineBuf      ; reuse lineBuf as token buffer
    ; collect until delim or EOL
tok_loop:
    mov al, [rsi]
    cmp al, ' '
    je tok_done
    cmp al, 9
    je tok_done
    cmp al, ','
    je tok_done
    test al, al
    jz tok_done
    mov [rdi], al
    inc rdi
    inc rsi
    jmp tok_loop

tok_done:
    mov byte ptr [rdi], 0
    ; add symbol if non-empty and not directive
    cmp byte ptr [lineBuf], 0
    je parse_tokens
    lea rcx, lineBuf
    call add_symbol
    jmp parse_tokens

check_proc:
    ; Look for " PROC" anywhere in line
    mov rcx, psz_local
    mov rdx, OFFSET PROC_kw
    call find_ci
    cmp rax, -1
    je done
    ; collect first token up to space/tab/:
    mov rsi, psz_local
    lea rdi, lineBuf
name_loop:
    mov al, [rsi]
    cmp al, ' '
    je have_name
    cmp al, 9
    je have_name
    cmp al, ':'
    je have_name
    test al, al
    jz done
    mov [rdi], al
    inc rdi
    inc rsi
    jmp name_loop
have_name:
    mov byte ptr [rdi], 0
    cmp byte ptr [lineBuf], 0
    je done
    lea rcx, lineBuf
    call add_symbol

done:
    ret
process_line endp

; read file and process lines
process_file proc uses rax rbx rcx rdx rsi rdi r12 r13, psz_local:QWORD
    ; open file for read
    sub rsp, 32
    mov rcx, psz_local
    mov edx, GENERIC_READ
    mov r8, FILE_SHARE_READ
    mov r9, 0
    mov qword ptr [rsp+20h], OPEN_EXISTING
    mov qword ptr [rsp+28h], FILE_ATTRIBUTE_NORMAL
    mov qword ptr [rsp+30h], 0
    mov qword ptr [rsp+38h], 0
    call CreateFileA
    add rsp, 32
    cmp rax, INVALID_HANDLE_VALUE
    je pf_done
    mov hIn, rax

    ; read loop
    mov rdi, 0                ; current index in buffer
    mov rsi, 0                ; current line length
    jmp read_chunk

read_chunk:
    sub rsp, 32
    mov rcx, hIn
    lea rdx, readBuf
    mov r8, 65536
    lea r9, bytesIO
    call ReadFile
    add rsp, 32
    test eax, eax
    jz close_file
    mov rbx, bytesIO
    mov rbx, [rbx]
    cmp rbx, 0
    je close_file

    ; Base pointers for indexed addressing (avoid ADDR32 relocations in x64)
    lea r12, readBuf
    lea r13, lineBuf

    ; process rbx bytes from readBuf
    xor rdi, rdi
process_bytes:
    cmp rdi, rbx
    jae read_chunk
    mov al, [r12+rdi]
    inc rdi
    cmp al, 13
    je newline
    cmp al, 10
    je newline
    ; accumulate
    mov [r13+rsi], al
    inc rsi
    cmp rsi, 4094
    jb process_bytes
    ; flush long line
newline:
    mov byte ptr [r13+rsi], 0
    cmp rsi, 0
    je reset_line
    lea rcx, lineBuf
    call process_line
reset_line:
    xor rsi, rsi
    jmp process_bytes

close_file:
    mov rcx, hIn
    call CloseHandle

pf_done:
    ret
process_file endp

; write output header to outPath from symbolsBuf
write_header proc uses rax rbx rcx rdx rsi rdi
    ; open output file
    sub rsp, 32
    mov rcx, OFFSET outPath
    mov edx, GENERIC_WRITE
    mov r8, 0
    mov r9, 0
    mov qword ptr [rsp+20h], CREATE_ALWAYS
    mov qword ptr [rsp+28h], FILE_ATTRIBUTE_NORMAL
    mov qword ptr [rsp+30h], 0
    mov qword ptr [rsp+38h], 0
    call CreateFileA
    add rsp, 32
    cmp rax, INVALID_HANDLE_VALUE
    je wh_done
    mov hOut, rax

    ; header text
    mov rcx, hOut
    mov rdx, OFFSET GEN_HEADER_1
    call writeZ
    mov rcx, hOut
    mov rdx, OFFSET GEN_HEADER_2
    call writeZ

    ; iterate symbolsBuf
    mov rsi, OFFSET symbolsBuf
next_sym:
    cmp byte ptr [rsi], 0
    je close_out
    ; write EXTERNDEF <sym>:PROC\r\n
    ; build line in lineBuf
    lea rdi, lineBuf
    ; EXTERNDEF 
    mov byte ptr [rdi+0], 'E'
    mov byte ptr [rdi+1], 'X'
    mov byte ptr [rdi+2], 'T'
    mov byte ptr [rdi+3], 'E'
    mov byte ptr [rdi+4], 'R'
    mov byte ptr [rdi+5], 'N'
    mov byte ptr [rdi+6], 'D'
    mov byte ptr [rdi+7], 'E'
    mov byte ptr [rdi+8], 'F'
    mov byte ptr [rdi+9], ' '
    lea rbx, [rdi+10]
    ; copy symbol
    xor rax, rax
copy_loop1:
    mov al, [rsi+rax]
    mov [rbx+rax], al
    test al, al
    jz @f
    inc rax
    jmp copy_loop1
@@:
    ; append :PROC\r\n
    mov byte ptr [rbx+rax], ':'
    mov byte ptr [rbx+rax+1], 'P'
    mov byte ptr [rbx+rax+2], 'R'
    mov byte ptr [rbx+rax+3], 'O'
    mov byte ptr [rbx+rax+4], 'C'
    mov byte ptr [rbx+rax+5], 13
    mov byte ptr [rbx+rax+6], 10
    mov byte ptr [rbx+rax+7], 0
    mov rcx, hOut
    lea rdx, lineBuf
    call writeZ

    ; PROTO line: <sym> PROTO\r\n
    lea rdi, lineBuf
    ; copy symbol
    xor rax, rax
copy_loop2:
    mov al, [rsi+rax]
    mov [rdi+rax], al
    test al, al
    jz @f
    inc rax
    jmp copy_loop2
@@:
    mov byte ptr [rdi+rax], ' '
    mov byte ptr [rdi+rax+1], 'P'
    mov byte ptr [rdi+rax+2], 'R'
    mov byte ptr [rdi+rax+3], 'O'
    mov byte ptr [rdi+rax+4], 'T'
    mov byte ptr [rdi+rax+5], 'O'
    mov byte ptr [rdi+rax+6], 13
    mov byte ptr [rdi+rax+7], 10
    mov byte ptr [rdi+rax+8], 0
    mov rcx, hOut
    lea rdx, lineBuf
    call writeZ

    ; move rsi to next symbol (skip until null then +1)
skip_loop:
    cmp byte ptr [rsi], 0
    je @f
    inc rsi
    jmp skip_loop
@@:
    inc rsi
    jmp next_sym

close_out:
    mov rcx, hOut
    call CloseHandle

wh_done:
    ret
write_header endp

; build search pattern into searchPattern = inDir + "\\*.asm"
build_pattern proc
    push rax
    push rcx
    push rdx
    lea rcx, inDir
    call strlenA
    lea rdx, inDir
    ; ensure trailing backslash
    cmp rax, 0
    je copy_suffix
    dec rax
    mov cl, byte ptr [rdx+rax]
    cmp cl, 5Ch
    je copy_suffix
    ; append backslash
    lea rcx, inDir
    lea rdx, backslash
    call strcatA
copy_suffix:
    lea rcx, searchPattern
    lea rdx, inDir
    call strcpyA
    lea rcx, searchPattern
    lea rdx, patternSuffix
    call strcatA
    pop rdx
    pop rcx
    pop rax
    ret
build_pattern endp

; Build file path = inDir + "\\" + findData.cFileName
build_filepath proc
    push rax
    push rbx
    push rcx
    push rdx
    ; copy inDir to filePath
    lea rcx, filePath
    lea rdx, inDir
    call strcpyA
    ; ensure backslash
    lea rcx, filePath
    call strlenA
    lea rdx, filePath
    cmp rax, 0
    je append_name
    dec rax
    mov cl, byte ptr [rdx+rax]
    cmp cl, 5Ch
    je append_name
    lea rcx, filePath
    lea rdx, backslash
    call strcatA
append_name:
    ; find cFileName offset in findData (WIN32_FIND_DATAA: name at offset 44h)
    lea rbx, findData
    add rbx, 44h
    lea rcx, filePath
    mov rdx, rbx
    call strcatA
    pop rdx
    pop rcx
    pop rbx
    pop rax
    ret
build_filepath endp

; Minimal command line parse: expects two args after program name
parse_args proc
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    sub rsp, 32
    call GetCommandLineA
    add rsp, 32
    mov rsi, rax
    ; Skip program path (handle quotes)
    mov al, [rsi]
    cmp al, '"'
    jne skip1
    inc rsi
quote_loop:
    mov al, [rsi]
    test al, al
    jz usage
    cmp al, '"'
    je @f
    inc rsi
    jmp quote_loop
@@:
    inc rsi
    jmp sp1
skip1:
skip_loop1:
    mov al, [rsi]
    test al, al
    jz usage
    cmp al, ' '
    je sp1
    inc rsi
    jmp skip_loop1
sp1:
    ; skip spaces
space_loop1:
    mov al, [rsi]
    test al, al
    jz usage
    cmp al, ' '
    jne arg1
    inc rsi
    jmp space_loop1
arg1:
    ; read arg1 to inDir until space
    mov rdi, OFFSET inDir
arg1_loop:
    mov al, [rsi]
    test al, al
    jz end_a1
    cmp al, ' '
    je end_a1
    mov [rdi], al
    inc rdi
    inc rsi
    jmp arg1_loop
end_a1:
    mov byte ptr [rdi], 0
    ; skip spaces to arg2
space_loop2:
    mov al, [rsi]
    test al, al
    jz usage
    cmp al, ' '
    jne arg2
    inc rsi
    jmp space_loop2
arg2:
    mov rdi, OFFSET outPath
arg2_loop:
    mov al, [rsi]
    test al, al
    jz end_a2
    cmp al, ' '
    je end_a2
    mov [rdi], al
    inc rdi
    inc rsi
    jmp arg2_loop
end_a2:
    mov byte ptr [rdi], 0
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    ret
usage:
    ; print usage and exit with code 1
    sub rsp, 32
    mov ecx, STD_OUTPUT_HANDLE
    call GetStdHandle
    add rsp, 32
    mov hStdOut, rax
    mov rcx, hStdOut
    mov rdx, OFFSET USAGE_TEXT
    call writeZ
    sub rsp, 32
    mov ecx, 1
    call ExitProcess
parse_args endp

main proc
    ; stdout handle
    sub rsp, 32
    mov ecx, STD_OUTPUT_HANDLE
    call GetStdHandle
    add rsp, 32
    mov hStdOut, rax

    ; parse args to inDir/outPath
    call parse_args

    ; build search pattern
    call build_pattern

    ; enumerate files
    sub rsp, 32
    lea rcx, searchPattern
    lea rdx, findData
    call FindFirstFileA
    add rsp, 32
    cmp rax, INVALID_HANDLE_VALUE
    je done
    mov hFind, rax

next_file:
    ; skip directories (FILE_ATTRIBUTE_DIRECTORY=10h at offset 0 in WIN32_FIND_DATAA)
    mov eax, dword ptr [findData]
    test eax, 10h
    jnz cont_next

    ; build filepath and process
    call build_filepath
    lea rcx, filePath
    call process_file

cont_next:
    sub rsp, 32
    mov rcx, hFind
    lea rdx, findData
    call FindNextFileA
    add rsp, 32
    test eax, eax
    jnz next_file

    ; close find handle
    mov rcx, hFind
    call FindClose

    ; write header
    call write_header

done:
    sub rsp, 32
    xor ecx, ecx
    call ExitProcess
main endp

end




