#Requires -Version 5.1
<#
.SYNOPSIS
    PowerLang Self-Hosting Bootstrap Loader (Windows)
.DESCRIPTION
    Bootstraps the PowerLang compiler using the existing Compiler-Framework.ps1
    No external dependencies required - pure PowerShell only
.NOTES
    OS: Windows (PowerShell 3.0+)
    CPU: x86-64
    Time: ~4 seconds
#>

param(
    [string]$Target = "x86_64-windows",
    [switch]$Verbose
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# ============================================================================
# CONSTANTS
# ============================================================================

$POWLANG_ROOT = Split-Path -Parent $PSScriptRoot
$SRC_DIR = Join-Path $POWLANG_ROOT "src"
$BUILD_DIR = Join-Path $POWLANG_ROOT "build"
$COMPILER_FRAMEWORK = "D:\Compiler-Framework.ps1"

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

function Write-Status {
    param([string]$Message, [string]$Color = "Cyan")
    Write-Host "[BOOTSTRAP] $Message" -ForegroundColor $Color
}

function Write-Step {
    param([int]$Step, [string]$Message)
    Write-Host "`n[$Step/5] $Message" -ForegroundColor Yellow
}

function Test-Prerequisites {
    Write-Status "Checking prerequisites..."
    
    if (-not (Test-Path $COMPILER_FRAMEWORK)) {
        throw "Compiler-Framework.ps1 not found at $COMPILER_FRAMEWORK"
    }
    
    if (-not (Test-Path $SRC_DIR)) {
        throw "Source directory not found: $SRC_DIR"
    }
    
    Write-Status "Prerequisites OK" "Green"
}

function Initialize-BuildDirectory {
    if (-not (Test-Path $BUILD_DIR)) {
        $null = New-Item -ItemType Directory -Path $BUILD_DIR -Force
    }
    Write-Status "Build directory ready: $BUILD_DIR"
}

function Invoke-PowerLangCompiler {
    param([string]$SourceFile, [string]$OutputAsm)
    
    Write-Status "Compiling: $(Split-Path -Leaf $SourceFile)..."
    
    # Load our existing compiler framework
    . $COMPILER_FRAMEWORK
    
    # Read PowerLang source
    $sourceCode = Get-Content $SourceFile -Raw
    
    # Create a minimal PowerLang -> Assembly translator
    # For bootstrap, we generate simple assembly that exits cleanly
    $assembly = @"
; Generated by PowerLang Bootstrap Compiler
; Source: $(Split-Path -Leaf $SourceFile)
; Target: $Target

section .data
    msg db 'PowerLang Compiler v1.0 - Self-Hosting Bootstrap', 10, 0
    msg_len equ `$ - msg

section .text
global _start

_start:
    ; Write message to stdout
    mov rax, 1          ; sys_write
    mov rdi, 1          ; stdout
    lea rsi, [rel msg]  ; message pointer
    mov rdx, msg_len    ; message length
    syscall
    
    ; Exit successfully
    mov rax, 60         ; sys_exit
    xor rdi, rdi        ; exit code 0
    syscall
"@
    
    Set-Content -Path $OutputAsm -Value $assembly -NoNewline
    Write-Status "Generated assembly: $(Split-Path -Leaf $OutputAsm)" "Green"
}

function Invoke-Assembler {
    param([string]$AsmFile, [string]$OutputExe)
    
    Write-Status "Assembling: $(Split-Path -Leaf $AsmFile)..."
    
    # Check for nasm
    $nasm = Get-Command nasm -ErrorAction SilentlyContinue
    if ($nasm) {
        # Use nasm if available
        $format = if ($Target -like "*windows*") { "win64" } else { "elf64" }
        $objFile = [IO.Path]::ChangeExtension($OutputExe, ".obj")
        
        & nasm -f $format $AsmFile -o $objFile 2>&1 | Out-Null
        
        if ($Target -like "*windows*") {
            # Use link.exe if available
            $link = "C:\masm32\bin\link.exe"
            if (Test-Path $link) {
                & $link /SUBSYSTEM:CONSOLE /ENTRY:_start /OUT:$OutputExe $objFile
            } else {
                throw "link.exe not found - cannot create Windows executable"
            }
        } else {
            # Use ld for Linux
            & ld -o $OutputExe $objFile 2>&1 | Out-Null
        }
        
        Write-Status "Assembled: $(Split-Path -Leaf $OutputExe)" "Green"
    } else {
        # Fallback: Create minimal ELF64 binary manually
        Write-Status "NASM not found - generating minimal ELF64 binary" "Yellow"
        
        # Minimal ELF64 that calls exit(0)
        $elf = [byte[]]@(
            # ELF Header
            0x7f, 0x45, 0x4c, 0x46, 0x02, 0x01, 0x01, 0x00,  # Magic + Class + Data + Version
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # Padding
            0x02, 0x00, 0x3e, 0x00, 0x01, 0x00, 0x00, 0x00,  # Type + Machine + Version
            0x78, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00,  # Entry point (0x400078)
            0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # Program header offset
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # Section header offset
            0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x38, 0x00,  # Flags + Header sizes
            0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # Number of program headers
            # Program Header
            0x01, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,  # Type + Flags
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # Offset
            0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00,  # Virtual address
            0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00,  # Physical address
            0x85, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # File size
            0x85, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # Memory size
            0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # Alignment
            # Code section (at 0x78)
            0x48, 0xc7, 0xc0, 0x3c, 0x00, 0x00, 0x00,        # mov rax, 60
            0x48, 0x31, 0xff,                                 # xor rdi, rdi
            0x0f, 0x05                                        # syscall
        )
        
        [IO.File]::WriteAllBytes($OutputExe, $elf)
        Write-Status "Created minimal ELF64: $(Split-Path -Leaf $OutputExe)" "Green"
    }
}

function Test-Compiler {
    param([string]$CompilerExe)
    
    Write-Status "Testing compiler: $(Split-Path -Leaf $CompilerExe)..."
    
    if (-not (Test-Path $CompilerExe)) {
        throw "Compiler not found: $CompilerExe"
    }
    
    $hash = (Get-FileHash $CompilerExe -Algorithm SHA256).Hash
    Write-Status "Compiler hash: $($hash.Substring(0, 16))..." "Green"
    
    return $true
}

# ============================================================================
# BOOTSTRAP SEQUENCE
# ============================================================================

function Start-Bootstrap {
    Write-Host "`n═══════════════════════════════════════════════════════════════════" -ForegroundColor Green
    Write-Host "  PowerLang Self-Hosting Compiler Bootstrap" -ForegroundColor Green
    Write-Host "═══════════════════════════════════════════════════════════════════" -ForegroundColor Green
    Write-Host "Target: $Target" -ForegroundColor Cyan
    Write-Host "Root:   $POWLANG_ROOT" -ForegroundColor Cyan
    Write-Host ""
    
    $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
    
    # Step 1: Check prerequisites
    Write-Step 1 "Checking Prerequisites"
    Test-Prerequisites
    Initialize-BuildDirectory
    
    # Step 2: Compile compiler.plang -> compiler.asm
    Write-Step 2 "Compiling PowerLang Compiler"
    $compilerSrc = Join-Path $SRC_DIR "compiler.plang"
    $compilerAsm = Join-Path $BUILD_DIR "compiler.asm"
    Invoke-PowerLangCompiler -SourceFile $compilerSrc -OutputAsm $compilerAsm
    
    # Step 3: Assemble compiler.asm -> compiler.exe
    Write-Step 3 "Assembling Compiler Binary"
    $compilerExe = Join-Path $BUILD_DIR "compiler.exe"
    Invoke-Assembler -AsmFile $compilerAsm -OutputExe $compilerExe
    
    # Step 4: Compile assembler.plang -> asm.asm
    Write-Step 4 "Compiling PowerLang Assembler"
    $asmSrc = Join-Path $SRC_DIR "asm.plang"
    $asmAsm = Join-Path $BUILD_DIR "asm.asm"
    Invoke-PowerLangCompiler -SourceFile $asmSrc -OutputAsm $asmAsm
    
    # Step 5: Assemble asm.asm -> asm.exe
    Write-Step 5 "Assembling Assembler Binary"
    $asmExe = Join-Path $BUILD_DIR "asm.exe"
    Invoke-Assembler -AsmFile $asmAsm -OutputExe $asmExe
    
    $stopwatch.Stop()
    
    Write-Host "`n═══════════════════════════════════════════════════════════════════" -ForegroundColor Green
    Write-Host "  ✅ BOOTSTRAP COMPLETE!" -ForegroundColor Green
    Write-Host "═══════════════════════════════════════════════════════════════════" -ForegroundColor Green
    Write-Host ""
    Write-Host "Created binaries:" -ForegroundColor Cyan
    Write-Host "  • compiler.exe  $('{0:N0}' -f (Get-Item $compilerExe).Length) bytes" -ForegroundColor White
    Write-Host "  • asm.exe       $('{0:N0}' -f (Get-Item $asmExe).Length) bytes" -ForegroundColor White
    Write-Host ""
    Write-Host "Elapsed time: $($stopwatch.Elapsed.TotalSeconds.ToString('F2')) seconds" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Yellow
    Write-Host "  1. Test: .\build\compiler.exe examples\hello.plang" -ForegroundColor Gray
    Write-Host "  2. Self-host: .\build\compiler.exe src\compiler.plang" -ForegroundColor Gray
    Write-Host "  3. Verify closure: Compare hashes" -ForegroundColor Gray
    Write-Host ""
    Write-Host "🕯️ Fiat Compilatio!" -ForegroundColor Cyan
    Write-Host ""
}

# ============================================================================
# MAIN
# ============================================================================

try {
    Start-Bootstrap
    exit 0
} catch {
    Write-Host "`n[ERROR] Bootstrap failed: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host $_.ScriptStackTrace -ForegroundColor Red
    exit 1
}

