# CMake generated Testfile for 
# Source directory: E:/RawrXD
# Build directory: E:/RawrXD/build_universal
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_Compression]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running compression smoke test...")
  set_tests_properties([=[SmokeTest_Compression]=] PROPERTIES  PASS_REGULAR_EXPRESSION "compression smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;7;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_Compression]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running compression smoke test...")
  set_tests_properties([=[SmokeTest_Compression]=] PROPERTIES  PASS_REGULAR_EXPRESSION "compression smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;7;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_Compression]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running compression smoke test...")
  set_tests_properties([=[SmokeTest_Compression]=] PROPERTIES  PASS_REGULAR_EXPRESSION "compression smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;7;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_Compression]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running compression smoke test...")
  set_tests_properties([=[SmokeTest_Compression]=] PROPERTIES  PASS_REGULAR_EXPRESSION "compression smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;7;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_Compression]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_FlashAttention]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running flash attention smoke test...")
  set_tests_properties([=[SmokeTest_FlashAttention]=] PROPERTIES  PASS_REGULAR_EXPRESSION "flash attention smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;18;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_FlashAttention]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running flash attention smoke test...")
  set_tests_properties([=[SmokeTest_FlashAttention]=] PROPERTIES  PASS_REGULAR_EXPRESSION "flash attention smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;18;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_FlashAttention]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running flash attention smoke test...")
  set_tests_properties([=[SmokeTest_FlashAttention]=] PROPERTIES  PASS_REGULAR_EXPRESSION "flash attention smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;18;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_FlashAttention]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running flash attention smoke test...")
  set_tests_properties([=[SmokeTest_FlashAttention]=] PROPERTIES  PASS_REGULAR_EXPRESSION "flash attention smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;18;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_FlashAttention]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_Checkpoints]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running checkpoint manager smoke test...")
  set_tests_properties([=[SmokeTest_Checkpoints]=] PROPERTIES  PASS_REGULAR_EXPRESSION "checkpoint manager smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;29;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_Checkpoints]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running checkpoint manager smoke test...")
  set_tests_properties([=[SmokeTest_Checkpoints]=] PROPERTIES  PASS_REGULAR_EXPRESSION "checkpoint manager smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;29;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_Checkpoints]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running checkpoint manager smoke test...")
  set_tests_properties([=[SmokeTest_Checkpoints]=] PROPERTIES  PASS_REGULAR_EXPRESSION "checkpoint manager smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;29;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_Checkpoints]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running checkpoint manager smoke test...")
  set_tests_properties([=[SmokeTest_Checkpoints]=] PROPERTIES  PASS_REGULAR_EXPRESSION "checkpoint manager smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;29;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_Checkpoints]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_CICD]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running CI/CD pipeline smoke test...")
  set_tests_properties([=[SmokeTest_CICD]=] PROPERTIES  PASS_REGULAR_EXPRESSION "CI/CD pipeline smoke test" TIMEOUT "15" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;40;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_CICD]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running CI/CD pipeline smoke test...")
  set_tests_properties([=[SmokeTest_CICD]=] PROPERTIES  PASS_REGULAR_EXPRESSION "CI/CD pipeline smoke test" TIMEOUT "15" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;40;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_CICD]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running CI/CD pipeline smoke test...")
  set_tests_properties([=[SmokeTest_CICD]=] PROPERTIES  PASS_REGULAR_EXPRESSION "CI/CD pipeline smoke test" TIMEOUT "15" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;40;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_CICD]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running CI/CD pipeline smoke test...")
  set_tests_properties([=[SmokeTest_CICD]=] PROPERTIES  PASS_REGULAR_EXPRESSION "CI/CD pipeline smoke test" TIMEOUT "15" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;40;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_CICD]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_Encryption]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running AES-GCM encryption smoke test...")
  set_tests_properties([=[SmokeTest_Encryption]=] PROPERTIES  PASS_REGULAR_EXPRESSION "AES-GCM encryption smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;51;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_Encryption]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running AES-GCM encryption smoke test...")
  set_tests_properties([=[SmokeTest_Encryption]=] PROPERTIES  PASS_REGULAR_EXPRESSION "AES-GCM encryption smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;51;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_Encryption]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running AES-GCM encryption smoke test...")
  set_tests_properties([=[SmokeTest_Encryption]=] PROPERTIES  PASS_REGULAR_EXPRESSION "AES-GCM encryption smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;51;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_Encryption]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running AES-GCM encryption smoke test...")
  set_tests_properties([=[SmokeTest_Encryption]=] PROPERTIES  PASS_REGULAR_EXPRESSION "AES-GCM encryption smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;51;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_Encryption]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_GGUFLoader]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running GGUF loader smoke test...")
  set_tests_properties([=[SmokeTest_GGUFLoader]=] PROPERTIES  PASS_REGULAR_EXPRESSION "GGUF loader smoke test" TIMEOUT "20" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;62;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_GGUFLoader]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running GGUF loader smoke test...")
  set_tests_properties([=[SmokeTest_GGUFLoader]=] PROPERTIES  PASS_REGULAR_EXPRESSION "GGUF loader smoke test" TIMEOUT "20" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;62;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_GGUFLoader]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running GGUF loader smoke test...")
  set_tests_properties([=[SmokeTest_GGUFLoader]=] PROPERTIES  PASS_REGULAR_EXPRESSION "GGUF loader smoke test" TIMEOUT "20" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;62;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_GGUFLoader]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running GGUF loader smoke test...")
  set_tests_properties([=[SmokeTest_GGUFLoader]=] PROPERTIES  PASS_REGULAR_EXPRESSION "GGUF loader smoke test" TIMEOUT "20" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;62;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_GGUFLoader]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_AgenticBridge]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running agentic copilot bridge smoke test...")
  set_tests_properties([=[SmokeTest_AgenticBridge]=] PROPERTIES  PASS_REGULAR_EXPRESSION "agentic copilot bridge smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;73;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_AgenticBridge]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running agentic copilot bridge smoke test...")
  set_tests_properties([=[SmokeTest_AgenticBridge]=] PROPERTIES  PASS_REGULAR_EXPRESSION "agentic copilot bridge smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;73;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_AgenticBridge]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running agentic copilot bridge smoke test...")
  set_tests_properties([=[SmokeTest_AgenticBridge]=] PROPERTIES  PASS_REGULAR_EXPRESSION "agentic copilot bridge smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;73;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_AgenticBridge]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running agentic copilot bridge smoke test...")
  set_tests_properties([=[SmokeTest_AgenticBridge]=] PROPERTIES  PASS_REGULAR_EXPRESSION "agentic copilot bridge smoke test" TIMEOUT "10" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/smoke_tests.cmake;73;add_test;E:/RawrXD/smoke_tests.cmake;0;;E:/RawrXD/CMakeLists.txt;1875;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_AgenticBridge]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[masm_solo_hello]=] "E:/RawrXD/build_universal/Debug/masm_solo_compiler.exe" "E:/RawrXD/tests/masm/hello.asm" "E:/RawrXD/build_universal/hello_solo.exe")
  set_tests_properties([=[masm_solo_hello]=] PROPERTIES  LABELS "masm;solo" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;208;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[masm_solo_hello]=] "E:/RawrXD/build_universal/Release/masm_solo_compiler.exe" "E:/RawrXD/tests/masm/hello.asm" "E:/RawrXD/build_universal/hello_solo.exe")
  set_tests_properties([=[masm_solo_hello]=] PROPERTIES  LABELS "masm;solo" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;208;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[masm_solo_hello]=] "E:/RawrXD/build_universal/MinSizeRel/masm_solo_compiler.exe" "E:/RawrXD/tests/masm/hello.asm" "E:/RawrXD/build_universal/hello_solo.exe")
  set_tests_properties([=[masm_solo_hello]=] PROPERTIES  LABELS "masm;solo" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;208;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[masm_solo_hello]=] "E:/RawrXD/build_universal/RelWithDebInfo/masm_solo_compiler.exe" "E:/RawrXD/tests/masm/hello.asm" "E:/RawrXD/build_universal/hello_solo.exe")
  set_tests_properties([=[masm_solo_hello]=] PROPERTIES  LABELS "masm;solo" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;208;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[masm_solo_hello]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[masm_solo_factorial]=] "E:/RawrXD/build_universal/Debug/masm_solo_compiler.exe" "E:/RawrXD/tests/masm/factorial.asm" "E:/RawrXD/build_universal/factorial_solo.exe")
  set_tests_properties([=[masm_solo_factorial]=] PROPERTIES  LABELS "masm;solo" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;212;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[masm_solo_factorial]=] "E:/RawrXD/build_universal/Release/masm_solo_compiler.exe" "E:/RawrXD/tests/masm/factorial.asm" "E:/RawrXD/build_universal/factorial_solo.exe")
  set_tests_properties([=[masm_solo_factorial]=] PROPERTIES  LABELS "masm;solo" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;212;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[masm_solo_factorial]=] "E:/RawrXD/build_universal/MinSizeRel/masm_solo_compiler.exe" "E:/RawrXD/tests/masm/factorial.asm" "E:/RawrXD/build_universal/factorial_solo.exe")
  set_tests_properties([=[masm_solo_factorial]=] PROPERTIES  LABELS "masm;solo" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;212;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[masm_solo_factorial]=] "E:/RawrXD/build_universal/RelWithDebInfo/masm_solo_compiler.exe" "E:/RawrXD/tests/masm/factorial.asm" "E:/RawrXD/build_universal/factorial_solo.exe")
  set_tests_properties([=[masm_solo_factorial]=] PROPERTIES  LABELS "masm;solo" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;212;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[masm_solo_factorial]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[masm_cli_hello]=] "E:/RawrXD/build_universal/Debug/masm_cli_compiler.exe" "--verbose" "E:/RawrXD/tests/masm/hello.asm" "-o" "E:/RawrXD/build_universal/hello_cli.exe")
  set_tests_properties([=[masm_cli_hello]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;222;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[masm_cli_hello]=] "E:/RawrXD/build_universal/Release/masm_cli_compiler.exe" "--verbose" "E:/RawrXD/tests/masm/hello.asm" "-o" "E:/RawrXD/build_universal/hello_cli.exe")
  set_tests_properties([=[masm_cli_hello]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;222;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[masm_cli_hello]=] "E:/RawrXD/build_universal/MinSizeRel/masm_cli_compiler.exe" "--verbose" "E:/RawrXD/tests/masm/hello.asm" "-o" "E:/RawrXD/build_universal/hello_cli.exe")
  set_tests_properties([=[masm_cli_hello]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;222;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[masm_cli_hello]=] "E:/RawrXD/build_universal/RelWithDebInfo/masm_cli_compiler.exe" "--verbose" "E:/RawrXD/tests/masm/hello.asm" "-o" "E:/RawrXD/build_universal/hello_cli.exe")
  set_tests_properties([=[masm_cli_hello]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;222;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[masm_cli_hello]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[masm_cli_factorial]=] "E:/RawrXD/build_universal/Debug/masm_cli_compiler.exe" "-O2" "E:/RawrXD/tests/masm/factorial.asm" "-o" "E:/RawrXD/build_universal/factorial_cli.exe")
  set_tests_properties([=[masm_cli_factorial]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;226;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[masm_cli_factorial]=] "E:/RawrXD/build_universal/Release/masm_cli_compiler.exe" "-O2" "E:/RawrXD/tests/masm/factorial.asm" "-o" "E:/RawrXD/build_universal/factorial_cli.exe")
  set_tests_properties([=[masm_cli_factorial]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;226;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[masm_cli_factorial]=] "E:/RawrXD/build_universal/MinSizeRel/masm_cli_compiler.exe" "-O2" "E:/RawrXD/tests/masm/factorial.asm" "-o" "E:/RawrXD/build_universal/factorial_cli.exe")
  set_tests_properties([=[masm_cli_factorial]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;226;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[masm_cli_factorial]=] "E:/RawrXD/build_universal/RelWithDebInfo/masm_cli_compiler.exe" "-O2" "E:/RawrXD/tests/masm/factorial.asm" "-o" "E:/RawrXD/build_universal/factorial_cli.exe")
  set_tests_properties([=[masm_cli_factorial]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;226;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[masm_cli_factorial]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[masm_cli_multifile]=] "E:/RawrXD/build_universal/Debug/masm_cli_compiler.exe" "--verbose" "-g" "E:/RawrXD/tests/masm/hello.asm" "E:/RawrXD/tests/masm/factorial.asm" "-o" "E:/RawrXD/build_universal/combined.exe")
  set_tests_properties([=[masm_cli_multifile]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;230;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[masm_cli_multifile]=] "E:/RawrXD/build_universal/Release/masm_cli_compiler.exe" "--verbose" "-g" "E:/RawrXD/tests/masm/hello.asm" "E:/RawrXD/tests/masm/factorial.asm" "-o" "E:/RawrXD/build_universal/combined.exe")
  set_tests_properties([=[masm_cli_multifile]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;230;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[masm_cli_multifile]=] "E:/RawrXD/build_universal/MinSizeRel/masm_cli_compiler.exe" "--verbose" "-g" "E:/RawrXD/tests/masm/hello.asm" "E:/RawrXD/tests/masm/factorial.asm" "-o" "E:/RawrXD/build_universal/combined.exe")
  set_tests_properties([=[masm_cli_multifile]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;230;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[masm_cli_multifile]=] "E:/RawrXD/build_universal/RelWithDebInfo/masm_cli_compiler.exe" "--verbose" "-g" "E:/RawrXD/tests/masm/hello.asm" "E:/RawrXD/tests/masm/factorial.asm" "-o" "E:/RawrXD/build_universal/combined.exe")
  set_tests_properties([=[masm_cli_multifile]=] PROPERTIES  LABELS "masm;cli" TIMEOUT "30" WORKING_DIRECTORY "E:/RawrXD/build_universal" _BACKTRACE_TRIPLES "E:/RawrXD/cmake/MASMCompiler.cmake;230;add_test;E:/RawrXD/cmake/MASMCompiler.cmake;0;;E:/RawrXD/CMakeLists.txt;2244;include;E:/RawrXD/CMakeLists.txt;0;")
else()
  add_test([=[masm_cli_multifile]=] NOT_AVAILABLE)
endif()
subdirs("_deps/zlib-build")
subdirs("3rdparty/ggml")
subdirs("src/orchestration")
subdirs("src/git")
subdirs("src/terminal")
subdirs("src/paint")
subdirs("src/masm")
