[Launch]
ProgramExecutable=Spotify\Spotify.exe
WorkingDirectory=%PAL:AppDir%\Spotify
SingleAppInstance=true
WaitForProgram=true
DirectoryMoveOK=yes
SupportsUNC=yes

[Activate]
Registry=true

[RegistryKeys]
Spotify="HKCU\Software\Spotify"
-=HKCU\Software\Classes\spotify
;-=HKCU\Software\Microsoft\Windows\CurrentVersion\Run
-=HKCU\Software\Microsoft\Direct3D\MostRecentApplication
-=HKCU\Software\Microsoft\Internet Explorer\Low Rights
-=HKCU\Software\Chromium\BLBeacon
-=HKLM\SOFTWARE\Classes\spotify

[RegistryCleanupIfEmpty]
1=HKCU\Software\Spotify
2=HKCU\Software\Chromium

[DirectoriesMove]
LocalData\Spotify=%LOCALAPPDATA%\Spotify
AppData\Spotify=%APPDATA%\Spotify

[DirectoriesCleanupForce]
1=%PAL:DataDir%\LocalData\Spotify\Data