#pragma once
#include <string>
#include <filesystem>
#include <vector>

namespace RawrXD {

struct ReactServerConfig {
    std::string name;
    std::string description = "Generated by RawrXD AI";
    bool include_typescript = false;
    bool include_tailwind = false;
    bool include_auth = false;
    bool include_database = false;
    std::string database_type = "sqlite"; // sqlite, mongodb, postgresql
    std::string auth_type = "jwt"; // jwt, session
    std::string author = "RawrXD AI";
    std::string port = "3000";
    bool include_docker = false;
    bool include_tests = false;
    std::vector<std::string> additional_dependencies;
};

class ReactServerGenerator {
public:
    static bool Generate(const std::string& project_dir, const ReactServerConfig& config);
    static bool GeneratePackageJson(const std::filesystem::path& dir, const ReactServerConfig& config);
    static bool GenerateServerJs(const std::filesystem::path& dir, const ReactServerConfig& config);
    static bool GenerateIndexHtml(const std::filesystem::path& dir, const ReactServerConfig& config);
    static bool GenerateAppJs(const std::filesystem::path& dir, const ReactServerConfig& config);
    static bool GenerateEnvFile(const std::filesystem::path& dir, const ReactServerConfig& config);
    static bool GenerateReadme(const std::filesystem::path& dir, const ReactServerConfig& config);
    static bool GenerateGitignore(const std::filesystem::path& dir, const ReactServerConfig& config);
    static bool GenerateDockerfile(const std::filesystem::path& dir, const ReactServerConfig& config);
    static bool GenerateTestFiles(const std::filesystem::path& dir, const ReactServerConfig& config);
    
private:
    static std::string GetPackageJsonContent(const ReactServerConfig& config);
    static std::string GetServerJsContent(const ReactServerConfig& config);
    static std::string GetIndexHtmlContent(const ReactServerConfig& config);
    static std::string GetAppJsContent(const ReactServerConfig& config);
    static std::string GetEnvContent(const ReactServerConfig& config);
    static std::string GetReadmeContent(const ReactServerConfig& config);
    static std::string GetGitignoreContent(const ReactServerConfig& config);
    static std::string GetDockerfileContent(const ReactServerConfig& config);
    static std::string GetTestContent(const ReactServerConfig& config);
}; // class ReactServerGenerator
} // namespace RawrXD
