// ============================================================================
// js_extension_host.hpp — QuickJS-Based VSIX Extension Host
// ============================================================================
#include <queue>
//
// Phase 37: JavaScript Extension Runtime — VSIX Compatibility Beyond Native
//
// Purpose:
//   Embeds a lightweight JavaScript engine (QuickJS) that executes unmodified
//   VS Code extensions (.vsix). Binds the full vscode.* API surface to the
//   existing C++ VSCodeExtensionAPI layer. Includes a self-creating polyfill
//   engine that hotpatches missing Node.js APIs, Electron menus, and remote
//   system calls at runtime.
//
// Architecture:
//   ┌──────────────────────────────────────────────────┐
//   │            VSIX (.zip) Extension                 │
//   │  extension/package.json                          │
//   │  extension/out/extension.js                      │
//   │  extension/node_modules/ (optional)              │
//   └────────────────┬─────────────────────────────────┘
//                    │ Extract & Parse
//                    ▼
//   ┌──────────────────────────────────────────────────┐
//   │           JSExtensionHost                        │
//   │  ┌──────────────┐  ┌──────────────────────────┐  │
//   │  │   QuickJS     │  │  PolyfillEngine          │  │
//   │  │   Runtime     │  │  (Auto-shim generator)   │  │
//   │  │              │  │                          │  │
//   │  │  vscode.*    │◄─┤  require() interceptor   │  │
//   │  │  bindings    │  │  Node API shims          │  │
//   │  │              │  │  Electron menu stubs     │  │
//   │  │  Event loop  │  │  Remote system proxies   │  │
//   │  └──────┬───────┘  └──────────────────────────┘  │
//   │         │                                        │
//   │         ▼ C++ function calls                     │
//   │  ┌──────────────────────────────────────────┐    │
//   │  │  VSCodeExtensionAPI (existing C++ layer) │    │
//   │  │  Commands, Window, Workspace, Languages  │    │
//   │  │  Debug, Tasks, SCM, Env, Extensions      │    │
//   │  └──────────────────────────────────────────┘    │
//   └──────────────────────────────────────────────────┘
//
// Design Principles:
//   - PatchResult-style structured results (no exceptions)
//   - Function pointer callbacks for JS→C++ bridge
//   - QuickJS runs in its own thread with message queue
//   - Polyfill engine uses hotpatch layer for runtime shim injection
//   - No circular includes (depends on vscode_extension_api.h only)
//   - Compatible with existing VSIX loader + extension manifest parser
//
// Rule: NO SOURCE FILE IS TO BE SIMPLIFIED
// ============================================================================

#pragma once

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

#include <cstdint>
#include <cstddef>
#include <cstring>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <mutex>
#include <atomic>
#include <functional>
#include <memory>
/* Qt removed */

// Forward declarations
struct VSCodeExtensionManifest;
struct VSCodeExtensionContext;
struct VSCodeAPIResult;
#include "model_memory_hotpatch.hpp"  // PatchResult full definition

// ============================================================================
// Polyfill Descriptor — Describes a runtime shim for a missing API
// ============================================================================
struct PolyfillDescriptor {
    enum class Category : uint8_t {
        NodeBuiltin     = 0,    // fs, path, os, process, etc.
        NodeModule      = 1,    // Popular npm modules (minimal-compat shimmed)
        ElectronAPI     = 2,    // Electron menu, dialog, shell, etc.
        RemoteSystem    = 3,    // vscode-remote, SSH, WSL, Docker
        BrowserAPI      = 4,    // DOM stubs for webview extensions
        Custom          = 5,    // User-defined or auto-generated
    };

    enum class Strategy : uint8_t {
        FullShim        = 0,    // Complete JavaScript implementation
        PartialShim     = 1,    // Subset of methods implemented
        NoOpStub        = 2,    // Methods exist but return safe defaults
        ProxyToNative   = 3,    // Redirect to C++ native implementation
        HotpatchInject  = 4,    // Generated at first-use via hotpatch engine
        ErrorWithHelp   = 5,    // Throw descriptive error with migration guide
    };

    char            moduleName[128];
    Category        category;
    Strategy        strategy;
    uint8_t         compatibilityScore; // 0-100: how complete the shim is
    uint8_t         reserved;
    const char*     jsSource;           // JavaScript source for the polyfill
    size_t          jsSourceLen;
    bool            isGenerated;        // True if auto-generated by polyfill engine
    uint64_t        hitCount;           // Number of times require()'d
    uint64_t        lastUsedTimestamp;
};

// ============================================================================
// JSMessage — Message queue entry for cross-thread communication
// ============================================================================
struct JSMessage {
    enum class Type : uint8_t {
        ExecuteScript       = 0,
        ActivateExtension   = 1,
        DeactivateExtension = 2,
        FireEvent           = 3,
        CallCallback        = 4,
        DisposeResource     = 5,
        Shutdown            = 6,
        TimerFire           = 7,
        PromiseResolve      = 8,
        RequireModule       = 9,
    };

    Type            type;
    uint64_t        requestId;
    std::string     extensionId;
    std::string     data;           // JSON or script content
    void*           context;        // Optional native context
    void            (*completionCallback)(bool success, const char* result, void* ctx);
    void*           completionCtx;
};

// ============================================================================
// JSExtensionState — Per-extension runtime state
// ============================================================================
struct JSExtensionState {
    std::string     extensionId;
    std::string     entryPoint;     // Path to main JS file
    std::string     extensionPath;  // Root directory of extracted extension
    bool            activated;
    bool            hasDeactivate;
    uint64_t        activateTime;
    uint64_t        apiCallCount;

    // QuickJS context handle (opaque, managed by host)
    void*           jsContext;      // JSContext*
    void*           jsModule;       // JSModuleDef*

    // Subscriptions for cleanup
    std::vector<uint64_t>   disposableIds;
    std::vector<std::string> registeredCommands;
    std::vector<std::string> registeredProviders;

    // Polyfills consumed by this extension
    std::vector<std::string> requiredPolyfills;
};

// ============================================================================
// PolyfillEngine — Self-Creating Shim/Polyfill Generator
// ============================================================================
//
// When an extension calls require('fs'), require('path'), require('electron'),
// or any other module not available in QuickJS, the PolyfillEngine:
//   1. Checks its registry for a pre-built shim
//   2. If not found, auto-generates a minimal shim based on the module name
//   3. Injects the shim into the QuickJS module system
//   4. Records the shim for future use (learning/caching)
//   5. Optionally routes calls to C++ native implementations via hotpatch
//
class PolyfillEngine {
public:
    static PolyfillEngine& instance();

    // Initialize the polyfill registry with built-in shims
    PatchResult initialize();
    PatchResult shutdown();

    // ---- Polyfill Registry ----

    // Register a pre-built polyfill
    PatchResult registerPolyfill(const char* moduleName,
                                  PolyfillDescriptor::Category category,
                                  PolyfillDescriptor::Strategy strategy,
                                  const char* jsSource,
                                  uint8_t compatScore);

    // Look up a polyfill by module name
    const PolyfillDescriptor* getPolyfill(const char* moduleName) const;

    // ---- Auto-Generation ----

    // Attempt to auto-generate a polyfill for an unknown module.
    // Returns true if a shim was generated and registered.
    bool autoGeneratePolyfill(const char* moduleName,
                               const char* requiredByExtension);

    // Generate a stub module that exports safe defaults for all accessed properties
    std::string generateStubModule(const char* moduleName,
                                     const std::vector<std::string>& accessedProperties);

    // ---- Hotpatch Integration ----

    // When a polyfill needs native backing (e.g., fs.readFile → Win32 ReadFile),
    // create a hotpatch bridge that routes JS calls to C++ functions
    PatchResult createNativeBridge(const char* moduleName,
                                    const char* functionName,
                                    void* nativeFunction);

    // ---- Analysis ----

    // Scan a JS source file for require() calls and return list of module names
    std::vector<std::string> analyzeRequires(const char* jsSource, size_t sourceLen);

    // Get all registered polyfills
    void getAllPolyfills(PolyfillDescriptor* outDescs, size_t maxDescs, size_t* outCount) const;

    // Get statistics
    struct Stats {
        uint64_t totalPolyfills;
        uint64_t generatedPolyfills;
        uint64_t nativeBridges;
        uint64_t requireHits;
        uint64_t requireMisses;
        uint64_t hotpatchInjections;
    };
    Stats getStats() const;

private:
    PolyfillEngine();
    ~PolyfillEngine();
    PolyfillEngine(const PolyfillEngine&) = delete;
    PolyfillEngine& operator=(const PolyfillEngine&) = delete;

    // Built-in polyfill source generators
    std::string generateFsPolyfill();
    std::string generatePathPolyfill();
    std::string generateOsPolyfill();
    std::string generateProcessPolyfill();
    std::string generateChildProcessPolyfill();
    std::string generateCryptoPolyfill();
    std::string generateHttpPolyfill();
    std::string generateEventsPolyfill();
    std::string generateStreamPolyfill();
    std::string generateBufferPolyfill();
    std::string generateUtilPolyfill();
    std::string generateUrlPolyfill();
    std::string generateQuerystringPolyfill();
    std::string generateElectronPolyfill();
    std::string generateRemotePolyfill();

    // Registry
    std::unordered_map<std::string, PolyfillDescriptor>     m_registry;
    std::unordered_map<std::string, std::string>            m_sourceCache;  // module → JS source
    mutable std::mutex                                      m_mutex;

    // Native bridges (module.function → C++ function pointer)
    struct NativeBridge {
        std::string     moduleName;
        std::string     functionName;
        void*           nativeFunction;
    };
    std::vector<NativeBridge>       m_bridges;

    // Stats
    mutable Stats   m_stats;
    bool            m_initialized;
};

// ============================================================================
// JSExtensionHost — QuickJS-Based VSIX Extension Runtime
// ============================================================================
class JSExtensionHost {
public:
    static JSExtensionHost& instance();

    // ---- Lifecycle ----
    PatchResult initialize();
    PatchResult shutdown();
    bool isInitialized() const;

    // ---- VSIX Loading ----

    // Extract a VSIX file and prepare it for execution
    PatchResult loadVSIX(const char* vsixPath, const char* installDir);

    // Load an already-extracted extension from its directory
    PatchResult loadExtensionFromDir(const char* extensionDir);

    // ---- Extension Lifecycle ----
    PatchResult activateExtension(const char* extensionId);
    PatchResult deactivateExtension(const char* extensionId);
    PatchResult unloadExtension(const char* extensionId);

    // Check if an extension is a JS extension (vs native DLL)
    bool isJSExtension(const VSCodeExtensionManifest* manifest) const;

    // ---- Event Dispatch ----

    // Fire a VS Code event into all active JS extensions
    PatchResult fireEvent(const char* eventName, const char* dataJson);

    // ---- Module Resolution ----

    // Register a custom module resolver for a specific module name
    PatchResult registerModuleResolver(const char* moduleName,
                                        const char* jsSource);

    // ---- Execution ----

    // Execute arbitrary JS in the context of an extension
    PatchResult executeScript(const char* extensionId,
                               const char* script,
                               char* outResult, size_t maxResultLen);

    // ---- Timer Management ----
    // JS extensions use setTimeout/setInterval — these are bridged here
    uint64_t createTimer(uint64_t delayMs, bool repeat, void* jsCallback);
    void cancelTimer(uint64_t timerId);

    // ---- Statistics ----
    struct Stats {
        uint64_t    jsExtensionsLoaded;
        uint64_t    jsExtensionsActive;
        uint64_t    totalJSApiCalls;
        uint64_t    totalScriptExecutions;
        uint64_t    polyfillsUsed;
        uint64_t    requireCalls;
        uint64_t    timersCreated;
        uint64_t    eventsDispatched;
        double      avgActivationTimeMs;
    };
    Stats getStats() const;

    // ---- Extension List ----
    void getLoadedExtensions(JSExtensionState* outStates, size_t maxStates,
                              size_t* outCount) const;

    // ---- VSIX Signature Verification ----
    // Verify the integrity and signature of a VSIX package before loading
    struct VSIXVerificationResult {
        bool        isValid;
        bool        isSigned;
        bool        signatureVerified;
        char        publisher[128];
        char        errorDetail[256];
    };
    VSIXVerificationResult verifyVSIX(const char* vsixPath) const;

private:
    JSExtensionHost();
    ~JSExtensionHost();
    JSExtensionHost(const JSExtensionHost&) = delete;
    JSExtensionHost& operator=(const JSExtensionHost&) = delete;

    // ---- QuickJS Runtime ----
    void*   m_jsRuntime;    // JSRuntime*
    void*   m_jsContext;    // JSContext* (main context for shared modules)

    // ---- vscode.* API Bindings ----
    // These functions register C functions into QuickJS that call the existing
    // C++ VSCodeExtensionAPI layer
    void bindVSCodeCommands(void* ctx);
    void bindVSCodeWindow(void* ctx);
    void bindVSCodeWorkspace(void* ctx);
    void bindVSCodeLanguages(void* ctx);
    void bindVSCodeDebug(void* ctx);
    void bindVSCodeTasks(void* ctx);
    void bindVSCodeEnv(void* ctx);
    void bindVSCodeExtensions(void* ctx);

    // Master binding: creates the 'vscode' global object with all namespaces
    void bindVSCodeAPI(void* ctx);

    // ---- require() Hook ----
    // Custom module loader that intercepts require() calls
    // 1. Check if module is a built-in polyfill
    // 2. Check if module exists in extension's node_modules
    // 3. Check if polyfill engine can auto-generate
    // 4. Return error with helpful message
    static void* moduleLoader(void* ctx, const char* moduleName, void* hostPtr);

    // ---- VSIX Extraction ----
    PatchResult extractZip(const char* zipPath, const char* destDir);
    PatchResult parseManifest(const char* extensionDir,
                               VSCodeExtensionManifest* outManifest);

    // ---- Extension Worker Thread ----
    static DWORD WINAPI extensionHostThread(LPVOID param);
    void processMessageQueue();

    // ---- Message Queue ----
    std::queue<JSMessage>   m_messageQueue;
    std::mutex              m_queueMutex;
    HANDLE                  m_queueEvent;   // Signaled when messages are available

    // ---- Extension Registry ----
    std::unordered_map<std::string, std::unique_ptr<JSExtensionState>>  m_extensions;
    mutable std::mutex                                                    m_extensionsMutex;

    // ---- Timer Registry ----
    struct TimerEntry {
        uint64_t    id;
        uint64_t    fireTime;   // GetTickCount64() target
        uint64_t    intervalMs; // 0 = one-shot
        bool        repeat;
        bool        cancelled;
        void*       jsCallback;
    };
    std::vector<TimerEntry>     m_timers;
    std::mutex                  m_timerMutex;
    uint64_t                    m_nextTimerId;

    // ---- State ----
    bool                m_initialized;
    HANDLE              m_hostThread;
    std::atomic<bool>   m_running;

    // ---- Statistics ----
    mutable Stats       m_stats;
};

