# CMake generated Testfile for 
# Source directory: D:/rawrxd/tests
# Build directory: D:/rawrxd/build_license/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ai_completions]=] "D:/rawrxd/build_license/tests/test_ai_completions.exe")
set_tests_properties([=[test_ai_completions]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;91;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_llm_connectivity]=] "D:/rawrxd/build_license/tests/test_llm_connectivity.exe")
set_tests_properties([=[test_llm_connectivity]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;110;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_semantic_diff_analyzer]=] "D:/rawrxd/build_license/tests/test_semantic_diff_analyzer.exe")
set_tests_properties([=[test_semantic_diff_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;146;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_ai_merge_resolver]=] "D:/rawrxd/build_license/tests/test_ai_merge_resolver.exe")
set_tests_properties([=[test_ai_merge_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;158;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_sandboxed_terminal]=] "D:/rawrxd/build_license/tests/test_sandboxed_terminal.exe")
set_tests_properties([=[test_sandboxed_terminal]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;167;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_agentic_file_operations]=] "D:/rawrxd/build_license/tests/test_agentic_file_operations.exe")
set_tests_properties([=[test_agentic_file_operations]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;176;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[model_registry_test]=] "D:/rawrxd/build_license/tests/model_registry_test.exe")
set_tests_properties([=[model_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;213;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[license_validation_suite]=] "D:/rawrxd/build_license/tests/license_validation_suite.exe")
set_tests_properties([=[license_validation_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;249;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_production_regression]=] "D:/rawrxd/build_license/tests/test_production_regression.exe")
set_tests_properties([=[test_production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;277;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_instructions_provider]=] "D:/rawrxd/build_license/tests/test_instructions_provider.exe")
set_tests_properties([=[test_instructions_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;298;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[license_gate_validator]=] "D:/rawrxd/build_license/tools/license_gate_validator.exe")
set_tests_properties([=[license_gate_validator]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;326;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[generate_license_keys]=] "D:/rawrxd/build_license/tools/license_key_generator.exe" "D:/rawrxd/build_license/tools")
set_tests_properties([=[generate_license_keys]=] PROPERTIES  FIXTURES_SETUP "license_keys" WORKING_DIRECTORY "D:/rawrxd/build_license" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;327;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[license_gate_validator_with_keys]=] "D:/rawrxd/build_license/tools/license_gate_validator.exe" "D:/rawrxd/build_license/tools")
set_tests_properties([=[license_gate_validator_with_keys]=] PROPERTIES  FIXTURES_REQUIRED "license_keys" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;330;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[cuda_test]=] "D:/rawrxd/build_license/tests/cuda_test.exe")
set_tests_properties([=[cuda_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;379;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[grammar_test]=] "D:/rawrxd/build_license/tests/grammar_test.exe")
set_tests_properties([=[grammar_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;396;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[lora_test]=] "D:/rawrxd/build_license/tests/lora_test.exe")
set_tests_properties([=[lora_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;413;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[cache_test]=] "D:/rawrxd/build_license/tests/cache_test.exe")
set_tests_properties([=[cache_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;436;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[airgap_test]=] "D:/rawrxd/build_license/tests/airgap_test.exe")
set_tests_properties([=[airgap_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;457;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[hsm_test]=] "D:/rawrxd/build_license/tests/hsm_test.exe")
set_tests_properties([=[hsm_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;480;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[fips_test]=] "D:/rawrxd/build_license/tests/fips_test.exe")
set_tests_properties([=[fips_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;503;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[policy_test]=] "D:/rawrxd/build_license/tests/policy_test.exe")
set_tests_properties([=[policy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;520;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[keymgmt_test]=] "D:/rawrxd/build_license/tests/keymgmt_test.exe")
set_tests_properties([=[keymgmt_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;537;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[classnet_test]=] "D:/rawrxd/build_license/tests/classnet_test.exe")
set_tests_properties([=[classnet_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;554;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[auditlog_test]=] "D:/rawrxd/build_license/tests/auditlog_test.exe")
set_tests_properties([=[auditlog_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;571;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[k8s_test]=] "D:/rawrxd/build_license/tests/k8s_test.exe")
set_tests_properties([=[k8s_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;588;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
