// ============================================================================
// RawrXD_Telemetry_MASM_Bridge.h — C++ ↔ MASM Telemetry Integration
// ============================================================================
//
// Provides extern "C" declarations for all symbols exported by:
//   - RawrXD_Telemetry_Kernel.asm   (UTC counters, ring buffer, log I/O)
//   - RawrXD_Prometheus_Exporter.asm (Prometheus text-format generation)
//
// Usage from C++:
//   #include "telemetry/RawrXD_Telemetry_MASM_Bridge.h"
//
//   // Increment the inference counter (single `lock xadd` instruction)
//   UTC_IncrementCounter(&g_Counter_Inference);
//
//   // Log an event to the wait-free ring buffer
//   UTC_LogEvent("Model loaded: GGUF Q4_K_M 7B");
//
//   // Export Prometheus payload
//   char buf[65536];
//   size_t len = ExportPrometheus(buf);
//   // buf now contains valid Prometheus text exposition format
//
// Architecture:
//   ┌─────────────────────────────────────────────────────────┐
//   │  C++ Code (BoundedAgentLoop, InferenceEngine, etc.)     │
//   │                                                         │
//   │  UTC_IncrementCounter(&g_Counter_Inference);  ──────┐   │
//   │  UTC_LogEvent("step complete");               ──┐   │   │
//   │  ExportPrometheus(buffer);                    ┐ │   │   │
//   └───────────────────────────────────────────────┼─┼───┼───┘
//                          extern "C"               │ │   │
//   ┌───────────────────────────────────────────────┼─┼───┼───┐
//   │  RawrXD_Telemetry_Kernel.asm                  │ │   │   │
//   │    g_Counter_Inference  ◄──────────────────────┼─┼───┘   │
//   │    g_EventBuffer[8192 × 256]  ◄───────────────┼─┘       │
//   │    g_hLogFile (direct Win32)                  │         │
//   ├───────────────────────────────────────────────┤         │
//   │  RawrXD_Prometheus_Exporter.asm               │         │
//   │    ExportPrometheus(buf)  ◄────────────────────┘         │
//   │    Internal_U64ToAscii (no sprintf)                     │
//   └─────────────────────────────────────────────────────────┘
//
// Pattern: PatchResult-style (no exceptions), extern "C" linkage.
// Rule:    NO SOURCE FILE IS TO BE SIMPLIFIED.
// ============================================================================

#pragma once

#include <cstdint>
#include <cstddef>

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// Telemetry Kernel — Atomic Counters (.data segment globals)
// ============================================================================
// Each counter is 64-byte aligned in the ASM .data segment to prevent
// false sharing across CPU cache lines. Access via lock xadd / lock inc.
// ============================================================================

/// Sentinel: start of metric table (value: 0xDEADBEEFCAFEBABE)
extern uint64_t g_MetricTableStart;

/// Total tokens generated by ASM inference kernels
extern uint64_t g_Counter_Inference;

/// Hardware SCSI timeout / failure count
extern uint64_t g_Counter_ScsiFails;

/// Total agentic loop steps executed
extern uint64_t g_Counter_AgentLoop;

/// Byte-level GGUF hotpatches applied
extern uint64_t g_Counter_BytePatches;

/// Memory-layer hotpatches applied (via VirtualProtect)
extern uint64_t g_Counter_MemPatches;

/// Server-layer request/response patches applied
extern uint64_t g_Counter_ServerPatches;

/// Ring buffer flush-to-disk operations
extern uint64_t g_Counter_FlushOps;

/// Total errors observed across all subsystems
extern uint64_t g_Counter_Errors;

/// Sentinel: end of metric table (value: 0xBADCAFEDEADFACE)
extern uint64_t g_MetricTableEnd;

// ============================================================================
// Telemetry Kernel — Lifecycle
// ============================================================================

/// Initialize telemetry subsystem: opens log file, resets counters.
/// @param logPath  Path to log file (null-terminated), or NULL for default
///                 ("rawrxd_kernel.log")
/// @return 0 on success, Win32 error code on failure
uint64_t UTC_InitTelemetry(const char* logPath);

/// Shut down telemetry: flush remaining events, close file handle.
/// @return 0 on success
uint64_t UTC_ShutdownTelemetry(void);

// ============================================================================
// Telemetry Kernel — Atomic Counter Operations
// ============================================================================

/// Thread-safe atomic increment via `lock xadd`.
/// Single cache-lock cycle — practically invisible to the profiler.
/// @param counterAddr  Pointer to a g_Counter_* global
/// @return New value after increment
uint64_t UTC_IncrementCounter(volatile uint64_t* counterAddr);

/// Thread-safe atomic decrement via `lock xadd`.
/// @param counterAddr  Pointer to a g_Counter_* global
/// @return New value after decrement
uint64_t UTC_DecrementCounter(volatile uint64_t* counterAddr);

/// Non-destructive atomic read with acquire fence (lfence).
/// @param counterAddr  Pointer to a g_Counter_* global
/// @return Current value
uint64_t UTC_ReadCounter(const volatile uint64_t* counterAddr);

/// Atomically exchange counter to zero and return old value.
/// @param counterAddr  Pointer to a g_Counter_* global
/// @return Previous value before reset
uint64_t UTC_ResetCounter(volatile uint64_t* counterAddr);

// ============================================================================
// Telemetry Kernel — Wait-Free Ring Buffer
// ============================================================================

/// Write a log event to the wait-free ring buffer.
/// Uses `lock xadd` for slot reservation — threads never stall.
/// @param message  Null-terminated ASCII string
/// @return Slot index used
uint64_t UTC_LogEvent(const char* message);

/// Drain ring buffer to the log file via direct Win32 WriteFile.
/// Single-consumer model: only one thread should call this.
/// @return Number of events flushed
uint64_t UTC_FlushToDisk(void);

/// Returns pointer to the metric table start sentinel.
/// Useful for walking the counter table programmatically.
/// @return Address of g_MetricTableStart
void* UTC_GetMetricTableBase(void);

/// Returns ring buffer head and tail indices (for diagnostics).
/// @return RAX = head index, RDX = tail index (use struct to capture both)
uint64_t UTC_GetEventBufferStats(void);

// ============================================================================
// Prometheus Exporter — Text Format Generation
// ============================================================================

/// Generate full Prometheus metrics payload into the provided buffer.
/// Format: Prometheus text exposition v0.0.4.
/// Buffer should be >= 8KB (recommended 64KB).
/// @param destBuffer  Destination buffer (caller-allocated)
/// @return Total bytes written (not including null terminator)
uint64_t ExportPrometheus(char* destBuffer);

/// Export a single metric line: "<name> <value>\n"
/// @param destBuffer  Destination buffer
/// @param metricName  Null-terminated metric name
/// @param counterPtr  Pointer to the uint64_t counter
/// @return Bytes written
uint64_t ExportPrometheusMetric(char* destBuffer, const char* metricName,
                                 const volatile uint64_t* counterPtr);

// ============================================================================
// Convenience Inline Helpers for C++ Integration
// ============================================================================

#ifdef __cplusplus
} // extern "C"

namespace RawrXD {
namespace Telemetry {
namespace MASM {

/// Helper: increment and return new value
inline uint64_t IncrementInference()    { return UTC_IncrementCounter(&g_Counter_Inference); }
inline uint64_t IncrementAgentLoop()    { return UTC_IncrementCounter(&g_Counter_AgentLoop); }
inline uint64_t IncrementScsiFails()    { return UTC_IncrementCounter(&g_Counter_ScsiFails); }
inline uint64_t IncrementBytePatches()  { return UTC_IncrementCounter(&g_Counter_BytePatches); }
inline uint64_t IncrementMemPatches()   { return UTC_IncrementCounter(&g_Counter_MemPatches); }
inline uint64_t IncrementServerPatches(){ return UTC_IncrementCounter(&g_Counter_ServerPatches); }
inline uint64_t IncrementErrors()       { return UTC_IncrementCounter(&g_Counter_Errors); }

/// Read all counters into a snapshot structure
struct MASMCounterSnapshot {
    uint64_t inference;
    uint64_t scsiFails;
    uint64_t agentLoop;
    uint64_t bytePatches;
    uint64_t memPatches;
    uint64_t serverPatches;
    uint64_t flushOps;
    uint64_t errors;
};

inline MASMCounterSnapshot ReadAllCounters() {
    MASMCounterSnapshot s;
    s.inference     = UTC_ReadCounter(&g_Counter_Inference);
    s.scsiFails     = UTC_ReadCounter(&g_Counter_ScsiFails);
    s.agentLoop     = UTC_ReadCounter(&g_Counter_AgentLoop);
    s.bytePatches   = UTC_ReadCounter(&g_Counter_BytePatches);
    s.memPatches    = UTC_ReadCounter(&g_Counter_MemPatches);
    s.serverPatches = UTC_ReadCounter(&g_Counter_ServerPatches);
    s.flushOps      = UTC_ReadCounter(&g_Counter_FlushOps);
    s.errors        = UTC_ReadCounter(&g_Counter_Errors);
    return s;
}

/// Generate Prometheus payload into a std::string-compatible buffer
inline size_t ExportPrometheusToBuffer(char* buf, size_t /*bufSize*/) {
    return static_cast<size_t>(ExportPrometheus(buf));
}

} // namespace MASM
} // namespace Telemetry
} // namespace RawrXD

#else
// Pure C: extern "C" block was already closed above
#endif

#endif // Included via #pragma once
