# CMake generated Testfile for 
# Source directory: D:/rawrxd/tests
# Build directory: D:/rawrxd/build_sovereign_smoke_gate/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ai_completions]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_ai_completions.exe")
set_tests_properties([=[test_ai_completions]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;82;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_llm_connectivity]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_llm_connectivity.exe")
set_tests_properties([=[test_llm_connectivity]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;94;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_tool_registry]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_tool_registry.exe")
set_tests_properties([=[test_tool_registry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;106;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_voice_processor]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_voice_processor.exe")
set_tests_properties([=[test_voice_processor]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;115;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_zero_retention_manager]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_zero_retention_manager.exe")
set_tests_properties([=[test_zero_retention_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;124;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_semantic_diff_analyzer]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_semantic_diff_analyzer.exe")
set_tests_properties([=[test_semantic_diff_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;133;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_ai_merge_resolver]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_ai_merge_resolver.exe")
set_tests_properties([=[test_ai_merge_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;145;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_ide_model_autonomy]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_ide_model_autonomy.exe")
set_tests_properties([=[test_ide_model_autonomy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;157;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_sandboxed_terminal]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_sandboxed_terminal.exe")
set_tests_properties([=[test_sandboxed_terminal]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;166;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_agentic_file_operations]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_agentic_file_operations.exe")
set_tests_properties([=[test_agentic_file_operations]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;175;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[model_registry_test]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/model_registry_test.exe")
set_tests_properties([=[model_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;184;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_gguf_integration]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_gguf_integration.exe")
set_tests_properties([=[test_gguf_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;193;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_swarm_scheduler_pin]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_swarm_scheduler_pin.exe")
set_tests_properties([=[test_swarm_scheduler_pin]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;206;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_swarm_expert_heatmap_stress]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_swarm_expert_heatmap_stress.exe")
set_tests_properties([=[test_swarm_expert_heatmap_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;219;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_mixture_reference]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_moe_mixture_reference.exe")
set_tests_properties([=[test_moe_mixture_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;227;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_down_project_policy]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_moe_down_project_policy.exe")
set_tests_properties([=[test_moe_down_project_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;235;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_plan_row_mixture_pack_cache]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_moe_plan_row_mixture_pack_cache.exe")
set_tests_properties([=[test_moe_plan_row_mixture_pack_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;243;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_batched_down_project]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_moe_batched_down_project.exe")
set_tests_properties([=[test_moe_batched_down_project]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;251;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_pack_hud_metrics]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_moe_pack_hud_metrics.exe")
set_tests_properties([=[test_moe_pack_hud_metrics]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;259;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_basic_profiler]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_basic_profiler.exe")
set_tests_properties([=[test_basic_profiler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;278;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_batch3_profiler_smoke]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_batch3_profiler_smoke.exe")
set_tests_properties([=[test_batch3_profiler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;290;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_production_regression]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_production_regression.exe")
set_tests_properties([=[test_production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;325;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_instructions_provider]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_instructions_provider.exe")
set_tests_properties([=[test_instructions_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;346;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[sovereign_assembler_smoke]=] "D:/rawrxd/build_sovereign_smoke_gate/bin/sovereign_assembler_smoke.exe")
set_tests_properties([=[sovereign_assembler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;351;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_model_loader_streamer_smoke]=] "D:/rawrxd/build_sovereign_smoke_gate/tests/test_model_loader_streamer_smoke.exe")
set_tests_properties([=[test_model_loader_streamer_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;380;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
