<#
.SYNOPSIS
    RawrXD Browser Module
    
.DESCRIPTION
    Contains Browser-related functions extracted from RawrXD.ps1
    
.NOTES
    Generated by Refactor-RawrXD.ps1
    Original functions: 3
    Generated: 2025-11-25 16:39:06
#>

# Module variables
$script:ModuleName = 'RawrXD.Browser'
$script:ModuleVersion = '1.0.0'

# Function definitions

# ============================================
# Function: Test-DotNetVersionForWebView2
# ============================================
function Test-DotNetVersionForWebView2 {
    try {
        # For PowerShell 7+, check the actual .NET runtime version
        if ($PSVersionTable.PSVersion.Major -ge 7) {
            $runtimeInfo = [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
            Write-StartupLog ".NET Runtime: $runtimeInfo" "INFO"
            
            # Check if it's .NET 8 (best for WebView2)
            if ($runtimeInfo -match '\.NET 8\.') {
                Write-StartupLog "✓ .NET 8 detected - optimal for WebView2" "SUCCESS"
                return $true
            }
            # Check if it's .NET 9+ (has compatibility issues)
            elseif ($runtimeInfo -match '\.NET 9\.') {
                Write-StartupLog "⚠ .NET 9 detected - WebView2 may have compatibility issues" "WARNING"
                return $false
            }
            # Check if it's .NET 6 or 7 (should work but .NET 8 is recommended)
            elseif ($runtimeInfo -match '\.NET [67]\.') {
                Write-StartupLog "⚠ .NET 6/7 detected - .NET 8 recommended for best WebView2 compatibility" "WARNING"
                return $true  # Will work but not optimal
            }
            else {
                Write-StartupLog "⚠ Unknown .NET version: $runtimeInfo" "WARNING"
                return $true  # Try anyway
            }
        }
        else {
            # Windows PowerShell 5.1 uses .NET Framework 4.8, which works with WebView2
            Write-StartupLog "Windows PowerShell 5.1 detected - .NET Framework 4.8 (WebView2 compatible)" "INFO"
            return $true
        }
    }
    catch {
        Write-StartupLog "Could not determine .NET version: $($_.Exception.Message)" "WARNING"
        return $true  # Try anyway
    }
}


# ============================================
# Function: Update-UndoRedoMenuState
# ============================================
function Update-UndoRedoMenuState {
    $undoItem.Enabled = ($script:undoStack.Count -gt 0)
    $redoItem.Enabled = ($script:redoStack.Count -gt 0)
}


# ============================================
# Function: New-ChatTab
# ============================================
function New-ChatTab {
    param(
        [string]$TabName = "Chat",
        [string]$Model = $null
    )
    
    # Check max chat tabs limit
    $currentTabCount = if ($script:chatTabs) { @($script:chatTabs).Count } else { 0 }
    if ($currentTabCount -ge $global:settings.MaxChatTabs) {
        Write-DevConsole "⚠ Maximum chat tabs ($($global:settings.MaxChatTabs)) reached" "WARNING"
        return $null
    }
    
    $script:chatTabCounter++
    $tabId = "chat_$($script:chatTabCounter)"
    $finalTabName = if ($TabName -eq "Chat") { "Chat $($script:chatTabCounter)" } else { $TabName }
    
    # Create new tab page
    $newChatTabPage = New-Object System.Windows.Forms.TabPage
    $newChatTabPage.Text = $finalTabName
    $newChatTabPage.Name = $tabId
    
    # Create chat splitter for this tab
    $chatSplitter = New-Object System.Windows.Forms.SplitContainer
    $chatSplitter.Dock = [System.Windows.Forms.DockStyle]::Fill
    $chatSplitter.Orientation = [System.Windows.Forms.Orientation]::Horizontal
    $chatSplitter.SplitterDistance = 350
    $chatSplitter.Panel2MinSize = 80
    $chatSplitter.IsSplitterFixed = $false
    # Add collapsible functionality
    $chatSplitter.Panel1Collapsed = $false
    $chatSplitter.Panel2Collapsed = $false
    $newChatTabPage.Controls.Add($chatSplitter)
    
    # Chat display area - Use TextBox instead of RichTextBox to avoid RTF errors
    $chatBox = New-Object System.Windows.Forms.TextBox
    $chatBox.Dock = [System.Windows.Forms.DockStyle]::Fill
    $chatBox.Multiline = $true
    $chatBox.ReadOnly = $true
    $chatBox.ScrollBars = [System.Windows.Forms.ScrollBars]::Vertical
    $chatBox.Font = New-Object System.Drawing.Font("Segoe UI", 9)
    # CRITICAL FIX: Use light gray text for visibility (same as editor)
    $chatBox.BackColor = [System.Drawing.Color]::FromArgb(30, 30, 30)
    $chatBox.ForeColor = [System.Drawing.Color]::FromArgb(220, 220, 220)  # Light gray for visibility
    $chatBox.WordWrap = $true
    $chatSplitter.Panel1.Controls.Add($chatBox)
    
    # Input area container
    $inputContainer = New-Object System.Windows.Forms.Panel
    $inputContainer.Dock = [System.Windows.Forms.DockStyle]::Fill
    $inputContainer.Height = 80
    $inputContainer.Padding = New-Object System.Windows.Forms.Padding(0, 0, 0, 2)
    $chatSplitter.Panel2.Controls.Add($inputContainer)
    
    # Model selector
    $modelPanel = New-Object System.Windows.Forms.Panel
    $modelPanel.Dock = [System.Windows.Forms.DockStyle]::Top
    $modelPanel.Height = 20
    $modelPanel.Margin = New-Object System.Windows.Forms.Padding(0)
    $inputContainer.Controls.Add($modelPanel)
    
    $modelLabel = New-Object System.Windows.Forms.Label
    $modelLabel.Text = "Model:"
    $modelLabel.Dock = [System.Windows.Forms.DockStyle]::Left
    $modelLabel.Width = 45
    $modelLabel.TextAlign = [System.Drawing.ContentAlignment]::MiddleLeft
    $modelLabel.Font = New-Object System.Drawing.Font("Segoe UI", 8)
    $modelLabel.Margin = New-Object System.Windows.Forms.Padding(0)
    $modelPanel.Controls.Add($modelLabel)
    
    $modelCombo = New-Object System.Windows.Forms.ComboBox
    $modelCombo.Dock = [System.Windows.Forms.DockStyle]::Left
    $modelCombo.Width = 180
    $modelCombo.Height = 18
    $modelCombo.Font = New-Object System.Drawing.Font("Segoe UI", 8)
    $modelCombo.DropDownStyle = [System.Windows.Forms.ComboBoxStyle]::DropDownList
    $modelCombo.Items.AddRange(@("bigdaddyg-fast:latest", "llama3.2", "llama3.2:1b", "llama3.1", "codellama", "mistral", "qwen2.5-coder"))
    $modelCombo.SelectedItem = if ($Model) { $Model } else { $global:settings.OllamaModel }
    $modelCombo.Margin = New-Object System.Windows.Forms.Padding(0)
    $modelPanel.Controls.Add($modelCombo)
    
    # Input box - Fill the remaining space after model panel
    $inputBox = New-Object System.Windows.Forms.TextBox
    $inputBox.Dock = [System.Windows.Forms.DockStyle]::Fill
    $inputBox.Multiline = $true
    $inputBox.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    $inputBox.ScrollBars = [System.Windows.Forms.ScrollBars]::Vertical
    $inputBox.WordWrap = $true
    # CRITICAL FIX: Use light gray text for visibility (consistent with editor and chat display)
    $inputBox.BackColor = [System.Drawing.Color]::FromArgb(40, 40, 40)
    $inputBox.ForeColor = [System.Drawing.Color]::FromArgb(220, 220, 220)  # Light gray for visibility
    $inputBox.BorderStyle = [System.Windows.Forms.BorderStyle]::FixedSingle
    $inputBox.TabIndex = 0
    $inputBox.ReadOnly = $false
    $inputBox.Enabled = $true
    $inputContainer.Controls.Add($inputBox)
    
    # Chat session data
    $chatSession = @{
        TabId        = $tabId
        TabPage      = $newChatTabPage
        ChatBox      = $chatBox
        InputBox     = $inputBox
        ModelCombo   = $modelCombo
        Messages     = @()
        IsActive     = $false
        CreatedTime  = Get-Date
        LastActivity = Get-Date
    }
    
    # Store chat tab
    $script:chatTabs[$tabId] = $chatSession
    
    # Add to tab control
    $chatTabControl.TabPages.Add($newChatTabPage)
    
    # Event handlers for this chat - use current tab approach
    $inputBox.add_KeyDown({
            param($keyDownSender, $e)
            if ($e.Control -and $e.KeyCode -eq "Enter") {
                # Find the active chat tab based on selected tab
                $selectedTab = $chatTabControl.SelectedTab
                if ($selectedTab -and $script:chatTabs.ContainsKey($selectedTab.Name)) {
                    Send-ChatMessage -TabId $selectedTab.Name
                }
                elseif ($script:activeChatTabId -and $script:chatTabs.ContainsKey($script:activeChatTabId)) {
                    Send-ChatMessage -TabId $script:activeChatTabId
                }
            }
        })
    
    $modelCombo.add_SelectedIndexChanged({
            param($comboSender, $e)
            # Find the active chat tab based on selected tab
            $selectedTab = $chatTabControl.SelectedTab
            if ($selectedTab -and $script:chatTabs.ContainsKey($selectedTab.Name)) {
                Update-ChatModel -TabId $selectedTab.Name -Model $comboSender.SelectedItem
            }
            elseif ($script:activeChatTabId -and $script:chatTabs.ContainsKey($script:activeChatTabId)) {
                Update-ChatModel -TabId $script:activeChatTabId -Model $sender.SelectedItem
            }
        })
    
    # Add focus and cursor positioning handlers
    $inputBox.add_GotFocus({
            param($focusSender, $e)
            # Ensure cursor is visible and positioned correctly at the very top
            $focusSender.SelectionStart = 0
            $focusSender.SelectionLength = 0
            $focusSender.ScrollToCaret()
        })
    
    $inputBox.add_Click({
            param($clickSender, $e)
            # Ensure cursor positioning on click - force to start of text area
            $clickSender.Focus()
            $clickSender.SelectionStart = 0
            $clickSender.ScrollToCaret()
        })
    
    $inputBox.add_Enter({
            param($enterSender, $e)
            # Ensure proper positioning when entering the control
            $enterSender.SelectionStart = 0
            $enterSender.ScrollToCaret()
        })
    
    # Select the new tab
    $chatTabControl.SelectedTab = $newChatTabPage
    $script:activeChatTabId = $tabId
    
    # Ensure input box can receive focus
    $inputBox.Focus()
    
    Update-ChatStatus
    Write-DevConsole "✅ Created new chat tab: $finalTabName" "SUCCESS"
    
    return $tabId
}

# Export functions
$ExportedFunctions = @(
    'Test-DotNetVersionForWebView2',
    'Update-UndoRedoMenuState',
    'New-ChatTab'
)

Export-ModuleMember -Function $ExportedFunctions
