<#
.SYNOPSIS
    RawrXD Video Module
    
.DESCRIPTION
    Contains Video-related functions extracted from RawrXD.ps1
    
.NOTES
    Generated by Refactor-RawrXD.ps1
    Original functions: 10
    Generated: 2025-11-25 16:39:06
#>

# Module variables
$script:ModuleName = 'RawrXD.Video'
$script:ModuleVersion = '1.0.0'

# Function definitions

# ============================================
# Function: Register-ErrorHandler
# ============================================
function Register-ErrorHandler {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ErrorMessage,
        
        [Parameter(Mandatory = $false)]
        [ValidateSet("CRITICAL", "SECURITY", "NETWORK", "FILESYSTEM", "UI", "OLLAMA", "AUTH", "PERFORMANCE", "TELEMETRY")]
        [string]$ErrorCategory = "UI",
        
        [Parameter(Mandatory = $false)]
        [ValidateSet("LOW", "MEDIUM", "HIGH", "CRITICAL")]
        [string]$Severity = "MEDIUM",
        
        [Parameter(Mandatory = $false)]
        [string]$SourceFunction = "",
        
        [Parameter(Mandatory = $false)]
        [hashtable]$AdditionalData = @{},
        
        [Parameter(Mandatory = $false)]
        [bool]$ShowToUser = $true
    )
    
    $currentTime = Get-Date
    $timeSinceLastError = ($currentTime - $script:ErrorTracker.LastErrorTime).TotalMinutes
    
    # Rate limiting: prevent error spam
    if ($timeSinceLastError -lt 1) {
        $script:ErrorTracker.ErrorCount++
        if ($script:ErrorTracker.ErrorCount -gt $script:ErrorNotificationConfig.MaxErrorsPerMinute) {
            Write-StartupLog "Error rate limit exceeded, suppressing notifications" "WARNING"
            return
        }
    }
    else {
        $script:ErrorTracker.ErrorCount = 1
        $script:ErrorTracker.LastErrorTime = $currentTime
    }
    
    # Create detailed error record
    $errorRecord = @{
        Timestamp      = $currentTime.ToString("yyyy-MM-dd HH:mm:ss.fff")
        Message        = $ErrorMessage
        Category       = $ErrorCategory
        Severity       = $Severity
        SourceFunction = $SourceFunction
        SessionId      = if ($script:CurrentSession -and $script:CurrentSession.SessionId) { $script:CurrentSession.SessionId } else { "Unknown" }
        ProcessId      = $PID
        UserContext    = [Environment]::UserName
        MachineName    = [Environment]::MachineName
        AdditionalData = $AdditionalData
        StackTrace     = (Get-PSCallStack | Select-Object -Skip 1 | ForEach-Object { "$($_.Command):$($_.ScriptLineNumber)" }) -join " -> "
    }
    
    # Add to error history
    $script:ErrorTracker.ErrorHistory += $errorRecord
    
    # Keep only last 100 errors to prevent memory issues
    if (@($script:ErrorTracker.ErrorHistory).Count -gt 100) {
        $script:ErrorTracker.ErrorHistory = $script:ErrorTracker.ErrorHistory | Select-Object -Last 100
    }
    
    # Log to startup log
    Write-StartupLog "[$ErrorCategory - $Severity] $ErrorMessage" "ERROR"
    if ($SourceFunction) {
        Write-StartupLog "  Source: $SourceFunction" "ERROR"
    }
    
    # Log to security log if available
    if (Get-Command Write-SecurityLog -ErrorAction SilentlyContinue) {
        Write-SecurityLog "Application error" "ERROR" "$ErrorCategory - $ErrorMessage"
    }
    
    # Log to Windows Event Log (requires admin)
    if ($script:ErrorNotificationConfig.LogToEventLog -and $script:IsAdmin) {
        try {
            if (-not ([System.Diagnostics.EventLog]::SourceExists("RawrXD"))) {
                [System.Diagnostics.EventLog]::CreateEventSource("RawrXD", "Application")
            }
            
            $eventId = switch ($Severity) {
                "LOW" { 1001 }
                "MEDIUM" { 1002 }
                "HIGH" { 1003 }
                "CRITICAL" { 1004 }
                default { 1000 }
            }
            
            [System.Diagnostics.EventLog]::WriteEntry("RawrXD", "$ErrorCategory Error: $ErrorMessage`nSource: $SourceFunction", "Error", $eventId)
        }
        catch {
            Write-StartupLog "Failed to write to Event Log: $_" "WARNING"
        }
    }
    
    # Visual notification to user
    if ($ShowToUser -and $script:ErrorNotificationConfig.EnablePopupNotifications) {
        Show-ErrorNotification -ErrorRecord $errorRecord
    }
    
    # Sound notification
    if ($script:ErrorNotificationConfig.EnableSoundNotifications -and $Severity -in @("HIGH", "CRITICAL")) {
        try {
            [System.Media.SystemSounds]::Exclamation.Play()
        }
        catch {
            Write-StartupLog "Failed to play sound notification: $_" "DEBUG"
        }
    }
    
    # Email notification for critical errors
    if ($script:ErrorNotificationConfig.EnableEmailNotifications -and $Severity -eq "CRITICAL") {
        Send-ErrorNotificationEmail -ErrorRecord $errorRecord
    }
    
    # Auto-recovery for specific error types
    Invoke-AutoRecovery -ErrorRecord $errorRecord
}


# ============================================
# Function: Read-FileChunked
# ============================================
function Read-FileChunked {
    <#
    .SYNOPSIS
        Reads a large file in chunks to avoid memory issues
    .PARAMETER FilePath
        Path to the file
    .PARAMETER ChunkSizeMB
        Size of each chunk in MB (default: 1MB)
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,
        
        [Parameter(Mandatory = $false)]
        [int]$ChunkSizeMB = 1
    )
    
    $chunkSize = $ChunkSizeMB * 1MB
    $fileInfo = Get-Item -Path $FilePath
    $totalSize = $fileInfo.Length
    $chunks = [math]::Ceiling($totalSize / $chunkSize)
    
    for ($i = 0; $i -lt $chunks; $i++) {
        $offset = $i * $chunkSize
        $length = [math]::Min($chunkSize, $totalSize - $offset)
        
        $buffer = New-Object byte[] $length
        $stream = [System.IO.File]::OpenRead($FilePath)
        $stream.Position = $offset
        $bytesRead = $stream.Read($buffer, 0, $length)
        $stream.Close()
        
        $chunk = [System.Text.Encoding]::UTF8.GetString($buffer, 0, $bytesRead)
        Write-Output $chunk
    }
}


# ============================================
# Function: Update-ContextUsageDisplay
# ============================================
function Update-ContextUsageDisplay {
    if ($global:ContextUsage.TotalContext -gt 0) {
        $percentage = [math]::Round(($global:ContextUsage.UsedContext / $global:ContextUsage.TotalContext) * 100, 1)
        $global:ContextUsage.Percentage = $percentage
        
        $color = if ($percentage -lt 50) { 'LightGreen' } 
        elseif ($percentage -lt 80) { 'Yellow' } 
        else { 'OrangeRed' }
        
        $contextUsageLabel.Text = "Context: $percentage%"
        $contextUsageLabel.ForeColor = $color
    }
    else {
        $contextUsageLabel.Text = "Context: 0%"
        $contextUsageLabel.ForeColor = 'LightGray'
    }
}


# ============================================
# Function: Get-VSCodeMarketplaceExtensions
# ============================================
function Get-VSCodeMarketplaceExtensions {
    <#
    .SYNOPSIS
        Fetches extensions from the official VSCode Marketplace API
    .DESCRIPTION
        Queries the VSCode Marketplace to get real extension data including
        popular extensions like GitHub Copilot, Amazon Q, etc.
    .PARAMETER Query
        Search query to find specific extensions
    .PARAMETER PageSize
        Number of results to return (default: 50, max: 100)
    .EXAMPLE
        Get-VSCodeMarketplaceExtensions -Query "copilot"
    #>
    param(
        [string]$Query = "",
        [int]$PageSize = 50
    )
    
    try {
        Write-DevConsole "Fetching extensions from VSCode Marketplace API..." "INFO"
        
        # VSCode Marketplace API endpoint
        $apiUrl = "https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery"
        
        # Build the request body for the VSCode Marketplace API
        $requestBody = @{
            filters = @(
                @{
                    criteria   = @(
                        @{
                            filterType = 8  # Extension name or display name
                            value      = if ($Query) { $Query } else { "" }
                        }
                        @{
                            filterType = 10  # Target platform
                            value      = "Microsoft.VisualStudio.Code"
                        }
                    )
                    pageNumber = 1
                    pageSize   = $PageSize
                    sortBy     = 4  # Sort by download count (most popular)
                    sortOrder  = 2  # Descending
                }
            )
            flags   = 0x192  # Flags for what data to include (statistics, versions, files, etc.)
        } | ConvertTo-Json -Depth 10
        
        # Make the API request
        $headers = @{
            "Content-Type" = "application/json"
            "Accept"       = "application/json;api-version=7.1-preview.1"
            "User-Agent"   = "RawrXD-Editor/1.0"
        }
        
        $response = Invoke-RestMethod -Uri $apiUrl -Method Post -Body $requestBody -Headers $headers -TimeoutSec 15
        
        $extensions = @()
        
        if ($response.results -and $response.results[0].extensions) {
            foreach ($ext in $response.results[0].extensions) {
                try {
                    # Extract extension metadata
                    $publisher = $ext.publisher.publisherName
                    $extName = $ext.extensionName
                    $displayName = $ext.displayName
                    $shortDesc = $ext.shortDescription
                    $version = if ($ext.versions -and $ext.versions[0]) { $ext.versions[0].version } else { "1.0.0" }
                    
                    # Get statistics (downloads, ratings)
                    $downloads = 0
                    $rating = 0
                    if ($ext.statistics) {
                        $downloadStat = $ext.statistics | Where-Object { $_.statisticName -eq "install" } | Select-Object -First 1
                        if ($downloadStat) { $downloads = [int]$downloadStat.value }
                        
                        $ratingStat = $ext.statistics | Where-Object { $_.statisticName -eq "averagerating" } | Select-Object -First 1
                        if ($ratingStat) { $rating = [math]::Round([double]$ratingStat.value, 1) }
                    }
                    
                    # Get tags/categories
                    $tags = @()
                    if ($ext.tags) {
                        $tags = $ext.tags
                    }
                    if ($ext.categories) {
                        $tags += $ext.categories
                    }
                    
                    $category = if ($ext.categories -and $ext.categories[0]) { $ext.categories[0] } else { "Other" }
                    
                    # Create normalized extension entry
                    $extensions += @{
                        Id           = "$publisher.$extName"
                        Name         = $displayName
                        Description  = $shortDesc
                        Author       = $publisher
                        Version      = $version
                        Downloads    = $downloads
                        Rating       = $rating
                        Category     = $category
                        Tags         = $tags
                        Source       = "VSCode Marketplace (Live)"
                        Language     = $script:LANG_CUSTOM
                        Capabilities = $script:CAP_SYNTAX_HIGHLIGHT
                        Installed    = $false
                    }
                }
                catch {
                    Write-DevConsole "Error parsing extension: $_" "WARNING"
                }
            }
        }
        
        Write-DevConsole "✅ Fetched $($extensions.Count) extensions from VSCode Marketplace" "SUCCESS"
        return $extensions
    }
    catch {
        Write-DevConsole "⚠️ Failed to fetch from VSCode Marketplace API: $($_.Exception.Message)" "WARNING"
        Write-StartupLog "VSCode Marketplace API error: $($_.Exception.Message)" "WARNING"
        return @()
    }
}


# ============================================
# Function: Search-Marketplace
# ============================================
function Search-Marketplace {
    param(
        [string]$Query,
        [int]$LanguageFilter = -1,
        [switch]$IncludeInstalled,
        [switch]$IncludeRemote
    )

    if (-not $IncludeInstalled.IsPresent -and -not $IncludeRemote.IsPresent) {
        $IncludeInstalled = $true
        $IncludeRemote = $true
    }

    $results = @()
    $seenIds = @{}

    $evaluateEntry = {
        param($entry, $defaultSource)

        if (-not $entry) {
            return
        }

        if (-not $entry.Source -and $defaultSource) {
            $entry.Source = $defaultSource
        }

        $idKey = if ($entry.Id) { $entry.Id } elseif ($entry.MarketplaceId) { $entry.MarketplaceId } else { '' }
        if ($idKey) {
            $idKey = $idKey.ToString().ToLower()
            if ($seenIds.ContainsKey($idKey)) {
                return
            }
        }

        $match = [string]::IsNullOrEmpty($Query)
        if (-not $match) {
            # Search in Name, Description, Author, Category
            foreach ($field in @($entry.Name, $entry.Description, $entry.Author, $entry.Category)) {
                if ($field -and $field -like "*$Query*") {
                    $match = $true
                    break
                }
            }
            
            # Also search in Tags array if present
            if (-not $match -and $entry.Tags) {
                foreach ($tag in $entry.Tags) {
                    if ($tag -and $tag -like "*$Query*") {
                        $match = $true
                        break
                    }
                }
            }
            
            # Also check ID for direct matches
            if (-not $match -and $entry.Id -and $entry.Id -like "*$Query*") {
                $match = $true
            }
        }

        if ($match -and ($LanguageFilter -eq -1 -or (-not (Get-Member -InputObject $entry -Name 'Language') -or $entry.Language -eq $LanguageFilter))) {
            $results += $entry
            if ($idKey) {
                $seenIds[$idKey] = $true
            }
        }
    }

    if ($IncludeInstalled) {
        foreach ($ext in $script:extensionRegistry) {
            & $evaluateEntry $ext "Installed"
        }
    }

    if ($IncludeRemote) {
        $catalog = Load-MarketplaceCatalog
        foreach ($entry in $catalog) {
            $source = if ($entry.Source) { $entry.Source } else { 'Marketplace' }
            & $evaluateEntry $entry $source
        }
    }

    return $results | Sort-Object @{ Expression = { if ($_.Downloads) { $_.Downloads } else { 0 } }; Descending = $true }, @{ Expression = { $_.Name }; Descending = $false }
}


# ============================================
# Function: Update-AgentChangesDisplay
# ============================================
function Update-AgentChangesDisplay {
    <#
    .SYNOPSIS
        Updates the Agent Changes tab with all approved edits and changes
    #>
    
    if (-not $script:agentChangesList) {
        return
    }
    
    try {
        $script:agentChangesList.Items.Clear()
        
        # Process all approved edits
        foreach ($edit in $global:agentContext.Edits) {
            $fileName = [System.IO.Path]::GetFileName($edit.File)
            $changeDesc = if ($edit.Description) { $edit.Description } else { "File modified" }
            $timestamp = if ($edit.Timestamp) { $edit.Timestamp.ToString("HH:mm:ss") } else { "Unknown" }
            $changeType = if ($edit.Type) { $edit.Type } else { "Edit" }
            
            $item = New-Object System.Windows.Forms.ListViewItem($fileName)
            $item.SubItems.Add($changeDesc) | Out-Null
            $item.SubItems.Add($timestamp) | Out-Null
            $item.SubItems.Add($changeType) | Out-Null
            $item.Tag = $edit
            $item.ForeColor = [System.Drawing.Color]::LightGreen
            $script:agentChangesList.Items.Add($item) | Out-Null
        }
        
        # Also track file operations from Commands
        foreach ($cmd in $global:agentContext.Commands) {
            if ($cmd.Tool -and $cmd.Result) {
                $fileName = "N/A"
                $changeDesc = "Command executed"
                $timestamp = if ($cmd.Timestamp) { $cmd.Timestamp.ToString("HH:mm:ss") } else { "Unknown" }
                
                # Try to extract file information from command
                if ($cmd.Arguments -and $cmd.Arguments.ContainsKey("File")) {
                    $fileName = [System.IO.Path]::GetFileName($cmd.Arguments["File"])
                    $changeDesc = "Tool: $($cmd.Tool)"
                }
                elseif ($cmd.Tool -match "file|edit|write|create") {
                    $changeDesc = "Tool: $($cmd.Tool)"
                }
                
                $item = New-Object System.Windows.Forms.ListViewItem($fileName)
                $item.SubItems.Add($changeDesc) | Out-Null
                $item.SubItems.Add($timestamp) | Out-Null
                $item.SubItems.Add("Command") | Out-Null
                $item.Tag = $cmd
                $item.ForeColor = [System.Drawing.Color]::LightBlue
                $script:agentChangesList.Items.Add($item) | Out-Null
            }
        }
        
        # Sort by timestamp (newest first)
        $script:agentChangesList.Sorting = [System.Windows.Forms.SortOrder]::Descending
        $script:agentChangesList.Sort()
        
        Write-DevConsole "Agent Changes display updated: $($script:agentChangesList.Items.Count) change(s)" "DEBUG"
    }
    catch {
        Write-DevConsole "Error updating Agent Changes display: $_" "ERROR"
    }
}


# ============================================
# Function: Start-ParallelChatProcessing
# ============================================
function Start-ParallelChatProcessing {
    <#
    .SYNOPSIS
        Processes multiple chat requests in parallel across different tabs
    .PARAMETER ChatRequests
        Array of chat request objects with TabId, Message, Model
    #>
    param([array]$ChatRequests)
    
    if (-not $script:threadSafeContext.RunspacePool) {
        Write-DevConsole "⚠ Multithreading not available, processing chats sequentially" "WARNING"
        foreach ($request in $ChatRequests) {
            Send-ChatMessage -TabId $request.TabId
        }
        return
    }
    
    Write-DevConsole "🔄 Starting parallel chat processing for $($ChatRequests.Count) requests" "INFO"
    
    $chatJobs = @()
    
    foreach ($request in $ChatRequests) {
        $powershell = [powershell]::Create()
        $powershell.RunspacePool = $script:threadSafeContext.RunspacePool
        
        $null = $powershell.AddScript({
                param($TabId, $Message, $Model, $ChatHistory)
            
                try {
                    # Build context from chat history with available commands
                    $systemContext = @"
You are an AI assistant in RawrXD IDE. You have access to these commands:
- /grep <pattern> or grep <pattern> - Search for text patterns in files
- /search <query> or search <query> - Semantic codebase search
- /list [path] or list [path] - List files and directories
- /summarize - Summarize chat context and conversation
- /theme <name> - Change UI theme

You can help users search code, find files, and navigate the codebase.
"@
                    
                    $context = "System: $systemContext`n`n"
                    foreach ($msg in $ChatHistory) {
                        $context += "$($msg.Role): $($msg.Content)`n"
                    }
                
                    $body = @{
                        model  = $Model
                        prompt = $context + "user: $Message`n"
                        stream = $false
                    } | ConvertTo-Json -Depth 3
                
                    # PRODUCTION SECURITY: Runspace-safe API key retrieval
                    $apiKey = $null
                    
                    # Try function first (may not be available in runspace)
                    try {
                        if (Get-Command -Name Get-SecureAPIKey -CommandType Function -ErrorAction SilentlyContinue) {
                            $apiKey = Get-SecureAPIKey
                        }
                    }
                    catch { }
                    
                    # Try global settings next
                    if (-not $apiKey) {
                        try {
                            if ($global:settings -and $global:settings.OllamaAPIKey) {
                                $apiKey = $global:settings.OllamaAPIKey
                            }
                        }
                        catch { }
                    }
                    
                    # Fall back to environment variables (always accessible in runspaces)
                    if (-not $apiKey) {
                        foreach ($envVar in @('RAWRXD_API_KEY', 'OLLAMA_API_KEY', 'RAWRAI_API_KEY')) {
                            $val = [System.Environment]::GetEnvironmentVariable($envVar)
                            if ($val -and $val.Trim() -ne '') {
                                $apiKey = $val
                                break
                            }
                        }
                    }
                    
                    $headers = @{
                        "Content-Type" = "application/json"
                    }
                    if ($apiKey) {
                        $headers["Authorization"] = "Bearer $apiKey"
                        $headers["X-Ollama-API-Key"] = $apiKey
                    }
                    $response = Invoke-RestMethod -Uri "http://localhost:11434/api/generate" -Method POST -Body $body -ContentType "application/json" -Headers $headers
                
                    return @{
                        TabId          = $TabId
                        Success        = $true
                        Response       = $response.response
                        ProcessingTime = (Get-Date)
                    }
                }
                catch {
                    return @{
                        TabId          = $TabId
                        Success        = $false
                        Error          = $_.Exception.Message
                        ProcessingTime = (Get-Date)
                    }
                }
            })
        
        $null = $powershell.AddParameter("TabId", $request.TabId)
        $null = $powershell.AddParameter("Message", $request.Message)
        $null = $powershell.AddParameter("Model", $request.Model)
        $null = $powershell.AddParameter("ChatHistory", $request.ChatHistory)
        
        $job = $powershell.BeginInvoke()
        
        $chatJobs += @{
            PowerShell = $powershell
            Job        = $job
            TabId      = $request.TabId
            StartTime  = Get-Date
        }
    }
    
    # Monitor chat jobs completion
    Start-ChatJobMonitor -ChatJobsToAdd $chatJobs
}


# ============================================
# Function: Update-AgentChangesDisplay
# ============================================
function Update-AgentChangesDisplay {
    <#
    .SYNOPSIS
        Updates the Agent Changes tab with all approved edits and changes
    #>
    
    if (-not $script:agentChangesList) {
        return
    }
    
    try {
        $script:agentChangesList.Items.Clear()
        
        # Process all approved edits
        foreach ($edit in $global:agentContext.Edits) {
            $fileName = [System.IO.Path]::GetFileName($edit.File)
            $changeDesc = if ($edit.Description) { $edit.Description } else { "File modified" }
            $timestamp = if ($edit.Timestamp) { $edit.Timestamp.ToString("yyyy-MM-dd HH:mm:ss") } else { "Unknown" }
            
            # Add edit to display
            $item = New-Object System.Windows.Forms.ListViewItem($fileName)
            $item.SubItems.Add($changeDesc) | Out-Null
            $script:agentChangesList.Items.Add($item) | Out-Null
        }
        
        # Sort by timestamp (newest first)
        $script:agentChangesList.Sorting = [System.Windows.Forms.SortOrder]::Descending
        $script:agentChangesList.Sort()
        
        Write-DevConsole "Agent Changes display updated" "INFO"
    }
    catch {
        Write-DevConsole "Error updating Agent Changes display" "WARNING"
    }
}


# ============================================
# Function: Invoke-CliChat
# ============================================
function Invoke-CliChat {
    <#
    .SYNOPSIS
        Start an interactive chat session with Ollama
    .DESCRIPTION
        Interactive chat with enhanced security, input validation, and error handling
    #>
    param(
        [Parameter(Mandatory = $false)]
        [ValidateNotNullOrEmpty()]
        [string]$Model = "llama2"
    )
    
    # Validate model name to prevent injection
    if ($Model -match '[<>"|&;`]') {
        Write-Error "Invalid model name - contains illegal characters"
        return $false
    }
    
    # Limit model name length
    if ($Model.Length -gt 100) {
        Write-Error "Model name too long (max 100 characters)"
        return $false
    }
    
    Write-Host "`n=== Interactive Chat Session ===" -ForegroundColor Cyan
    Write-Host "Model: $Model" -ForegroundColor Yellow
    Write-Host "Type 'exit' or 'quit' to end the session`n" -ForegroundColor Gray
    
    # Test connection first
    if (-not (Invoke-CliTestOllama)) {
        Write-Error "Ollama service is not running. Please start it first."
        return $false
    }
    
    $conversationHistory = @()
    $ollamaUri = "http://localhost:11434/api/generate"  # HTTPS enforced
    
    # Validate Ollama endpoint URL (HTTPS required)
    if ($ollamaUri -notmatch '^http://localhost:11434/') {
        Write-Error "Invalid Ollama endpoint - security validation failed"
        return $false
    }
    
    while ($true) {
        Write-Host "You: " -NoNewline -ForegroundColor Green
        $userInput = Read-SecureInput -Prompt "You" -AsSecureString:$false
        
        if ($userInput -match "^(exit|quit)$") {
            Write-Host "`nEnding chat session. Goodbye!" -ForegroundColor Cyan
            break
        }
        
        if ([string]::IsNullOrWhiteSpace($userInput)) {
            continue
        }
        
        # Validate input length to prevent DoS
        if ($userInput.Length -gt 10000) {
            Write-Host "Error: Input too long (max 10000 characters)" -ForegroundColor Red
            Write-Host ""
            continue
        }
        
        # Handle built-in commands before sending to AI
        $handled = $false
        
        # GREP command - search for text patterns
        if ($userInput -match "^/(grep|search-text)\s+(.+)" -or $userInput -match "^(grep|search)\s+(.+)" -or $userInput -match "search for (.+) in") {
            $searchPattern = if ($matches[1] -eq "grep" -or $matches[1] -eq "search-text" -or $matches[1] -eq "search") { $matches[2] } else { $matches[1] }
            $searchPattern = $searchPattern.Trim()
            
            Write-Host "🔍 Searching for pattern: '$searchPattern'`n" -ForegroundColor Yellow
            
            try {
                $currentDir = Get-Location
                $results = @()
                $fileCount = 0
                $matchCount = 0
                
                Get-ChildItem -Path $currentDir -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
                    try {
                        $content = Get-Content $_.FullName -Raw -ErrorAction SilentlyContinue
                        if ($content -match $searchPattern) {
                            $fileCount++
                            $lines = $content -split "`n"
                            $lineMatches = @()
                            for ($i = 0; $i -lt $lines.Count; $i++) {
                                if ($lines[$i] -match $searchPattern) {
                                    $lineMatches += "  Line $($i + 1): $($lines[$i].Trim())"
                                    $matchCount++
                                }
                            }
                            if ($lineMatches.Count -gt 0) {
                                $results += "📄 $($_.Name) ($($_.FullName))"
                                $results += $lineMatches[0..([Math]::Min(5, $lineMatches.Count - 1))]
                                if ($lineMatches.Count -gt 5) {
                                    $results += "  ... and $($lineMatches.Count - 5) more matches"
                                }
                            }
                        }
                    }
                    catch { }
                }
                
                if ($results.Count -eq 0) {
                    Write-Host "❌ No matches found for pattern '$searchPattern' in $currentDir" -ForegroundColor Red
                }
                else {
                    Write-Host "✅ Found $matchCount match(es) in $fileCount file(s):`n" -ForegroundColor Green
                    $displayResults = if ($results.Count -gt 20) { $results[0..19] } else { $results }
                    Write-Host ($displayResults -join "`n") -ForegroundColor White
                    if ($results.Count -gt 20) {
                        Write-Host "... (showing first 20 results)" -ForegroundColor Gray
                    }
                }
            }
            catch {
                Write-Host "❌ Error searching: $($_.Exception.Message)" -ForegroundColor Red
            }
            
            Write-Host ""
            $handled = $true
        }
        
        # SEARCH command - semantic codebase search
        if (-not $handled -and ($userInput -match "^/(search|find|codebase-search)\s+(.+)" -or $userInput -match "^(search|find)\s+(.+)" -or $userInput -match "search codebase for (.+)")) {
            $searchQuery = if ($matches[1] -eq "search" -or $matches[1] -eq "find" -or $matches[1] -eq "codebase-search") { $matches[2] } else { $matches[1] }
            $searchQuery = $searchQuery.Trim()
            
            Write-Host "🔎 Semantic search for: '$searchQuery'`n" -ForegroundColor Yellow
            
            try {
                $currentDir = Get-Location
                $results = @()
                $fileCount = 0
                
                Get-ChildItem -Path $currentDir -Recurse -File -ErrorAction SilentlyContinue | 
                Where-Object { $_.Extension -match '\.(ps1|psm1|txt|md|json|xml|yaml|yml|js|ts|py|java|cpp|h|cs)$' } | 
                ForEach-Object {
                    try {
                        $content = Get-Content $_.FullName -Raw -ErrorAction SilentlyContinue
                        $keywords = $searchQuery -split '\s+'
                        $matchScore = 0
                        foreach ($keyword in $keywords) {
                            if ($content -match [regex]::Escape($keyword)) {
                                $matchScore++
                            }
                        }
                        if ($matchScore -gt 0) {
                            $fileCount++
                            $results += "📄 $($_.Name) (Score: $matchScore/$($keywords.Count)) - $($_.FullName)"
                            if ($results.Count -ge 10) { return }
                        }
                    }
                    catch { }
                }
                
                if ($results.Count -eq 0) {
                    Write-Host "❌ No relevant files found for '$searchQuery'" -ForegroundColor Red
                }
                else {
                    Write-Host "✅ Found $fileCount relevant file(s):`n" -ForegroundColor Green
                    Write-Host ($results -join "`n") -ForegroundColor White
                }
            }
            catch {
                Write-Host "❌ Error searching: $($_.Exception.Message)" -ForegroundColor Red
            }
            
            Write-Host ""
            $handled = $true
        }
        
        # LIST command - list files/directories
        if (-not $handled -and ($userInput -match "^/(list|ls|dir)\s*(.*)" -or $userInput -match "^(list|show)\s+(files|directories|dir)\s*(.*)" -or $userInput -match "list (.+)")) {
            $listPath = if ($matches[1] -and $matches[1] -ne "list" -and $matches[1] -ne "ls" -and $matches[1] -ne "dir") { $matches[1] } 
            elseif ($matches[2]) { $matches[2] } 
            else { "" }
            $listPath = $listPath.Trim()
            
            try {
                if ([string]::IsNullOrWhiteSpace($listPath)) {
                    $listPath = Get-Location
                }
                
                if (-not (Test-Path $listPath)) {
                    Write-Host "❌ Path not found: $listPath" -ForegroundColor Red
                }
                else {
                    $items = Get-ChildItem -Path $listPath -ErrorAction SilentlyContinue | Sort-Object Name
                    $dirs = $items | Where-Object { $_.PSIsContainer }
                    $files = $items | Where-Object { -not $_.PSIsContainer }
                    
                    Write-Host "📁 Directory: $listPath`n" -ForegroundColor Cyan
                    Write-Host "📂 Directories ($($dirs.Count)):" -ForegroundColor Yellow
                    foreach ($dir in $dirs) {
                        Write-Host "  📁 $($dir.Name)" -ForegroundColor White
                    }
                    Write-Host "`n📄 Files ($($files.Count)):" -ForegroundColor Yellow
                    foreach ($file in $files) {
                        $size = if ($file.Length -lt 1KB) { "$($file.Length) B" }
                        elseif ($file.Length -lt 1MB) { "$([math]::Round($file.Length/1KB, 2)) KB" }
                        else { "$([math]::Round($file.Length/1MB, 2)) MB" }
                        Write-Host "  📄 $($file.Name) ($size)" -ForegroundColor White
                    }
                    
                    if ($items.Count -gt 50) {
                        Write-Host "`n... (showing first 50 items)" -ForegroundColor Gray
                    }
                }
            }
            catch {
                Write-Host "❌ Error listing directory: $($_.Exception.Message)" -ForegroundColor Red
            }
            
            Write-Host ""
            $handled = $true
        }
        
        # SUMMARIZE command - summarize chat context
        if (-not $handled -and ($userInput -match "^/(summarize|summary|context)" -or $userInput -match "summarize (chat|conversation|context)")) {
            Write-Host "📋 Chat Context Summary`n" -ForegroundColor Cyan
            
            try {
                $messageCount = $conversationHistory.Count
                $userMessages = $conversationHistory | Where-Object { $_.Role -eq "user" }
                $aiMessages = $conversationHistory | Where-Object { $_.Role -eq "assistant" }
                
                Write-Host "📊 Statistics:" -ForegroundColor Yellow
                Write-Host "  • Total messages: $messageCount" -ForegroundColor White
                Write-Host "  • User messages: $($userMessages.Count)" -ForegroundColor White
                Write-Host "  • AI responses: $($aiMessages.Count)" -ForegroundColor White
                if ($conversationHistory.Count -gt 0) {
                    $duration = (Get-Date) - $conversationHistory[0].Timestamp
                    Write-Host "  • Session duration: $($duration.ToString('hh\:mm\:ss'))" -ForegroundColor White
                }
                
                Write-Host "`n💬 Recent Topics:" -ForegroundColor Yellow
                $recentMessages = $conversationHistory[-10..-1] | Where-Object { $_ }
                $topics = @()
                foreach ($msg in $recentMessages) {
                    if ($msg.Role -eq "user" -and $msg.Content.Length -gt 10) {
                        $words = $msg.Content -split '\s+' | Where-Object { $_.Length -gt 4 }
                        if ($words.Count -gt 0) {
                            $topics += $words[0..2] -join " "
                        }
                    }
                }
                $uniqueTopics = $topics | Select-Object -Unique | Select-Object -First 5
                foreach ($topic in $uniqueTopics) {
                    Write-Host "  • $topic" -ForegroundColor White
                }
                
                Write-Host "`n📝 Key Points:" -ForegroundColor Yellow
                foreach ($msg in $userMessages[0..([Math]::Min(3, $userMessages.Count - 1))]) {
                    $preview = if ($msg.Content.Length -gt 60) { $msg.Content.Substring(0, 60) + "..." } else { $msg.Content }
                    Write-Host "  • $preview" -ForegroundColor White
                }
            }
            catch {
                Write-Host "❌ Error generating summary: $($_.Exception.Message)" -ForegroundColor Red
            }
            
            Write-Host ""
            $handled = $true
        }
        
        # If command was handled, skip AI call
        if ($handled) {
            continue
        }
        
        # Send to AI with context
        try {
            Write-Host "AI: " -NoNewline -ForegroundColor Cyan
            
            # Build context with available commands
            $systemContext = @"
You are an AI assistant in RawrXD IDE. You have access to these commands:
- /grep <pattern> or grep <pattern> - Search for text patterns in files
- /search <query> or search <query> - Semantic codebase search
- /list [path] or list [path] - List files and directories
- /summarize - Summarize chat context and conversation

You can help users search code, find files, and navigate the codebase.
"@
            
            # Build conversation context
            $context = "System: $systemContext`n`n"
            foreach ($msg in $conversationHistory) {
                $context += "$($msg.Role): $($msg.Content)`n"
            }
            
            # Sanitize model name in request body
            $sanitizedModel = $Model.Trim()
            $sanitizedInput = $context + "user: $($userInput.Trim())`n"
            
            $body = @{
                model  = $sanitizedModel
                prompt = $sanitizedInput
                stream = $false
            } | ConvertTo-Json -Compress
            
            $response = Invoke-RestMethod -Uri $ollamaUri -Method Post -Body $body -ContentType "application/json" -TimeoutSec 120 -ErrorAction Stop
            
            if ($response.response) {
                Write-Host $response.response -ForegroundColor White
                # Store in conversation history
                $conversationHistory += @{ Role = "user"; Content = $userInput; Timestamp = Get-Date }
                $conversationHistory += @{ Role = "assistant"; Content = $response.response; Timestamp = Get-Date }
            }
            else {
                Write-Host "No response received from model" -ForegroundColor Red
            }
            
            Write-Host ""
        }
        catch [System.Net.WebException] {
            Write-Host "Error: Connection failed - $($_.Exception.Message)" -ForegroundColor Red
            Write-Host ""
        }
        catch {
            Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red
            Write-Host ""
        }
    }
    
    return $true
}


# ============================================
# Function: Invoke-CliAnalyzeFile
# ============================================
function Invoke-CliAnalyzeFile {
    <#
    .SYNOPSIS
        Analyze a file with AI
    .DESCRIPTION
        Analyzes a file with enhanced security, path validation, and error handling
    #>
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$FilePath,
        
        [Parameter(Mandatory = $false)]
        [ValidateNotNullOrEmpty()]
        [string]$Model = "llama2"
    )
    
    Write-Host "`n=== File Analysis ===" -ForegroundColor Cyan
    
    # Validate and sanitize file path to prevent path traversal attacks
    try {
        $resolvedPath = Resolve-Path -Path $FilePath -ErrorAction Stop
        $fullPath = $resolvedPath.Path
        
        # Additional security: ensure path is within reasonable bounds
        if ($fullPath.Length -gt 260) {
            Write-Error "File path too long (max 260 characters)"
            return $false
        }
    }
    catch {
        Write-Host "✗ Invalid file path: $FilePath" -ForegroundColor Red
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
        Write-Error "File path validation failed: $($_.Exception.Message)" -ErrorAction Continue
        return $false
    }
    
    if (-not (Test-Path $fullPath)) {
        Write-Host "✗ File not found: $fullPath" -ForegroundColor Red
        Write-Error "File not found: $fullPath" -ErrorAction Continue
        return $false
    }
    
    # Validate it's actually a file, not a directory
    $fileItem = Get-Item -Path $fullPath -ErrorAction Stop
    if ($fileItem.PSIsContainer) {
        Write-Host "✗ Path is a directory, not a file: $fullPath" -ForegroundColor Red
        Write-Error "Path is a directory: $fullPath" -ErrorAction Continue
        return $false
    }
    
    # Validate file size (prevent loading huge files)
    $maxFileSize = 10MB
    if ($fileItem.Length -gt $maxFileSize) {
        Write-Host "✗ File too large: $([Math]::Round($fileItem.Length / 1MB, 2)) MB (max 10 MB)" -ForegroundColor Red
        Write-Error "File too large for analysis: $([Math]::Round($fileItem.Length / 1MB, 2)) MB" -ErrorAction Continue
        return $false
    }
    
    # Validate model name
    if ($Model -match '[<>"|&;`]') {
        Write-Error "Invalid model name - contains illegal characters"
        return $false
    }
    
    try {
        $content = Get-Content -Path $fullPath -Raw -ErrorAction Stop
        $fileInfo = Get-Item $fullPath
        
        Write-Host "File: $($fileInfo.Name)" -ForegroundColor Yellow
        Write-Host "Size: $([Math]::Round($fileInfo.Length / 1KB, 2)) KB" -ForegroundColor Gray
        Write-Host "Lines: $(($content -split "`n").Count)" -ForegroundColor Gray
        Write-Host "`nAnalyzing with $Model...`n" -ForegroundColor Cyan
        
        # Limit prompt size to prevent issues
        $maxPromptLength = 50000
        if ($content.Length -gt $maxPromptLength) {
            Write-Host "⚠ File content truncated for analysis (showing first $maxPromptLength characters)" -ForegroundColor Yellow
            $content = $content.Substring(0, $maxPromptLength) + "`n`n[Content truncated...]"
        }
        
        $prompt = "Analyze this code file and provide insights about its purpose, structure, and any potential improvements:`n`n$content"
        
        # Validate Ollama endpoint URL
        $ollamaUri = "http://localhost:11434/api/generate"
        if ($ollamaUri -notmatch '^http://localhost:11434/') {
            Write-Error "Invalid Ollama endpoint - security validation failed"
            return $false
        }
        
        $body = @{
            model  = $Model.Trim()
            prompt = $prompt
            stream = $false
        } | ConvertTo-Json -Compress
        
        $response = Invoke-RestMethod -Uri $ollamaUri -Method Post -Body $body -ContentType "application/json" -TimeoutSec 180 -ErrorAction Stop
        
        if ($response.response) {
            Write-Host "Analysis:" -ForegroundColor Green
            Write-Host $response.response -ForegroundColor White
        }
        else {
            Write-Host "✗ No analysis received from model" -ForegroundColor Red
        }
        
        return $true
    }
    catch [System.IO.IOException] {
        Write-Host "✗ Failed to read file" -ForegroundColor Red
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
        Write-Error "File analysis failed - IO error: $($_.Exception.Message)" -ErrorAction Continue
        return $false
    }
    catch [System.Net.WebException] {
        Write-Host "✗ Failed to analyze file - connection error" -ForegroundColor Red
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
        Write-Error "File analysis failed - network error: $($_.Exception.Message)" -ErrorAction Continue
        return $false
    }
    catch {
        Write-Host "✗ Failed to analyze file" -ForegroundColor Red
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
        Write-Error "File analysis failed: $($_.Exception.Message)" -ErrorAction Continue
        return $false
    }
}

# Export functions
$ExportedFunctions = @(
    'Register-ErrorHandler',
    'Read-FileChunked',
    'Update-ContextUsageDisplay',
    'Get-VSCodeMarketplaceExtensions',
    'Search-Marketplace',
    'Update-AgentChangesDisplay',
    'Start-ParallelChatProcessing',
    'Update-AgentChangesDisplay',
    'Invoke-CliChat',
    'Invoke-CliAnalyzeFile'
)

Export-ModuleMember -Function $ExportedFunctions
