<#
.SYNOPSIS
    RawrXD Marketplace Module
    
.DESCRIPTION
    Contains Marketplace-related functions extracted from RawrXD.ps1
    
.NOTES
    Generated by Refactor-RawrXD.ps1
    Original functions: 1
    Generated: 2025-11-25 16:25:35
#>

# Import necessary assemblies
Add-Type -AssemblyName System.Text.RegularExpressions

# Module variables
$script:ModuleName = 'RawrXD.Marketplace'
$script:ModuleVersion = '1.0.0'

# Define constants for language codes
$script:LANG_CUSTOM    = 'custom'
$script:LANG_ASM       = 'asm'
$script:LANG_PYTHON    = 'python'
$script:LANG_C         = 'c'
$script:LANG_CPP      = 'cpp'
$script:LANG_RUST      = 'rust'
$script:LANG_GO        = 'go'
$script:LANG_JAVASCRIPT = 'javascript'

# Function definitions

# ============================================
# Function: Resolve-MarketplaceLanguageCode
# ============================================
function Resolve-MarketplaceLanguageCode {
    param (
        [string]$LanguageInput,
        [bool]$UseDefault
    )

    if (!$LanguageInput) { return $LANG_CUSTOM }
    if ($LanguageInput -is [int]) { return $LanguageInput }

    # Check for numeric input
    if ($LanguageInput -match '^\d+$') {
        return [int]$LanguageInput
    }

    # Convert to lowercase and check against language codes
    $token = $LanguageInput.ToLower()
    switch ($token) {
        'asm' { return $LANG_ASM }
        'python' { return $LANG_PYTHON }
        'c' { return $LANG_C }
        'cpp' { return $LANG_CPP }
        'c++' { return $LANG_CPP }
        'rust' { return $LANG_RUST }
        'go' { return $LANG_GO }
        'js' { return $LANG_JAVASCRIPT }
        'javascript' { return $LANG_JAVASCRIPT }
        default {
            if ($UseDefault) {
                return $LANG_CUSTOM
            } else {
                throw "Invalid language code: $token"
            }
        }
    }
}

# Export functions
$ExportedFunctions = @(
    'Resolve-MarketplaceLanguageCode'
)

Export-ModuleMember -Function $ExportedFunctions
