# PowerShell Studio Pro - Complete IDE for PowerShell Development
# Features: Visual GUI Designer, Code Editor, Debugger, Packager, and more

# Auto-restart in STA mode
if ($Host.Runspace.ApartmentState -ne 'STA') {
  Write-Host "Restarting in STA mode..."
  PowerShell.exe -STA -File $PSCommandPath
  exit
}

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
Add-Type -AssemblyName System.Design

# Global state
$script:CurrentProject = $null
$script:DesignerControls = @()
$script:SelectedControl = $null
$script:PropertyGrid = $null
$script:CodeEditorText = ""
$script:DebugBreakpoints = @()
$script:SnippetLibrary = @{}
$script:RecentProjects = @()

# (Syntax highlighting engine removed per 'no demos' simplification.)

# Project Management
function New-PSProject {
  param(
    [string]$Name,
    [string]$Path,
    [ValidateSet('Script', 'GUI-WinForms', 'GUI-WPF', 'Module', 'Service')]
    [string]$Type = 'GUI-WinForms'
  )
    
  $projectPath = Join-Path $Path $Name
  New-Item -ItemType Directory -Path $projectPath -Force | Out-Null
    
  $project = [PSCustomObject]@{
    Name     = $Name
    Path     = $projectPath
    Type     = $Type
    MainFile = "$Name.ps1"
    Forms    = @()
    Modules  = @()
    Snippets = @()
    Created  = Get-Date
    Version  = "1.0.0"
    Author   = $env:USERNAME
  }
    
  $project | ConvertTo-Json -Depth 10 | Set-Content "$projectPath\project.json"
    
  # Create initial files
  switch ($Type) {
    'GUI-WinForms' {
      @"
# Generated by PowerShell Studio Pro
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# Form Designer Code
`$form = New-Object System.Windows.Forms.Form
`$form.Text = "$Name"
`$form.Size = New-Object System.Drawing.Size(800, 600)
`$form.StartPosition = "CenterScreen"

# Your code here

[void]`$form.ShowDialog()
"@ | Set-Content "$projectPath\$($project.MainFile)"
    }
    'GUI-WPF' {
      $wpfTemplate = @'
# Generated by PowerShell Studio Pro
Add-Type -AssemblyName PresentationFramework

[xml]$xaml = @"
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        Title="{0}" Height="600" Width="800">
    <Grid>
        <!-- Your controls here -->
    </Grid>
</Window>
"@

$reader = New-Object System.Xml.XmlNodeReader $xaml
$window = [Windows.Markup.XamlReader]::Load($reader)

$window.ShowDialog() | Out-Null
'@
      $wpfTemplate -f $Name | Set-Content "$projectPath\$($project.MainFile)"
    }
  }
    
  return $project
}

# Code Snippet Manager
function Add-CodeSnippet {
  param([string]$Name, [string]$Code, [string]$Description)
    
  $script:SnippetLibrary[$Name] = @{
    Code        = $Code
    Description = $Description
    Created     = Get-Date
  }
}

# Initialize default snippets (kept; not demo script execution)
Add-CodeSnippet -Name "Function Template" -Description "Advanced function with parameter validation" -Code @"
function Verb-Noun {
    <#
    .SYNOPSIS
        Brief description
    .DESCRIPTION
        Detailed description
    .PARAMETER Name
        Parameter description
    .EXAMPLE
        Verb-Noun -Name "Example"
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=`$true)]
        [ValidateNotNullOrEmpty()]
        [string]`$Name
    )
    
    begin { Write-Verbose "Starting Verb-Noun" }
    process { # Main logic }
    end { Write-Verbose "Completed Verb-Noun" }
}
"@

Add-CodeSnippet -Name "Error Handling" -Description "Try-Catch with logging" -Code @"
try {
    # Your code here
} catch {
    Write-Error "Error: `$(`$_.Exception.Message)"
    Write-Verbose "Stack trace: `$(`$_.ScriptStackTrace)"
    throw
}
"@

Add-CodeSnippet -Name "Progress Bar" -Description "Progress bar with percentage" -Code @"
`$total = 100
for (`$i = 0; `$i -lt `$total; `$i++) {
    `$percent = (`$i / `$total) * 100
    Write-Progress -Activity "Processing" -Status "`$percent% Complete" -PercentComplete `$percent
    Start-Sleep -Milliseconds 50
}
Write-Progress -Activity "Processing" -Completed
"@

# GUI Designer Engine
function New-DesignerControl {
  param(
    [System.Windows.Forms.Control]$Control,
    [string]$ControlType,
    [System.Drawing.Point]$Location,
    [System.Drawing.Size]$Size
  )
    
  $Control.Location = $Location
  $Control.Size = $Size
  $Control.Name = "${ControlType}_$([Guid]::NewGuid().ToString().Substring(0,8))"
    
  $Control.AllowDrop = $true
  $Control.Cursor = [System.Windows.Forms.Cursors]::SizeAll
    
  $Control.add_Click({ param($sender, $e) Select-DesignerControl -Control $sender })
    
  $designerControl = [PSCustomObject]@{ Control = $Control; Type = $ControlType; Name = $Control.Name; Properties = @{}; Events = @{} }
  $script:DesignerControls += $designerControl
  return $designerControl
}

function Export-HTMLGUI {
  param(
    [Parameter(Mandatory)][string]$OutputPath,
    [Parameter(Mandatory)][hashtable]$GuiDefinition
  )
  $controlsHtml = ""
  foreach ($ctrl in $GuiDefinition.Controls) {
    switch ($ctrl.type) {
      'button' { $controlsHtml += "<button onclick=`"invokePS('$($ctrl.action)')`">$($ctrl.text)</button>`n" }
      'textbox' { $controlsHtml += "<input id='$($ctrl.name)' placeholder='$($ctrl.placeholder)' />`n" }
      'label' { $controlsHtml += "<label>$($ctrl.text)</label>`n" }
      'checkbox' { $controlsHtml += "<input type='checkbox' id='$($ctrl.name)'> <label>$($ctrl.text)</label>`n" }
    }
  }
  $html = @"
<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'>
<title>$($GuiDefinition.Title)</title>
<style>
body { font-family:'Segoe UI',Arial,sans-serif; margin:20px; background:linear-gradient(135deg,#667eea 0%,#764ba2 100%); min-height:100vh; }
.container { max-width:$($GuiDefinition.Width)px; margin:auto; background:#fff; padding:30px; border-radius:10px; box-shadow:0 10px 40px rgba(0,0,0,.3); }
h2 { color:#333; border-bottom:3px solid #667eea; padding-bottom:10px; }
button { padding:10px 20px; margin:8px 0; width:100%; font-size:14px; background:#667eea; color:#fff; border:none; border-radius:5px; cursor:pointer; transition:.3s; }
button:hover { background:#764ba2; transform:translateY(-2px); box-shadow:0 5px 15px rgba(0,0,0,.2); }
input { padding:10px; margin:8px 0; width:100%; font-size:14px; border:2px solid #ddd; border-radius:5px; box-sizing:border-box; }
input:focus { outline:none; border-color:#667eea; }
label { display:block; margin:8px 0; color:#555; }
.status { margin-top:20px; padding:10px; background:#f0f0f0; border-radius:5px; font-size:12px; color:#666; }
</style>
</head>
<body>
<div class='container'>
<h2>$($GuiDefinition.Title)</h2>
$controlsHtml
<div class='status' id='status'>Ready</div>
</div>
<script>
async function invokePS(action){ document.getElementById('status').innerText='Executing: '+action; try{ window.location.href='pscmd://run/?code='+encodeURIComponent(action);}catch(e){ alert('PowerShell handler not installed. Run Install-PS1XHandler first.'); } setTimeout(()=>{ document.getElementById('status').innerText='Command sent to PowerShell'; },500); }
function getInputValue(id){ return document.getElementById(id).value; }
</script>
</body>
</html>
"@
  Set-Content -Path $OutputPath -Value $html -Encoding UTF8
  Write-Host "HTML GUI exported to: $OutputPath" -ForegroundColor Green
}

function Install-PS1XHandler {
  param([switch]$Uninstall)
  if ($Uninstall) {
    Remove-Item "HKCU:\Software\Classes\pscmd" -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item "HKCU:\Software\Classes\.ps1x" -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item "HKCU:\Software\Classes\PowerShellScriptX" -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "PS1X handlers uninstalled" -ForegroundColor Yellow
    return
  }
  try {
    New-Item -Path "HKCU:\Software\Classes\pscmd" -Force | Out-Null
    Set-ItemProperty "HKCU:\Software\Classes\pscmd" "(Default)" "URL:PowerShell Command Handler"
    New-ItemProperty "HKCU:\Software\Classes\pscmd" -Name "URL Protocol" -Value "" -Force | Out-Null
    New-Item "HKCU:\Software\Classes\pscmd\shell\open\command" -Force | Out-Null
    $psPath = (Get-Process -Id $PID).Path
    Set-ItemProperty "HKCU:\Software\Classes\pscmd\shell\open\command" "(Default)" "`"$psPath`" -ExecutionPolicy Bypass -WindowStyle Hidden -Command `"Invoke-Expression ([uri]::UnescapeDataString('%1').Split('=')[1])`""
    New-Item "HKCU:\Software\Classes\.ps1x" -Force | Out-Null
    Set-ItemProperty "HKCU:\Software\Classes\.ps1x" "(Default)" "PowerShellScriptX"
    New-Item "HKCU:\Software\Classes\PowerShellScriptX\shell\open\command" -Force | Out-Null
    Set-ItemProperty "HKCU:\Software\Classes\PowerShellScriptX\shell\open\command" "(Default)" "`"$psPath`" -ExecutionPolicy Bypass -File `"%1`""
    New-Item "HKCU:\Software\Classes\.psui" -Force | Out-Null
    Set-ItemProperty "HKCU:\Software\Classes\.psui" "(Default)" "PowerShellUIScript"
    New-Item "HKCU:\Software\Classes\PowerShellUIScript\shell\open\command" -Force | Out-Null
    Set-ItemProperty "HKCU:\Software\Classes\PowerShellUIScript\shell\open\command" "(Default)" "`"$psPath`" -STA -ExecutionPolicy Bypass -File `"%1`""
    Write-Host "✓ PS1X handlers installed successfully!" -ForegroundColor Green
  }
  catch { Write-Error "Failed to install handlers: $_" }
}

function Export-PS1X {
  param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][string]$Code, [switch]$IsUIScript)
  if ($IsUIScript -and -not $Path.EndsWith('.psui')) { $Path = [IO.Path]::ChangeExtension($Path, '.psui') }
  elseif (-not $Path.EndsWith('.ps1x') -and -not $IsUIScript) { $Path = [IO.Path]::ChangeExtension($Path, '.ps1x') }
  Set-Content -Path $Path -Value $Code -Encoding UTF8
  Write-Host "Exported: $Path" -ForegroundColor Green
}

function Export-DesignerToHTML {
  param([System.Windows.Forms.Form]$DesignerForm, [string]$OutputPath)
  $controls = @()
  foreach ($dc in $script:DesignerControls) {
    $ctrl = $dc.Control
    $def = @{ type = $dc.Type.ToLower(); name = $ctrl.Name; text = $ctrl.Text }
    if ($dc.Type -eq 'Button' -and $dc.Events.ContainsKey('Click')) { $def.action = $dc.Events['Click'] }
    if ($dc.Type -eq 'TextBox') { $def.placeholder = $ctrl.Text }
    $controls += $def
  }
  $guiDef = @{ Title = $DesignerForm.Text; Width = $DesignerForm.Width; Height = $DesignerForm.Height; Controls = $controls }
  Export-HTMLGUI -OutputPath $OutputPath -GuiDefinition $guiDef
}

function Select-DesignerControl {
  param([System.Windows.Forms.Control]$Control)
  if ($script:SelectedControl) { $script:SelectedControl.BackColor = [System.Drawing.SystemColors]::Control }
  $Control.BackColor = [System.Drawing.Color]::LightBlue
  $script:SelectedControl = $Control
  if ($script:PropertyGrid) { $script:PropertyGrid.SelectedObject = $Control }
}

function Export-WinFormsCode {
  param([System.Windows.Forms.Form]$DesignerForm)
  $code = @"
# Generated by PowerShell Studio Pro - $(Get-Date)
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

`$form = New-Object System.Windows.Forms.Form
`$form.Text = "$($DesignerForm.Text)"
`$form.Size = New-Object System.Drawing.Size($($DesignerForm.Width), $($DesignerForm.Height))
`$form.StartPosition = "CenterScreen"
"@
  foreach ($dc in $script:DesignerControls) {
    $ctrl = $dc.Control
    $var = "`$$($ctrl.Name)"
    $code += @"
# $($dc.Type)
$var = New-Object System.Windows.Forms.$($dc.Type)
$var.Name = "$($ctrl.Name)"
$var.Text = "$($ctrl.Text)"
$var.Location = New-Object System.Drawing.Point($($ctrl.Location.X), $($ctrl.Location.Y))
$var.Size = New-Object System.Drawing.Size($($ctrl.Width), $($ctrl.Height))
"@
    foreach ($event in $dc.Events.Keys) {
      $code += @"
$var.add_$event({
$($dc.Events[$event])
})
"@
    }
    $code += "`$form.Controls.Add($var)`n`n"
  }
  $code += @"
[void]`$form.ShowDialog()
"@
  return $code
}

function ConvertTo-Executable {
  param([string]$ScriptPath, [string]$OutputPath, [switch]$IncludePS7Runtime, [string]$IconPath, [switch]$RequireAdmin, [switch]$NoConsole)
  $scriptContent = Get-Content $ScriptPath -Raw
  $csharpCode = @"
using System;using System.Management.Automation;using System.Collections.ObjectModel;
namespace PSExecutable { class Program { static void Main(string[] args) { using (PowerShell ps = PowerShell.Create()) { string script = @"{0}"; ps.AddScript(script); foreach (var a in args) { ps.AddArgument(a); } try { Collection<PSObject> r = ps.Invoke(); foreach (var o in r) { Console.WriteLine(o); } if (ps.HadErrors) { foreach (var e in ps.Streams.Error) { Console.Error.WriteLine(e); } Environment.Exit(1); } } catch (Exception ex) { Console.Error.WriteLine("Error: " + ex.Message); Environment.Exit(1); } } } } }
"@
  $escaped = ($scriptContent -replace '"', '""')
  $csharpCode = $csharpCode -f $escaped
  Write-Host "Executable packaging would compile C# wrapper (stub)." -ForegroundColor Cyan
  return @{ Success = $true; Path = $OutputPath; Code = $csharpCode }
}

function Start-PerformanceMonitor {
  param([scriptblock]$Script)
  $start = Get-Date; $memStart = [GC]::GetTotalMemory($false); $proc = Get-Process -Id $PID; $cpuStart = $proc.TotalProcessorTime
  $res = & $Script
  $end = Get-Date; $memEnd = [GC]::GetTotalMemory($false); $proc.Refresh(); $cpuEnd = $proc.TotalProcessorTime
  [PSCustomObject]@{ Result = $res; Duration = $end - $start; MemoryUsed = $memEnd - $memStart; CPUTime = $cpuEnd - $cpuStart }
}

# Main IDE Window
$mainForm = New-Object System.Windows.Forms.Form
$mainForm.Text = "PowerShell Studio Pro - IDE"
$mainForm.Size = New-Object System.Drawing.Size(1400, 900)
$mainForm.StartPosition = "CenterScreen"
$mainForm.Icon = [System.Drawing.SystemIcons]::Application

# Menu Bar (File/Edit/View/Debug/Tools)
$menuStrip = New-Object System.Windows.Forms.MenuStrip
$fileMenu = New-Object System.Windows.Forms.ToolStripMenuItem -Property @{ Text = '&File' }
$newProjectItem = New-Object System.Windows.Forms.ToolStripMenuItem -Property @{ Text = 'New Project...' }
$openProjectItem = New-Object System.Windows.Forms.ToolStripMenuItem -Property @{ Text = 'Open Project...' }
$saveProjectItem = New-Object System.Windows.Forms.ToolStripMenuItem -Property @{ Text = 'Save' }
$fileMenu.DropDownItems.AddRange(@($newProjectItem, $openProjectItem, $saveProjectItem)) | Out-Null
$menuStrip.Items.Add($fileMenu) | Out-Null
$mainForm.Controls.Add($menuStrip); $mainForm.MainMenuStrip = $menuStrip

# Toolbar
$toolStrip = New-Object System.Windows.Forms.ToolStrip
$newBtn = New-Object System.Windows.Forms.ToolStripButton -Property @{ Text = 'New' }
$runBtn = New-Object System.Windows.Forms.ToolStripButton -Property @{ Text = '▶ Run' }
$toolStrip.Items.AddRange(@($newBtn, $runBtn)) | Out-Null
$mainForm.Controls.Add($toolStrip)

# Status Bar
$statusStrip = New-Object System.Windows.Forms.StatusStrip
$statusLabel = New-Object System.Windows.Forms.ToolStripStatusLabel -Property @{ Text = 'Ready'; Spring = $true }
$psVersionLabel = New-Object System.Windows.Forms.ToolStripStatusLabel -Property @{ Text = "PS $($PSVersionTable.PSVersion)" }
$statusStrip.Items.AddRange(@($statusLabel, $psVersionLabel)) | Out-Null
$mainForm.Controls.Add($statusStrip)

# Split Containers and Tabs
$mainSplit = New-Object System.Windows.Forms.SplitContainer -Property @{ Dock = 'Fill'; SplitterDistance = 250 }
$mainForm.Controls.Add($mainSplit)
$leftTabs = New-Object System.Windows.Forms.TabControl -Property @{ Dock = 'Fill' }
$mainSplit.Panel1.Controls.Add($leftTabs)
$toolboxTab = New-Object System.Windows.Forms.TabPage -Property @{ Text = 'Toolbox' }
$propertiesTab = New-Object System.Windows.Forms.TabPage -Property @{ Text = 'Properties' }
$explorerTab = New-Object System.Windows.Forms.TabPage -Property @{ Text = 'Explorer' }
$leftTabs.TabPages.AddRange(@($toolboxTab, $propertiesTab, $explorerTab)) | Out-Null
$toolboxList = New-Object System.Windows.Forms.ListBox -Property @{ Dock = 'Fill' }
$toolboxList.Items.AddRange(@('Button', 'TextBox', 'Label', 'CheckBox', 'RadioButton', 'ComboBox', 'ListBox', 'Panel', 'GroupBox'))
$toolboxTab.Controls.Add($toolboxList)
$script:PropertyGrid = New-Object System.Windows.Forms.PropertyGrid -Property @{ Dock = 'Fill'; HelpVisible = $true }
$propertiesTab.Controls.Add($script:PropertyGrid)
$explorerTree = New-Object System.Windows.Forms.TreeView -Property @{ Dock = 'Fill' }
$explorerTab.Controls.Add($explorerTree)

$centerTabs = New-Object System.Windows.Forms.TabControl -Property @{ Dock = 'Fill' }
$mainSplit.Panel2.Controls.Add($centerTabs)
$designerTab = New-Object System.Windows.Forms.TabPage -Property @{ Text = 'Designer' }
$codeTab = New-Object System.Windows.Forms.TabPage -Property @{ Text = 'Code' }
$centerTabs.TabPages.AddRange(@($designerTab, $codeTab)) | Out-Null
$designerPanel = New-Object System.Windows.Forms.Panel -Property @{ Dock = 'Fill'; BackColor = [System.Drawing.Color]::White; BorderStyle = 'FixedSingle'; AutoScroll = $true }
$designerTab.Controls.Add($designerPanel)
$designerForm = New-Object System.Windows.Forms.Form -Property @{ Text = 'Form1'; Size = (New-Object System.Drawing.Size(600, 400)); TopLevel = $false; BackColor = [System.Drawing.SystemColors]::Control }
$designerPanel.Controls.Add($designerForm); $designerForm.Show()

$codeEditor = New-Object System.Windows.Forms.RichTextBox -Property @{ Dock = 'Fill'; Font = (New-Object System.Drawing.Font('Consolas', 10)); AcceptsTab = $true; WordWrap = $false; ScrollBars = 'Both' }
$codeEditor.Text = @"
# PowerShell Script Editor
# (No demo code loaded.)
"@
$codeTab.Controls.Add($codeEditor)

# Basic Run Handler
$runBtn.add_Click({
    $scriptText = $codeEditor.Text
    try {
      $statusLabel.Text = 'Running...'
      $output = powershell.exe -NoProfile -Command $scriptText
      [System.Windows.Forms.MessageBox]::Show('Execution complete.', 'Run', 'OK', 'Information')
      $statusLabel.Text = 'Completed'
    }
    catch { $statusLabel.Text = "Error: $($_.Exception.Message)" }
  })

# Show IDE
[void]$mainForm.ShowDialog()
