#pragma once
// Auto-generated by scripts/generate_source_menu.py
// Source File Registry — maps every repo file to a Win32 menu item

#include <windows.h>
#include <string>
#include <unordered_map>

#define IDM_SRCFILE_BASE 60000
#define IDM_SRCFILE_COUNT 3467
#define IDM_SRCFILE_MAX  63466

// Returns true if cmdId is a source-file menu item
inline bool IsSourceFileCommand(UINT cmdId) {
    return cmdId >= 60000 && cmdId <= 63466;
}

// Get the relative file path for a source-file command ID
const wchar_t* GetSourceFilePath(UINT cmdId);

// Build the Source Files popup menu hierarchy
HMENU BuildSourceFileMenu();

// Total source files registered
constexpr int SRCFILE_TOTAL = 3467;

