// Win32IDE_Accelerators.cpp — Accelerator table for the production message loop (TranslateAccelerator).
// Menu command IDs must stay aligned with Win32IDE.cpp / Win32IDE_Commands.cpp.

#include "Win32IDE.h"
#include "Win32IDE_Commands.h"

#ifndef IDM_FILE_NEW
#define IDM_FILE_NEW 2001
#define IDM_FILE_OPEN 2002
#define IDM_FILE_SAVE 2003
#define IDM_FILE_SAVEAS 2004
#endif
#ifndef IDM_FILE_OPEN_FOLDER
#define IDM_FILE_OPEN_FOLDER 1037
#endif
#ifndef IDM_EDIT_SELECT_ALL
#define IDM_EDIT_SELECT_ALL 2006
#endif
#ifndef IDM_EDIT_UNDO
#define IDM_EDIT_UNDO 2007
#define IDM_EDIT_REDO 2008
#define IDM_EDIT_CUT 2009
#define IDM_EDIT_COPY 2010
#define IDM_EDIT_PASTE 2011
#define IDM_EDIT_FIND 2016
#define IDM_EDIT_REPLACE 2017
#define IDM_EDIT_FIND_NEXT 2018
#define IDM_EDIT_FIND_PREV 2019
#endif
#ifndef IDM_BUILD_PROJECT
#define IDM_BUILD_PROJECT 2801
#define IDM_BUILD_CLEAN 2802
#define IDM_BUILD_REBUILD 2803
#define IDM_BUILD_RUN 2804
#define IDM_BUILD_STOP 2805
#define IDM_BUILD_ASM_CURRENT 2808
#endif

void Win32IDE::createAcceleratorTable()
{
    if (m_hAccel)
    {
        DestroyAcceleratorTable(m_hAccel);
        m_hAccel = nullptr;
    }

    ACCEL accelTable[] = {
        {FVIRTKEY, VK_F7, IDM_BUILD_PROJECT},
        {FCONTROL | FSHIFT | FVIRTKEY, 'B', IDM_BUILD_REBUILD},
        {FCONTROL | FVIRTKEY, VK_F7, IDM_BUILD_ASM_CURRENT},
        {FVIRTKEY, VK_F5, IDM_DBG_GO},
        {FALT | FVIRTKEY, VK_F5, IDM_DBG_BREAK},
        {FCONTROL | FVIRTKEY, VK_F5, IDM_BUILD_RUN},
        {FSHIFT | FVIRTKEY, VK_F5, IDM_DBG_KILL},
        {FCONTROL | FSHIFT | FVIRTKEY, VK_F5, 2108},
        {FVIRTKEY, VK_F10, IDM_DBG_STEP_OVER},
        {FVIRTKEY, VK_F11, IDM_DBG_STEP_INTO},
        {FSHIFT | FVIRTKEY, VK_F11, IDM_DBG_STEP_OUT},
        {FCONTROL | FVIRTKEY, VK_OEM_2, IDM_EDITOR_TOGGLE_COMMENT},
        {FCONTROL | FSHIFT | FVIRTKEY, 'K', IDM_EDITOR_DELETE_LINE},
        {FALT | FSHIFT | FVIRTKEY, VK_DOWN, IDM_EDITOR_DUPLICATE_LINE},
        {FALT | FSHIFT | FVIRTKEY, VK_UP, IDM_EDITOR_DUPLICATE_LINE},
        {FALT | FVIRTKEY, VK_UP, IDM_EDITOR_MOVE_LINE_UP},
        {FALT | FVIRTKEY, VK_DOWN, IDM_EDITOR_MOVE_LINE_DOWN},
        {FCONTROL | FVIRTKEY, 'Z', IDM_EDIT_UNDO},
        {FCONTROL | FVIRTKEY, 'Y', IDM_EDIT_REDO},
        {FCONTROL | FVIRTKEY, 'X', IDM_EDIT_CUT},
        {FCONTROL | FVIRTKEY, 'C', IDM_EDIT_COPY},
        {FCONTROL | FVIRTKEY, 'V', IDM_EDIT_PASTE},
        {FCONTROL | FVIRTKEY, 'A', IDM_EDIT_SELECT_ALL},
        {FCONTROL | FVIRTKEY, 'F', IDM_EDIT_FIND},
        {FCONTROL | FVIRTKEY, 'H', IDM_EDIT_REPLACE},
        {FVIRTKEY, VK_F3, IDM_EDIT_FIND_NEXT},
        {FSHIFT | FVIRTKEY, VK_F3, IDM_EDIT_FIND_PREV},
        {FCONTROL | FVIRTKEY, 'N', IDM_FILE_NEW},
        {FCONTROL | FVIRTKEY, 'O', IDM_FILE_OPEN},
        {FCONTROL | FSHIFT | FVIRTKEY, 'O', IDM_FILE_OPEN_FOLDER},
        {FCONTROL | FVIRTKEY, 'S', IDM_FILE_SAVE},
        {FCONTROL | FSHIFT | FVIRTKEY, 'S', IDM_FILE_SAVEAS},
        {FCONTROL | FVIRTKEY, 'P', IDM_FILE_QUICK_OPEN},
        {FCONTROL | FVIRTKEY, VK_OEM_3, 2029},
        {FCONTROL | FVIRTKEY, VK_OEM_8, 2029},
        {FCONTROL | FSHIFT | FVIRTKEY, VK_OEM_3, 4011},
        {FCONTROL | FSHIFT | FVIRTKEY, VK_OEM_8, 4011},
        {FCONTROL | FVIRTKEY, 'J', IDM_VIEW_TOGGLE_BOTTOM_PANEL},
        {FCONTROL | FVIRTKEY, 'B', 2028},
        {FCONTROL | FSHIFT | FVIRTKEY, 'E', IDM_VIEW_FILE_EXPLORER},
        {FCONTROL | FSHIFT | FVIRTKEY, 'X', IDM_VIEW_EXTENSIONS},
        {FCONTROL | FSHIFT | FVIRTKEY, 'P', 7008},
        {FVIRTKEY, VK_F1, 7008},
        {FCONTROL | FVIRTKEY, 'L', 3009},
        {FCONTROL | FVIRTKEY, 'G', IDM_EDITOR_GOTO_LINE},
        {FCONTROL | FSHIFT | FVIRTKEY, 'O', IDM_EDITOR_GOTO_SYMBOL},
        {FCONTROL | FALT | FSHIFT | FVIRTKEY, 'O', IDM_EDITOR_GOTO_WORKSPACE_SYMBOL},
        {FALT | FVIRTKEY, VK_F12, IDM_EDITOR_PEEK_DEFINITION},
        {FSHIFT | FVIRTKEY, VK_F12, IDM_EDITOR_PEEK_REFERENCES},
        {FCONTROL | FVIRTKEY, VK_F12, IDM_EDITOR_GOTO_IMPLEMENTATION},
        {FCONTROL | FALT | FVIRTKEY, VK_F12, IDM_EDITOR_GOTO_TYPE_DEFINITION},
        {FSHIFT | FALT | FVIRTKEY, 'F', IDM_EDITOR_FORMAT_SELECTION},
        {FCONTROL | FVIRTKEY, VK_OEM_PERIOD, IDM_EDITOR_CODE_ACTIONS},
        {FCONTROL | FALT | FVIRTKEY, 'I', IDM_EDITOR_SHOW_INLAY_HINTS},
        {FCONTROL | FALT | FVIRTKEY, 'T', 4011},
        {FCONTROL | FALT | FVIRTKEY, 'A', 4012},
        {FCONTROL | FSHIFT | FVIRTKEY, 'Y', IDM_AGENT_TOGGLE_FILE_CONTEXT},
    };
    m_hAccel = CreateAcceleratorTableA(accelTable, static_cast<int>(sizeof(accelTable) / sizeof(accelTable[0])));
}
