// ============================================================================
// auto_feature_registry.hpp — AUTO-GENERATED Command Registration Header
// ============================================================================
// Generated by: scripts/auto_register_commands.py
// Generated at: 2026-02-11 07:10:24
// Total new registrations: 432
// New stub handlers: 286
//
// Architecture: C++20, Win32, no Qt, no exceptions
// This file is auto-generated. Do NOT edit manually.
// Re-run: python scripts/auto_register_commands.py
// Rule: NO SOURCE FILE IS TO BE SIMPLIFIED.
// ============================================================================

#pragma once

#ifndef RAWRXD_AUTO_FEATURE_REGISTRY_HPP
#define RAWRXD_AUTO_FEATURE_REGISTRY_HPP

#include "shared_feature_dispatch.h"

// ============================================================================
// INITIALIZATION — Call once at startup (after FeatureRegistrar static init)
// ============================================================================

void initAutoFeatureRegistry();

// ============================================================================
// COVERAGE QUERY — Runtime introspection
// ============================================================================

struct RegistryCoverage {
    size_t totalIdmDefines;       // All IDM_* found in source
    size_t registeredBefore;      // Already in feature_registration.cpp
    size_t autoRegistered;        // Added by this auto-registration
    size_t totalAfter;            // Grand total
    size_t stubHandlers;          // Handlers using generic stub
    size_t realHandlers;          // Handlers with real implementation
    float  coveragePercent;       // totalAfter / totalIdmDefines * 100
};

RegistryCoverage getRegistryCoverage();
const char* getRegistryVersionHash();

// ============================================================================
// STUB HANDLER DECLARATIONS — 286 new handlers
// ============================================================================
// These are generic stubs that report the command name.
// Replace with real implementations as features are built.
// ============================================================================

CommandResult handleAgentConfigureModel(const CommandContext& ctx);
CommandResult handleAgentExecuteCmd(const CommandContext& ctx);
CommandResult handleAgentStartLoop(const CommandContext& ctx);
CommandResult handleAiChatMode(const CommandContext& ctx);
CommandResult handleAiContext128k(const CommandContext& ctx);
CommandResult handleAiContext1m(const CommandContext& ctx);
CommandResult handleAiContext256k(const CommandContext& ctx);
CommandResult handleAiContext32k(const CommandContext& ctx);
CommandResult handleAiContext4k(const CommandContext& ctx);
CommandResult handleAiContext512k(const CommandContext& ctx);
CommandResult handleAiContext64k(const CommandContext& ctx);
CommandResult handleAiExplainCode(const CommandContext& ctx);
CommandResult handleAiFixErrors(const CommandContext& ctx);
CommandResult handleAiGenerateDocs(const CommandContext& ctx);
CommandResult handleAiGenerateTests(const CommandContext& ctx);
CommandResult handleAiInlineComplete(const CommandContext& ctx);
CommandResult handleAiModeDeepResearch(const CommandContext& ctx);
CommandResult handleAiModeDeepThink(const CommandContext& ctx);
CommandResult handleAiModeMax(const CommandContext& ctx);
CommandResult handleAiModeNoRefusal(const CommandContext& ctx);
CommandResult handleAiModelSelect(const CommandContext& ctx);
CommandResult handleAiOptimizeCode(const CommandContext& ctx);
CommandResult handleAiRefactor(const CommandContext& ctx);
CommandResult handleAsmFindLabelRefs(const CommandContext& ctx);
CommandResult handleAsmGotoLabel(const CommandContext& ctx);
CommandResult handleAsmParseSymbols(const CommandContext& ctx);
CommandResult handleAsmShowCallGraph(const CommandContext& ctx);
CommandResult handleAsmShowDataFlow(const CommandContext& ctx);
CommandResult handleAsmShowSections(const CommandContext& ctx);
CommandResult handleAsmShowSymbolTable(const CommandContext& ctx);
CommandResult handleAuditCheckMenus(const CommandContext& ctx);
CommandResult handleAuditDetectStubs(const CommandContext& ctx);
CommandResult handleAuditExportReport(const CommandContext& ctx);
CommandResult handleAuditQuickStats(const CommandContext& ctx);
CommandResult handleAuditRunFull(const CommandContext& ctx);
CommandResult handleAuditRunTests(const CommandContext& ctx);
CommandResult handleAuditShowDashboard(const CommandContext& ctx);
CommandResult handleAutonomyMemory(const CommandContext& ctx);
CommandResult handleAutonomySetGoal(const CommandContext& ctx);
CommandResult handleAutonomyStatus(const CommandContext& ctx);
CommandResult handleBackendSwitchOpenai(const CommandContext& ctx);
CommandResult handleDecompCopyAll(const CommandContext& ctx);
CommandResult handleDecompCopyLine(const CommandContext& ctx);
CommandResult handleDecompFindRefs(const CommandContext& ctx);
CommandResult handleDecompGotoAddr(const CommandContext& ctx);
CommandResult handleDecompGotoDef(const CommandContext& ctx);
CommandResult handleDecompRenameVar(const CommandContext& ctx);
CommandResult handleEditClipboardHistory(const CommandContext& ctx);
CommandResult handleEditCopyFormat(const CommandContext& ctx);
CommandResult handleEditFindNext(const CommandContext& ctx);
CommandResult handleEditFindPrev(const CommandContext& ctx);
CommandResult handleEditGotoLine(const CommandContext& ctx);
CommandResult handleEditMulticursorAdd(const CommandContext& ctx);
CommandResult handleEditMulticursorRemove(const CommandContext& ctx);
CommandResult handleEditPastePlain(const CommandContext& ctx);
CommandResult handleEditSelectall(const CommandContext& ctx);
CommandResult handleEditSnippet(const CommandContext& ctx);
CommandResult handleEditorEngineCycleCmd(const CommandContext& ctx);
CommandResult handleEditorEngineMonacocoreCmd(const CommandContext& ctx);
CommandResult handleEditorEngineRicheditCmd(const CommandContext& ctx);
CommandResult handleEditorEngineStatusCmd(const CommandContext& ctx);
CommandResult handleEditorEngineWebview2Cmd(const CommandContext& ctx);
CommandResult handleFileAutosave(const CommandContext& ctx);
CommandResult handleFileCloseFolder(const CommandContext& ctx);
CommandResult handleFileCloseTab(const CommandContext& ctx);
CommandResult handleFileExit(const CommandContext& ctx);
CommandResult handleFileModelFromHf(const CommandContext& ctx);
CommandResult handleFileModelFromUrl(const CommandContext& ctx);
CommandResult handleFileModelQuickLoad(const CommandContext& ctx);
CommandResult handleFileModelUnified(const CommandContext& ctx);
CommandResult handleFileNewWindow(const CommandContext& ctx);
CommandResult handleFileOpenFolder(const CommandContext& ctx);
CommandResult handleFileRecentClear(const CommandContext& ctx);
CommandResult handleFileSaveall(const CommandContext& ctx);
CommandResult handleFileSaveas(const CommandContext& ctx);
CommandResult handleGauntletExport(const CommandContext& ctx);
CommandResult handleGauntletRun(const CommandContext& ctx);
CommandResult handleGitPanel(const CommandContext& ctx);
CommandResult handleHelpCmdref(const CommandContext& ctx);
CommandResult handleHelpPsdocs(const CommandContext& ctx);
CommandResult handleHelpSearch(const CommandContext& ctx);
CommandResult handleHotpatchByteApply(const CommandContext& ctx);
CommandResult handleHotpatchByteSearch(const CommandContext& ctx);
CommandResult handleHotpatchMemoryApply(const CommandContext& ctx);
CommandResult handleHotpatchMemoryRevert(const CommandContext& ctx);
CommandResult handleHotpatchPresetLoad(const CommandContext& ctx);
CommandResult handleHotpatchPresetSave(const CommandContext& ctx);
CommandResult handleHotpatchProxyBias(const CommandContext& ctx);
CommandResult handleHotpatchProxyRewrite(const CommandContext& ctx);
CommandResult handleHotpatchProxyTerminate(const CommandContext& ctx);
CommandResult handleHotpatchProxyValidate(const CommandContext& ctx);
CommandResult handleHotpatchResetStats(const CommandContext& ctx);
CommandResult handleHotpatchServerAdd(const CommandContext& ctx);
CommandResult handleHotpatchServerRemove(const CommandContext& ctx);
CommandResult handleHotpatchShowEventLog(const CommandContext& ctx);
CommandResult handleHotpatchShowProxyStats(const CommandContext& ctx);
CommandResult handleHotpatchShowStatus(const CommandContext& ctx);
CommandResult handleHotpatchToggleAll(const CommandContext& ctx);
CommandResult handleLspClearDiagnostics(const CommandContext& ctx);
CommandResult handleLspFindReferences(const CommandContext& ctx);
CommandResult handleLspGotoDefinition(const CommandContext& ctx);
CommandResult handleLspHoverInfo(const CommandContext& ctx);
CommandResult handleLspRenameSymbol(const CommandContext& ctx);
CommandResult handleLspRestartServer(const CommandContext& ctx);
CommandResult handleLspServerConfig(const CommandContext& ctx);
CommandResult handleLspServerExportSymbols(const CommandContext& ctx);
CommandResult handleLspServerLaunchStdio(const CommandContext& ctx);
CommandResult handleLspServerPublishDiag(const CommandContext& ctx);
CommandResult handleLspServerReindex(const CommandContext& ctx);
CommandResult handleLspServerStart(const CommandContext& ctx);
CommandResult handleLspServerStats(const CommandContext& ctx);
CommandResult handleLspServerStatus(const CommandContext& ctx);
CommandResult handleLspServerStop(const CommandContext& ctx);
CommandResult handleLspShowDiagnostics(const CommandContext& ctx);
CommandResult handleLspShowStatus(const CommandContext& ctx);
CommandResult handleLspShowSymbolInfo(const CommandContext& ctx);
CommandResult handleModulesExport(const CommandContext& ctx);
CommandResult handleModulesImport(const CommandContext& ctx);
CommandResult handleModulesRefresh(const CommandContext& ctx);
CommandResult handlePdbCacheClear(const CommandContext& ctx);
CommandResult handlePdbEnable(const CommandContext& ctx);
CommandResult handlePdbExports(const CommandContext& ctx);
CommandResult handlePdbFetch(const CommandContext& ctx);
CommandResult handlePdbIatStatus(const CommandContext& ctx);
CommandResult handlePdbImports(const CommandContext& ctx);
CommandResult handlePdbLoad(const CommandContext& ctx);
CommandResult handlePdbResolve(const CommandContext& ctx);
CommandResult handlePdbStatus(const CommandContext& ctx);
CommandResult handleQwAlertDismissAll(const CommandContext& ctx);
CommandResult handleQwAlertResourceStatus(const CommandContext& ctx);
CommandResult handleQwAlertShowHistory(const CommandContext& ctx);
CommandResult handleQwAlertToggleMonitor(const CommandContext& ctx);
CommandResult handleQwBackupAutoToggle(const CommandContext& ctx);
CommandResult handleQwBackupCreate(const CommandContext& ctx);
CommandResult handleQwBackupList(const CommandContext& ctx);
CommandResult handleQwBackupPrune(const CommandContext& ctx);
CommandResult handleQwBackupRestore(const CommandContext& ctx);
CommandResult handleQwShortcutEditor(const CommandContext& ctx);
CommandResult handleQwShortcutReset(const CommandContext& ctx);
CommandResult handleQwSloDashboard(const CommandContext& ctx);
CommandResult handleRevengAnalyze(const CommandContext& ctx);
CommandResult handleRevengCfg(const CommandContext& ctx);
CommandResult handleRevengCompare(const CommandContext& ctx);
CommandResult handleRevengCompile(const CommandContext& ctx);
CommandResult handleRevengDataFlow(const CommandContext& ctx);
CommandResult handleRevengDecompClose(const CommandContext& ctx);
CommandResult handleRevengDecompRename(const CommandContext& ctx);
CommandResult handleRevengDecompSync(const CommandContext& ctx);
CommandResult handleRevengDecompilerView(const CommandContext& ctx);
CommandResult handleRevengDemangle(const CommandContext& ctx);
CommandResult handleRevengDetectVulns(const CommandContext& ctx);
CommandResult handleRevengDisasm(const CommandContext& ctx);
CommandResult handleRevengDumpbin(const CommandContext& ctx);
CommandResult handleRevengExportGhidra(const CommandContext& ctx);
CommandResult handleRevengExportIda(const CommandContext& ctx);
CommandResult handleRevengFunctions(const CommandContext& ctx);
CommandResult handleRevengLicenseInfo(const CommandContext& ctx);
CommandResult handleRevengRecursiveDisasm(const CommandContext& ctx);
CommandResult handleRevengSsa(const CommandContext& ctx);
CommandResult handleRevengTypeRecovery(const CommandContext& ctx);
CommandResult handleRouterShowCapabilities(const CommandContext& ctx);
CommandResult handleRouterShowDecision(const CommandContext& ctx);
CommandResult handleRouterShowFallbacks(const CommandContext& ctx);
CommandResult handleRouterShowStatus(const CommandContext& ctx);
CommandResult handleSubagentChain(const CommandContext& ctx);
CommandResult handleSubagentStatus(const CommandContext& ctx);
CommandResult handleSubagentSwarm(const CommandContext& ctx);
CommandResult handleSubagentTodoClear(const CommandContext& ctx);
CommandResult handleSubagentTodoList(const CommandContext& ctx);
CommandResult handleSwarmAddNode(const CommandContext& ctx);
CommandResult handleSwarmBlacklistNode(const CommandContext& ctx);
CommandResult handleSwarmBuildCmake(const CommandContext& ctx);
CommandResult handleSwarmBuildSources(const CommandContext& ctx);
CommandResult handleSwarmCacheClear(const CommandContext& ctx);
CommandResult handleSwarmCacheStatus(const CommandContext& ctx);
CommandResult handleSwarmCancelBuild(const CommandContext& ctx);
CommandResult handleSwarmFitnessTest(const CommandContext& ctx);
CommandResult handleSwarmListNodes(const CommandContext& ctx);
CommandResult handleSwarmRemoveNode(const CommandContext& ctx);
CommandResult handleSwarmResetStats(const CommandContext& ctx);
CommandResult handleSwarmShowConfig(const CommandContext& ctx);
CommandResult handleSwarmShowEvents(const CommandContext& ctx);
CommandResult handleSwarmShowStats(const CommandContext& ctx);
CommandResult handleSwarmShowTaskGraph(const CommandContext& ctx);
CommandResult handleSwarmStartBuild(const CommandContext& ctx);
CommandResult handleSwarmStartHybrid(const CommandContext& ctx);
CommandResult handleSwarmStartLeader(const CommandContext& ctx);
CommandResult handleSwarmStartWorker(const CommandContext& ctx);
CommandResult handleSwarmStop(const CommandContext& ctx);
CommandResult handleSwarmToggleDiscovery(const CommandContext& ctx);
CommandResult handleSwarmWorkerConnect(const CommandContext& ctx);
CommandResult handleSwarmWorkerDisconnect(const CommandContext& ctx);
CommandResult handleSwarmWorkerStatus(const CommandContext& ctx);
CommandResult handleTelemetryClear(const CommandContext& ctx);
CommandResult handleTelemetryExportCsv(const CommandContext& ctx);
CommandResult handleTelemetryExportJson(const CommandContext& ctx);
CommandResult handleTelemetryShowDashboard(const CommandContext& ctx);
CommandResult handleTelemetrySnapshot(const CommandContext& ctx);
CommandResult handleTelemetryToggle(const CommandContext& ctx);
CommandResult handleTerminalClearAll(const CommandContext& ctx);
CommandResult handleTerminalCmd(const CommandContext& ctx);
CommandResult handleTerminalPowershell(const CommandContext& ctx);
CommandResult handleTerminalSplitCode(const CommandContext& ctx);
CommandResult handleTerminalStop(const CommandContext& ctx);
CommandResult handleThemeAbyss(const CommandContext& ctx);
CommandResult handleThemeCatppuccinMocha(const CommandContext& ctx);
CommandResult handleThemeCyberpunkNeon(const CommandContext& ctx);
CommandResult handleThemeDarkPlus(const CommandContext& ctx);
CommandResult handleThemeDracula(const CommandContext& ctx);
CommandResult handleThemeGruvboxDark(const CommandContext& ctx);
CommandResult handleThemeHighContrast(const CommandContext& ctx);
CommandResult handleThemeLightPlus(const CommandContext& ctx);
CommandResult handleThemeMonokai(const CommandContext& ctx);
CommandResult handleThemeNord(const CommandContext& ctx);
CommandResult handleThemeOneDarkPro(const CommandContext& ctx);
CommandResult handleThemeRawrxdCrimson(const CommandContext& ctx);
CommandResult handleThemeSolarizedDark(const CommandContext& ctx);
CommandResult handleThemeSolarizedLight(const CommandContext& ctx);
CommandResult handleThemeSynthwave84(const CommandContext& ctx);
CommandResult handleThemeTokyoNight(const CommandContext& ctx);
CommandResult handleToolsAnalyzeScript(const CommandContext& ctx);
CommandResult handleToolsBuild(const CommandContext& ctx);
CommandResult handleToolsCommandPalette(const CommandContext& ctx);
CommandResult handleToolsDebug(const CommandContext& ctx);
CommandResult handleToolsExtensions(const CommandContext& ctx);
CommandResult handleToolsProfileResults(const CommandContext& ctx);
CommandResult handleToolsProfileStart(const CommandContext& ctx);
CommandResult handleToolsProfileStop(const CommandContext& ctx);
CommandResult handleToolsSettings(const CommandContext& ctx);
CommandResult handleToolsTerminal(const CommandContext& ctx);
CommandResult handleTransparency100(const CommandContext& ctx);
CommandResult handleTransparency40(const CommandContext& ctx);
CommandResult handleTransparency50(const CommandContext& ctx);
CommandResult handleTransparency60(const CommandContext& ctx);
CommandResult handleTransparency70(const CommandContext& ctx);
CommandResult handleTransparency80(const CommandContext& ctx);
CommandResult handleTransparency90(const CommandContext& ctx);
CommandResult handleTransparencyCustom(const CommandContext& ctx);
CommandResult handleTransparencyToggle(const CommandContext& ctx);
CommandResult handleViewFloatingPanel(const CommandContext& ctx);
CommandResult handleViewMinimap(const CommandContext& ctx);
CommandResult handleViewModuleBrowser(const CommandContext& ctx);
CommandResult handleViewMonacoDevtools(const CommandContext& ctx);
CommandResult handleViewMonacoReload(const CommandContext& ctx);
CommandResult handleViewMonacoSyncTheme(const CommandContext& ctx);
CommandResult handleViewMonacoZoomIn(const CommandContext& ctx);
CommandResult handleViewMonacoZoomOut(const CommandContext& ctx);
CommandResult handleViewOutputPanel(const CommandContext& ctx);
CommandResult handleViewOutputTabs(const CommandContext& ctx);
CommandResult handleViewSidebar(const CommandContext& ctx);
CommandResult handleViewTerminal(const CommandContext& ctx);
CommandResult handleViewThemeEditor(const CommandContext& ctx);
CommandResult handleViewToggleFullscreen(const CommandContext& ctx);
CommandResult handleViewToggleMonaco(const CommandContext& ctx);
CommandResult handleViewToggleOutput(const CommandContext& ctx);
CommandResult handleViewToggleSidebar(const CommandContext& ctx);
CommandResult handleViewToggleTerminal(const CommandContext& ctx);
CommandResult handleViewUseStreamingLoader(const CommandContext& ctx);
CommandResult handleViewUseVulkanRenderer(const CommandContext& ctx);
CommandResult handleViewZoomIn(const CommandContext& ctx);
CommandResult handleViewZoomOut(const CommandContext& ctx);
CommandResult handleViewZoomReset(const CommandContext& ctx);
CommandResult handleVoiceAutoNextVoice(const CommandContext& ctx);
CommandResult handleVoiceAutoPrevVoice(const CommandContext& ctx);
CommandResult handleVoiceAutoRateDown(const CommandContext& ctx);
CommandResult handleVoiceAutoRateUp(const CommandContext& ctx);
CommandResult handleVoiceAutoSettings(const CommandContext& ctx);
CommandResult handleVoiceAutoStop(const CommandContext& ctx);
CommandResult handleVoiceAutoToggle(const CommandContext& ctx);
CommandResult handleVoiceJoinRoom(const CommandContext& ctx);
CommandResult handleVoiceModeContinuous(const CommandContext& ctx);
CommandResult handleVoiceModeDisabled(const CommandContext& ctx);
CommandResult handleVoiceModePtt(const CommandContext& ctx);
CommandResult handleVoicePtt(const CommandContext& ctx);
CommandResult handleVoiceShowDevices(const CommandContext& ctx);
CommandResult handleVoiceTogglePanel(const CommandContext& ctx);
CommandResult handleVscextApiDeactivateAll(const CommandContext& ctx);
CommandResult handleVscextApiDiagnostics(const CommandContext& ctx);
CommandResult handleVscextApiExportConfig(const CommandContext& ctx);
CommandResult handleVscextApiExtensions(const CommandContext& ctx);
CommandResult handleVscextApiListCommands(const CommandContext& ctx);
CommandResult handleVscextApiListProviders(const CommandContext& ctx);
CommandResult handleVscextApiLoadNative(const CommandContext& ctx);
CommandResult handleVscextApiReload(const CommandContext& ctx);
CommandResult handleVscextApiStats(const CommandContext& ctx);
CommandResult handleVscextApiStatus(const CommandContext& ctx);

#endif // RAWRXD_AUTO_FEATURE_REGISTRY_HPP
