#include "feature_handlers.h"

#include <string>
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

namespace {
CommandResult linkGapHandler(const CommandContext& ctx, const char* name) {
    if (ctx.isGui && ctx.hwnd != nullptr) {
        PostMessageA(reinterpret_cast<HWND>(ctx.hwnd), WM_COMMAND, static_cast<WPARAM>(ctx.commandId), 0);
    }
    if (ctx.outputFn != nullptr) {
        std::string msg = std::string("[SSOT link-gap] fallback handler executed: ") + name + "\\n";
        ctx.output(msg.c_str());
    }
    return CommandResult::ok(name);
}
} // namespace

#define DEFINE_LINK_GAP_HANDLER(name) \
CommandResult name(const CommandContext& ctx) { return linkGapHandler(ctx, #name); }

DEFINE_LINK_GAP_HANDLER(handleAuditCheckMenus)
DEFINE_LINK_GAP_HANDLER(handleAuditDetectStubs)
DEFINE_LINK_GAP_HANDLER(handleAuditExportReport)
DEFINE_LINK_GAP_HANDLER(handleAuditQuickStats)
DEFINE_LINK_GAP_HANDLER(handleAuditRunFull)
DEFINE_LINK_GAP_HANDLER(handleAuditRunTests)
DEFINE_LINK_GAP_HANDLER(handleAutonomyMemory)
DEFINE_LINK_GAP_HANDLER(handleAutonomyStatus)
DEFINE_LINK_GAP_HANDLER(handleDecompCopyAll)
DEFINE_LINK_GAP_HANDLER(handleDecompCopyLine)
DEFINE_LINK_GAP_HANDLER(handleDecompFindRefs)
DEFINE_LINK_GAP_HANDLER(handleDecompGotoAddr)
DEFINE_LINK_GAP_HANDLER(handleDecompGotoDef)
DEFINE_LINK_GAP_HANDLER(handleDecompRenameVar)
DEFINE_LINK_GAP_HANDLER(handleEditCopyFormat)
DEFINE_LINK_GAP_HANDLER(handleEditFindNext)
DEFINE_LINK_GAP_HANDLER(handleEditFindPrev)
DEFINE_LINK_GAP_HANDLER(handleEditGotoLine)
DEFINE_LINK_GAP_HANDLER(handleEditMulticursorAdd)
DEFINE_LINK_GAP_HANDLER(handleEditMulticursorRemove)
DEFINE_LINK_GAP_HANDLER(handleEditPastePlain)
DEFINE_LINK_GAP_HANDLER(handleEditSnippet)
DEFINE_LINK_GAP_HANDLER(handleFileCloseFolder)
DEFINE_LINK_GAP_HANDLER(handleFileCloseTab)
DEFINE_LINK_GAP_HANDLER(handleFileExit)
DEFINE_LINK_GAP_HANDLER(handleFileNewWindow)
DEFINE_LINK_GAP_HANDLER(handleFileOpenFolder)
DEFINE_LINK_GAP_HANDLER(handleFileRecentClear)
DEFINE_LINK_GAP_HANDLER(handleGauntletExport)
DEFINE_LINK_GAP_HANDLER(handleGauntletRun)
DEFINE_LINK_GAP_HANDLER(handleHelpSearch)
DEFINE_LINK_GAP_HANDLER(handleHotpatchByteSearch)
DEFINE_LINK_GAP_HANDLER(handleHotpatchPresetLoad)
DEFINE_LINK_GAP_HANDLER(handleHotpatchPresetSave)
DEFINE_LINK_GAP_HANDLER(handleHotpatchProxyBias)
DEFINE_LINK_GAP_HANDLER(handleHotpatchProxyRewrite)
DEFINE_LINK_GAP_HANDLER(handleHotpatchProxyTerminate)
DEFINE_LINK_GAP_HANDLER(handleHotpatchProxyValidate)
DEFINE_LINK_GAP_HANDLER(handleHotpatchResetStats)
DEFINE_LINK_GAP_HANDLER(handleHotpatchServerRemove)
DEFINE_LINK_GAP_HANDLER(handleHotpatchToggleAll)
DEFINE_LINK_GAP_HANDLER(handlePdbCacheClear)
DEFINE_LINK_GAP_HANDLER(handlePdbEnable)
DEFINE_LINK_GAP_HANDLER(handlePdbExports)
DEFINE_LINK_GAP_HANDLER(handlePdbFetch)
DEFINE_LINK_GAP_HANDLER(handlePdbIatStatus)
DEFINE_LINK_GAP_HANDLER(handlePdbImports)
DEFINE_LINK_GAP_HANDLER(handlePdbLoad)
DEFINE_LINK_GAP_HANDLER(handlePdbResolve)
DEFINE_LINK_GAP_HANDLER(handlePdbStatus)
DEFINE_LINK_GAP_HANDLER(handleQwAlertResourceStatus)
DEFINE_LINK_GAP_HANDLER(handleQwBackupAutoToggle)
DEFINE_LINK_GAP_HANDLER(handleQwBackupCreate)
DEFINE_LINK_GAP_HANDLER(handleQwBackupList)
DEFINE_LINK_GAP_HANDLER(handleQwBackupPrune)
DEFINE_LINK_GAP_HANDLER(handleQwBackupRestore)
DEFINE_LINK_GAP_HANDLER(handleQwShortcutEditor)
DEFINE_LINK_GAP_HANDLER(handleQwShortcutReset)
DEFINE_LINK_GAP_HANDLER(handleQwSloDashboard)
DEFINE_LINK_GAP_HANDLER(handleSwarmBuildCmake)
DEFINE_LINK_GAP_HANDLER(handleSwarmBuildSources)
DEFINE_LINK_GAP_HANDLER(handleSwarmCacheClear)
DEFINE_LINK_GAP_HANDLER(handleSwarmCacheStatus)
DEFINE_LINK_GAP_HANDLER(handleSwarmCancelBuild)
DEFINE_LINK_GAP_HANDLER(handleSwarmRemoveNode)
DEFINE_LINK_GAP_HANDLER(handleSwarmResetStats)
DEFINE_LINK_GAP_HANDLER(handleSwarmStartBuild)
DEFINE_LINK_GAP_HANDLER(handleSwarmStartHybrid)
DEFINE_LINK_GAP_HANDLER(handleSwarmStartLeader)
DEFINE_LINK_GAP_HANDLER(handleSwarmStartWorker)
DEFINE_LINK_GAP_HANDLER(handleSwarmWorkerConnect)
DEFINE_LINK_GAP_HANDLER(handleSwarmWorkerDisconnect)
DEFINE_LINK_GAP_HANDLER(handleSwarmWorkerStatus)
DEFINE_LINK_GAP_HANDLER(handleTelemetryClear)
DEFINE_LINK_GAP_HANDLER(handleTelemetryExportCsv)
DEFINE_LINK_GAP_HANDLER(handleTelemetryExportJson)
DEFINE_LINK_GAP_HANDLER(handleTelemetrySnapshot)
DEFINE_LINK_GAP_HANDLER(handleTelemetryToggle)
DEFINE_LINK_GAP_HANDLER(handleTerminalSplitCode)
DEFINE_LINK_GAP_HANDLER(handleThemeAbyss)
DEFINE_LINK_GAP_HANDLER(handleThemeDracula)
DEFINE_LINK_GAP_HANDLER(handleThemeHighContrast)
DEFINE_LINK_GAP_HANDLER(handleThemeLightPlus)
DEFINE_LINK_GAP_HANDLER(handleThemeMonokai)
DEFINE_LINK_GAP_HANDLER(handleThemeNord)
DEFINE_LINK_GAP_HANDLER(handleToolsBuild)
DEFINE_LINK_GAP_HANDLER(handleToolsCommandPalette)
DEFINE_LINK_GAP_HANDLER(handleToolsDebug)
DEFINE_LINK_GAP_HANDLER(handleToolsExtensions)
DEFINE_LINK_GAP_HANDLER(handleToolsSettings)
DEFINE_LINK_GAP_HANDLER(handleToolsTerminal)
DEFINE_LINK_GAP_HANDLER(handleViewFloatingPanel)
DEFINE_LINK_GAP_HANDLER(handleViewMinimap)
DEFINE_LINK_GAP_HANDLER(handleViewModuleBrowser)
DEFINE_LINK_GAP_HANDLER(handleViewOutputPanel)
DEFINE_LINK_GAP_HANDLER(handleViewOutputTabs)
DEFINE_LINK_GAP_HANDLER(handleViewSidebar)
DEFINE_LINK_GAP_HANDLER(handleViewTerminal)
DEFINE_LINK_GAP_HANDLER(handleViewThemeEditor)
DEFINE_LINK_GAP_HANDLER(handleViewToggleFullscreen)
DEFINE_LINK_GAP_HANDLER(handleViewToggleOutput)
DEFINE_LINK_GAP_HANDLER(handleViewToggleSidebar)
DEFINE_LINK_GAP_HANDLER(handleViewToggleTerminal)
DEFINE_LINK_GAP_HANDLER(handleViewZoomIn)
DEFINE_LINK_GAP_HANDLER(handleViewZoomOut)
DEFINE_LINK_GAP_HANDLER(handleViewZoomReset)
DEFINE_LINK_GAP_HANDLER(handleVoiceAutoNextVoice)
DEFINE_LINK_GAP_HANDLER(handleVoiceAutoPrevVoice)
DEFINE_LINK_GAP_HANDLER(handleVoiceAutoRateDown)
DEFINE_LINK_GAP_HANDLER(handleVoiceAutoRateUp)
DEFINE_LINK_GAP_HANDLER(handleVoiceAutoSettings)
DEFINE_LINK_GAP_HANDLER(handleVoiceAutoStop)
DEFINE_LINK_GAP_HANDLER(handleVoiceAutoToggle)
DEFINE_LINK_GAP_HANDLER(handleVoiceJoinRoom)
DEFINE_LINK_GAP_HANDLER(handleVoiceModeContinuous)
DEFINE_LINK_GAP_HANDLER(handleVoiceModeDisabled)
