# Digest-SourceManifest.ps1
# Scans all source files under src/ and Ship/, extracts features, and writes a manifest.
# Use: .\scripts\Digest-SourceManifest.ps1 [-RepoRoot D:\rawrxd] [-OutDir D:\rawrxd\build] [-Format json|cmake|both]

param(
    [string]$RepoRoot = $PSScriptRoot + "\..",
    [string]$OutDir   = "",
    [ValidateSet("json", "cmake", "both")]
    [string]$Format = "both"
)

$ErrorActionPreference = "Stop"
if (-not $OutDir) { $OutDir = Join-Path $RepoRoot "build" }

$srcDir  = Join-Path $RepoRoot "src"
$shipDir = Join-Path $RepoRoot "Ship"

if (-not (Test-Path $srcDir)) {
    Write-Error "src not found: $srcDir"
}

$extensions = @("*.cpp", "*.h", "*.hpp")
$allFiles   = @()
foreach ($dir in @($srcDir, $shipDir)) {
    if (-not (Test-Path $dir)) { continue }
    $allFiles += Get-ChildItem -Path $dir -Recurse -Include $extensions -File -ErrorAction SilentlyContinue
}

$total = $allFiles.Count
Write-Host "Digesting $total source files (src + Ship)..." -ForegroundColor Cyan

$manifest = @{
    generated = (Get-Date -Format "o")
    repoRoot  = $RepoRoot
    totalFiles = $total
    byExtension = @{ cpp = 0; h = 0; hpp = 0 }
    byRoot     = @{ src = 0; Ship = 0 }
    modules    = @{}
    files      = @()
}

$cmakeList = New-Object System.Collections.ArrayList

foreach ($f in $allFiles) {
    $relPath = $f.FullName.Substring($RepoRoot.Length).TrimStart("\", "/")
    $ext     = $f.Extension.TrimStart(".")
    if ($manifest.byExtension.ContainsKey($ext)) { $manifest.byExtension[$ext]++ }
    $root = if ($f.FullName.StartsWith($srcDir)) { "src" } else { "Ship" }
    $manifest.byRoot[$root]++

    # Module = first path segment under src or Ship (e.g. src/agentic -> agentic, Ship -> Ship)
    $parts = $relPath -split [regex]::Escape([IO.Path]::DirectorySeparatorChar)
    $module = if ($parts.Length -ge 2) { $parts[1] } else { $parts[0] }
    if (-not $manifest.modules.ContainsKey($module)) { $manifest.modules[$module] = 0 }
    $manifest.modules[$module]++

    $lines = Get-Content -LiteralPath $f.FullName -ErrorAction SilentlyContinue
    $lineCount = if ($lines) { $lines.Count } else { 0 }
    $includes = @()
    $namespaces = @()
    foreach ($line in $lines) {
        $t = $line.Trim()
        if ($t -match '^\s*#\s*include\s+[<"]([^>"]+)[>"]') { $includes += $Matches[1] }
        if ($t -match '^\s*namespace\s+(\w+)\s*\{') { $namespaces += $Matches[1] }
    }

    $entry = @{
        path      = $relPath
        fullPath  = $f.FullName
        extension = $ext
        module    = $module
        root      = $root
        lineCount = $lineCount
        includes  = $includes
        namespaces = $namespaces
    }
    $manifest.files += $entry

    $cmakePath = $relPath -replace "\\", "/"
    [void]$cmakeList.Add("  ${cmakePath}")
}

# Ensure output directory exists
$null = New-Item -ItemType Directory -Path $OutDir -Force -ErrorAction SilentlyContinue

if ($Format -eq "json" -or $Format -eq "both") {
    $jsonPath = Join-Path $OutDir "source_manifest.json"
    $manifest | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonPath -Encoding UTF8
    Write-Host "  Wrote $jsonPath" -ForegroundColor Green
}

if ($Format -eq "cmake" -or $Format -eq "both") {
    $cmakePath = Join-Path $OutDir "RAWRXD_SOURCE_LIST.cmake"
    $header = @"
# RAWRXD_SOURCE_LIST.cmake - Generated by Digest-SourceManifest.ps1
# Total: $total files (src + Ship). Do not edit by hand.
set(RAWRXD_ALL_SOURCES
$($cmakeList -join "`n")
)
list(LENGTH RAWRXD_ALL_SOURCES RAWRXD_SOURCE_COUNT)
message(STATUS "[Manifest] RAWRXD_SOURCE_COUNT = \${RAWRXD_SOURCE_COUNT}")
"@
    $header | Set-Content -Path $cmakePath -Encoding UTF8
    Write-Host "  Wrote $cmakePath" -ForegroundColor Green
}

# Summary
Write-Host "`nManifest summary:" -ForegroundColor Cyan
Write-Host "  Total: $total files" -ForegroundColor White
Write-Host "  .cpp: $($manifest.byExtension.cpp)  .h: $($manifest.byExtension.h)  .hpp: $($manifest.byExtension.hpp)" -ForegroundColor White
Write-Host "  src: $($manifest.byRoot.src)  Ship: $($manifest.byRoot.Ship)" -ForegroundColor White
Write-Host "  Top modules: $(($manifest.modules.GetEnumerator() | Sort-Object Value -Descending | Select-Object -First 8 | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join ", ")" -ForegroundColor White
Write-Host "  Output: $OutDir" -ForegroundColor White

exit 0
