import sys
import hashlib
import os

def derive_silicon_key(cpu_vendor, cpu_ext_features, pci_gpu_id):
    """
    Derive the 256-bit Titan Key from hardware IDs.
    Matches the derivation logic in security_identity.asm.
    """
    # Simulate the hardware entropy mix
    # CPU_VENDOR: "AuthenticAMD"
    # CPU_EXT_FEATURES: 0x10000 (AVX512F set)
    # PCI_GPU_ID: 1002747E (RX 7800 XT)
    
    entropy_pool = f"{cpu_vendor}_{cpu_ext_features:08x}_{pci_gpu_id:08x}".encode('utf-8')
    titan_hash = hashlib.sha256(entropy_pool).digest()
    return titan_hash

def encrypt_winmain_blob(input_file, output_file, key):
    """
    Encrypt the WinMain entry point blob using the derived Silicon Key.
    """
    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found.")
        return False
        
    with open(input_file, "rb") as f:
        plaintext = f.read()
        
    # Simplified XOR stream encryption (Matches ASM xor_loop)
    # In a full deployment, this would be AES-256-GCM.
    ciphertext = bytearray()
    for i in range(len(plaintext)):
        # Cycles through the 32-byte hash
        ciphertext.append(plaintext[i] ^ key[i % 32])
        
    with open(output_file, "wb") as f:
        f.write(ciphertext)
    
    print(f"Sovereign Encryption Complete: {output_file} is now Silicon-Locked.")
    return True

if __name__ == "__main__":
    # Example Hardware Configuration
    CPU_VENDOR = "AuthenticAMD"
    CPU_EXT_FEATURES = 0x10000 # AVX512F
    PCI_GPU_ID = 0x1002747E
    
    titan_key = derive_silicon_key(CPU_VENDOR, CPU_EXT_FEATURES, PCI_GPU_ID)
    
    # Target files (Assumes winmain_stub.bin is generated by the build as a raw code blob)
    encrypt_winmain_blob("bin/winmain_raw.bin", "src/core/winmain_locked.bin", titan_key)
