# EXTENSION ECOSYSTEM CONSOLIDATION HAMMER
# Fixes undefined publishers, generates enterprise manifests, wires unified agentic IDE

$ErrorActionPreference = "Stop"
$extensions = @{
    "cursor-simple-ai"       = @{ "pub" = "ItsMehRAWRXD"; "type" = "ai";    "deps" = @() }
    "rawrz-agentic"          = @{ "pub" = "rawrz-underground"; "type" = "agent"; "deps" = @("cursor-simple-ai") }
    "rawrxd-lsp-client"       = @{ "pub" = "ItsMehRAWRXD"; "type" = "lsp";  "deps" = @() }
    "cursor-ollama-proxy"     = @{ "pub" = "ItsMehRAWRXD"; "type" = "proxy"; "deps" = @() }
    "cursor-multi-ai"        = @{ "pub" = "ItsMehRAWRXD"; "type" = "ai";   "deps" = @("cursor-simple-ai") }
    "bigdaddyg-copilot"       = @{ "pub" = "bigdaddyg"; "type" = "copilot"; "deps" = @("cursor-multi-ai", "rawrxd-lsp-client") }
    "bigdaddyg-cursor-chat"   = @{ "pub" = "bigdaddyg"; "type" = "chat";   "deps" = @("bigdaddyg-copilot") }
    "bigdaddyg-asm-ide"       = @{ "pub" = "bigdaddyg"; "type" = "ide";   "deps" = @("rawrxd-lsp-client", "bigdaddyg-copilot") }
    "bigdaddyg-asm-extension" = @{ "pub" = "bigdaddyg"; "type" = "lang";  "deps" = @() }
}

$basePath = "D:\rawrxd\extensions"
if (-not (Split-Path -IsAbsolute $basePath)) { $basePath = Join-Path $PSScriptRoot "..\extensions" }
New-Item -ItemType Directory -Force -Path $basePath | Out-Null

foreach ($entry in $extensions.GetEnumerator()) {
    $name = $entry.Key
    $cfg = $entry.Value
    $extId = "$($cfg.pub).$name"
    $extPath = Join-Path $basePath $extId
    New-Item -ItemType Directory -Force -Path $extPath | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $extPath "src") | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $extPath "out") | Out-Null

    $extensionDeps = $cfg.deps | ForEach-Object {
        $depCfg = $extensions[$_]
        "$($depCfg.pub).$_"
    }

    $manifest = @{
        name               = $name
        publisher          = $cfg.pub
        version            = "14.2.0"
        engines            = @{ vscode = "^1.90.0" }
        categories         = @("Programming Languages", "Machine Learning", "Debuggers")
        activationEvents   = @("onStartupFinished")
        main               = "./out/extension.js"
        extensionDependencies = @($extensionDeps)
        contributes        = @{
            commands = @(
                @{ command = "$name.activate"; title = "Activate $name"; category = "RawrXD" }
                @{ command = "$name.hammer"; title = "Execute Hammer Protocol"; category = "RawrXD" }
            )
            configuration = @{
                title = $name
                properties = @{
                    "$name.enabled"     = @{ type = "boolean"; default = $true; description = "Enable $name" }
                    "$name.autoConnect" = @{ type = "boolean"; default = $true; description = "Auto-connect to RawrXD core" }
                }
            }
            views = @{
                explorer = @(@{ id = "$name.view"; name = "$name Agentic Panel"; when = "rawrxd.enabled" })
            }
        }
        scripts = @{
            compile  = "tsc -p ./"
            watch    = "tsc -watch -p ./"
            package  = "vsce package"
        }
        devDependencies = @{
            "@types/vscode" = "^1.90.0"
            typescript      = "^5.4.0"
            vsce            = "^2.15.0"
        }
    }

    $manifestJson = $manifest | ConvertTo-Json -Depth 10
    [System.IO.File]::WriteAllText((Join-Path $extPath "package.json"), $manifestJson)

    $tsStub = @"
// Auto-generated by Extension Hammer v14.2.0
import * as vscode from 'vscode';
import { spawn } from 'child_process';
import { join } from 'path';

const EXT_ID = '$extId';
const HAMMER_PATH = 'D:\\rawrxd\\build_prod\\RawrXD_Agent.exe';

export function activate(context: vscode.ExtensionContext) {
    const output = vscode.window.createOutputChannel('$name');
    output.appendLine('[RawrXD] Extension Hammer Activated: $name');

    // Wire to MASM64 backend via named pipe (when RawrXD_Agent exists)
    let pipe: ReturnType<typeof spawn> | null = null;
    try {
        pipe = spawn(HAMMER_PATH, ['--extension-pipe', EXT_ID], { detached: true, stdio: ['pipe', 'ignore', 'ignore'] });
    } catch {
        output.appendLine('[RawrXD] Backend not found - run RawrXD IDE to enable pipe.');
    }

    context.subscriptions.push(
        vscode.commands.registerCommand('$name.activate', () => {
            vscode.window.showInformationMessage('$name: Connected to RawrXD Core');
            pipe?.stdin?.write('INIT:$name\n');
        }),

        vscode.commands.registerCommand('$name.hammer', () => {
            pipe?.stdin?.write('HAMMER:EXECUTE\n');
            output.appendLine('Hammer protocol executed');
        })
    );

    if (vscode.workspace.getConfiguration(EXT_ID).get('autoConnect') && pipe?.stdin) {
        setTimeout(() => pipe.stdin?.write('AUTOCONNECT\n'), 1000);
    }
}

export function deactivate() {
    // Cleanup MASM64 connections
}
"@
    [System.IO.File]::WriteAllText((Join-Path $extPath "src\extension.ts"), $tsStub)

    $tsconfig = @{
        compilerOptions = @{
            module   = "commonjs"
            target   = "ES2020"
            lib      = @("ES2020")
            outDir   = "./out"
            rootDir  = "./src"
            strict   = $true
        }
        exclude = @("node_modules", ".vscode-test")
    }
    [System.IO.File]::WriteAllText((Join-Path $extPath "tsconfig.json"), ($tsconfig | ConvertTo-Json -Depth 5))

    Write-Host "  Generated: $extId" -ForegroundColor Green
}

# Extension Pack (Unified RawrXD Distribution)
$packPath = Join-Path $basePath "ItsMehRAWRXD.rawrxd-complete-pack"
New-Item -ItemType Directory -Force -Path $packPath | Out-Null
$packList = $extensions.GetEnumerator() | ForEach-Object { "$($_.Value.pub).$($_.Key)" }
$packManifest = @{
    name           = "rawrxd-complete-pack"
    publisher      = "ItsMehRAWRXD"
    version        = "14.2.0"
    displayName    = "RawrXD Complete Agentic IDE"
    description    = "Complete MASM64 AI IDE with Copilot, LSP, and Ollama Proxy"
    extensionPack  = @($packList)
}
[System.IO.File]::WriteAllText((Join-Path $packPath "package.json"), ($packManifest | ConvertTo-Json -Depth 5))
Write-Host "  Pack: ItsMehRAWRXD.rawrxd-complete-pack" -ForegroundColor Cyan

# Build script
$buildScript = @'
# Extension Build Pipeline - compile all extensions
param([switch]$Install, [switch]$Publish)

$base = "D:\rawrxd\extensions"
if ($env:RAWRXD_EXT_BASE) { $base = $env:RAWRXD_EXT_BASE }

$exts = @(
    "ItsMehRAWRXD.cursor-simple-ai",
    "rawrz-underground.rawrz-agentic",
    "ItsMehRAWRXD.rawrxd-lsp-client",
    "ItsMehRAWRXD.cursor-ollama-proxy",
    "ItsMehRAWRXD.cursor-multi-ai",
    "bigdaddyg.bigdaddyg-copilot",
    "bigdaddyg.bigdaddyg-cursor-chat",
    "bigdaddyg.bigdaddyg-asm-ide",
    "bigdaddyg.bigdaddyg-asm-extension"
)

foreach ($id in $exts) {
    $dir = Join-Path $base $id
    if (-not (Test-Path $dir)) {
        Write-Host "Skip (missing): $id" -ForegroundColor Yellow
        continue
    }
    Write-Host "Building $id..." -ForegroundColor Cyan
    Push-Location $dir
    try {
        npm install 2>$null
        npx tsc 2>$null
        npx vsce package --no-dependencies 2>$null
        if ($Install) {
            $vsix = Get-ChildItem -Filter "*.vsix" | Select-Object -First 1
            if ($vsix) { code --install-extension $vsix.FullName --force }
        }
    } finally {
        Pop-Location
    }
}

if ($Publish) {
    foreach ($id in $exts) {
        $dir = Join-Path $base $id
        if (Test-Path $dir) {
            Push-Location $dir
            npx vsce publish --pat $env:VSCE_PAT
            Pop-Location
        }
    }
}

Write-Host "Done." -ForegroundColor Green
'@
[System.IO.File]::WriteAllText((Join-Path $basePath "BUILD_ALL_EXTENSIONS.ps1"), $buildScript)

Write-Host ""
Write-Host "EXTENSION ECOSYSTEM HAMMERED" -ForegroundColor Magenta
Write-Host "  Extensions: 9 packages" -ForegroundColor Gray
Write-Host "  Pack: ItsMehRAWRXD.rawrxd-complete-pack" -ForegroundColor Gray
Write-Host ""
Write-Host "RUN:  .\extensions\BUILD_ALL_EXTENSIONS.ps1 -Install" -ForegroundColor Yellow
