#!/usr/bin/env python3
"""
Generate the Win32 IDE Source File menu registry and C++ builder.

Scans the entire repo, categorizes every source file, and produces:
  1. src/win32app/SourceFileRegistry.h   — IDM constants + file path table
  2. src/win32app/SourceFileRegistry.cpp  — menu builder + WM_COMMAND handler

Every file gets a menu item under Source Files > <Category> > <Subcategory> ...
Clicking an item opens it in the editor via openFileInEditor().
"""

import os
import sys
import json
from pathlib import Path
from collections import defaultdict

REPO_ROOT = Path(__file__).resolve().parent.parent

SKIP_DIRS = {".git", "node_modules", "3rdparty", ".vs", "__pycache__",
             "build", "build2_clean", "build_clean2", "build_fix",
             "build_gold", "build_ide", "out", "dist"}

SOURCE_EXTS = {
    ".cpp", ".c", ".h", ".hpp", ".asm", ".inc",
    ".py", ".ps1", ".psm1", ".js", ".sh", ".bat",
    ".cmake", ".html", ".json", ".yml", ".yaml",
}

# IDM base — source file menu items start at 60000
IDM_BASE = 60000


def scan_files():
    files = []
    for root, dirs, fnames in os.walk(REPO_ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fname in sorted(fnames):
            ext = os.path.splitext(fname)[1].lower()
            if ext not in SOURCE_EXTS:
                continue
            full = os.path.join(root, fname)
            rel = os.path.relpath(full, REPO_ROOT).replace("\\", "/")
            files.append(rel)
    return sorted(files)


def build_tree(files):
    tree = {}
    for f in files:
        parts = f.split("/")
        node = tree
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = f  # leaf = full relative path
    return tree


def escape_cpp_string(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate_header(files):
    lines = [
        "#pragma once",
        "// Auto-generated by scripts/generate_source_menu.py",
        "// Source File Registry — maps every repo file to a Win32 menu item",
        "",
        "#include <windows.h>",
        "#include <string>",
        "#include <unordered_map>",
        "",
        f"#define IDM_SRCFILE_BASE {IDM_BASE}",
        f"#define IDM_SRCFILE_COUNT {len(files)}",
        f"#define IDM_SRCFILE_MAX  {IDM_BASE + len(files) - 1}",
        "",
        "// Returns true if cmdId is a source-file menu item",
        "inline bool IsSourceFileCommand(UINT cmdId) {",
        f"    return cmdId >= {IDM_BASE} && cmdId <= {IDM_BASE + len(files) - 1};",
        "}",
        "",
        "// Get the relative file path for a source-file command ID",
        "const wchar_t* GetSourceFilePath(UINT cmdId);",
        "",
        "// Build the Source Files popup menu hierarchy",
        "HMENU BuildSourceFileMenu();",
        "",
        "// Total source files registered",
        f"constexpr int SRCFILE_TOTAL = {len(files)};",
        "",
    ]
    return "\n".join(lines) + "\n"


def _emit_menu_tree(tree, lines, idm_counter, depth=0):
    """Recursively emit menu building code for the tree."""
    indent = "    " * (depth + 1)
    
    # Separate subdirs from files
    subdirs = {k: v for k, v in sorted(tree.items()) if isinstance(v, dict)}
    leaves = {k: v for k, v in sorted(tree.items()) if isinstance(v, str)}
    
    for dirname, subtree in subdirs.items():
        var = f"hSub_{depth}_{idm_counter[0]}"
        lines.append(f"{indent}HMENU {var} = CreatePopupMenu();")
        idm_counter[0] = _emit_menu_tree(subtree, lines, idm_counter, depth + 1)
        safe_name = dirname.replace("&", "&&")
        lines.append(f'{indent}AppendMenuW(hParent{"" if depth == 0 else f"_{depth}"}, MF_POPUP, (UINT_PTR){var}, L"{escape_cpp_string(safe_name)}");')
    
    for fname, relpath in leaves:
        idm = idm_counter[0]
        safe_label = fname.replace("&", "&&")
        lines.append(f'{indent}AppendMenuW(hParent{"" if depth == 0 else f"_{depth}"}, MF_STRING, {idm}, L"{escape_cpp_string(safe_label)}");')
        idm_counter[0] = idm + 1
    
    return idm_counter[0]


def generate_cpp(files, tree):
    lines = [
        "// Auto-generated by scripts/generate_source_menu.py",
        "// Source File Registry — every file in the repo mapped to a Win32 menu item",
        "",
        '#include "SourceFileRegistry.h"',
        "",
        "// Path table — indexed by (cmdId - IDM_SRCFILE_BASE)",
        f"static const wchar_t* s_paths[{len(files)}] = {{",
    ]
    
    for f in files:
        lines.append(f'    L"{escape_cpp_string(f)}",')
    
    lines.append("};")
    lines.append("")
    lines.append("const wchar_t* GetSourceFilePath(UINT cmdId) {")
    lines.append("    if (!IsSourceFileCommand(cmdId)) return nullptr;")
    lines.append("    return s_paths[cmdId - IDM_SRCFILE_BASE];")
    lines.append("}")
    lines.append("")
    
    # Build the menu construction function using iterative approach
    lines.append("HMENU BuildSourceFileMenu() {")
    lines.append("    HMENU hRoot = CreatePopupMenu();")
    lines.append("    if (!hRoot) return nullptr;")
    lines.append("")
    
    idm = IDM_BASE
    
    def emit_node(node, parent_var, depth):
        nonlocal idm, lines
        subdirs_sorted = sorted((k, v) for k, v in node.items() if isinstance(v, dict))
        leaves_sorted = sorted((k, v) for k, v in node.items() if isinstance(v, str))
        
        for dirname, subtree in subdirs_sorted:
            var = f"h_{depth}_{idm}"
            lines.append(f"    HMENU {var} = CreatePopupMenu();")
            emit_node(subtree, var, depth + 1)
            safe = escape_cpp_string(dirname.replace("&", "&&"))
            lines.append(f'    AppendMenuW({parent_var}, MF_POPUP, (UINT_PTR){var}, L"{safe}");')
        
        for fname, relpath in leaves_sorted:
            safe = escape_cpp_string(fname.replace("&", "&&"))
            lines.append(f'    AppendMenuW({parent_var}, MF_STRING, {idm}, L"{safe}");')
            idm += 1
    
    emit_node(tree, "hRoot", 0)
    
    lines.append("")
    lines.append("    return hRoot;")
    lines.append("}")
    lines.append("")
    
    return "\n".join(lines) + "\n"


def main():
    files = scan_files()
    tree = build_tree(files)
    
    hdr_path = REPO_ROOT / "src" / "win32app" / "SourceFileRegistry.h"
    cpp_path = REPO_ROOT / "src" / "win32app" / "SourceFileRegistry.cpp"
    json_path = REPO_ROOT / "config" / "source_file_registry.json"
    
    hdr_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Generate header
    with open(hdr_path, "w", encoding="utf-8") as f:
        f.write(generate_header(files))
    
    # Generate cpp
    with open(cpp_path, "w", encoding="utf-8") as f:
        f.write(generate_cpp(files, tree))
    
    # Generate JSON registry
    registry = [{"id": IDM_BASE + i, "path": fp} for i, fp in enumerate(files)]
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({"total": len(files), "idm_base": IDM_BASE, "files": registry}, f, indent=2)
    
    print(f"Generated {len(files)} source file entries:")
    print(f"  {hdr_path}")
    print(f"  {cpp_path}")
    print(f"  {json_path}")


if __name__ == "__main__":
    main()
