<#
.SYNOPSIS
    RawrXD Browser Module - Agentic Web Browser with Video Streaming

.DESCRIPTION
    Pure PowerShell browser implementation with autonomous capabilities,
    video streaming support, and integration with RawrXD ecosystem.

.NOTES
    Generated by RawrXD Refactoring System
    Requires WebView2 runtime for full functionality
#>

#region Module Setup
if (-not $PSScriptRoot) {
    $PSScriptRoot = Split-Path -Parent -Path $MyInvocation.MyCommand.Path
}

# Fallback logger if core logging is unavailable
if (-not (Get-Command Write-DevConsole -ErrorAction SilentlyContinue)) {
    function Write-DevConsole {
        param(
            [string]$Message,
            [string]$Level = "INFO"
        )
        Write-Verbose "[$Level] $Message"
    }
}

# Import required types
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
try {
    Add-Type -AssemblyName Microsoft.Web.WebView2.Core -ErrorAction Stop
}
catch {
    Write-Verbose "WebView2.Core assembly not available; WebView2 features disabled."
}
try {
    Add-Type -AssemblyName Microsoft.Web.WebView2.WinForms -ErrorAction Stop
}
catch {
    Write-Verbose "WebView2.WinForms assembly not available; WebView2 features disabled."
}

# Global browser state
$script:BrowserInstances = @{}
$script:VideoStreams = @{}
$script:AgentTasks = [System.Collections.Concurrent.ConcurrentDictionary[string, hashtable]]::new()
$script:WebView2Available = $false

# Check for WebView2 availability
try {
    $webView2Type = [Microsoft.Web.WebView2.WinForms.WebView2]
    if ($webView2Type) {
        $script:WebView2Available = $true
    }
}
catch {
    $script:WebView2Available = $false
}
#endregion

#region Browser Classes
class BrowserAgent {
    [string]$Id
    [object]$Control  # WebView2 or WebBrowser control
    [string]$CurrentUrl
    [bool]$IsLoading
    [bool]$IsVideoPlaying
    [hashtable]$AgentState
    [System.Collections.Generic.List[hashtable]]$TaskQueue

    BrowserAgent([string]$browserId) {
        $this.Id = $browserId
        $this.IsLoading = $false
        $this.IsVideoPlaying = $false
        $this.AgentState = @{}
        $this.TaskQueue = [System.Collections.Generic.List[hashtable]]::new()
    }

    [void]Initialize([object]$parentControl) {
        if ($script:WebView2Available) {
            $this.InitializeWebView2($parentControl)
        }
        else {
            $this.InitializeWebBrowser($parentControl)
        }
    }

    [void]InitializeWebView2([object]$parentControl) {
        try {
            $this.Control = New-Object Microsoft.Web.WebView2.WinForms.WebView2
            $this.Control.CreationProperties = New-Object Microsoft.Web.WebView2.Core.CoreWebView2CreationProperties
            $this.Control.CreationProperties.BrowserExecutableFolder = ""

            # Event handlers
            $this.Control.NavigationStarting += {
                param($sender, $args)
                $this.IsLoading = $true
                Write-DevConsole "🌐 Navigating to: $($args.Uri)" "INFO"
            }

            $this.Control.NavigationCompleted += {
                param($sender, $args)
                $this.IsLoading = $false
                $this.CurrentUrl = $sender.Source.ToString()
                Write-DevConsole "✅ Loaded: $($this.CurrentUrl)" "SUCCESS"
                $this.CheckForVideoContent()
            }

            $this.Control.CoreWebView2InitializationCompleted += {
                param($sender, $args)
                if ($args.IsSuccess) {
                    Write-DevConsole "WebView2 initialized successfully" "SUCCESS"
                }
                else {
                    Write-DevConsole "WebView2 initialization failed: $($args.InitializationException)" "ERROR"
                }
            }

            # Add to parent
            $parentControl.Controls.Add($this.Control)
            $this.Control.EnsureCoreWebView2Async($null)
        }
        catch {
            Write-DevConsole "Failed to initialize WebView2, falling back to WebBrowser: $_" "WARNING"
            $this.InitializeWebBrowser($parentControl)
        }
    }

    [void]InitializeWebBrowser([object]$parentControl) {
            $this.Control = New-Object System.Windows.Forms.WebBrowser
            $this.Control.ScriptErrorsSuppressed = $true
            $this.Control.Dock = "Fill"

        # Event handlers
        $this.Control.Navigating += {
            param($sender, $args)
            $this.IsLoading = $true
            Write-DevConsole "🌐 Navigating to: $($args.Url)" "INFO"
        }

        $this.Control.DocumentCompleted += {
            param($sender, $args)
            $this.IsLoading = $false
            $this.CurrentUrl = $args.Url.ToString()
            Write-DevConsole "✅ Loaded: $($this.CurrentUrl)" "SUCCESS"
            $this.CheckForVideoContent()
        }

        # Add to parent
        $parentControl.Controls.Add($this.Control)
    }

    [void]Navigate([string]$url) {
        if ($this.IsLoading) {
            Write-DevConsole "Browser is currently loading, queuing navigation..." "WARNING"
            $this.TaskQueue.Add(@{ Action = "Navigate"; Url = $url })
            return
        }

        try {
            $this.Control.Navigate($url)
        }
        catch {
            Write-DevConsole "Navigation failed: $_" "ERROR"
        }
    }

    [void]ExecuteScript([string]$script) {
        try {
            if ($script:WebView2Available -and $this.Control.GetType().Name -eq "WebView2") {
                $this.Control.ExecuteScriptAsync($script)
            }
            elseif ($this.Control.Document) {
                $this.Control.Document.InvokeScript("eval", @($script))
            }
        }
        catch {
            Write-DevConsole "Script execution failed: $_" "ERROR"
        }
    }

    [void]CheckForVideoContent() {
        $videoCheckScript = @"
(function() {
    var videos = document.querySelectorAll('video');
    if (videos.length > 0) {
        console.log('Found ' + videos.length + ' video elements');
        return {
            count: videos.length,
            playing: Array.from(videos).some(v => !v.paused)
        };
    }
    return { count: 0, playing: false };
})();
"@

        $result = $this.ExecuteScript($videoCheckScript)
        if ($result) {
            $videoInfo = $result | ConvertFrom-Json
            if ($videoInfo.count -gt 0) {
                Write-DevConsole "🎬 Found $($videoInfo.count) video element(s)" "INFO"
                if ($videoInfo.playing) {
                    $this.IsVideoPlaying = $true
                    Write-DevConsole "▶️ Video is currently playing" "SUCCESS"
                }
            }
        }
    }

    [void]PlayVideo() {
        $playScript = @"
(function() {
    var videos = document.querySelectorAll('video');
    for (var i = 0; i < videos.length; i++) {
        videos[i].play();
    }
    return videos.length;
})();
"@

        $result = $this.ExecuteScript($playScript)
        if ($result -gt 0) {
            $this.IsVideoPlaying = $true
            Write-DevConsole "▶️ Started playback for $result video(s)" "SUCCESS"
        }
        else {
            Write-DevConsole "❌ No videos found to play" "WARNING"
        }
    }

    [void]PauseVideo() {
        $pauseScript = @"
(function() {
    var videos = document.querySelectorAll('video');
    for (var i = 0; i < videos.length; i++) {
        videos[i].pause();
    }
    return videos.length;
})();
"@

        $result = $this.ExecuteScript($pauseScript)
        if ($result -gt 0) {
            $this.IsVideoPlaying = $false
            Write-DevConsole "⏸️ Paused $result video(s)" "SUCCESS"
        }
        else {
            Write-DevConsole "❌ No videos found to pause" "WARNING"
        }
    }

    [void]TakeScreenshot([string]$outputPath) {
        try {
            # Use WebBrowser's built-in screenshot capability or external tool
            Write-DevConsole "📸 Screenshot capability not implemented in pure PowerShell" "WARNING"
            Write-DevConsole "Consider using external tools like Selenium for screenshots" "INFO"
        }
        catch {
            Write-DevConsole "Screenshot failed: $_" "ERROR"
        }
    }

    [void]ClickElement([string]$selector) {
        $clickScript = @"
(function() {
    var element = document.querySelector('$selector');
    if (element) {
        element.click();
        return true;
    }
    return false;
})();
"@

        $result = $this.ExecuteScript($clickScript)
        if ($result) {
            Write-DevConsole "👆 Clicked element: $selector" "SUCCESS"
        }
        else {
            Write-DevConsole "❌ Element not found: $selector" "ERROR"
        }
    }

    [void]FillForm([string]$selector, [string]$value) {
        $fillScript = @"
(function() {
    var element = document.querySelector('$selector');
    if (element) {
        element.value = '$value';
        return true;
    }
    return false;
})();
"@

        $result = $this.ExecuteScript($fillScript)
        if ($result) {
            Write-DevConsole "✏️ Filled form element: $selector" "SUCCESS"
        }
        else {
            Write-DevConsole "❌ Form element not found: $selector" "ERROR"
        }
    }

    [string]GetPageTitle() {
        $titleScript = @"
(function() {
    return document.title;
})();
"@

        $result = $this.ExecuteScript($titleScript)
        return $result
    }

    [string]GetPageText() {
        $textScript = @"
(function() {
    return document.body.innerText;
})();
"@

        $result = $this.ExecuteScript($textScript)
        return $result
    }
}

class AgentTask {
    [string]$Id
    [string]$Type
    [hashtable]$Parameters
    [scriptblock]$Action
    [datetime]$Created
    [datetime]$LastRun
    [int]$RunCount
    [bool]$IsActive

    AgentTask([string]$taskId, [string]$taskType) {
        $this.Id = $taskId
        $this.Type = $taskType
        $this.Parameters = @{}
        $this.Created = Get-Date
        $this.LastRun = [DateTime]::MinValue
        $this.RunCount = 0
        $this.IsActive = $true
    }

    [void]Execute([BrowserAgent]$browser) {
        try {
            $this.LastRun = Get-Date
            $this.RunCount++

            Write-DevConsole "🤖 Executing agent task: $($this.Id)" "INFO"

            switch ($this.Type) {
                "Navigate" {
                    $browser.Navigate($this.Parameters.Url)
                }
                "Click" {
                    $browser.ClickElement($this.Parameters.Selector)
                }
                "FillForm" {
                    $browser.FillForm($this.Parameters.Selector, $this.Parameters.Value)
                }
                "PlayVideo" {
                    $browser.PlayVideo()
                }
                "PauseVideo" {
                    $browser.PauseVideo()
                }
                "Screenshot" {
                    $browser.TakeScreenshot($this.Parameters.OutputPath)
                }
                "CustomScript" {
                    $browser.ExecuteScript($this.Parameters.Script)
                }
                default {
                    Write-DevConsole "Unknown task type: $($this.Type)" "WARNING"
                }
            }

            Write-DevConsole "✅ Agent task completed: $($this.Id)" "SUCCESS"
        }
        catch {
            Write-DevConsole "❌ Agent task failed: $($this.Id) - $_" "ERROR"
        }
    }
}
#endregion

#region Public Functions
function New-BrowserAgent {
    <#
    .SYNOPSIS
        Creates a new browser agent instance

    .PARAMETER Id
        Unique identifier for the browser agent

    .PARAMETER ParentControl
        Parent control to host the browser

    .EXAMPLE
        $agent = New-BrowserAgent -Id "main" -ParentControl $panel
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$Id,

        [Parameter(Mandatory = $true)]
        [object]$ParentControl
    )

    $agent = [BrowserAgent]::new($Id)
    $agent.Initialize($ParentControl)
    $script:BrowserInstances[$Id] = $agent

    Write-DevConsole "🆕 Created browser agent: $Id" "SUCCESS"
    return $agent
}

function Get-BrowserAgent {
    <#
    .SYNOPSIS
        Gets an existing browser agent

    .PARAMETER Id
        Browser agent identifier

    .EXAMPLE
        $agent = Get-BrowserAgent -Id "main"
    #>
    param([string]$Id)

    if ($script:BrowserInstances.ContainsKey($Id)) {
        return $script:BrowserInstances[$Id]
    }
    else {
        Write-DevConsole "Browser agent not found: $Id" "WARNING"
        return $null
    }
}

function Invoke-BrowserNavigation {
    <#
    .SYNOPSIS
        Navigates browser to specified URL

    .PARAMETER AgentId
        Browser agent identifier

    .PARAMETER Url
        URL to navigate to

    .EXAMPLE
        Invoke-BrowserNavigation -AgentId "main" -Url "https://www.youtube.com"
    #>
    param(
        [string]$AgentId,
        [string]$Url
    )

    $agent = Get-BrowserAgent -Id $AgentId
    if ($agent) {
        $agent.Navigate($Url)
    }
}

function Invoke-BrowserVideoControl {
    <#
    .SYNOPSIS
        Controls video playback in browser

    .PARAMETER AgentId
        Browser agent identifier

    .PARAMETER Action
        Action: Play, Pause, Stop

    .EXAMPLE
        Invoke-BrowserVideoControl -AgentId "main" -Action "Play"
    #>
    param(
        [string]$AgentId,
        [ValidateSet("Play", "Pause", "Stop")]
        [string]$Action
    )

    $agent = Get-BrowserAgent -Id $AgentId
    if ($agent) {
        switch ($Action) {
            "Play" { $agent.PlayVideo() }
            "Pause" { $agent.PauseVideo() }
            "Stop" { $agent.PauseVideo() }
        }
    }
}

function Invoke-BrowserScreenshot {
    <#
    .SYNOPSIS
        Takes screenshot of browser content

    .PARAMETER AgentId
        Browser agent identifier

    .PARAMETER OutputPath
        Path to save screenshot

    .EXAMPLE
        Invoke-BrowserScreenshot -AgentId "main" -OutputPath "screenshot.png"
    #>
    param(
        [string]$AgentId,
        [string]$OutputPath
    )

    $agent = Get-BrowserAgent -Id $AgentId
    if ($agent) {
        $agent.TakeScreenshot($OutputPath)
    }
}

function Invoke-BrowserElementInteraction {
    <#
    .SYNOPSIS
        Interacts with browser elements

    .PARAMETER AgentId
        Browser agent identifier

    .PARAMETER Action
        Action type: Click, Fill

    .PARAMETER Selector
        CSS selector for element

    .PARAMETER Value
        Value for fill action

    .EXAMPLE
        Invoke-BrowserElementInteraction -AgentId "main" -Action "Click" -Selector "#play-button"

        Invoke-BrowserElementInteraction -AgentId "main" -Action "Fill" -Selector "#search-input" -Value "PowerShell"
    #>
    param(
        [string]$AgentId,
        [ValidateSet("Click", "Fill")]
        [string]$Action,
        [string]$Selector,
        [string]$Value
    )

    $agent = Get-BrowserAgent -Id $AgentId
    if ($agent) {
        switch ($Action) {
            "Click" { $agent.ClickElement($Selector) }
            "Fill" { $agent.FillForm($Selector, $Value) }
        }
    }
}

function New-AgentTask {
    <#
    .SYNOPSIS
        Creates a new autonomous agent task

    .PARAMETER Id
        Task identifier

    .PARAMETER Type
        Task type

    .PARAMETER Parameters
        Task parameters

    .EXAMPLE
        New-AgentTask -Id "youtube-nav" -Type "Navigate" -Parameters @{ Url = "https://youtube.com" }
    #>
    param(
        [string]$Id,
        [string]$Type,
        [hashtable]$Parameters
    )

    $task = [AgentTask]::new($Id, $Type)
    $task.Parameters = $Parameters
    $script:AgentTasks[$Id] = $task

    Write-DevConsole "📋 Created agent task: $Id ($Type)" "SUCCESS"
    return $task
}

function Invoke-AgentTask {
    <#
    .SYNOPSIS
        Executes an agent task on specified browser

    .PARAMETER TaskId
        Task identifier

    .PARAMETER AgentId
        Browser agent identifier

    .EXAMPLE
        Invoke-AgentTask -TaskId "youtube-nav" -AgentId "main"
    #>
    param(
        [string]$TaskId,
        [string]$AgentId
    )

    $task = $script:AgentTasks[$TaskId]
    $agent = Get-BrowserAgent -Id $AgentId

    if ($task -and $agent) {
        $task.Execute($agent)
    }
    else {
        Write-DevConsole "Task or agent not found: $TaskId, $AgentId" "ERROR"
    }
}

function Start-AgentAutomation {
    <#
    .SYNOPSIS
        Starts autonomous browser automation

    .PARAMETER AgentId
        Browser agent identifier

    .PARAMETER TaskSequence
        Array of task IDs to execute in sequence

    .PARAMETER Interval
        Interval between task executions (seconds)

    .EXAMPLE
        Start-AgentAutomation -AgentId "main" -TaskSequence @("nav-youtube", "play-video") -Interval 5
    #>
    param(
        [string]$AgentId,
        [string[]]$TaskSequence,
        [int]$Interval = 2
    )

    $agent = Get-BrowserAgent -Id $AgentId
    if (-not $agent) {
        Write-DevConsole "Browser agent not found: $AgentId" "ERROR"
        return
    }

    Write-DevConsole "🤖 Starting autonomous automation sequence..." "INFO"

    foreach ($taskId in $TaskSequence) {
        Invoke-AgentTask -TaskId $taskId -AgentId $AgentId
        if ($Interval -gt 0) {
            Start-Sleep -Seconds $Interval
        }
    }

    Write-DevConsole "✅ Automation sequence completed" "SUCCESS"
}

function Get-BrowserInfo {
    <#
    .SYNOPSIS
        Gets information about browser agents

    .EXAMPLE
        Get-BrowserInfo
    #>
    $info = @{
        WebView2Available = $script:WebView2Available
        ActiveAgents = $script:BrowserInstances.Keys
        AgentTasks = $script:AgentTasks.Keys
        VideoStreams = $script:VideoStreams.Keys
    }

    return $info
}

function Initialize-BrowserModule {
    <#
    .SYNOPSIS
        Initializes the browser module

    .EXAMPLE
        Initialize-BrowserModule
    #>
    Write-DevConsole "🔧 Initializing RawrXD Browser Module..." "INFO"
    Write-DevConsole "WebView2 Available: $($script:WebView2Available)" "INFO"
    Write-DevConsole "✅ Browser module ready" "SUCCESS"
}

# Initialize on module load
Initialize-BrowserModule
#endregion

#region Module Export
$ExportFunctions = @(
    'New-BrowserAgent',
    'Get-BrowserAgent',
    'Invoke-BrowserNavigation',
    'Invoke-BrowserVideoControl',
    'Invoke-BrowserScreenshot',
    'Invoke-BrowserElementInteraction',
    'New-AgentTask',
    'Invoke-AgentTask',
    'Start-AgentAutomation',
    'Get-BrowserInfo'
)

Export-ModuleMember -Function $ExportFunctions
#endregion
