#!/usr/bin/env pwsh
# Auto-generated by RawrXD Agentic Build System
# Project: RawrXD-ModelLoader v1.0.13

param(
    [string]$Target = 'all',
    [switch]$Clean,
    [switch]$Verbose
)

function Write-BuildInfo { param($msg) Write-Host "[BUILD] $msg" -ForegroundColor Green }
function Write-BuildError { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red }

$CXX = 'cl.exe'
$LINK = 'link.exe'
$CXXFLAGS = '/std:c++20', '/EHsc', '/MD', '/O2'
$LINKFLAGS = '/SUBSYSTEM:CONSOLE'

$DEFINES = '-DNOMINMAX', '-D_WIN32_WINNT=0x0A00', '-DHAVE_QT_CORE', '-DQT_NO_OPENGL'
$INCLUDES = '/Iinclude', '/Isrc'

if ($Clean) {
    Write-BuildInfo 'Cleaning build artifacts...'
    Remove-Item -Recurse -Force obj, bin, lib -ErrorAction SilentlyContinue
    exit 0
}

Write-BuildInfo 'Creating build directories...'
New-Item -ItemType Directory -Force obj, bin, lib | Out-Null

# Building ggml_interface
Write-BuildInfo 'Building ggml_interface...'
New-Item -ItemType Directory -Force obj\ggml_interface | Out-Null

# Link ggml_interface
& $LINK $LINKFLAGS  '/OUT:lib\ggml_interface.lib'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-QtShell
Write-BuildInfo 'Building RawrXD-QtShell...'
New-Item -ItemType Directory -Force obj\RawrXD-QtShell | Out-Null

# Compile src/qtapp/main_qt.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/main_qt.cpp' '/Foobj\RawrXD-QtShell\main_qt.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/MainWindow.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/MainWindow.cpp' '/Foobj\RawrXD-QtShell\MainWindow.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/ActivityBar.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/ActivityBar.cpp' '/Foobj\RawrXD-QtShell\ActivityBar.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/ActivityBarButton.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/ActivityBarButton.cpp' '/Foobj\RawrXD-QtShell\ActivityBarButton.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/TerminalWidget.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/TerminalWidget.cpp' '/Foobj\RawrXD-QtShell\TerminalWidget.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/TerminalManager.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/TerminalManager.cpp' '/Foobj\RawrXD-QtShell\TerminalManager.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/inference_engine.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/inference_engine.cpp' '/Foobj\RawrXD-QtShell\inference_engine.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/transformer_inference.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/transformer_inference.cpp' '/Foobj\RawrXD-QtShell\transformer_inference.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/bpe_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/bpe_tokenizer.cpp' '/Foobj\RawrXD-QtShell\bpe_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/sentencepiece_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/sentencepiece_tokenizer.cpp' '/Foobj\RawrXD-QtShell\sentencepiece_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/vocabulary_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/vocabulary_loader.cpp' '/Foobj\RawrXD-QtShell\vocabulary_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gguf_server.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gguf_server.cpp' '/Foobj\RawrXD-QtShell\gguf_server.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/inflate_deflate_cpp.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/inflate_deflate_cpp.cpp' '/Foobj\RawrXD-QtShell\inflate_deflate_cpp.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/deflate_brutal_stub.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/deflate_brutal_stub.cpp' '/Foobj\RawrXD-QtShell\deflate_brutal_stub.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/ai_switcher.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/ai_switcher.cpp' '/Foobj\RawrXD-QtShell\ai_switcher.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/unified_backend.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/unified_backend.cpp' '/Foobj\RawrXD-QtShell\unified_backend.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/widgets/layer_quant_widget.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/widgets/layer_quant_widget.cpp' '/Foobj\RawrXD-QtShell\layer_quant_widget.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/streaming_inference.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/streaming_inference.cpp' '/Foobj\RawrXD-QtShell\streaming_inference.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/model_monitor.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/model_monitor.cpp' '/Foobj\RawrXD-QtShell\model_monitor.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/command_palette.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/command_palette.cpp' '/Foobj\RawrXD-QtShell\command_palette.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/ai_chat_panel.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/ai_chat_panel.cpp' '/Foobj\RawrXD-QtShell\ai_chat_panel.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/model_memory_hotpatch.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/model_memory_hotpatch.cpp' '/Foobj\RawrXD-QtShell\model_memory_hotpatch.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/byte_level_hotpatcher.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/byte_level_hotpatcher.cpp' '/Foobj\RawrXD-QtShell\byte_level_hotpatcher.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gguf_server_hotpatch.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gguf_server_hotpatch.cpp' '/Foobj\RawrXD-QtShell\gguf_server_hotpatch.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/unified_hotpatch_manager.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/unified_hotpatch_manager.cpp' '/Foobj\RawrXD-QtShell\unified_hotpatch_manager.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/proxy_hotpatcher.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/proxy_hotpatcher.cpp' '/Foobj\RawrXD-QtShell\proxy_hotpatcher.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/model_queue.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/model_queue.cpp' '/Foobj\RawrXD-QtShell\model_queue.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/streaming_inference_api.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/streaming_inference_api.cpp' '/Foobj\RawrXD-QtShell\streaming_inference_api.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gpu_backend.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gpu_backend.cpp' '/Foobj\RawrXD-QtShell\gpu_backend.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/metrics_collector.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/metrics_collector.cpp' '/Foobj\RawrXD-QtShell\metrics_collector.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/backup_manager.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/backup_manager.cpp' '/Foobj\RawrXD-QtShell\backup_manager.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/sla_manager.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/sla_manager.cpp' '/Foobj\RawrXD-QtShell\sla_manager.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-QtShell
& $LINK $LINKFLAGS obj\RawrXD-QtShell\main_qt.obj obj\RawrXD-QtShell\MainWindow.obj obj\RawrXD-QtShell\ActivityBar.obj obj\RawrXD-QtShell\ActivityBarButton.obj obj\RawrXD-QtShell\TerminalWidget.obj obj\RawrXD-QtShell\TerminalManager.obj obj\RawrXD-QtShell\inference_engine.obj obj\RawrXD-QtShell\transformer_inference.obj obj\RawrXD-QtShell\bpe_tokenizer.obj obj\RawrXD-QtShell\sentencepiece_tokenizer.obj obj\RawrXD-QtShell\vocabulary_loader.obj obj\RawrXD-QtShell\gguf_server.obj obj\RawrXD-QtShell\inflate_deflate_cpp.obj obj\RawrXD-QtShell\deflate_brutal_stub.obj obj\RawrXD-QtShell\ai_switcher.obj obj\RawrXD-QtShell\unified_backend.obj obj\RawrXD-QtShell\layer_quant_widget.obj obj\RawrXD-QtShell\streaming_inference.obj obj\RawrXD-QtShell\model_monitor.obj obj\RawrXD-QtShell\command_palette.obj obj\RawrXD-QtShell\ai_chat_panel.obj obj\RawrXD-QtShell\model_memory_hotpatch.obj obj\RawrXD-QtShell\byte_level_hotpatcher.obj obj\RawrXD-QtShell\gguf_server_hotpatch.obj obj\RawrXD-QtShell\unified_hotpatch_manager.obj obj\RawrXD-QtShell\proxy_hotpatcher.obj obj\RawrXD-QtShell\model_queue.obj obj\RawrXD-QtShell\streaming_inference_api.obj obj\RawrXD-QtShell\gpu_backend.obj obj\RawrXD-QtShell\metrics_collector.obj obj\RawrXD-QtShell\backup_manager.obj obj\RawrXD-QtShell\sla_manager.obj '/OUT:bin\RawrXD-QtShell.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building self_test_gate
Write-BuildInfo 'Building self_test_gate...'
New-Item -ItemType Directory -Force obj\self_test_gate | Out-Null

# Compile src/agent/self_test.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/self_test.cpp' '/Foobj\self_test_gate\self_test.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/agent/self_test_gate.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/self_test_gate.cpp' '/Foobj\self_test_gate\self_test_gate.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/agent/rollback.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/rollback.cpp' '/Foobj\self_test_gate\rollback.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link self_test_gate
& $LINK $LINKFLAGS obj\self_test_gate\self_test.obj obj\self_test_gate\self_test_gate.obj obj\self_test_gate\rollback.obj '/OUT:lib\self_test_gate.lib'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building quant_utils
Write-BuildInfo 'Building quant_utils...'
New-Item -ItemType Directory -Force obj\quant_utils | Out-Null

# Compile STATIC src/qtapp/quant_utils.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'STATIC src/qtapp/quant_utils.cpp' '/Foobj\quant_utils\quant_utils.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link quant_utils
& $LINK $LINKFLAGS obj\quant_utils\quant_utils.obj '/OUT:lib\quant_utils.lib'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building production_feature_test
Write-BuildInfo 'Building production_feature_test...'
New-Item -ItemType Directory -Force obj\production_feature_test | Out-Null

# Compile src/qtapp/production_feature_test.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/production_feature_test.cpp' '/Foobj\production_feature_test\production_feature_test.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gpu_backend.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gpu_backend.cpp' '/Foobj\production_feature_test\gpu_backend.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/metrics_collector.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/metrics_collector.cpp' '/Foobj\production_feature_test\metrics_collector.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/sla_manager.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/sla_manager.cpp' '/Foobj\production_feature_test\sla_manager.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link production_feature_test
& $LINK $LINKFLAGS obj\production_feature_test\production_feature_test.obj obj\production_feature_test\gpu_backend.obj obj\production_feature_test\metrics_collector.obj obj\production_feature_test\sla_manager.obj '/OUT:bin\production_feature_test.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building simple_gpu_test
Write-BuildInfo 'Building simple_gpu_test...'
New-Item -ItemType Directory -Force obj\simple_gpu_test | Out-Null

# Compile src/qtapp/simple_gpu_test.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/simple_gpu_test.cpp' '/Foobj\simple_gpu_test\simple_gpu_test.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gpu_backend.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gpu_backend.cpp' '/Foobj\simple_gpu_test\gpu_backend.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/metrics_collector.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/metrics_collector.cpp' '/Foobj\simple_gpu_test\metrics_collector.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link simple_gpu_test
& $LINK $LINKFLAGS obj\simple_gpu_test\simple_gpu_test.obj obj\simple_gpu_test\gpu_backend.obj obj\simple_gpu_test\metrics_collector.obj '/OUT:bin\simple_gpu_test.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building gpu_inference_benchmark
Write-BuildInfo 'Building gpu_inference_benchmark...'
New-Item -ItemType Directory -Force obj\gpu_inference_benchmark | Out-Null

# Compile src/qtapp/gpu_inference_benchmark.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gpu_inference_benchmark.cpp' '/Foobj\gpu_inference_benchmark\gpu_inference_benchmark.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/inference_engine.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/inference_engine.cpp' '/Foobj\gpu_inference_benchmark\inference_engine.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gguf_loader.cpp' '/Foobj\gpu_inference_benchmark\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\gpu_inference_benchmark\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/transformer_inference.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/transformer_inference.cpp' '/Foobj\gpu_inference_benchmark\transformer_inference.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/bpe_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/bpe_tokenizer.cpp' '/Foobj\gpu_inference_benchmark\bpe_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/sentencepiece_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/sentencepiece_tokenizer.cpp' '/Foobj\gpu_inference_benchmark\sentencepiece_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/vocabulary_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/vocabulary_loader.cpp' '/Foobj\gpu_inference_benchmark\vocabulary_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gpu_backend.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gpu_backend.cpp' '/Foobj\gpu_inference_benchmark\gpu_backend.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/metrics_collector.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/metrics_collector.cpp' '/Foobj\gpu_inference_benchmark\metrics_collector.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/quant_utils.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/quant_utils.cpp' '/Foobj\gpu_inference_benchmark\quant_utils.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link gpu_inference_benchmark
& $LINK $LINKFLAGS obj\gpu_inference_benchmark\gpu_inference_benchmark.obj obj\gpu_inference_benchmark\inference_engine.obj obj\gpu_inference_benchmark\gguf_loader.obj obj\gpu_inference_benchmark\gguf_loader.obj obj\gpu_inference_benchmark\transformer_inference.obj obj\gpu_inference_benchmark\bpe_tokenizer.obj obj\gpu_inference_benchmark\sentencepiece_tokenizer.obj obj\gpu_inference_benchmark\vocabulary_loader.obj obj\gpu_inference_benchmark\gpu_backend.obj obj\gpu_inference_benchmark\metrics_collector.obj obj\gpu_inference_benchmark\quant_utils.obj '/OUT:bin\gpu_inference_benchmark.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building minimal_qt_test
Write-BuildInfo 'Building minimal_qt_test...'
New-Item -ItemType Directory -Force obj\minimal_qt_test | Out-Null

# Compile src/minimal_qt_test.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/minimal_qt_test.cpp' '/Foobj\minimal_qt_test\minimal_qt_test.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link minimal_qt_test
& $LINK $LINKFLAGS obj\minimal_qt_test\minimal_qt_test.obj '/OUT:bin\minimal_qt_test.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building gguf_hotpatch_tester
Write-BuildInfo 'Building gguf_hotpatch_tester...'
New-Item -ItemType Directory -Force obj\gguf_hotpatch_tester | Out-Null

# Compile src/qtapp/gguf_hotpatch_tester.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gguf_hotpatch_tester.cpp' '/Foobj\gguf_hotpatch_tester\gguf_hotpatch_tester.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/inference_engine.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/inference_engine.cpp' '/Foobj\gguf_hotpatch_tester\inference_engine.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gguf_loader.cpp' '/Foobj\gguf_hotpatch_tester\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\gguf_hotpatch_tester\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/transformer_inference.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/transformer_inference.cpp' '/Foobj\gguf_hotpatch_tester\transformer_inference.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/bpe_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/bpe_tokenizer.cpp' '/Foobj\gguf_hotpatch_tester\bpe_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/sentencepiece_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/sentencepiece_tokenizer.cpp' '/Foobj\gguf_hotpatch_tester\sentencepiece_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/vocabulary_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/vocabulary_loader.cpp' '/Foobj\gguf_hotpatch_tester\vocabulary_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gpu_backend.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gpu_backend.cpp' '/Foobj\gguf_hotpatch_tester\gpu_backend.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/metrics_collector.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/metrics_collector.cpp' '/Foobj\gguf_hotpatch_tester\metrics_collector.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/quant_utils.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/quant_utils.cpp' '/Foobj\gguf_hotpatch_tester\quant_utils.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link gguf_hotpatch_tester
& $LINK $LINKFLAGS obj\gguf_hotpatch_tester\gguf_hotpatch_tester.obj obj\gguf_hotpatch_tester\inference_engine.obj obj\gguf_hotpatch_tester\gguf_loader.obj obj\gguf_hotpatch_tester\gguf_loader.obj obj\gguf_hotpatch_tester\transformer_inference.obj obj\gguf_hotpatch_tester\bpe_tokenizer.obj obj\gguf_hotpatch_tester\sentencepiece_tokenizer.obj obj\gguf_hotpatch_tester\vocabulary_loader.obj obj\gguf_hotpatch_tester\gpu_backend.obj obj\gguf_hotpatch_tester\metrics_collector.obj obj\gguf_hotpatch_tester\quant_utils.obj '/OUT:bin\gguf_hotpatch_tester.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_chat_streaming
Write-BuildInfo 'Building test_chat_streaming...'
New-Item -ItemType Directory -Force obj\test_chat_streaming | Out-Null

# Compile src/qtapp/test_chat_streaming.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/test_chat_streaming.cpp' '/Foobj\test_chat_streaming\test_chat_streaming.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/inference_engine.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/inference_engine.cpp' '/Foobj\test_chat_streaming\inference_engine.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gguf_loader.cpp' '/Foobj\test_chat_streaming\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\test_chat_streaming\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/transformer_inference.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/transformer_inference.cpp' '/Foobj\test_chat_streaming\transformer_inference.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/bpe_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/bpe_tokenizer.cpp' '/Foobj\test_chat_streaming\bpe_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/sentencepiece_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/sentencepiece_tokenizer.cpp' '/Foobj\test_chat_streaming\sentencepiece_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/vocabulary_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/vocabulary_loader.cpp' '/Foobj\test_chat_streaming\vocabulary_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gpu_backend.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gpu_backend.cpp' '/Foobj\test_chat_streaming\gpu_backend.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/metrics_collector.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/metrics_collector.cpp' '/Foobj\test_chat_streaming\metrics_collector.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/quant_utils.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/quant_utils.cpp' '/Foobj\test_chat_streaming\quant_utils.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_chat_streaming
& $LINK $LINKFLAGS obj\test_chat_streaming\test_chat_streaming.obj obj\test_chat_streaming\inference_engine.obj obj\test_chat_streaming\gguf_loader.obj obj\test_chat_streaming\gguf_loader.obj obj\test_chat_streaming\transformer_inference.obj obj\test_chat_streaming\bpe_tokenizer.obj obj\test_chat_streaming\sentencepiece_tokenizer.obj obj\test_chat_streaming\vocabulary_loader.obj obj\test_chat_streaming\gpu_backend.obj obj\test_chat_streaming\metrics_collector.obj obj\test_chat_streaming\quant_utils.obj '/OUT:bin\test_chat_streaming.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-Agent
Write-BuildInfo 'Building RawrXD-Agent...'
New-Item -ItemType Directory -Force obj\RawrXD-Agent | Out-Null

# Compile src/agent/agent_main.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/agent_main.cpp' '/Foobj\RawrXD-Agent\agent_main.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/agent/planner.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/planner.cpp' '/Foobj\RawrXD-Agent\planner.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/agent/self_patch.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/self_patch.cpp' '/Foobj\RawrXD-Agent\self_patch.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/agent/sign_binary.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/sign_binary.cpp' '/Foobj\RawrXD-Agent\sign_binary.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/agent/release_agent.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/release_agent.cpp' '/Foobj\RawrXD-Agent\release_agent.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/agent/meta_learn.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/meta_learn.cpp' '/Foobj\RawrXD-Agent\meta_learn.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/agent/hot_reload.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agent/hot_reload.cpp' '/Foobj\RawrXD-Agent\hot_reload.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-Agent
& $LINK $LINKFLAGS obj\RawrXD-Agent\agent_main.obj obj\RawrXD-Agent\planner.obj obj\RawrXD-Agent\self_patch.obj obj\RawrXD-Agent\sign_binary.obj obj\RawrXD-Agent\release_agent.obj obj\RawrXD-Agent\meta_learn.obj obj\RawrXD-Agent\hot_reload.obj '/OUT:bin\RawrXD-Agent.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-Compiler
Write-BuildInfo 'Building RawrXD-Compiler...'
New-Item -ItemType Directory -Force obj\RawrXD-Compiler | Out-Null

# Compile src/cli/rawrxd_cli_compiler.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/cli/rawrxd_cli_compiler.cpp' '/Foobj\RawrXD-Compiler\rawrxd_cli_compiler.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-Compiler
& $LINK $LINKFLAGS obj\RawrXD-Compiler\rawrxd_cli_compiler.obj '/OUT:bin\RawrXD-Compiler.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building rawrxd_compiler_qt
Write-BuildInfo 'Building rawrxd_compiler_qt...'
New-Item -ItemType Directory -Force obj\rawrxd_compiler_qt | Out-Null

# Compile src/compiler/rawrxd_compiler_qt.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/compiler/rawrxd_compiler_qt.cpp' '/Foobj\rawrxd_compiler_qt\rawrxd_compiler_qt.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link rawrxd_compiler_qt
& $LINK $LINKFLAGS obj\rawrxd_compiler_qt\rawrxd_compiler_qt.obj '/OUT:lib\rawrxd_compiler_qt.lib'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-Win32IDE
Write-BuildInfo 'Building RawrXD-Win32IDE...'
New-Item -ItemType Directory -Force obj\RawrXD-Win32IDE | Out-Null

# Compile src/win32app/main_win32.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/main_win32.cpp' '/Foobj\RawrXD-Win32IDE\main_win32.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Window.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Window.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_Window.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Sidebar.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Sidebar.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_Sidebar.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_VSCodeUI.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_VSCodeUI.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_VSCodeUI.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_PowerShellPanel.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_PowerShellPanel.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_PowerShellPanel.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_PowerShell.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_PowerShell.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_PowerShell.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Logger.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Logger.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_Logger.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/TransparentRenderer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/TransparentRenderer.cpp' '/Foobj\RawrXD-Win32IDE\TransparentRenderer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32TerminalManager.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32TerminalManager.cpp' '/Foobj\RawrXD-Win32IDE\Win32TerminalManager.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_FileOps.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_FileOps.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_FileOps.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Commands.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Commands.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_Commands.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Debugger.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Debugger.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_Debugger.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_AgenticBridge.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_AgenticBridge.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_AgenticBridge.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_AgentCommands.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_AgentCommands.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_AgentCommands.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Autonomy.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Autonomy.cpp' '/Foobj\RawrXD-Win32IDE\Win32IDE_Autonomy.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\RawrXD-Win32IDE\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_vocab_resolver.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_vocab_resolver.cpp' '/Foobj\RawrXD-Win32IDE\gguf_vocab_resolver.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/streaming_gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/streaming_gguf_loader.cpp' '/Foobj\RawrXD-Win32IDE\streaming_gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/utils/ErrorReporter.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/utils/ErrorReporter.cpp' '/Foobj\RawrXD-Win32IDE\ErrorReporter.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/utils/Diagnostics.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/utils/Diagnostics.cpp' '/Foobj\RawrXD-Win32IDE\Diagnostics.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-Win32IDE
& $LINK $LINKFLAGS obj\RawrXD-Win32IDE\main_win32.obj obj\RawrXD-Win32IDE\Win32IDE.obj obj\RawrXD-Win32IDE\Win32IDE_Window.obj obj\RawrXD-Win32IDE\Win32IDE_Sidebar.obj obj\RawrXD-Win32IDE\Win32IDE_VSCodeUI.obj obj\RawrXD-Win32IDE\Win32IDE_PowerShellPanel.obj obj\RawrXD-Win32IDE\Win32IDE_PowerShell.obj obj\RawrXD-Win32IDE\Win32IDE_Logger.obj obj\RawrXD-Win32IDE\TransparentRenderer.obj obj\RawrXD-Win32IDE\Win32TerminalManager.obj obj\RawrXD-Win32IDE\Win32IDE_FileOps.obj obj\RawrXD-Win32IDE\Win32IDE_Commands.obj obj\RawrXD-Win32IDE\Win32IDE_Debugger.obj obj\RawrXD-Win32IDE\Win32IDE_AgenticBridge.obj obj\RawrXD-Win32IDE\Win32IDE_AgentCommands.obj obj\RawrXD-Win32IDE\Win32IDE_Autonomy.obj obj\RawrXD-Win32IDE\gguf_loader.obj obj\RawrXD-Win32IDE\gguf_vocab_resolver.obj obj\RawrXD-Win32IDE\streaming_gguf_loader.obj obj\RawrXD-Win32IDE\ErrorReporter.obj obj\RawrXD-Win32IDE\Diagnostics.obj '/OUT:bin\RawrXD-Win32IDE.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_terminal
Write-BuildInfo 'Building test_terminal...'
New-Item -ItemType Directory -Force obj\test_terminal | Out-Null

# Compile src/win32app/test_terminal.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/test_terminal.cpp' '/Foobj\test_terminal\test_terminal.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32TerminalManager.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32TerminalManager.cpp' '/Foobj\test_terminal\Win32TerminalManager.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_terminal
& $LINK $LINKFLAGS obj\test_terminal\test_terminal.obj obj\test_terminal\Win32TerminalManager.obj '/OUT:bin\test_terminal.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-Chat
Write-BuildInfo 'Building RawrXD-Chat...'
New-Item -ItemType Directory -Force obj\RawrXD-Chat | Out-Null

# Compile src/win32app/main_chat.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/main_chat.cpp' '/Foobj\RawrXD-Chat\main_chat.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32ChatApp.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32ChatApp.cpp' '/Foobj\RawrXD-Chat\Win32ChatApp.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-Chat
& $LINK $LINKFLAGS obj\RawrXD-Chat\main_chat.obj obj\RawrXD-Chat\Win32ChatApp.obj '/OUT:bin\RawrXD-Chat.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-ModelLoader
Write-BuildInfo 'Building RawrXD-ModelLoader...'
New-Item -ItemType Directory -Force obj\RawrXD-ModelLoader | Out-Null

# Compile src/main.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/main.cpp' '/Foobj\RawrXD-ModelLoader\main.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\RawrXD-ModelLoader\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/vulkan_compute.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/vulkan_compute.cpp' '/Foobj\RawrXD-ModelLoader\vulkan_compute.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/hf_downloader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/hf_downloader.cpp' '/Foobj\RawrXD-ModelLoader\hf_downloader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gui.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gui.cpp' '/Foobj\RawrXD-ModelLoader\gui.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/api_server.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/api_server.cpp' '/Foobj\RawrXD-ModelLoader\api_server.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/settings.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/settings.cpp' '/Foobj\RawrXD-ModelLoader\settings.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/telemetry.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/telemetry.cpp' '/Foobj\RawrXD-ModelLoader\telemetry.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/telemetry/ai_metrics.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/telemetry/ai_metrics.cpp' '/Foobj\RawrXD-ModelLoader\ai_metrics.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/overclock_vendor.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/overclock_vendor.cpp' '/Foobj\RawrXD-ModelLoader\overclock_vendor.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/overclock_governor.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/overclock_governor.cpp' '/Foobj\RawrXD-ModelLoader\overclock_governor.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/baseline_profile.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/baseline_profile.cpp' '/Foobj\RawrXD-ModelLoader\baseline_profile.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-ModelLoader
& $LINK $LINKFLAGS obj\RawrXD-ModelLoader\main.obj obj\RawrXD-ModelLoader\gguf_loader.obj obj\RawrXD-ModelLoader\vulkan_compute.obj obj\RawrXD-ModelLoader\hf_downloader.obj obj\RawrXD-ModelLoader\gui.obj obj\RawrXD-ModelLoader\api_server.obj obj\RawrXD-ModelLoader\settings.obj obj\RawrXD-ModelLoader\telemetry.obj obj\RawrXD-ModelLoader\ai_metrics.obj obj\RawrXD-ModelLoader\overclock_vendor.obj obj\RawrXD-ModelLoader\overclock_governor.obj obj\RawrXD-ModelLoader\baseline_profile.obj '/OUT:bin\RawrXD-ModelLoader.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-CLI
Write-BuildInfo 'Building RawrXD-CLI...'
New-Item -ItemType Directory -Force obj\RawrXD-CLI | Out-Null

# Compile src/rawrxd_cli.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/rawrxd_cli.cpp' '/Foobj\RawrXD-CLI\rawrxd_cli.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\RawrXD-CLI\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/vulkan_compute.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/vulkan_compute.cpp' '/Foobj\RawrXD-CLI\vulkan_compute.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/hf_downloader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/hf_downloader.cpp' '/Foobj\RawrXD-CLI\hf_downloader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/api_server.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/api_server.cpp' '/Foobj\RawrXD-CLI\api_server.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/settings.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/settings.cpp' '/Foobj\RawrXD-CLI\settings.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/telemetry.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/telemetry.cpp' '/Foobj\RawrXD-CLI\telemetry.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/overclock_vendor.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/overclock_vendor.cpp' '/Foobj\RawrXD-CLI\overclock_vendor.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/overclock_governor.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/overclock_governor.cpp' '/Foobj\RawrXD-CLI\overclock_governor.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/baseline_profile.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/baseline_profile.cpp' '/Foobj\RawrXD-CLI\baseline_profile.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-CLI
& $LINK $LINKFLAGS obj\RawrXD-CLI\rawrxd_cli.obj obj\RawrXD-CLI\gguf_loader.obj obj\RawrXD-CLI\vulkan_compute.obj obj\RawrXD-CLI\hf_downloader.obj obj\RawrXD-CLI\api_server.obj obj\RawrXD-CLI\settings.obj obj\RawrXD-CLI\telemetry.obj obj\RawrXD-CLI\overclock_vendor.obj obj\RawrXD-CLI\overclock_governor.obj obj\RawrXD-CLI\baseline_profile.obj '/OUT:bin\RawrXD-CLI.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building model_loader_bench
Write-BuildInfo 'Building model_loader_bench...'
New-Item -ItemType Directory -Force obj\model_loader_bench | Out-Null

# Compile src/bench_main.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/bench_main.cpp' '/Foobj\model_loader_bench\bench_main.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\model_loader_bench\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/vulkan_compute.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/vulkan_compute.cpp' '/Foobj\model_loader_bench\vulkan_compute.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/settings.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/settings.cpp' '/Foobj\model_loader_bench\settings.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/telemetry.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/telemetry.cpp' '/Foobj\model_loader_bench\telemetry.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link model_loader_bench
& $LINK $LINKFLAGS obj\model_loader_bench\bench_main.obj obj\model_loader_bench\gguf_loader.obj obj\model_loader_bench\vulkan_compute.obj obj\model_loader_bench\settings.obj obj\model_loader_bench\telemetry.obj '/OUT:bin\model_loader_bench.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building rawrxd_stress
Write-BuildInfo 'Building rawrxd_stress...'
New-Item -ItemType Directory -Force obj\rawrxd_stress | Out-Null

# Compile src/oc_stress.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/oc_stress.cpp' '/Foobj\rawrxd_stress\oc_stress.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/telemetry.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/telemetry.cpp' '/Foobj\rawrxd_stress\telemetry.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link rawrxd_stress
& $LINK $LINKFLAGS obj\rawrxd_stress\oc_stress.obj obj\rawrxd_stress\telemetry.obj '/OUT:bin\rawrxd_stress.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building rawrxd_test_baseline
Write-BuildInfo 'Building rawrxd_test_baseline...'
New-Item -ItemType Directory -Force obj\rawrxd_test_baseline | Out-Null

# Link rawrxd_test_baseline
& $LINK $LINKFLAGS  '/OUT:bin\rawrxd_test_baseline.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building rawrxd_test_pid
Write-BuildInfo 'Building rawrxd_test_pid...'
New-Item -ItemType Directory -Force obj\rawrxd_test_pid | Out-Null

# Link rawrxd_test_pid
& $LINK $LINKFLAGS  '/OUT:bin\rawrxd_test_pid.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-IDE
Write-BuildInfo 'Building RawrXD-IDE...'
New-Item -ItemType Directory -Force obj\RawrXD-IDE | Out-Null

# Compile src/ide_main.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/ide_main.cpp' '/Foobj\RawrXD-IDE\ide_main.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/ide_window.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/ide_window.cpp' '/Foobj\RawrXD-IDE\ide_window.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-IDE
& $LINK $LINKFLAGS obj\RawrXD-IDE\ide_main.obj obj\RawrXD-IDE\ide_window.obj '/OUT:bin\RawrXD-IDE.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-SimpleIDE
Write-BuildInfo 'Building RawrXD-SimpleIDE...'
New-Item -ItemType Directory -Force obj\RawrXD-SimpleIDE | Out-Null

# Compile src/qtapp/main_simple.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/main_simple.cpp' '/Foobj\RawrXD-SimpleIDE\main_simple.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/MainWindowSimple.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/MainWindowSimple.cpp' '/Foobj\RawrXD-SimpleIDE\MainWindowSimple.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/editor_buffer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/editor_buffer.cpp' '/Foobj\RawrXD-SimpleIDE\editor_buffer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/syntax_engine.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/syntax_engine.cpp' '/Foobj\RawrXD-SimpleIDE\syntax_engine.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/overclock_vendor.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/overclock_vendor.cpp' '/Foobj\RawrXD-SimpleIDE\overclock_vendor.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/overclock_governor.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/overclock_governor.cpp' '/Foobj\RawrXD-SimpleIDE\overclock_governor.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/settings.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/settings.cpp' '/Foobj\RawrXD-SimpleIDE\settings.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/telemetry.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/telemetry.cpp' '/Foobj\RawrXD-SimpleIDE\telemetry.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/baseline_profile.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/baseline_profile.cpp' '/Foobj\RawrXD-SimpleIDE\baseline_profile.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\RawrXD-SimpleIDE\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/telemetry/ai_metrics.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/telemetry/ai_metrics.cpp' '/Foobj\RawrXD-SimpleIDE\ai_metrics.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/session/ai_session.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/session/ai_session.cpp' '/Foobj\RawrXD-SimpleIDE\ai_session.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/backend/ollama_client.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/backend/ollama_client.cpp' '/Foobj\RawrXD-SimpleIDE\ollama_client.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/backend/websocket_server.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/backend/websocket_server.cpp' '/Foobj\RawrXD-SimpleIDE\websocket_server.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/backend/agentic_tools.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/backend/agentic_tools.cpp' '/Foobj\RawrXD-SimpleIDE\agentic_tools.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/tools/file_ops.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/tools/file_ops.cpp' '/Foobj\RawrXD-SimpleIDE\file_ops.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/tools/git_client.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/tools/git_client.cpp' '/Foobj\RawrXD-SimpleIDE\git_client.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/context/indexer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/context/indexer.cpp' '/Foobj\RawrXD-SimpleIDE\indexer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/context/semantic_store.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/context/semantic_store.cpp' '/Foobj\RawrXD-SimpleIDE\semantic_store.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/ui/split_layout.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/ui/split_layout.cpp' '/Foobj\RawrXD-SimpleIDE\split_layout.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/ui/chat_panel.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/ui/chat_panel.cpp' '/Foobj\RawrXD-SimpleIDE\chat_panel.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-SimpleIDE
& $LINK $LINKFLAGS obj\RawrXD-SimpleIDE\main_simple.obj obj\RawrXD-SimpleIDE\MainWindowSimple.obj obj\RawrXD-SimpleIDE\editor_buffer.obj obj\RawrXD-SimpleIDE\syntax_engine.obj obj\RawrXD-SimpleIDE\overclock_vendor.obj obj\RawrXD-SimpleIDE\overclock_governor.obj obj\RawrXD-SimpleIDE\settings.obj obj\RawrXD-SimpleIDE\telemetry.obj obj\RawrXD-SimpleIDE\baseline_profile.obj obj\RawrXD-SimpleIDE\gguf_loader.obj obj\RawrXD-SimpleIDE\ai_metrics.obj obj\RawrXD-SimpleIDE\ai_session.obj obj\RawrXD-SimpleIDE\ollama_client.obj obj\RawrXD-SimpleIDE\websocket_server.obj obj\RawrXD-SimpleIDE\agentic_tools.obj obj\RawrXD-SimpleIDE\file_ops.obj obj\RawrXD-SimpleIDE\git_client.obj obj\RawrXD-SimpleIDE\indexer.obj obj\RawrXD-SimpleIDE\semantic_store.obj obj\RawrXD-SimpleIDE\split_layout.obj obj\RawrXD-SimpleIDE\chat_panel.obj '/OUT:bin\RawrXD-SimpleIDE.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-Chromatic
Write-BuildInfo 'Building RawrXD-Chromatic...'
New-Item -ItemType Directory -Force obj\RawrXD-Chromatic | Out-Null

# Compile src/chromatic_main.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/chromatic_main.cpp' '/Foobj\RawrXD-Chromatic\chromatic_main.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/ui/chromatic_window.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/ui/chromatic_window.cpp' '/Foobj\RawrXD-Chromatic\chromatic_window.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-Chromatic
& $LINK $LINKFLAGS obj\RawrXD-Chromatic\chromatic_main.obj obj\RawrXD-Chromatic\chromatic_window.obj '/OUT:bin\RawrXD-Chromatic.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building stub_test
Write-BuildInfo 'Building stub_test...'
New-Item -ItemType Directory -Force obj\stub_test | Out-Null

# Compile WIN32 src/stub_main.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'WIN32 src/stub_main.cpp' '/Foobj\stub_test\stub_main.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link stub_test
& $LINK $LINKFLAGS obj\stub_test\stub_main.obj '/OUT:bin\stub_test.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_ide_main
Write-BuildInfo 'Building test_ide_main...'
New-Item -ItemType Directory -Force obj\test_ide_main | Out-Null

# Compile WIN32 src/test_ide_main.cpp src/agentic_ide.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'WIN32 src/test_ide_main.cpp src/agentic_ide.cpp' '/Foobj\test_ide_main\agentic_ide.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_ide_main
& $LINK $LINKFLAGS obj\test_ide_main\agentic_ide.obj '/OUT:bin\test_ide_main.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_qmainwindow
Write-BuildInfo 'Building test_qmainwindow...'
New-Item -ItemType Directory -Force obj\test_qmainwindow | Out-Null

# Compile WIN32 src/test_qmainwindow.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'WIN32 src/test_qmainwindow.cpp' '/Foobj\test_qmainwindow\test_qmainwindow.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_qmainwindow
& $LINK $LINKFLAGS obj\test_qmainwindow\test_qmainwindow.obj '/OUT:bin\test_qmainwindow.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_header
Write-BuildInfo 'Building test_header...'
New-Item -ItemType Directory -Force obj\test_header | Out-Null

# Compile src/agentic_ide_test.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/agentic_ide_test.cpp' '/Foobj\test_header\agentic_ide_test.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_header
& $LINK $LINKFLAGS obj\test_header\agentic_ide_test.obj '/OUT:bin\test_header.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building RawrXD-TestRunner
Write-BuildInfo 'Building RawrXD-TestRunner...'
New-Item -ItemType Directory -Force obj\RawrXD-TestRunner | Out-Null

# Compile src/win32app/test_runner.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/test_runner.cpp' '/Foobj\RawrXD-TestRunner\test_runner.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Window.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Window.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_Window.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Commands.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Commands.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_Commands.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Debugger.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Debugger.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_Debugger.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_FileOps.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_FileOps.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_FileOps.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_PowerShell.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_PowerShell.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_PowerShell.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_PowerShellPanel.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_PowerShellPanel.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_PowerShellPanel.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_Sidebar.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_Sidebar.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_Sidebar.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_VSCodeUI.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_VSCodeUI.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_VSCodeUI.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_AgenticBridge.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_AgenticBridge.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_AgenticBridge.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32IDE_AgentCommands.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32IDE_AgentCommands.cpp' '/Foobj\RawrXD-TestRunner\Win32IDE_AgentCommands.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/Win32TerminalManager.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/Win32TerminalManager.cpp' '/Foobj\RawrXD-TestRunner\Win32TerminalManager.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/TransparentRenderer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/TransparentRenderer.cpp' '/Foobj\RawrXD-TestRunner\TransparentRenderer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/win32app/VulkanRenderer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/win32app/VulkanRenderer.cpp' '/Foobj\RawrXD-TestRunner\VulkanRenderer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\RawrXD-TestRunner\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/streaming_gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/streaming_gguf_loader.cpp' '/Foobj\RawrXD-TestRunner\streaming_gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link RawrXD-TestRunner
& $LINK $LINKFLAGS obj\RawrXD-TestRunner\test_runner.obj obj\RawrXD-TestRunner\Win32IDE.obj obj\RawrXD-TestRunner\Win32IDE_Window.obj obj\RawrXD-TestRunner\Win32IDE_Commands.obj obj\RawrXD-TestRunner\Win32IDE_Debugger.obj obj\RawrXD-TestRunner\Win32IDE_FileOps.obj obj\RawrXD-TestRunner\Win32IDE_PowerShell.obj obj\RawrXD-TestRunner\Win32IDE_PowerShellPanel.obj obj\RawrXD-TestRunner\Win32IDE_Sidebar.obj obj\RawrXD-TestRunner\Win32IDE_VSCodeUI.obj obj\RawrXD-TestRunner\Win32IDE_AgenticBridge.obj obj\RawrXD-TestRunner\Win32IDE_AgentCommands.obj obj\RawrXD-TestRunner\Win32TerminalManager.obj obj\RawrXD-TestRunner\TransparentRenderer.obj obj\RawrXD-TestRunner\VulkanRenderer.obj obj\RawrXD-TestRunner\gguf_loader.obj obj\RawrXD-TestRunner\streaming_gguf_loader.obj '/OUT:bin\RawrXD-TestRunner.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_q8_0_end2end
Write-BuildInfo 'Building bench_q8_0_end2end...'
New-Item -ItemType Directory -Force obj\bench_q8_0_end2end | Out-Null

# Compile tests/bench_q8_0_end2end.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/bench_q8_0_end2end.cpp' '/Foobj\bench_q8_0_end2end\bench_q8_0_end2end.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link bench_q8_0_end2end
& $LINK $LINKFLAGS obj\bench_q8_0_end2end\bench_q8_0_end2end.obj '/OUT:bin\bench_q8_0_end2end.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_flash_attn
Write-BuildInfo 'Building bench_flash_attn...'
New-Item -ItemType Directory -Force obj\bench_flash_attn | Out-Null

# Compile tests/bench_flash_attn.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/bench_flash_attn.cpp' '/Foobj\bench_flash_attn\bench_flash_attn.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link bench_flash_attn
& $LINK $LINKFLAGS obj\bench_flash_attn\bench_flash_attn.obj '/OUT:bin\bench_flash_attn.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_flash_all_quant
Write-BuildInfo 'Building bench_flash_all_quant...'
New-Item -ItemType Directory -Force obj\bench_flash_all_quant | Out-Null

# Compile tests/bench_flash_all_quant.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/bench_flash_all_quant.cpp' '/Foobj\bench_flash_all_quant\bench_flash_all_quant.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link bench_flash_all_quant
& $LINK $LINKFLAGS obj\bench_flash_all_quant\bench_flash_all_quant.obj '/OUT:bin\bench_flash_all_quant.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_flash_asm_puppeteer
Write-BuildInfo 'Building bench_flash_asm_puppeteer...'
New-Item -ItemType Directory -Force obj\bench_flash_asm_puppeteer | Out-Null

# Compile tests/bench_flash_asm_puppeteer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/bench_flash_asm_puppeteer.cpp' '/Foobj\bench_flash_asm_puppeteer\bench_flash_asm_puppeteer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link bench_flash_asm_puppeteer
& $LINK $LINKFLAGS obj\bench_flash_asm_puppeteer\bench_flash_asm_puppeteer.obj '/OUT:bin\bench_flash_asm_puppeteer.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_deflate_godmode
Write-BuildInfo 'Building bench_deflate_godmode...'
New-Item -ItemType Directory -Force obj\bench_deflate_godmode | Out-Null

# Link bench_deflate_godmode
& $LINK $LINKFLAGS  '/OUT:bin\bench_deflate_godmode.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_deflate_brutal
Write-BuildInfo 'Building bench_deflate_brutal...'
New-Item -ItemType Directory -Force obj\bench_deflate_brutal | Out-Null

# Link bench_deflate_brutal
& $LINK $LINKFLAGS  '/OUT:bin\bench_deflate_brutal.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_deflate_neon
Write-BuildInfo 'Building bench_deflate_neon...'
New-Item -ItemType Directory -Force obj\bench_deflate_neon | Out-Null

# Link bench_deflate_neon
& $LINK $LINKFLAGS  '/OUT:bin\bench_deflate_neon.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_deflate_brutal_arm64
Write-BuildInfo 'Building bench_deflate_brutal_arm64...'
New-Item -ItemType Directory -Force obj\bench_deflate_brutal_arm64 | Out-Null

# Compile tests/bench_deflate_brutal_arm64.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/bench_deflate_brutal_arm64.cpp' '/Foobj\bench_deflate_brutal_arm64\bench_deflate_brutal_arm64.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link bench_deflate_brutal_arm64
& $LINK $LINKFLAGS obj\bench_deflate_brutal_arm64\bench_deflate_brutal_arm64.obj '/OUT:bin\bench_deflate_brutal_arm64.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building bench_deflate_50mb
Write-BuildInfo 'Building bench_deflate_50mb...'
New-Item -ItemType Directory -Force obj\bench_deflate_50mb | Out-Null

# Compile tests/bench_deflate_50mb.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/bench_deflate_50mb.cpp' '/Foobj\bench_deflate_50mb\bench_deflate_50mb.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link bench_deflate_50mb
& $LINK $LINKFLAGS obj\bench_deflate_50mb\bench_deflate_50mb.obj '/OUT:bin\bench_deflate_50mb.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building quant_engine_test
Write-BuildInfo 'Building quant_engine_test...'
New-Item -ItemType Directory -Force obj\quant_engine_test | Out-Null

# Compile tests/quant_engine_smoke.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/quant_engine_smoke.cpp' '/Foobj\quant_engine_test\quant_engine_smoke.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link quant_engine_test
& $LINK $LINKFLAGS obj\quant_engine_test\quant_engine_smoke.obj '/OUT:bin\quant_engine_test.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building quant_scalar_smoke
Write-BuildInfo 'Building quant_scalar_smoke...'
New-Item -ItemType Directory -Force obj\quant_scalar_smoke | Out-Null

# Compile tests/quant_scalar_smoke.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/quant_scalar_smoke.cpp' '/Foobj\quant_scalar_smoke\quant_scalar_smoke.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link quant_scalar_smoke
& $LINK $LINKFLAGS obj\quant_scalar_smoke\quant_scalar_smoke.obj '/OUT:bin\quant_scalar_smoke.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building quant_correctness_tests
Write-BuildInfo 'Building quant_correctness_tests...'
New-Item -ItemType Directory -Force obj\quant_correctness_tests | Out-Null

# Compile tests/quant_correctness_tests.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/quant_correctness_tests.cpp' '/Foobj\quant_correctness_tests\quant_correctness_tests.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link quant_correctness_tests
& $LINK $LINKFLAGS obj\quant_correctness_tests\quant_correctness_tests.obj '/OUT:bin\quant_correctness_tests.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_agent_coordinator
Write-BuildInfo 'Building test_agent_coordinator...'
New-Item -ItemType Directory -Force obj\test_agent_coordinator | Out-Null

# Compile tests/test_agent_coordinator.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/test_agent_coordinator.cpp' '/Foobj\test_agent_coordinator\test_agent_coordinator.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_agent_coordinator
& $LINK $LINKFLAGS obj\test_agent_coordinator\test_agent_coordinator.obj '/OUT:bin\test_agent_coordinator.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_agent_coordinator_integration
Write-BuildInfo 'Building test_agent_coordinator_integration...'
New-Item -ItemType Directory -Force obj\test_agent_coordinator_integration | Out-Null

# Compile tests/test_agent_coordinator_integration.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/test_agent_coordinator_integration.cpp' '/Foobj\test_agent_coordinator_integration\test_agent_coordinator_integration.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/model_loader/model_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/model_loader/model_loader.cpp' '/Foobj\test_agent_coordinator_integration\model_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/inference_engine_stub.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/inference_engine_stub.cpp' '/Foobj\test_agent_coordinator_integration\inference_engine_stub.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gguf_server.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gguf_server.cpp' '/Foobj\test_agent_coordinator_integration\gguf_server.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\test_agent_coordinator_integration\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/inflate_deflate_cpp.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/inflate_deflate_cpp.cpp' '/Foobj\test_agent_coordinator_integration\inflate_deflate_cpp.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_agent_coordinator_integration
& $LINK $LINKFLAGS obj\test_agent_coordinator_integration\test_agent_coordinator_integration.obj obj\test_agent_coordinator_integration\model_loader.obj obj\test_agent_coordinator_integration\inference_engine_stub.obj obj\test_agent_coordinator_integration\gguf_server.obj obj\test_agent_coordinator_integration\gguf_loader.obj obj\test_agent_coordinator_integration\inflate_deflate_cpp.obj '/OUT:bin\test_agent_coordinator_integration.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_kv_cache
Write-BuildInfo 'Building test_kv_cache...'
New-Item -ItemType Directory -Force obj\test_kv_cache | Out-Null

# Compile src/test_kv_cache.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/test_kv_cache.cpp' '/Foobj\test_kv_cache\test_kv_cache.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/vulkan_compute.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/vulkan_compute.cpp' '/Foobj\test_kv_cache\vulkan_compute.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_kv_cache
& $LINK $LINKFLAGS obj\test_kv_cache\test_kv_cache.obj obj\test_kv_cache\vulkan_compute.obj '/OUT:bin\test_kv_cache.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_gguf_loader
Write-BuildInfo 'Building test_gguf_loader...'
New-Item -ItemType Directory -Force obj\test_gguf_loader | Out-Null

# Compile tests/test_gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/test_gguf_loader.cpp' '/Foobj\test_gguf_loader\test_gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\test_gguf_loader\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_vocab_resolver.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_vocab_resolver.cpp' '/Foobj\test_gguf_loader\gguf_vocab_resolver.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_gguf_loader
& $LINK $LINKFLAGS obj\test_gguf_loader\test_gguf_loader.obj obj\test_gguf_loader\gguf_loader.obj obj\test_gguf_loader\gguf_vocab_resolver.obj '/OUT:bin\test_gguf_loader.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building test_gguf_loader_simple
Write-BuildInfo 'Building test_gguf_loader_simple...'
New-Item -ItemType Directory -Force obj\test_gguf_loader_simple | Out-Null

# Compile tests/test_gguf_loader_simple.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/test_gguf_loader_simple.cpp' '/Foobj\test_gguf_loader_simple\test_gguf_loader_simple.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\test_gguf_loader_simple\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_vocab_resolver.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_vocab_resolver.cpp' '/Foobj\test_gguf_loader_simple\gguf_vocab_resolver.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link test_gguf_loader_simple
& $LINK $LINKFLAGS obj\test_gguf_loader_simple\test_gguf_loader_simple.obj obj\test_gguf_loader_simple\gguf_loader.obj obj\test_gguf_loader_simple\gguf_vocab_resolver.obj '/OUT:bin\test_gguf_loader_simple.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building brutal_gzip
Write-BuildInfo 'Building brutal_gzip...'
New-Item -ItemType Directory -Force obj\brutal_gzip | Out-Null

# Link brutal_gzip
& $LINK $LINKFLAGS  '/OUT:lib\brutal_gzip.lib'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building memory_hotpatch
Write-BuildInfo 'Building memory_hotpatch...'
New-Item -ItemType Directory -Force obj\memory_hotpatch | Out-Null

# Compile STATIC src/qtapp/model_memory_hotpatch.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'STATIC src/qtapp/model_memory_hotpatch.cpp' '/Foobj\memory_hotpatch\model_memory_hotpatch.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link memory_hotpatch
& $LINK $LINKFLAGS obj\memory_hotpatch\model_memory_hotpatch.obj '/OUT:lib\memory_hotpatch.lib'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

# Building benchmark_completions
Write-BuildInfo 'Building benchmark_completions...'
New-Item -ItemType Directory -Force obj\benchmark_completions | Out-Null

# Compile tests/benchmark_completions_full.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'tests/benchmark_completions_full.cpp' '/Foobj\benchmark_completions\benchmark_completions_full.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/real_time_completion_engine.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/real_time_completion_engine.cpp' '/Foobj\benchmark_completions\real_time_completion_engine.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/inference_engine.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/inference_engine.cpp' '/Foobj\benchmark_completions\inference_engine.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/gguf_loader.cpp' '/Foobj\benchmark_completions\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/quant_utils.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/quant_utils.cpp' '/Foobj\benchmark_completions\quant_utils.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/transformer_inference.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/transformer_inference.cpp' '/Foobj\benchmark_completions\transformer_inference.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/bpe_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/bpe_tokenizer.cpp' '/Foobj\benchmark_completions\bpe_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/sentencepiece_tokenizer.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/sentencepiece_tokenizer.cpp' '/Foobj\benchmark_completions\sentencepiece_tokenizer.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/vocabulary_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/vocabulary_loader.cpp' '/Foobj\benchmark_completions\vocabulary_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/qtapp/inflate_deflate_cpp.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/qtapp/inflate_deflate_cpp.cpp' '/Foobj\benchmark_completions\inflate_deflate_cpp.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/gguf_loader.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/gguf_loader.cpp' '/Foobj\benchmark_completions\gguf_loader.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/ai/memory_mapped_file.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/ai/memory_mapped_file.cpp' '/Foobj\benchmark_completions\memory_mapped_file.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Compile src/ai/streaming_gguf_loader_qt.cpp
& $CXX $CXXFLAGS $DEFINES $INCLUDES /c 'src/ai/streaming_gguf_loader_qt.cpp' '/Foobj\benchmark_completions\streaming_gguf_loader_qt.obj'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Compilation failed'; exit 1 }

# Link benchmark_completions
& $LINK $LINKFLAGS obj\benchmark_completions\benchmark_completions_full.obj obj\benchmark_completions\real_time_completion_engine.obj obj\benchmark_completions\inference_engine.obj obj\benchmark_completions\gguf_loader.obj obj\benchmark_completions\quant_utils.obj obj\benchmark_completions\transformer_inference.obj obj\benchmark_completions\bpe_tokenizer.obj obj\benchmark_completions\sentencepiece_tokenizer.obj obj\benchmark_completions\vocabulary_loader.obj obj\benchmark_completions\inflate_deflate_cpp.obj obj\benchmark_completions\gguf_loader.obj obj\benchmark_completions\memory_mapped_file.obj obj\benchmark_completions\streaming_gguf_loader_qt.obj '/OUT:bin\benchmark_completions.exe'
if ($LASTEXITCODE -ne 0) { Write-BuildError 'Linking failed'; exit 1 }

Write-BuildInfo 'Build completed successfully!'
