// ============================================================================
// rawrxd_telemetry_exports.h — C++ Bridge to MASM Telemetry Kernel
// ============================================================================
// Declares the extern "C" symbols exported by:
//   - RawrXD_Telemetry_Kernel.asm  (UTC counters, ring buffer, flush)
//   - RawrXD_Prometheus_Exporter.asm (Prometheus text-format export)
//
// Usage:
//   #include "rawrxd_telemetry_exports.h"
//   UTC_IncrementCounter(&g_Counter_Inference);
//
// Pattern: PatchResult-style returns (RAX=0 success, RAX=error code on failure)
// Rule:    NO SOURCE FILE IS TO BE SIMPLIFIED.
// ============================================================================

#pragma once
#ifndef RAWRXD_TELEMETRY_EXPORTS_H
#define RAWRXD_TELEMETRY_EXPORTS_H

#include <cstdint>

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// Guard: Only available when MASM telemetry kernel is linked
// ============================================================================
#if defined(RAWRXD_LINK_TELEMETRY_KERNEL_ASM) || defined(RAWR_HAS_MASM)

// ============================================================================
// Atomic Metric Counters (defined in TELEMETRY_CL segment)
// Each counter occupies its own 64-byte cache line to prevent false sharing.
// ============================================================================
extern uint64_t g_MetricTableStart;       // Sentinel: 0xDEADBEEFCAFEBABE
extern uint64_t g_Counter_Inference;      // Total tokens generated by ASM kernels
extern uint64_t g_Counter_ScsiFails;      // Hardware SCSI timeout count
extern uint64_t g_Counter_AgentLoop;      // Total agentic loop steps executed
extern uint64_t g_Counter_BytePatches;    // Byte-level hotpatches applied
extern uint64_t g_Counter_MemPatches;     // Memory hotpatches applied
extern uint64_t g_Counter_ServerPatches;  // Server-layer hotpatches applied
extern uint64_t g_Counter_FlushOps;       // Number of flush-to-disk operations
extern uint64_t g_Counter_Errors;         // Total errors observed
extern uint64_t g_MetricTableEnd;         // Sentinel: 0xBADCAFEDEADFACE

// ============================================================================
// UTC Telemetry Kernel — Lifecycle
// ============================================================================

// Initialize the telemetry subsystem: open log file, reset all counters.
// logFilePath: path to log file (null-terminated), or nullptr for default
//              ("rawrxd_kernel.log")
// Returns: 0 on success, GetLastError() on failure.
uint64_t UTC_InitTelemetry(const char* logFilePath);

// Shutdown: flush remaining events, close log file handle.
// Returns: 0 on success.
uint64_t UTC_ShutdownTelemetry(void);

// ============================================================================
// UTC Telemetry Kernel — Atomic Counter Operations
// ============================================================================

// Thread-safe atomic increment (lock xadd + inc).
// counterAddr: pointer to one of the g_Counter_* variables above.
// Returns: new value after increment.
uint64_t UTC_IncrementCounter(volatile uint64_t* counterAddr);

// Thread-safe atomic decrement (lock xadd + dec).
// Returns: new value after decrement.
uint64_t UTC_DecrementCounter(volatile uint64_t* counterAddr);

// Acquire-fence read of a 64-bit counter (mov + lfence).
// Returns: current counter value.
uint64_t UTC_ReadCounter(const volatile uint64_t* counterAddr);

// Atomically zero a counter and return old value (lock xchg).
// Returns: previous value.
uint64_t UTC_ResetCounter(volatile uint64_t* counterAddr);

// ============================================================================
// UTC Telemetry Kernel — Wait-Free Ring Buffer
// ============================================================================

// Write a message to the ring buffer (wait-free, lock xadd slot reservation).
// message: pointer to null-terminated string.
// Returns: slot index used.
uint64_t UTC_LogEvent(const char* message);

// Drain the ring buffer to the log file (single-consumer model).
// Returns: number of events flushed.
uint64_t UTC_FlushToDisk(void);

// ============================================================================
// UTC Telemetry Kernel — Introspection
// ============================================================================

// Returns pointer to g_MetricTableStart (for table-walking all counters).
void* UTC_GetMetricTableBase(void);

// Returns head index in RAX, tail index in RDX.
// C++ side: use the struct below or call directly for RAX only.
uint64_t UTC_GetEventBufferStats(void);

// ============================================================================
// Prometheus Exporter (defined in RawrXD_Prometheus_Exporter.asm)
// ============================================================================

#if defined(RAWRXD_LINK_PROMETHEUS_EXPORTER_ASM) || defined(RAWR_HAS_MASM)

// Generate full Prometheus text-format payload into buffer.
// buffer: caller-provided buffer (>= 8KB recommended).
// Returns: total bytes written.
uint64_t ExportPrometheus(char* buffer);

// Export a single metric line: "<name> <value>\n"
// buffer:      destination buffer
// metricName:  null-terminated metric name string
// counterAddr: pointer to the QWORD counter
// Returns: bytes written.
uint64_t ExportPrometheusMetric(char* buffer,
                                 const char* metricName,
                                 const volatile uint64_t* counterAddr);

#endif // RAWRXD_LINK_PROMETHEUS_EXPORTER_ASM

#endif // RAWRXD_LINK_TELEMETRY_KERNEL_ASM

// ============================================================================
// C++ Convenience Wrappers (inline, zero-overhead)
// ============================================================================
#ifdef __cplusplus
} // extern "C"

#if defined(RAWRXD_LINK_TELEMETRY_KERNEL_ASM) || defined(RAWR_HAS_MASM)

namespace RawrXD {
namespace Telemetry {

// ============================================================================
// Counter ID enum — maps to the global counter addresses
// ============================================================================
enum class CounterId : uint8_t {
    Inference       = 0,
    ScsiFails       = 1,
    AgentLoop       = 2,
    BytePatches     = 3,
    MemPatches      = 4,
    ServerPatches   = 5,
    FlushOps        = 6,
    Errors          = 7,
    _Count          = 8
};

// Returns pointer to the counter for a given CounterId.
inline volatile uint64_t* GetCounterPtr(CounterId id) {
    // Counter table is 64-byte stride from g_MetricTableStart + 64
    // Layout: [Sentinel 64B] [Inference 64B] [ScsiFails 64B] ...
    switch (id) {
        case CounterId::Inference:     return &g_Counter_Inference;
        case CounterId::ScsiFails:     return &g_Counter_ScsiFails;
        case CounterId::AgentLoop:     return &g_Counter_AgentLoop;
        case CounterId::BytePatches:   return &g_Counter_BytePatches;
        case CounterId::MemPatches:    return &g_Counter_MemPatches;
        case CounterId::ServerPatches: return &g_Counter_ServerPatches;
        case CounterId::FlushOps:      return &g_Counter_FlushOps;
        case CounterId::Errors:        return &g_Counter_Errors;
        default:                       return nullptr;
    }
}

// Increment a counter by ID. Returns new value.
inline uint64_t Increment(CounterId id) {
    volatile uint64_t* p = GetCounterPtr(id);
    return p ? UTC_IncrementCounter(p) : 0;
}

// Read a counter by ID.
inline uint64_t Read(CounterId id) {
    volatile uint64_t* p = GetCounterPtr(id);
    return p ? UTC_ReadCounter(p) : 0;
}

// Reset a counter by ID. Returns old value.
inline uint64_t Reset(CounterId id) {
    volatile uint64_t* p = GetCounterPtr(id);
    return p ? UTC_ResetCounter(p) : 0;
}

// Log a message to the wait-free ring buffer.
inline uint64_t Log(const char* message) {
    return UTC_LogEvent(message);
}

// Flush ring buffer to disk. Returns events flushed.
inline uint64_t Flush() {
    return UTC_FlushToDisk();
}

// ============================================================================
// RAII Telemetry Session — init on construction, shutdown on destruction
// ============================================================================
class Session {
public:
    explicit Session(const char* logPath = nullptr) {
        m_result = UTC_InitTelemetry(logPath);
    }
    ~Session() {
        if (m_result == 0) {
            UTC_ShutdownTelemetry();
        }
    }

    bool isValid() const { return m_result == 0; }
    uint64_t errorCode() const { return m_result; }

    // Non-copyable, non-movable
    Session(const Session&) = delete;
    Session& operator=(const Session&) = delete;

private:
    uint64_t m_result;
};

// ============================================================================
// Scoped Timer — logs elapsed time for a scope via UTC_LogEvent
// ============================================================================
// Usage:
//   {
//       RawrXD::Telemetry::ScopedTimer timer("InferencePass");
//       // ... code being profiled ...
//   }
//   // Automatically logs "[InferencePass] elapsed: <N> ms"
//
// Implementation uses QueryPerformanceCounter (no CRT dependency).
// ============================================================================

#if defined(_WIN32) && !defined(RAWRXD_TELEMETRY_NO_SCOPED_TIMER)

} // namespace Telemetry
} // namespace RawrXD

// ScopedTimer needs QueryPerformanceCounter/Frequency.
// Include <windows.h> properly to avoid extern "C" signature conflicts.
#ifndef _WINDOWS_
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#endif

namespace RawrXD {
namespace Telemetry {

class ScopedTimer {
public:
    explicit ScopedTimer(const char* label) : m_label(label) {
        LARGE_INTEGER freq, start;
        QueryPerformanceFrequency(&freq);
        QueryPerformanceCounter(&start);
        m_freq = freq.QuadPart;
        m_start = start.QuadPart;
    }

    ~ScopedTimer() {
        LARGE_INTEGER end;
        QueryPerformanceCounter(&end);
        int64_t elapsedUs = ((end.QuadPart - m_start) * 1000000) / m_freq;

        // Format: "[<label>] elapsed: <N> us"
        char buf[256];
        int pos = 0;
        buf[pos++] = '[';
        for (const char* p = m_label; *p && pos < 200; ++p)
            buf[pos++] = *p;
        buf[pos++] = ']';
        buf[pos++] = ' ';
        // "elapsed: "
        const char* suffix = "elapsed: ";
        for (const char* p = suffix; *p; ++p)
            buf[pos++] = *p;
        // Convert elapsedUs to ASCII
        char numBuf[24];
        int numLen = 0;
        uint64_t val = static_cast<uint64_t>(elapsedUs);
        if (val == 0) {
            numBuf[numLen++] = '0';
        } else {
            while (val > 0) {
                numBuf[numLen++] = '0' + static_cast<char>(val % 10);
                val /= 10;
            }
        }
        for (int i = numLen - 1; i >= 0; --i)
            buf[pos++] = numBuf[i];
        // " us"
        buf[pos++] = ' ';
        buf[pos++] = 'u';
        buf[pos++] = 's';
        buf[pos] = '\0';

        UTC_LogEvent(buf);
    }

    // Non-copyable
    ScopedTimer(const ScopedTimer&) = delete;
    ScopedTimer& operator=(const ScopedTimer&) = delete;

private:
    const char* m_label;
    int64_t     m_start = 0;
    int64_t     m_freq  = 1;
};

#endif // _WIN32 && !RAWRXD_TELEMETRY_NO_SCOPED_TIMER

} // namespace Telemetry
} // namespace RawrXD

#endif // RAWRXD_LINK_TELEMETRY_KERNEL_ASM

#else
// C-only: nothing else needed
#endif // __cplusplus

#endif // RAWRXD_TELEMETRY_EXPORTS_H
