# CMake generated Testfile for 
# Source directory: D:/rawrxd/tests
# Build directory: D:/rawrxd/build_release/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ai_completions]=] "D:/rawrxd/build_release/tests/test_ai_completions.exe")
set_tests_properties([=[test_ai_completions]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;91;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_llm_connectivity]=] "D:/rawrxd/build_release/tests/test_llm_connectivity.exe")
set_tests_properties([=[test_llm_connectivity]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;110;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_semantic_diff_analyzer]=] "D:/rawrxd/build_release/tests/test_semantic_diff_analyzer.exe")
set_tests_properties([=[test_semantic_diff_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;146;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_ai_merge_resolver]=] "D:/rawrxd/build_release/tests/test_ai_merge_resolver.exe")
set_tests_properties([=[test_ai_merge_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;158;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_sandboxed_terminal]=] "D:/rawrxd/build_release/tests/test_sandboxed_terminal.exe")
set_tests_properties([=[test_sandboxed_terminal]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;167;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_agentic_file_operations]=] "D:/rawrxd/build_release/tests/test_agentic_file_operations.exe")
set_tests_properties([=[test_agentic_file_operations]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;176;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[model_registry_test]=] "D:/rawrxd/build_release/tests/model_registry_test.exe")
set_tests_properties([=[model_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;204;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[license_validation_suite]=] "D:/rawrxd/build_release/tests/license_validation_suite.exe")
set_tests_properties([=[license_validation_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;240;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_production_regression]=] "D:/rawrxd/build_release/tests/test_production_regression.exe")
set_tests_properties([=[test_production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;268;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_instructions_provider]=] "D:/rawrxd/build_release/tests/test_instructions_provider.exe")
set_tests_properties([=[test_instructions_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;289;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[license_gate_validator]=] "D:/rawrxd/build_release/tools/license_gate_validator.exe")
set_tests_properties([=[license_gate_validator]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;311;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[cuda_test]=] "D:/rawrxd/build_release/tests/cuda_test.exe")
set_tests_properties([=[cuda_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;361;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[grammar_test]=] "D:/rawrxd/build_release/tests/grammar_test.exe")
set_tests_properties([=[grammar_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;381;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[lora_test]=] "D:/rawrxd/build_release/tests/lora_test.exe")
set_tests_properties([=[lora_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;401;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[cache_test]=] "D:/rawrxd/build_release/tests/cache_test.exe")
set_tests_properties([=[cache_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;427;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[airgap_test]=] "D:/rawrxd/build_release/tests/airgap_test.exe")
set_tests_properties([=[airgap_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;451;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[hsm_test]=] "D:/rawrxd/build_release/tests/hsm_test.exe")
set_tests_properties([=[hsm_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;477;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[fips_test]=] "D:/rawrxd/build_release/tests/fips_test.exe")
set_tests_properties([=[fips_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;503;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[policy_test]=] "D:/rawrxd/build_release/tests/policy_test.exe")
set_tests_properties([=[policy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;523;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[keymgmt_test]=] "D:/rawrxd/build_release/tests/keymgmt_test.exe")
set_tests_properties([=[keymgmt_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;543;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[classnet_test]=] "D:/rawrxd/build_release/tests/classnet_test.exe")
set_tests_properties([=[classnet_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;563;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[auditlog_test]=] "D:/rawrxd/build_release/tests/auditlog_test.exe")
set_tests_properties([=[auditlog_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;583;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[k8s_test]=] "D:/rawrxd/build_release/tests/k8s_test.exe")
set_tests_properties([=[k8s_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;603;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
