param(
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot\..").Path
)

$symbolsPath = Join-Path $RepoRoot "src/core/ssot_beacon.symbols.txt"
$outPath = Join-Path $RepoRoot "src/core/ssot_beacon_table.inc"

if (!(Test-Path $symbolsPath)) { throw "Missing $symbolsPath" }

$symbols = Get-Content $symbolsPath |
    ForEach-Object { $_.Trim() } |
    Where-Object { $_ -and -not $_.StartsWith('#') } |
    Sort-Object -Unique

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Generated by tools/generate_ssot_beacon_table.ps1")
foreach ($symbol in $symbols) {
    $lines.Add("    HB(""$symbol""),")
}

Set-Content -Path $outPath -Value $lines -Encoding ascii
Write-Host "Generated $outPath ($($symbols.Count) symbols)"
