#include <iostream>
#include <string>

#include "win32app/debugger_status_text.h"

int main() {
    using rawrxd::win32app::formatDebuggerStatusText;
    using rawrxd::win32app::kDebuggerStatusTextLimit;

    {
        const std::string msg = "Debugger error: Adapter timeout";
        const std::string status = formatDebuggerStatusText(msg);
        if (status != msg) {
            std::cerr << "Expected short status text to remain unchanged\n";
            return 1;
        }
    }

    {
        const std::string longMsg(kDebuggerStatusTextLimit + 50, 'E');
        const std::string status = formatDebuggerStatusText(longMsg);

        if (status.size() != kDebuggerStatusTextLimit) {
            std::cerr << "Expected truncated status length to equal limit\n";
            return 1;
        }

        if (status.substr(status.size() - 3) != "...") {
            std::cerr << "Expected truncated status to end with ellipsis\n";
            return 1;
        }
    }

    {
        // Callback simulation: error text generated by debugger callback is routed
        // through the same formatter before status-bar presentation.
        const std::string callbackMessage =
            "Debugger error: Frame Stack Walk Failed - " +
            std::string(kDebuggerStatusTextLimit + 10, 'X');
        const std::string status = formatDebuggerStatusText(callbackMessage);
        if (status.empty() || status.size() > kDebuggerStatusTextLimit) {
            std::cerr << "Expected callback-derived status text to be bounded\n";
            return 1;
        }
    }

    return 0;
}
